build.sh

Include mailpoet-cron.php in the zip during build [MAILPOET-1576]

---

docker-compose.yml
tests/_data/acceptanceDump.sql

Fix timeouts on circle ci by using an older version of chrome.

Use older chrome

---

assets/css/src/admin.styl
assets/css/src/custom_fonts.styl
assets/css/src/newsletter_editor/common.styl
assets/js/src/handlebars_helpers.js
lib/Config/Menu.php
lib/Newsletter/Renderer/Renderer.php
lib/Newsletter/Renderer/StylesHelper.php
lib/Newsletter/Renderer/Template.html
package-lock.json
tests/javascript/newsletter_editor/blocks/footer.spec.js
tests/javascript/newsletter_editor/blocks/header.spec.js
tests/javascript/newsletter_editor/components/sidebar.spec.js
tests/unit/Newsletter/Renderer/StylesHelperTest.php
views/newsletter/editor.html
views/newsletter/templates/blocks/footer/settings.hbs
views/newsletter/templates/blocks/header/settings.hbs
views/newsletter/templates/components/sidebar/styles.hbs

Sorry for not splitting this PR into multiple commits. I didn't realize that there was many changes until I was done.
Please check the comments of the Jira tickets as they include additional specs.

adding custom fonts [MAILPOET-1493]

---

readme.txt

[MAILPOET-1628 Readme.txt Update](https://mailpoet.atlassian.net/browse/MAILPOET-1628)

Update readme.txt: Multisites are not supported

---

tests/integration/API/JSON/v1/NewsletterTemplatesTest.php

I really don't know what caused the flakiness. It shouldn't be, but it is. So I tried to make this changes and I am hoping for the best.

Try to fix test flakiness [MAILPOET-1580]

---

lib/API/JSON/API.php

Add fallback for API endpoint instantiation [MAILPOET-1639]

---

tests/_support/AcceptanceTester.php
tests/acceptance/EnableAndDisableSignupConfirmationCest.php
views/settings/signup.html

[MQ-87 Enable and disable sign up confirmation](https://mailpoet.atlassian.net/browse/MQ-87)

Test signup confirmation [MQ-87]

---

assets/css/src/welcome_wizard.styl
lib/Util/Notices/PHPVersionWarnings.php
lib/Util/Notices/PermanentNotices.php
tests/integration/Util/Notices/PHPVersionWarningsTest.php

We've just changed the notice in MAILPOET-1660, but this one takes priority.

Hide notices in the welcome wizard, change PHP 5.6 notice [MAILPOET-1659]

---

assets/css/src/admin.styl
assets/css/src/modal.styl
assets/css/src/settings.styl
assets/js/src/common/confirm_alert.jsx
assets/js/src/modal.js
assets/js/src/newsletters/listings/standard.jsx
assets/js/src/newsletters/templates/template_box.jsx
assets/js/src/settings/tabs.js
package.json
views/layout.html
views/settings.html

Change React Confirm Alert style [MAILPOET-1625]

---

lib/Analytics/Analytics.php
lib/Analytics/Reporter.php
lib/Models/Newsletter.php

[MAILPOET-1646 Collect more WooCommerce stats periodically via MixPanel](https://mailpoet.atlassian.net/browse/MAILPOET-1646)

Report more WooCommerce stats [MAILPOET-1646]

---

composer.json
composer.lock
lib/Util/ArrayColumn.php

I have also updated other deps (patch versions) for phpcs I had to add one fix in ArrayColumn polyfill

Upgrade codeception and lucatume/wp-browser [MAILPOET-1713]

---

assets/css/src/newsletter_congratulate.styl
assets/js/src/newsletter_editor/components/sidebar.js
assets/js/src/newsletters/send/congratulate/success.jsx
assets/js/src/poll.jsx
assets/js/src/webpack_admin_index.jsx
lib/Config/Changelog.php
lib/Config/Renderer.php
lib/Twig/Functions.php
lib/Twig/Polls.php
views/layout.html
views/newsletters.html
views/settings/mta.html

Poll first email sending success/failure [MAILPOET-1417]

---

views/newsletter/editor.html

Fix editor not loading when jQuery in noConflict mode

---

lib/Config/RequirementsChecker.php
lib/Subscribers/ImportExport/ImportExportFactory.php
views/subscribers/importExport/export.html

[[MAILPOET-1718]](https://mailpoet.atlassian.net/browse/MAILPOET-1718)

Remove zip extension dependency [MAILPOET-1718]

---

assets/js/src/newsletters/types/automatic_emails/event.jsx

[[MQ-163]](https://mailpoet.atlassian.net/browse/MQ-163)

Add data-automation-id to woocommerce events [MQ-163]

---

lib/Newsletter/Editor/StructureTransformer.php

Fix post images detection in editor

---

RoboFile.php

This command will make it easy to push templates assets to the SVN repo withoutr releasing the plugin, which allows us to test them.

Add command to push templates assets

---

.gitignore
RoboFile.php
lib/Config/Capabilities.php
lib/Config/Renderer.php
lib/Form/Util/Export.php
lib/Form/Widget.php
lib/Twig/Assets.php
tests/integration/Config/RendererTest.php
tests/integration/Twig/AssetsTest.php
webpack.config.js

[[MAILPOET-1687]](https://mailpoet.atlassian.net/browse/MAILPOET-1687)

Move generated assets to dist [MAILPOET-1687]

---

lib/Config/Hooks.php
lib/Config/Migrator.php
lib/Models/SubscriberSegment.php
lib/Subscribers/ConfirmationEmailMailer.php
lib/Subscription/Throttling.php
lib/WP/Functions.php
tests/integration/Config/ShortcodesTest.php
tests/integration/Models/SubscriberSegmentTest.php
tests/integration/Subscribers/ConfirmationEmailMailerTest.php

Limit number of confirmation emails sent to one email

---

assets/css/src/datepicker/jquery-ui-1.10.1.css
assets/css/src/datepicker/melon.datepicker.css
assets/css/src/form_editor.styl

[[[MAILPOET-1773]](https://mailpoet.atlassian.net/browse/MAILPOET-1773)](https://mailpoet.atlassian.net/browse/MAILPOET-1773)

Update images URLs on CSS [MAILPOET-1773]

---

assets/css/src/newsletter_editor/components/blockTools.styl

Change element controls position in editor

---

assets/css/src/newsletter_editor/common.styl

Make small inputs in editor larger to fit 4 digits

---

assets/js/src/newsletter_editor/behaviors/TextEditorBehavior.js

Fix scroll up when clicking on the bottom of long textareas [MAILPOET-1728]

---

RoboFile.php
tasks/release/Jira.php
tasks/release/ReleaseVersionController.php

Example: `./do j:r [3.19.2]` (if version is empty, the latest existing version will be used).

Add a command to assign release versions to Jira tickets [MAILPOET-1783]

---

tests/acceptance/EditExistingNewsletterCest.php

*Used factory instead of clicky method to create a newsletter to edit
*better used automation IDs, helpers, and vars
*removed useless stuff
*removed $I->seeInCurrentUrl several times

[MQ-177] Refactor edit existing newsletter test

---

tests/acceptance/ManageWelcomeEmailCest.php

*removed 11 of 12 $I->seeInCurrentUrl statements, kept the twelfth, because it's actually helpful. 
*renamed vars to follow camelCase
*minor cleanup

[MQ-178 refactor ManageWelcomeEmailCest tests

---

lib/Cron/Triggers/WordPress.php
lib/Cron/Workers/SimpleWorker.php
lib/Tasks/Sending.php
tests/integration/Cron/Triggers/WordPressTest.php
tests/integration/Cron/Workers/SimpleWorkerTest.php
tests/integration/Tasks/SendingTest.php

[[MAILPOET-1755]](https://mailpoet.atlassian.net/browse/MAILPOET-1755)

Cron optimization [MAILPOET-1755]

---

lib/Models/Subscriber.php

This method is used by Thrive Leads plugin

Return Subscriber::subscribe static method [MAILPOET-1865]

---

tests/_data/acceptanceMultisiteDump.sql
tests/docker/codeception/docker-entrypoint.sh

Here is a build result with enabled multisite tests: https://circleci.com/workflow-run/ef49a4d4-8568-4912-9830-b4d1c7ddcd22

Fix acceptance tests domain for multisite tests

---

tasks/release/ChangelogController.php
tasks/release/Jira.php

[MAILPOET-1867]
[MAILPOET-1867]: https://mailpoet.atlassian.net/browse/MAILPOET-1867

Skip "Won't Do" issues from changelog [MAILPOET-1867]

---

README.md
package-lock.json
package.json

Fixes #1905.
Tested locally, js tests all pass 💚

Update to handlebars ^4.1.1

---

.eslintrc.es6.json
assets/js/src/nps_poll.jsx
assets/js/src/welcome_wizard/steps_controller.jsx
package-lock.json
package.json

I've added two eslint rules:
- the first one is enforcing [rules of hooks](https://reactjs.org/docs/hooks-rules.html)
- second one is[ checking dependencies for effects](https://github.com/facebook/react/issues/14920)

Upgrade react + small refactors with hooks [MAILPOET-1916]

---

lib/Newsletter/Renderer/Blocks/Social.php

Fix social icons spacing in outlook [MAILPOET-1827]

---

lib/Newsletter/Editor/PostTransformer.php

[MAILPOET-1937]
[MAILPOET-1937]: https://mailpoet.atlassian.net/browse/MAILPOET-1937

Replace double quotes with unicode alternative [MAILPOET-1937]

---

composer.json
composer.lock
lib/Config/Renderer.php
lib/Config/RequirementsChecker.php
lib/Twig/Analytics.php
lib/Twig/Assets.php
lib/Twig/Filters.php
lib/Twig/Functions.php
lib/Twig/Handlebars.php
lib/Twig/Helpscout.php
lib/Twig/I18n.php
lib/Twig/Polls.php
prefixer/composer.json
prefixer/composer.lock
prefixer/fix-twig.php
tests/integration/Config/RendererTest.php
tests/integration/Twig/FunctionsTest.php

Move Twig to prefixed dependencies [MAILPOET-1929]

---

lib/API/JSON/v1/Subscribers.php
tests/integration/API/JSON/v1/SubscribersTest.php

Prevent scheduling welcome emails [MAILPOET-1908]

---

assets/js/src/subscribers/importExport/import.jsx

[MAILPOET-1816]
[MAILPOET-1816]: https://mailpoet.atlassian.net/browse/MAILPOET-1816

Fix creating custom fields on subscriber import [MAILPOET-1816]

---

lib/Newsletter/AutomatedLatestContent.php

[[MAILPOET-1960]](https://mailpoet.atlassian.net/browse/MAILPOET-1960)
[MAILPOET-1960]: https://mailpoet.atlassian.net/browse/MAILPOET-1960

Fix inconsistent ALC query type when used with/without taxonomies [MAILPOET-1960]

---

assets/js/src/date.js
assets/js/src/newsletters/listings/mixins.jsx
assets/js/src/newsletters/send/standard.jsx
lib/Config/Menu.php
package-lock.json
package.json
views/newsletters.html

Reverts mailpoet/mailpoet#1975

Revert "Display user's time for scheduled emails" [MAILPOET-2020]

---

lib/Subscribers/SubscriberPersonalDataEraser.php
lib/Util/Security.php
tests/DataFactories/Segment.php
tests/DataFactories/Subscriber.php
tests/DataFactories/WooCommerceCustomer.php
tests/DataFactories/WooCommerceOrder.php
tests/DataFactories/WooCommerceProduct.php
tests/_support/IntegrationTester.php
tests/_support/UnitTester.php
tests/integration/Util/SecurityTest.php

[MAILPOET-1902]
[MAILPOET-1902]: https://mailpoet.atlassian.net/browse/MAILPOET-1902

Random strings [MAILPOET-1902]

---

lib/Mailer/Methods/ErrorMappers/MailPoetMapper.php
tests/acceptance/UnauthorizedAddressCest.php

[MAILPOET-1991]
[MAILPOET-1991]: https://mailpoet.atlassian.net/browse/MAILPOET-1991

Show the old admin notice when using free email [MAILPOET-1991]

---

assets/js/src/common/sender_email_address_warning.jsx
assets/js/src/newsletters/send/sender_address_field.jsx
assets/js/src/settings/default_sender.jsx
assets/js/src/settings/settings.jsx
assets/js/src/settings/signup_confirmation_sender.jsx
tests/acceptance/SettingsFreeEmailAsFromAddressTriggersAlertCest.php
tests/acceptance/SettingsPageBasicsCest.php
views/layout.html

[MAILPOET-1986]
[MAILPOET-1986]: https://mailpoet.atlassian.net/browse/MAILPOET-1986

Remove free email address validation for MSS [MAILPOET-1986]

---

assets/css/src/components/_notice.scss
assets/js/src/announcements/free_plan_announcement.jsx
assets/js/src/newsletters/listings/heading.jsx
lib/Features/FeaturesController.php
tests/acceptance/FreePlanAnnouncementCest.php
views/newsletters.html
views/settings/mta.html
webpack.config.js

There are two issues because one is just a change of CTA button but would require implementing a feature flag, so I did it in one PR instead.

Free plan notice [MAILPOET-2051] [MAILPOET-2054]

---

lib/API/MP/v1/API.php
lib/Config/Menu.php
lib/Config/Populator.php
lib/Config/PopulatorData/DefaultForm.php
lib/Form/Widget.php
lib/Settings/SettingsController.php
lib/Subscribers/ImportExport/ImportExportFactory.php
lib/WP/Functions.php

[MAILPOET-2092]
[MAILPOET-2092]: https://mailpoet.atlassian.net/browse/MAILPOET-2092

Fix translation function names in WP\Functions [MAILPOET-2092]

---

tests/acceptance/ReceivePostNotificationCest.php
tests/acceptance/ReceiveStandardEmailCest.php
tests/acceptance/RevenueTrackingCookieCest.php

Fix flakey tests "RevenueTrackingCookieCest: Test Revenue cookie is saved" [MAILPOET-2111]

---

lib/Segments/WP.php
tests/integration/Segments/WPTest.php
tests/integration/Segments/WooCommerceTest.php

[MAILPOET-2126]
[MAILPOET-2126]: https://mailpoet.atlassian.net/browse/MAILPOET-2126

Force confirmation for bulk synced WordPress users [MAILPOET-2126]

---

lib/API/JSON/v1/Setup.php
lib/Config/Activator.php
lib/Config/MP2Migrator.php
lib/Config/Menu.php
lib/Config/Populator.php
lib/Cron/Daemon.php
lib/Cron/Triggers/WordPress.php
lib/Cron/Workers/Beamer.php
lib/Cron/Workers/WorkersFactory.php
lib/DI/ContainerConfigurator.php
tests/integration/Cron/DaemonHttpRunnerTest.php
tests/integration/Cron/DaemonTest.php
tests/integration/Cron/Triggers/WordPressTest.php
tests/integration/Cron/Workers/BeamerTest.php
tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php
tests/integration/Cron/Workers/SendingQueue/Tasks/MailerTest.php
tests/integration/Newsletter/ShortcodesTest.php
tests/integration/Subscription/UrlTest.php

[MAILPOET-2037]
[MAILPOET-2037]: https://mailpoet.atlassian.net/browse/MAILPOET-2037

Beamer API get last announcement [MAILPOET-2037]

---

lib/Config/Initializer.php

[MAILPOET-2170]
[MAILPOET-2170]: https://mailpoet.atlassian.net/browse/MAILPOET-2170

Initialize Hooks on the init action [MAILPOET-2170]

---

lib/Cron/Workers/StatsNotifications/Worker.php
views/emails/statsNotification.html
views/emails/statsNotification.txt

It looks like a big change, but it is just removing one `if` condition in the template.

Add stats link for free user [MAILPOET-2119]

---

lib/Segments/WooCommerce.php

Please test using various combinations of collations for the `email` column in the `mailpoet_subscribers` table and WP tables/columns from this list:
* `utf8mb4_unicode_ci`
* `utf8mb4_unicode_520_ci`
* `utf8_general_ci`
* Any more that we support?

Fix illegal collation mix error [MAILPOET-2122]

---

lib/Newsletter/Shortcodes/Categories/Newsletter.php

Same fix as in https://github.com/mailpoet/mailpoet/blob/master/lib/Newsletter/AutomatedLatestContent.php#L92

Fix [newsletter:post_title] with filters applied [MAILPOET-2214]

---

build.sh

[MAILPOET-2228]
[MAILPOET-2228]: https://mailpoet.atlassian.net/browse/MAILPOET-2228

Fix missing dependencies error [MAILPOET-2228]

---

build.sh

[MAILPOET-2234]
[MAILPOET-2234]: https://mailpoet.atlassian.net/browse/MAILPOET-2234

Add index.php only if no Index.php [MAILPOET-2234]

---

lib/Config/Migrator.php
lib/Config/Populator.php
lib/Cron/Daemon.php
lib/Cron/Triggers/WordPress.php
lib/Cron/Workers/UnsubscribeTokens.php
lib/Cron/Workers/WorkersFactory.php
lib/Models/Newsletter.php
lib/Models/Subscriber.php
lib/Util/Security.php
tests/_data/acceptanceDump.sql
tests/integration/API/JSON/v1/NewslettersTest.php
tests/integration/API/MP/APITest.php
tests/integration/Cron/Workers/UnsubscribeTokensTest.php
tests/integration/Models/SubscriberTest.php
tests/integration/Subscribers/ImportExport/Export/ExportTest.php

[MAILPOET-2153]
[MAILPOET-2153]: https://mailpoet.atlassian.net/browse/MAILPOET-2153

Create unsubscribe tokens for subscribers and newsletters [MAILPOET-2153]

---

tests/integration/Cron/Workers/SendingQueue/Tasks/NewsletterTest.php

Fix date format assertion in integration test [MAILPOET-2244]

---

lib/AdminPages/Pages/Settings.php

I found and fixed an issue with linux cron path in settings, but I couldn't replicate the issue from the story.

Fix Linux cron path [MAILPOET-2124]

---

assets/js/src/newsletters/send.jsx

[MAILPOET-2135]
[MAILPOET-2135]: https://mailpoet.atlassian.net/browse/MAILPOET-2135

Validate from address on form submit [MAILPOET-2135]

---

lib/Cron/Workers/StatsNotifications/Worker.php
tests/integration/Cron/Workers/StatsNotifications/WorkerTest.php

[MAILPOET-2255]
[MAILPOET-2255]: https://mailpoet.atlassian.net/browse/MAILPOET-2255

Use the rendered subject in stats email [MAILPOET-2255]

---

lib/API/JSON/v1/MP2Migrator.php
lib/Config/Changelog.php
lib/Config/MP2Migrator.php
lib/Config/Populator.php
lib/DI/ContainerConfigurator.php
lib/Referrals/ReferralDetector.php
tests/integration/API/JSON/v1/SetupTest.php
tests/integration/Config/MP2MigratorTest.php
tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php
tests/integration/Cron/Workers/SendingQueue/Tasks/MailerTest.php
tests/integration/Newsletter/ShortcodesTest.php
tests/integration/Subscription/UrlTest.php
tests/unit/Referrals/ReferralDetectorTest.php
tests/unit/_bootstrap.php

There is a small [related PR](https://github.com/mailpoet/mailpoet-premium/pull/275) in premium.

Referral id detection  [MAILPOET-2203]

---

lib/API/JSON/v1/Settings.php
lib/Config/Populator.php
tests/acceptance/EditSignUpConfirmationEmailCest.php
tests/acceptance/EnableAndDisableSignupConfirmationCest.php
tests/acceptance/SubscribeToMultipleListsCest.php
tests/acceptance/SubscriptionFormCest.php

[MAILPOET-1998]
[MAILPOET-1998]: https://mailpoet.atlassian.net/browse/MAILPOET-1998

Forms message [MAILPOET-1998]

---

build.sh
lib/Doctrine/ConfigurationFactory.php

[MAILPOET-2236]
[MAILPOET-2236]: https://mailpoet.atlassian.net/browse/MAILPOET-2236

Remove Doctrine unneeded annotations directory [MAILPOET-2236]

---

lib/Config/PrivacyPolicy.php

[MAILPOET-2220]
[MAILPOET-2220]: https://mailpoet.atlassian.net/browse/MAILPOET-2220

Update privacy notice [MAILPOET-2220]

---

lib/AdminPages/Pages/Newsletters.php
views/newsletters.html

[MAILPOET-2177]
[MAILPOET-2177]: https://mailpoet.atlassian.net/browse/MAILPOET-2177

Show NPS poll only after sending [MAILPOET-2177]

---

.circleci/config.yml

[MAILPOET-2294]
[MAILPOET-2294]: https://mailpoet.atlassian.net/browse/MAILPOET-2294

Run all jobs on smaller instances [MAILPOET-2294]

---

lib/Doctrine/MetadataCache.php

[MAILPOET-2298]
[MAILPOET-2298]: https://mailpoet.atlassian.net/browse/MAILPOET-2298

Auto-regenerate Doctrine metadata in dev mode [MAILPOET-2298]

---

assets/js/src/newsletters/types.jsx
tests/acceptance/NewsletterCreationCest.php
views/newsletters.html

[MAILPOET-2174]
[MAILPOET-2174]: https://mailpoet.atlassian.net/browse/MAILPOET-2174

Add premium notice to automatic emails [MAILPOET-2174]

---

lib/Subscribers/ImportExport/Export/Export.php
views/subscribers/importExport/export.html

[MAILPOET-2330]
[MAILPOET-2330]: https://mailpoet.atlassian.net/browse/MAILPOET-2330

Don't require zip extension when exporting to csv [MAILPOET-2330]

---

lib/API/JSON/API.php
lib/AdminPages/PageRenderer.php
lib/Tracy/DIPanel/DIPanel.php
lib/Tracy/DIPanel/di-panel.phtml

[MAILPOET-2293]
[MAILPOET-2293]: https://mailpoet.atlassian.net/browse/MAILPOET-2293

Add tracy panel for DI container [MAILPOET-2293]

---

assets/js/src/subscribers/list.jsx
lib/API/JSON/v1/Subscribers.php
lib/AdminPages/Pages/Subscribers.php
tests/acceptance/SubscribersListingCest.php
tests/integration/API/JSON/v1/SubscribersTest.php
views/subscribers/subscribers.html

[MAILPOET-2316]
[MAILPOET-2316]: https://mailpoet.atlassian.net/browse/MAILPOET-2316

Add "resend email" action to subscribers list item [MAILPOET-2316]

---

tests/docker/codeception/docker-entrypoint.sh

[MAILPOET-2349]
[MAILPOET-2349]: https://mailpoet.atlassian.net/browse/MAILPOET-2349

Fix running codeception without SKIP_DEPS=1 [MAILPOET-2349]

---

.circleci/config.yml
.circleci/setup.bash
lib/Models/Newsletter.php
lib/WP/Functions.php

[MAILPOET-2289]
[MAILPOET-2289]: https://mailpoet.atlassian.net/browse/MAILPOET-2289

Use more MySQL and WP versions for integration tests on Circle [MAILPOET-2289]

---

assets/js/src/newsletters/sending_status.jsx

[MAILPOET-2218]
[MAILPOET-2218]: https://mailpoet.atlassian.net/browse/MAILPOET-2218

Hide stats link if newsletter not sent yet [MAILPOET-2218]

---

views/forms.html
views/layout.html
views/newsletters.html
views/segments.html
views/settings.html
views/subscribers/subscribers.html

[MAILPOET-2338]
[MAILPOET-2338]: https://mailpoet.atlassian.net/browse/MAILPOET-2338

Add suggested articles to Beacon [MAILPOET-2338]

---

lib/Entities/NewsletterEntity.php

[MAILPOET-2350]
[MAILPOET-2350]: https://mailpoet.atlassian.net/browse/MAILPOET-2350

Check parent_id for falsy values [MAILPOET-2350]

---

lib/Subscription/Registration.php
tests/acceptance/SubscribeOnRegistrationPageCest.php

[MAILPOET-2210]
[MAILPOET-2210]: https://mailpoet.atlassian.net/browse/MAILPOET-2210

Subscribe new user to WP list only [MAILPOET-2210]

---

lib/Services/AuthorizedEmailsController.php
tests/integration/Services/AuthorizedEmailsControllerTest.php

[MAILPOET-2359]
[MAILPOET-2359]: https://mailpoet.atlassian.net/browse/MAILPOET-2359

Enable Authorized emails checks for all users [MAILPOET-2359]

---

lib/Cron/Workers/WooCommerceOrders.php

[MAILPOET-2361](https://mailpoet.atlassian.net/browse/MAILPOET-2361)

Fix hardcoded wp_post table in WooCommerce orders processing [MAILPOET-2361]

---

lib/Cron/Workers/SubscriberLinkTokens.php
lib/Models/Subscriber.php
lib/Subscribers/ImportExport/Import/Import.php
tests/integration/Models/SubscriberTest.php
tests/integration/Subscribers/ImportExport/Import/ImportTest.php

[MAILPOET-2364](https://mailpoet.atlassian.net/browse/MAILPOET-2364)

Add backward compatibility for link tokens [MAILPOET-2364]

---

lib/Doctrine/MetadataCache.php

[MAILPOET-2357]
[MAILPOET-2357]: https://mailpoet.atlassian.net/browse/MAILPOET-2357

Remove usage of @ operator [MAILPOET-2357]

---

assets/js/src/segments/list.jsx
lib/API/JSON/v1/Segments.php
lib/Models/Segment.php
views/segments.html

[MAILPOET-2352]
[MAILPOET-2352]: https://mailpoet.atlassian.net/browse/MAILPOET-2352

Don't allow deleting list which is assigned to automatic email [MAILPOET-2352]

---

assets/js/src/newsletters/listings/tabs.jsx

[PREMIUM-138]
[PREMIUM-138]: https://mailpoet.atlassian.net/browse/PREMIUM-138

Hide WC tab from Emails when WC is not active [PREMIUM-138]

---

assets/js/src/intro.jsx

[MAILPOET-2369](https://mailpoet.atlassian.net/browse/MAILPOET-2369)

Fix intro for users with restricted access [MAILPOET-2369]

---

.circleci/config.yml
tests/_support/CheckSkippedTestsExtension.php
tests/acceptance.suite.yml
tests/integration/Cron/CronHelperTest.php
tests/integration/Cron/SupervisorTest.php
tests/integration/Mailer/MailerTest.php
tests/integration/Mailer/Methods/AmazonSESTest.php
tests/integration/Mailer/Methods/MailPoetAPITest.php
tests/integration/Mailer/Methods/PHPMailTest.php
tests/integration/Mailer/Methods/SMTPTest.php
tests/integration/Mailer/Methods/SendGridTest.php
tests/integration/Services/BridgeTest.php
tests/integration/_bootstrap.php
tests/unit/Subscribers/ImportExport/Import/MailChimpTest.php

[MAILPOET-2358]
[MAILPOET-2358]: https://mailpoet.atlassian.net/browse/MAILPOET-2358

Tests skipping [MAILPOET-2358]

---

lib/Cron/Workers/Scheduler.php
lib/Cron/Workers/SendingQueue/SendingQueue.php
tests/integration/Cron/Workers/SchedulerTest.php
tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php

[MAILPOET-2331]
[MAILPOET-2331]: https://mailpoet.atlassian.net/browse/MAILPOET-2331

Make sure only subscribed users recieve welcome emails [MAILPOET-2331]

---

readme.txt

[MAILPOET-2371]
[MAILPOET-2371]: https://mailpoet.atlassian.net/browse/MAILPOET-2371

Format FAQ in WordPress repository [MAILPOET-2371]

---

assets/js/src/announcements/feature_announcement.jsx

[MAILPOET-2362]
[MAILPOET-2362]: https://mailpoet.atlassian.net/browse/MAILPOET-2362

Add WooCommerce segment for Beamer [MAILPOET-2362]

---

lib/Config/Populator.php
lib/DI/ContainerConfigurator.php
lib/Entities/NewsletterEntity.php
lib/Features/FeaturesController.php
lib/Models/Newsletter.php
lib/WooCommerce/TransactionalEmails.php
tests/integration/API/JSON/v1/SetupTest.php
tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php
tests/integration/Cron/Workers/SendingQueue/Tasks/MailerTest.php
tests/integration/Newsletter/ShortcodesTest.php
tests/integration/Subscription/UrlTest.php
tests/integration/WooCommerce/TransactionalEmailsTest.php

[MAILPOET-2280]
[MAILPOET-2280]: https://mailpoet.atlassian.net/browse/MAILPOET-2280

Create and store WC transactional email template [MAILPOET-2280]

---

assets/js/src/newsletters/templates.jsx
lib/Config/Populator.php
lib/Config/PopulatorData/Templates/NewsletterBlank121Column.php
lib/Config/PopulatorData/Templates/NewsletterBlank12Column.php
lib/Config/PopulatorData/Templates/NewsletterBlank13Column.php
lib/Config/PopulatorData/Templates/NewsletterBlank1Column.php
lib/Config/PopulatorData/Templates/PostNotificationsBlank1Column.php
lib/Config/PopulatorData/Templates/WelcomeBlank12Column.php
lib/Config/PopulatorData/Templates/WelcomeBlank1Column.php
views/newsletters.html

[MAILPOET-2345]
[MAILPOET-2345]: https://mailpoet.atlassian.net/browse/MAILPOET-2345

Update template sections [MAILPOET-2345]

---

lib/Subscribers/InactiveSubscribersController.php

The fix is suggested by the TDN sysadmin. Works much faster on a `statistics_opens` table with 30 million rows.

Optimize the inactives sync SQL query [MAILPOET-2377]

---

lib/API/JSON/v1/Subscribers.php
tests/integration/API/JSON/v1/SubscribersTest.php

[MAILPOET-2292]
[MAILPOET-2292]: https://mailpoet.atlassian.net/browse/MAILPOET-2292

Fix user being unsubscribed from non default lists [MAILPOET-2292]

---

lib/Cron/CronHelper.php
lib/Cron/DaemonHttpRunner.php
lib/Cron/Supervisor.php
tests/integration/Cron/CronHelperTest.php
tests/integration/Cron/DaemonHttpRunnerTest.php
tests/integration/Cron/SupervisorTest.php
tests/integration/Cron/Workers/InactiveSubscribersTest.php
tests/integration/Cron/Workers/SchedulerTest.php
tests/integration/Cron/Workers/SimpleWorkerTest.php

[MAILPOET-2367]
[MAILPOET-2367]: https://mailpoet.atlassian.net/browse/MAILPOET-2367

Allow modifying cron limits [MAILPOET-2367]

---

tasks/pack_translations.sh

[MAILPOET-2384]
[MAILPOET-2384]: https://mailpoet.atlassian.net/browse/MAILPOET-2384

Rename `de` translation as `de_DE-formal` [MAILPOET-2384]

---

assets/css/src/components/_settings.scss
lib/AdminPages/Pages/Settings.php
views/settings/woocommerce.html

[MAILPOET-2284]
[MAILPOET-2284]: https://mailpoet.atlassian.net/browse/MAILPOET-2284

Add setting to use editor for WooCommerce emails [MAILPOET-2284]

---

assets/js/src/newsletters/types.jsx
lib/Twig/Assets.php
views/layout.html
views/newsletters.html

[MAILPOET-2376]
[MAILPOET-2376]: https://mailpoet.atlassian.net/browse/MAILPOET-2376

Prefetch scripts early [MAILPOET-2376]

---

lib/Router/Router.php

[MAILPOET-2393]
[MAILPOET-2393]: https://mailpoet.atlassian.net/browse/MAILPOET-2393

Use better function to check url parametter [MAILPOET-2393]

---

assets/js/src/context/getConstantsContext.jsx
assets/js/src/context/getFeaturesContext.jsx
assets/js/src/context/getSegmentsContext.jsx
assets/js/src/context/getUsersContext.jsx
assets/js/src/context/index.jsx
assets/js/src/newsletters/send/congratulate/success.jsx
assets/js/src/subscribers/importExport/import/step_data_manipulation/select_segment.jsx
assets/js/src/subscribers/importExport/import/step_method_selection/select_import_method.jsx

[MAILPOET-2388]
[MAILPOET-2388]: https://mailpoet.atlassian.net/browse/MAILPOET-2388

Merge React contexts into a global one [MAILPOET-2388]

---

lib/Models/Subscriber.php

[MAILPOET-1953]
[MAILPOET-1953]: https://mailpoet.atlassian.net/browse/MAILPOET-1953

Handle incorrect group gracefully [MAILPOET-1953]

---

lib/Cron/Workers/SendingQueue/Tasks/Links.php
lib/Cron/Workers/StatsNotifications/Worker.php
lib/Models/NewsletterLink.php
lib/Newsletter/Links/Links.php
lib/Newsletter/Shortcodes/ShortcodesHelper.php
tests/integration/Cron/Workers/SendingQueue/Tasks/LinksTest.php
tests/integration/Newsletter/Links/LinksTest.php

[MAILPOET-2245](https://mailpoet.atlassian.net/browse/MAILPOET-2245)

Ensure that unsubscribe link is always saved [MAILPOET-2245]

---

assets/js/src/newsletters/types.jsx

[MAILPOET-2273]
[MAILPOET-2273]: https://mailpoet.atlassian.net/browse/MAILPOET-2273

Disable buttons after first click [MAILPOET-2273]

---

assets/js/src/ajax.js
assets/js/src/newsletters/templates.jsx
assets/js/src/newsletters/templates/template_box.jsx
assets/js/src/newsletters/types.jsx
lib/API/JSON/API.php
lib/API/JSON/Endpoint.php
lib/API/JSON/v1/NewsletterTemplates.php
lib/Subscription/Form.php
tests/integration/API/JSON/APITest.php

[MAILPOET-2378]
[MAILPOET-2378]: https://mailpoet.atlassian.net/browse/MAILPOET-2378

Templates speed-up [MAILPOET-2378]

---

assets/css/src/components/newsletterEditor/_layout.scss
assets/css/src/components/newsletterEditor/components/_heading.scss
assets/css/src/components/newsletterEditor/components/_save.scss
assets/js/src/newsletter_editor/components/content.js
assets/js/src/newsletter_editor/components/heading.js
assets/js/src/newsletter_editor/components/save.js
assets/js/src/newsletter_editor/components/sidebar.js
assets/js/src/newsletter_editor/initializer.jsx
lib/Twig/I18n.php
tests/javascript/newsletter_editor/components/heading.spec.js
tests/javascript/newsletter_editor/components/save.spec.js
views/newsletter/editor.html
views/newsletter/templates/components/heading.hbs
views/newsletter/templates/components/save.hbs
views/newsletter/templates/components/sidebar/sidebar.hbs

[MAILPOET-2281]
[MAILPOET-2281]: https://mailpoet.atlassian.net/browse/MAILPOET-2281

Editor for Woocommerce transactional emails [MAILPOET-2281]

---

tasks/fix-full-path-disclosure.php

[MAILPOET-2414]
[MAILPOET-2414]: https://mailpoet.atlassian.net/browse/MAILPOET-2414

Skip mailpoet-cron.php when prefixing files [MAILPOET-2414]

---

views/segments.html

[MAILPOET-2410]
[MAILPOET-2410]: https://mailpoet.atlassian.net/browse/MAILPOET-2410

Add new default Beacon KB on Lists pages [MAILPOET-2410]

---

tests/DataFactories/Settings.php
tests/acceptance/ManageSubscriptionLinkCest.php
tests/acceptance/ReceivePostNotificationCest.php
tests/acceptance/ReceiveStandardEmailCest.php
tests/acceptance/RevenueTrackingCookieCest.php
tests/acceptance/SettingsInactiveSubscribersChangeCest.php
tests/acceptance/WooCommerceListImportPageCest.php

[MAILPOET-2400]
[MAILPOET-2400]: https://mailpoet.atlassian.net/browse/MAILPOET-2400

Fix slow acceptance tests [MAILPOET-2400]

---

lib/DI/ContainerConfigurator.php
lib/Form/AssetsController.php
lib/Form/Widget.php
lib/Subscription/Pages.php

[MAILPOET-2250](https://mailpoet.atlassian.net/browse/MAILPOET-2250)

Add JS/CSS assets to subscription pages [MAILPOET-2250]

---

tasks/makepot/node_modules/grunt-wp-i18n/vendor/wp-i18n-tools/extract.php
views/premium.html

[MAILPOET-2416]
[MAILPOET-2416]: https://mailpoet.atlassian.net/browse/MAILPOET-2416

Missing twig translations [MAILPOET-2416]

---

readme.txt

[MAILPOET-2412]
[MAILPOET-2412]: https://mailpoet.atlassian.net/browse/MAILPOET-2412

Update tags on readme.txt [MAILPOET-2412]

---

prefixer/fix-swiftmailer.php

[MAILPOET-2442]
[MAILPOET-2442]: https://mailpoet.atlassian.net/browse/MAILPOET-2442

Remove unused invalid Swiftmailer file [MAILPOET-2442]

---

assets/css/src/components/_common.scss
assets/css/src/components/newsletterEditor/_common.scss
views/newsletter/templates/components/sidebar/preview.hbs

[MAILPOET-2427]
[MAILPOET-2427]: https://mailpoet.atlassian.net/browse/MAILPOET-2427

Fix Send preview help icon position [MAILPOET-2427]

---

prefixer/fix-swiftmailer.php
tests/acceptance/ReceiveStandardEmailCest.php
tests/integration/Mailer/Methods/AmazonSESTest.php
tests/integration/Mailer/Methods/MailPoetAPITest.php
tests/integration/Mailer/Methods/PHPMailTest.php
tests/integration/Mailer/Methods/SMTPTest.php
tests/integration/Mailer/Methods/SendGridTest.php

[MAILPOET-2448]
[MAILPOET-2448]: https://mailpoet.atlassian.net/browse/MAILPOET-2448

Fix swiftmailer [MAILPOET-2448]

---

assets/js/src/subscribers/importExport/import/step_data_manipulation/do_import.jsx
assets/js/src/subscribers/importExport/import/step_data_manipulation/generate_column_selection.jsx
assets/js/src/subscribers/importExport/import/step_data_manipulation/match_table.jsx
lib/Subscribers/ImportExport/Import/Import.php

[MAILPOET-2432](https://mailpoet.atlassian.net/browse/MAILPOET-2432)

Fix importing dates columns [MAILPOET-2432]

---

lib/Cron/Workers/WooCommerceOrders.php
lib/Models/StatisticsClicks.php
lib/Models/StatisticsWooCommercePurchases.php
lib/Statistics/Track/WooCommercePurchases.php
tests/integration/Cron/Workers/WooCommerceOrdersTest.php
tests/integration/Statistics/Track/WooCommercePurchasesTest.php

[MAILPOET-2446]
[MAILPOET-2446]: https://mailpoet.atlassian.net/browse/MAILPOET-2446

Fix woocommerce stats [MAILPOET-2446]

---

lib/Models/Subscriber.php

[MAILPOET-2457]
[MAILPOET-2457]: https://mailpoet.atlassian.net/browse/MAILPOET-2457

Make isWPUser return false for 0 [MAILPOET-2457]

---

lib/Cron/Daemon.php
lib/Cron/Triggers/WordPress.php
lib/Cron/Workers/WooCommerceOrders.php
lib/Cron/Workers/WooCommercePastOrders.php
lib/Cron/Workers/WorkersFactory.php
tests/integration/Cron/DaemonHttpRunnerTest.php
tests/integration/Cron/DaemonTest.php
tests/integration/Cron/Workers/WooCommerceOrdersTest.php

[MAILPOET-2465]
[MAILPOET-2465]: https://mailpoet.atlassian.net/browse/MAILPOET-2465

Woocommerce orders restart [MAILPOET-2465]

---

tests/integration/DynamicSegments/Persistence/Loading/SubscribersCountTest.php
tests/integration/DynamicSegments/Persistence/Loading/SubscribersIdsTest.php
tests/integration/Models/SubscribersInDynamicSegmentTest.php

[MAILPOET-2466]
[MAILPOET-2466]: https://mailpoet.atlassian.net/browse/MAILPOET-2466

Fix multisite tests [MAILPOET-2466]

---

assets/js/src/newsletters/types.jsx
assets/js/src/settings/tabs.js
lib/AdminPages/Pages/NewsletterEditor.php
lib/AdminPages/Pages/Settings.php
tests/DataFactories/Settings.php
tests/acceptance/WooCommerceEmailCustomizationCest.php

[MAILPOET-2408]
[MAILPOET-2408]: https://mailpoet.atlassian.net/browse/MAILPOET-2408

Block access to WC Email customizer if disabled [MAILPOET-2408]

---

assets/js/src/newsletter_editor/blocks/woocommerceContent.js
assets/js/src/newsletter_editor/webpack_index.jsx
lib/AdminPages/Pages/NewsletterEditor.php
lib/WooCommerce/TransactionalEmails.php
tests/javascript/newsletter_editor/blocks/woocommerceContent.spec.js
views/newsletter/editor.html
views/newsletter/templates/blocks/woocommerceContent/block.hbs
views/newsletter/templates/blocks/woocommerceContent/widget.hbs

[MAILPOET-2279]
[MAILPOET-2279]: https://mailpoet.atlassian.net/browse/MAILPOET-2279

Create WC Content widget [MAILPOET-2279]

---

assets/js/src/newsletters/templates.jsx

[MAILPOET-2467]
[MAILPOET-2467]: https://mailpoet.atlassian.net/browse/MAILPOET-2467

Remove WC templates from saved templates tab [MAILPOET-2467]

---

package.json

[MAILPOET-2406]
[MAILPOET-2406]: https://mailpoet.atlassian.net/browse/MAILPOET-2406

Use npm 6.12 [MAILPOET-2406]

---

assets/js/src/newsletters/automatic_emails.jsx
assets/js/src/newsletters/send/ga_tracking.jsx
assets/js/src/newsletters/send/notification.jsx
assets/js/src/newsletters/send/standard.jsx
assets/js/src/newsletters/send/welcome.jsx
lib/API/JSON/ResponseBuilders/NewslettersResponseBuilder.php
lib/Config/Migrator.php
lib/Config/Populator.php
lib/Cron/Workers/SendingQueue/Tasks/Newsletter.php
lib/Entities/NewsletterEntity.php
lib/Models/Newsletter.php
lib/Statistics/GATracking.php
lib/Util/SecondLevelDomainNames.php
tests/integration/API/JSON/v1/NewslettersTest.php
tests/integration/Statistics/GATrackingTest.php
tests/unit/Util/SecondLevelDomainNamesTest.php
views/newsletters.html

[MAILPOET-2397]
[MAILPOET-2397]: https://mailpoet.atlassian.net/browse/MAILPOET-2397

Move Google Analytics Tracking from Premium [MAILPOET-2397]

---

lib/Config/Populator.php

[MAILPOET-2501]
[MAILPOET-2501]: https://mailpoet.atlassian.net/browse/MAILPOET-2501

Fix serialization errors in integration tests [MAILPOET-2501]

---

assets/js/src/newsletters/automatic_emails/listings.jsx
assets/js/src/newsletters/automatic_emails/send_event_conditions.jsx

[MAILPOET-2499]
[MAILPOET-2499]: https://mailpoet.atlassian.net/browse/MAILPOET-2499

Fix saving options for WooCommerce product/category emails [MAILPOET-2499]

---

lib/Cron/CronTrigger.php
mailpoet-cron.php

[[MAILPOET-2507]](https://mailpoet.atlassian.net/browse/MAILPOET-2507)
[MAILPOET-2507]: https://mailpoet.atlassian.net/browse/MAILPOET-2507

Add configuration check to Linux Cron [MAILPOET-2507]

---

lib/DynamicSegments/Persistence/Loading/SubscribersCount.php
lib/DynamicSegments/Persistence/Loading/SubscribersIds.php
lib/DynamicSegments/RequirementsChecker.php
lib/Models/SubscribersInDynamicSegment.php
tests/integration/DynamicSegments/Persistence/Loading/SubscribersCountTest.php
tests/integration/DynamicSegments/Persistence/Loading/SubscribersIdsTest.php
tests/unit/DynamicSegments/RequirementsCheckerTest.php

[MAILPOET-2486]
[MAILPOET-2486]: https://mailpoet.atlassian.net/browse/MAILPOET-2486

Dynamic segments with missing woocommerce database [MAILPOET-2486]

---

lib/Subscription/Blacklist.php

[MAILPOET-2508]
[MAILPOET-2508]: https://mailpoet.atlassian.net/browse/MAILPOET-2508

Add new emails to blacklist [MAILPOET-2508]

---

lib/Subscription/Blacklist.php
tests/unit/Subscription/BlacklistTest.php

[MAILPOET-2509]
[MAILPOET-2509]: https://mailpoet.atlassian.net/browse/MAILPOET-2509

Blacklist domains [MAILPOET-2509]

---

lib/AdminPages/Pages/Settings.php
lib/Util/Notices/UnauthorizedEmailInNewslettersNotice.php
lib/Util/Notices/UnauthorizedEmailNotice.php

[MAILPOET-2494]
[MAILPOET-2494]: https://mailpoet.atlassian.net/browse/MAILPOET-2494

Add missing translation domains [MAILPOET-2494]

---

tests/docker/docker-compose.yml

[MAILPOET-2513]
[MAILPOET-2513]: https://mailpoet.atlassian.net/browse/MAILPOET-2513

Update Chrome in acceptance tests [MAILPOET-2513]

---

assets/js/src/listing/listing.jsx
assets/js/src/listing/listing_items.jsx
assets/js/src/newsletters/listings/notification.jsx
assets/js/src/newsletters/listings/notification_history.jsx
assets/js/src/newsletters/listings/standard.jsx
assets/js/src/newsletters/listings/welcome.jsx
views/newsletters.html

[MAILPOET-2472]
[MAILPOET-2472]: https://mailpoet.atlassian.net/browse/MAILPOET-2472

Show different message when no newsletter found [MAILPOET-2472]

---

lib/API/JSON/v1/Newsletters.php

[MAILPOET-2516]
[MAILPOET-2516]: https://mailpoet.atlassian.net/browse/MAILPOET-2516

Do not JSON-decode template body when being passed to a newsletter [MAILPOET-2516]

---

assets/js/src/newsletters/campaign_stats/page.jsx
assets/js/src/newsletters/campaign_stats/premium_banner.jsx
lib/AdminPages/Pages/Newsletters.php
lib/Config/Installer.php
views/newsletters.html

[MAILPOET-2506]
[MAILPOET-2506]: https://mailpoet.atlassian.net/browse/MAILPOET-2506

Display detailed stats only when premium initialized [MAILPOET-2506]

---

package-lock.json
package.json
tests/javascript/mochaTestHelper.js

According to the browser profiler, the problem is withing the TinyMCE code. I updated it and it seems to fix the problem.

Editor performance fix [MAILPOET-2529]

---

assets/js/src/newsletters/campaign_stats/newsletter_stats.jsx
views/newsletters.html

[MAILPOET-2522]
[MAILPOET-2522]: https://mailpoet.atlassian.net/browse/MAILPOET-2522

Fix missing GA translation [MAILPOET-2522]

---

lib/Cron/Workers/SimpleWorker.php

[MAILPOET-2530]
[MAILPOET-2530]: https://mailpoet.atlassian.net/browse/MAILPOET-2530

Trigger Cron workers only when needed [MAILPOET-2530]

---

tests/_support/AcceptanceTester.php
tests/acceptance/ConfirmTitleAlignmentSettingsInALCBlockCest.php
tests/acceptance/ManageSubscriptionLinkCest.php
tests/docker/docker-compose.yml

[MAILPOET-2544]
[MAILPOET-2544]: https://mailpoet.atlassian.net/browse/MAILPOET-2544

Acceptance test on WP 5.3/PHP 7.3 [MAILPOET-2544]

---

lib/Statistics/GATracking.php
tests/integration/Statistics/GATrackingTest.php

[MAILPOET-2540]
[MAILPOET-2540]: https://mailpoet.atlassian.net/browse/MAILPOET-2540

Shortcodes inside links are URL encoded when adding GA params [MAILPOET-2540]

---

lib-3rd-party/Idiorm/idiorm.php

[MAILPOET-2550]
[MAILPOET-2550]: https://mailpoet.atlassian.net/browse/MAILPOET-2550

Fix order of implode params for PHP 7.4 [MAILPOET-2550]

---

tasks/phpstan/phpstan-baseline-tests.neon
tests/_support/ErrorsExtension.php

[MAILPOET-2551]
[MAILPOET-2551]: https://mailpoet.atlassian.net/browse/MAILPOET-2551

Test errors [MAILPOET-2551]

---

assets/js/src/context/index.jsx
assets/js/src/dynamic_segments/dynamic_segments.jsx
assets/js/src/experimental_features/experimental_features.jsx
assets/js/src/form_editor/form_editor.jsx
assets/js/src/forms/forms.jsx
assets/js/src/help/help.jsx
assets/js/src/newsletters/newsletters.jsx
assets/js/src/segments/segments.jsx
assets/js/src/settings/settings.jsx
assets/js/src/subscribers/importExport/import.jsx
assets/js/src/subscribers/subscribers.jsx
assets/js/src/wizard/wizard.jsx

[MAILPOET-2389]
[MAILPOET-2389]: https://mailpoet.atlassian.net/browse/MAILPOET-2389

Provide context to all components

---

assets/css/src/components/_premiumPage.scss
views/premium.html

[MAILPOET-2534]
[MAILPOET-2534]: https://mailpoet.atlassian.net/browse/MAILPOET-2534

Promote agency plan on Premium page [MAILPOET-2534]

---

tests/_support/AcceptanceTester.php

[MAILPOET-2543]
[MAILPOET-2543]: https://mailpoet.atlassian.net/browse/MAILPOET-2543

Fix flaky clicks [MAILPOET-2543]

---

tasks/pack_translations.sh

[MAILPOET-2532]
[MAILPOET-2532]: https://mailpoet.atlassian.net/browse/MAILPOET-2532

Correct file names for formal german translations [MAILPOET-2532]

---

lib/Features/FeaturesController.php
lib/Mailer/WordPress/WordpressMailerReplacer.php
views/settings/advanced.html

[MAILPOET-2536]
[MAILPOET-2536]: https://mailpoet.atlassian.net/browse/MAILPOET-2536

Transactional emails setting [MAILPOET-2536]

---

.eslintrc.es6.json
assets/js/src/form_editor/blocks/blocks.jsx
assets/js/src/form_editor/blocks/email/edit.jsx
assets/js/src/form_editor/blocks/first_name/edit.jsx
assets/js/src/form_editor/blocks/first_name/first_name.jsx
assets/js/src/form_editor/blocks/first_name/icon.jsx
assets/js/src/form_editor/blocks/last_name/edit.jsx
assets/js/src/form_editor/blocks/last_name/icon.jsx
assets/js/src/form_editor/blocks/last_name/last_name.jsx
assets/js/src/form_editor/store/blocks_to_form_body.jsx
assets/js/src/form_editor/store/form_body_to_blocks.jsx
tests/acceptance/FormEditorAddNamesCest.php
tests/acceptance/FormsCreationCest.php
tests/javascript/form_editor/store/blocks_to_form_body.spec.js
tests/javascript/form_editor/store/form_body_to_blocks.spec.js
tests/javascript/form_editor/store/reducers/save_form_started.spec.js
views/form/editor.html

[MAILPOET-2452]
[MAILPOET-2452]: https://mailpoet.atlassian.net/browse/MAILPOET-2452

Add First and Last Name blocks in the Form Editor [MAILPOET-2452]

---

lib/Mailer/MetaInfo.php
tests/integration/Mailer/MetaInfoTest.php

[MAILPOET-2541]
[MAILPOET-2541]: https://mailpoet.atlassian.net/browse/MAILPOET-2541

Fix source being reported as NULL when sending [MAILPOET-2541]

---

lib/Newsletter/Editor/PostTransformer.php
lib/Subscribers/ImportExport/Export/DynamicSubscribersGetter.php
lib/Tasks/Sending.php
lib/WP/DateTime.php
lib/WP/Emoji.php
tasks/phpstan/phpstan.neon

[MAILPOET-2568]
[MAILPOET-2568]: https://mailpoet.atlassian.net/browse/MAILPOET-2568

Php stan config update  [MAILPOET-2568]

---

assets/css/src/components/_premiumPage.scss
views/premium.html

[MAILPOET-2505]
[MAILPOET-2505]: https://mailpoet.atlassian.net/browse/MAILPOET-2505

Premium page buttons [MAILPOET-2505]

---

.circleci/config.yml
tests/docker/docker-compose.yml

[MAILPOET-2301]
[MAILPOET-2301]: https://mailpoet.atlassian.net/browse/MAILPOET-2301

Run nightly acceptance tests [MAILPOET-2301]

---

mailpoet.php
readme.txt

[MAILPOET-2573]
[MAILPOET-2573]: https://mailpoet.atlassian.net/browse/MAILPOET-2573

Bump 'tested up to' WordPress version to 5.3 [MAILPOET-2573]

---

views/premium.html

[MAILPOET-2559]
[MAILPOET-2559]: https://mailpoet.atlassian.net/browse/MAILPOET-2559

Change Agency button on Premium page [MAILPOET-2559]

---

lib/Newsletter/Renderer/StylesHelper.php
tests/unit/Newsletter/Renderer/StylesHelperTest.php

[MAILPOET-2562]
[MAILPOET-2562]: https://mailpoet.atlassian.net/browse/MAILPOET-2562

Fix conditional font-include comment for Outlook [MAILPOET-2562]

---

assets/css/src/components/_notice.scss
assets/js/src/context/index.jsx
assets/js/src/context/useNotices.jsx
assets/js/src/dynamic_segments/dynamic_segments.jsx
assets/js/src/experimental_features/experimental_features.jsx
assets/js/src/form_editor/form_editor.jsx
assets/js/src/forms/forms.jsx
assets/js/src/help/help.jsx
assets/js/src/newsletters/listings/standard.jsx
assets/js/src/newsletters/newsletters.jsx
assets/js/src/notices/api_errors_notice.jsx
assets/js/src/notices/mailer_status_notice.jsx
assets/js/src/notices/notice.jsx
assets/js/src/notices/notices.jsx
assets/js/src/notices/subscribers_limit_notice.jsx
assets/js/src/segments/segments.jsx
assets/js/src/settings/settings.jsx
assets/js/src/subscribers/importExport/import.jsx
assets/js/src/subscribers/subscribers.jsx
assets/js/src/wizard/wizard.jsx
views/layout.html

[MAILPOET-2390]
[MAILPOET-2390]: https://mailpoet.atlassian.net/browse/MAILPOET-2390

Implement the `useNotices` hook [MAILPOET-2390]

---

lib/Util/Polyfills.php

[MAILPOET-2579]
[MAILPOET-2579]: https://mailpoet.atlassian.net/browse/MAILPOET-2579

Use Symfony\Polyfill\Mbstring from prefixed namespace [MAILPOET-2579]

---

lib/Cron/CronWorkerInterface.php
lib/Cron/CronWorkerRunner.php
lib/Cron/Daemon.php
lib/Cron/Workers/SendingQueue/Migration.php
lib/Cron/Workers/SimpleWorker.php
lib/DI/ContainerConfigurator.php
tests/integration/Cron/CronWorkerRunnerTest.php
tests/integration/Cron/CronWorkerSchedulerTest.php
tests/integration/Cron/DaemonHttpRunnerTest.php
tests/integration/Cron/DaemonTest.php
tests/integration/Cron/Workers/AuthorizedSendingEmailsCheckTest.php
tests/integration/Cron/Workers/BounceTest.php
tests/integration/Cron/Workers/SendingQueue/MigrationTest.php
tests/integration/Cron/Workers/SimpleWorkerTest.php
tests/integration/Cron/Workers/StatsNotifications/AutomatedEmailsTest.php
tests/integration/Cron/Workers/WooCommerceOrdersTest.php
tests/integration/Models/ScheduledTaskTest.php

[MAILPOET-2539]
[MAILPOET-2539]: https://mailpoet.atlassian.net/browse/MAILPOET-2539

Cron split [MAILPOET-2539]

---

lib/Mailer/WordPress/FallbackMailer.php
lib/Mailer/WordPress/WordpressMailerReplacer.php
tests/integration/Mailer/WordPress/WordpressMailerTest.php

[MAILPOET-2581]
[MAILPOET-2581]: https://mailpoet.atlassian.net/browse/MAILPOET-2581

Make fallback mailer initialization lazy to avoid crashing the plugin [MAILPOET-2581]

---

assets/js/src/newsletters/send/congratulate/success.jsx
assets/js/src/wizard/steps_numbers.jsx
lib/Features/FeaturesController.php

[MAILPOET-2336]
[MAILPOET-2336]: https://mailpoet.atlassian.net/browse/MAILPOET-2336

Remove MSS pitch feature flag [MAILPOET-2336]

---

assets/js/src/newsletter_editor/initializer.jsx

[MAILPOET-2557]
[MAILPOET-2557]: https://mailpoet.atlassian.net/browse/MAILPOET-2557

Remove container defaults on editor initialization [MAILPOET-2557]

---

assets/js/src/newsletters/automatic_emails/listings.jsx
assets/js/src/newsletters/listings/notification.jsx
assets/js/src/newsletters/listings/standard.jsx
assets/js/src/newsletters/listings/welcome.jsx
assets/js/src/newsletters/newsletters.jsx
assets/js/src/newsletters/types.jsx
lib/AdminPages/Pages/Newsletters.php
tests/acceptance/ConfirmNewsletterAutosaveCest.php
tests/acceptance/CreateWelcomeEmailCest.php
tests/acceptance/CreateWooCommerceNewsletterCest.php
tests/acceptance/ManageSubscriptionLinkCest.php
tests/acceptance/ManageWelcomeEmailCest.php
tests/acceptance/NewsletterCreationCest.php
tests/acceptance/NewsletterSendingErrorCest.php
tests/acceptance/NewslettersListingCest.php
tests/acceptance/ReceiveStandardEmailCest.php
tests/acceptance/ReinstallFromScratchCest.php
tests/acceptance/SaveNewsletterAsDraftCest.php
tests/acceptance/TemplatesPagesLoadCest.php
tests/acceptance/WooCommerceEmailCustomizationCest.php
tests/acceptance/WooCommerceListImportPageCest.php
views/newsletters.html

[MAILPOET-2383]
[MAILPOET-2383]: https://mailpoet.atlassian.net/browse/MAILPOET-2383

Better empty listings [MAILPOET-2383]

---

lib/Models/ModelValidator.php

[MAILPOET-2449]
[MAILPOET-2449]: https://mailpoet.atlassian.net/browse/MAILPOET-2449

Add 'nospam' to the list of role-based emails [MAILPOET-2449]

---

assets/css/src/components/formEditor/components/_custom_field.scss
assets/js/src/form_editor/blocks/blocks.jsx
assets/js/src/form_editor/blocks/custom_date/custom_date.jsx
assets/js/src/form_editor/blocks/custom_date/custom_field_settings.jsx
assets/js/src/form_editor/blocks/custom_date/edit.jsx
assets/js/src/form_editor/store/blocks_to_form_body.jsx
assets/js/src/form_editor/store/form_body_to_blocks.jsx
assets/js/src/form_editor/store/selectors.jsx
assets/js/src/form_editor/store/store.jsx
lib/AdminPages/Pages/FormEditor.php
tests/javascript/form_editor/store/blocks_to_form_body.spec.js
tests/javascript/form_editor/store/form_body_to_blocks.spec.js
views/form/editor.html

[MAILPOET-2453]
[MAILPOET-2453]: https://mailpoet.atlassian.net/browse/MAILPOET-2453

Form editor custom date field [MAILPOET-2453]

---

package-lock.json
package.json

[MAILPOET-2566] [MAILPOET-2558]
[MAILPOET-2566]: https://mailpoet.atlassian.net/browse/MAILPOET-2566
[MAILPOET-2558]: https://mailpoet.atlassian.net/browse/MAILPOET-2558

Update deps [MAILPOET-2566] [MAILPOET-2558]

---

lib/Entities/SubscriberEntity.php
lib/Mailer/MetaInfo.php
lib/Mailer/WordPress/WordPressMailer.php
lib/Mailer/WordPress/WordpressMailerReplacer.php
tests/integration/Mailer/MetaInfoTest.php
tests/integration/Mailer/WordPress/WordpressMailerTest.php

[MAILPOET-2574]
[MAILPOET-2574]: https://mailpoet.atlassian.net/browse/MAILPOET-2574

Wp meta info [MAILPOET-2574]

---

lib/Config/Initializer.php
mailpoet_initializer.php

[MAILPOET-2564]
[MAILPOET-2564]: https://mailpoet.atlassian.net/browse/MAILPOET-2564

Move requirement checker up [MAILPOET-2564]

---

lib/AutomaticEmails/WooCommerce/Events/PurchasedInCategory.php
lib/AutomaticEmails/WooCommerce/Events/PurchasedProduct.php
tasks/code_sniffer/MailPoet/ruleset.xml
tasks/phpstan/woocommerce.php
tests/integration/AutomaticEmails/WooCommerce/Events/PurchasedProductTest.php
tests/integration/_bootstrap.php

[MAILPOET-2586]
[MAILPOET-2586]: https://mailpoet.atlassian.net/browse/MAILPOET-2586

Category purchase error [MAILPOET-2586]

---

.circleci/config.yml

[MAILPOET-2578]
[MAILPOET-2578]: https://mailpoet.atlassian.net/browse/MAILPOET-2578

Use bigger executor for build [MAILPOET-2578]

---

RoboFile.php
lib/Analytics/Analytics.php
lib/Config/MP2Migrator.php
lib/Doctrine/MetadataCache.php
lib/Entities/NewsletterEntity.php
lib/Models/ScheduledTask.php
lib/Models/Subscriber.php
lib/Tracy/ApiPanel/ApiPanel.php
lib/Tracy/DIPanel/DIPanel.php
lib/Tracy/DoctrinePanel/DoctrinePanel.php
tasks/phpstan/composer.json
tasks/phpstan/composer.lock
tasks/phpstan/extensions/PHPUnit5CompatExtension/Type/CreateMockDynamicReturnTypeExtension.php
tasks/phpstan/extensions/PHPUnit5CompatExtension/Type/GetMockBuilderDynamicReturnTypeExtension.php
tasks/phpstan/extensions/PHPUnit5CompatExtension/Type/MockBuilderDynamicReturnTypeExtension.php
tasks/phpstan/extensions/PHPUnit5CompatExtension/extension.neon
tasks/phpstan/extensions/PHPUnit5CompatExtension/stubs/MockBuilder.php
tasks/phpstan/extensions/PHPUnit5CompatExtension/stubs/MockObject.php
tasks/phpstan/extensions/PHPUnit5CompatExtension/stubs/TestCase.php
tasks/phpstan/phpstan-baseline-tests.neon
tasks/phpstan/phpstan-baseline.neon
tasks/phpstan/phpstan-tests.neon
tasks/phpstan/phpstan.neon
tests/_support/IntegrationTester.php
tests/_support/UnitTester.php

[MAILPOET-2588]
[MAILPOET-2588]: https://mailpoet.atlassian.net/browse/MAILPOET-2588

Upgrade phpstan [MAILPOET-2588]

---

assets/js/src/newsletters/send.jsx
assets/js/src/notices/subscribers_limit_notice.jsx
lib/API/JSON/v1/Services.php
lib/AdminPages/Pages/Newsletters.php
lib/Cron/Workers/Beamer.php
lib/Cron/Workers/KeyCheck/KeyCheckWorker.php
lib/Cron/Workers/SimpleWorker.php
lib/Cron/Workers/StatsNotifications/Worker.php
lib/Cron/Workers/UnsubscribeTokens.php
lib/Cron/Workers/WooCommercePastOrders.php
lib/Util/License/Features/Subscribers.php
tests/integration/API/JSON/v1/ServicesTest.php
tests/unit/Util/License/Features/SubscribersTest.php
views/emails/statsNotification.txt
views/newsletters.html

[MAILPOET-2396]
[MAILPOET-2396]: https://mailpoet.atlassian.net/browse/MAILPOET-2396

New limit warning for users with API key [MAILPOET-2396]

---

lib/Util/Polyfills.php

[MAILPOET-2603]
[MAILPOET-2603]: https://mailpoet.atlassian.net/browse/MAILPOET-2603

Add mb_string constants [MAILPOET-2603]

---

lib/Util/License/Features/Subscribers.php
tests/unit/Util/License/Features/SubscribersTest.php
views/newsletters.html

[MAILPOET-2617]
[MAILPOET-2617]: https://mailpoet.atlassian.net/browse/MAILPOET-2617

Hide warning when API key  exists but limit missing [MAILPOET-2617]

---

assets/css/src/components/newsletterEditor/components/_forms.scss

[MAILPOET-2482]
[MAILPOET-2482]: https://mailpoet.atlassian.net/browse/MAILPOET-2482

Apply newsletter editor form overrides only on editor page [MAILPOET-2482]

---

lib/Config/PopulatorData/DefaultForm.php
tests/acceptance/ReinstallFromScratchCest.php
tests/integration/API/JSON/v1/FormsTest.php

[MAILPOET-2592]
[MAILPOET-2592]: https://mailpoet.atlassian.net/browse/MAILPOET-2592

Update default form name spelling [MAILPOET-2592]

---

lib/API/JSON/Endpoint.php

[MAILPOET-2628]
[MAILPOET-2628]: https://mailpoet.atlassian.net/browse/MAILPOET-2628

Allow POST method on GET endpoints [MAILPOET-2628]

---

assets/js/src/notices/subscribers_limit_notice.jsx
lib/AdminPages/Pages/Newsletters.php
lib/Cron/Workers/StatsNotifications/Worker.php
lib/Subscribers/SubscribersRepository.php
lib/Util/License/Features/Subscribers.php
tests/unit/Util/License/Features/SubscribersTest.php
views/emails/statsNotification.txt
views/newsletters.html

[MAILPOET-2624]
[MAILPOET-2624]: https://mailpoet.atlassian.net/browse/MAILPOET-2624

Fix subscribers limit warning [MAILPOET-2624]

---

lib/Form/Widget.php

[MAILPOET-2632]
[MAILPOET-2632]: https://mailpoet.atlassian.net/browse/MAILPOET-2632

Remove redundant keyword [MAILPOET-2632]

---

lib/DynamicSegments/Filters/WooCommerceCategory.php
lib/DynamicSegments/Filters/WooCommerceProduct.php

[MAILPOET-2524]
[MAILPOET-2524]: https://mailpoet.atlassian.net/browse/MAILPOET-2524

Ignore cancelled orders in segments [MAILPOET-2524]

---

lib/Config/Env.php

[MAILPOET-2636]
[MAILPOET-2636]: https://mailpoet.atlassian.net/browse/MAILPOET-2636

Add back compatibility for older Premium plugin with underscore naming [MAILPOET-2636]

---

tests/integration/API/JSON/v1/SegmentsTest.php
tests/integration/Config/MigratorTest.php
tests/integration/DynamicSegments/Persistence/SaverTest.php

[MAILPOET-2640]
[MAILPOET-2640]: https://mailpoet.atlassian.net/browse/MAILPOET-2640

Fix failing master [MAILPOET-2640]

---

lib/Subscription/Manage.php
tests/integration/Subscription/ManageTest.php

[MAILPOET-2537]
[MAILPOET-2537]: https://mailpoet.atlassian.net/browse/MAILPOET-2537

Manage subscription page unsubscribes from hidden lists [MAILPOET-2537]

---

assets/css/src/components/formEditor/components/_block_editor.scss
assets/js/src/form_editor/components/editor.jsx
assets/js/src/form_editor/store/actions.jsx
assets/js/src/form_editor/store/controls.jsx

[MAILPOET-2620]
[MAILPOET-2620]: https://mailpoet.atlassian.net/browse/MAILPOET-2620

Prevent deleting email and submit inputs from form [MAILPOET-2620]

---

lib/Config/Updater.php
lib/Newsletter/ViewInBrowser.php
lib/Subscription/Comment.php
tests/integration/Config/InstallerTest.php
tests/integration/Config/UpdaterTest.php
tests/integration/Cron/Workers/SendingQueue/Tasks/PostsTest.php
tests/integration/Router/Endpoints/ViewInBrowserTest.php

[MAILPOET-2635]
[MAILPOET-2635]: https://mailpoet.atlassian.net/browse/MAILPOET-2635

Camel case fixes [MAILPOET-2635]

---

lib/Util/License/Features/Subscribers.php
tests/unit/Util/License/Features/SubscribersTest.php

[MAILPOET-2637]
[MAILPOET-2637]: https://mailpoet.atlassian.net/browse/MAILPOET-2637

Fix key validity check [MAILPOET-2637]

---

assets/js/src/newsletters/send.jsx
assets/js/src/notices/notice.jsx
assets/js/src/notices/subscribers_limit_notice.jsx

[MAILPOET-2597]
[MAILPOET-2597]: https://mailpoet.atlassian.net/browse/MAILPOET-2597

Render banner near send button [MAILPOET-2597]

---

tests/_support/CleanupExtension.php
tests/_support/CleanupPremiumPluginExtension.php
tests/acceptance.suite.yml

[MAILPOET-2651]
[MAILPOET-2651]: https://mailpoet.atlassian.net/browse/MAILPOET-2651

Do not clean Premium Plugin in Premium acceptance tests [MAILPOET-2651]

---

lib/Subscribers/ImportExport/Import/Import.php

[MAILPOET-2649]
[MAILPOET-2649]: https://mailpoet.atlassian.net/browse/MAILPOET-2649

Fix subscriber import when existing emails contain uppercase chars [MAILPOET-2649]

---

lib/Models/Subscriber.php
lib/Subscribers/SubscribersRepository.php
lib/Util/License/Features/Subscribers.php
tests/unit/Util/License/Features/SubscribersTest.php

[MAILPOET-2631]
[MAILPOET-2631]: https://mailpoet.atlassian.net/browse/MAILPOET-2631

Stop counting WP users for the plugin limit [MAILPOET-2631]

---

lib/Form/Widget.php

Fix form widget rendering [MAILPOET-2654]

---

lib/Models/Segment.php
lib/Segments/WP.php
lib/Subscribers/ConfirmationEmailMailer.php
tests/acceptance/CreateNewWordPressUserCest.php
tests/integration/Segments/WPTest.php

[MAILPOET-2567]
[MAILPOET-2567]: https://mailpoet.atlassian.net/browse/MAILPOET-2567

Send a confirmation email when a user is added to a website [MAILPOET-2567]

---

readme.txt

[MAILPOET-2622]
[MAILPOET-2622]: https://mailpoet.atlassian.net/browse/MAILPOET-2622

Update FAQs [MAILPOET-2622]

---

lib/Models/Model.php
tests/integration/API/JSON/v1/SegmentsTest.php
tests/integration/DynamicSegments/Persistence/SaverTest.php

[MAILPOET-2642]
[MAILPOET-2642]: https://mailpoet.atlassian.net/browse/MAILPOET-2642

Fix duplicate key messages for MySQL >= 8.0.19 [MAILPOET-2642]

---

assets/js/src/form_editor/blocks/add_custom_field/add_custom_field_form.jsx
assets/js/src/form_editor/blocks/blocks.jsx
assets/js/src/form_editor/blocks/custom_checkbox/custom_field_settings.jsx
assets/js/src/form_editor/blocks/custom_date/edit.jsx
assets/js/src/form_editor/blocks/custom_radio/custom_field_settings.jsx
assets/js/src/form_editor/blocks/custom_radio/settings_preview.jsx
assets/js/src/form_editor/blocks/custom_select/edit.jsx
assets/js/src/form_editor/blocks/segment_select/settings_preview.jsx
assets/js/src/form_editor/components/notices.jsx
lib/Form/Block/Date.php
lib/Form/Block/Select.php
tests/acceptance/FormEditorAddNamesCest.php
tests/acceptance/FormEditorCreateCustomFieldCest.php

[MAILPOET-2652]
Note for QA:
point B) is not part of this pull request it will be in another after this and launch PRs will be merged.
[MAILPOET-2652]: https://mailpoet.atlassian.net/browse/MAILPOET-2652

Form improvements [MAILPOET-2652]

---

lib/Config/Populator.php

[MAILPOET-2296]
[MAILPOET-2296]: https://mailpoet.atlassian.net/browse/MAILPOET-2296

Update default WC checkbox on checkout label [MAILPOET-2296]

---

assets/js/src/form_editor/blocks/custom_checkbox/custom_field_settings.jsx
assets/js/src/form_editor/blocks/custom_checkbox/edit.jsx
assets/js/src/form_editor/blocks/custom_date/custom_field_settings.jsx
assets/js/src/form_editor/blocks/custom_date/edit.jsx
assets/js/src/form_editor/blocks/custom_radio/custom_field_settings.jsx
assets/js/src/form_editor/blocks/custom_radio/edit.jsx
assets/js/src/form_editor/blocks/custom_select/edit.jsx
assets/js/src/form_editor/blocks/custom_text/custom_field_settings.jsx
assets/js/src/form_editor/blocks/custom_text/edit.jsx
assets/js/src/form_editor/blocks/custom_textarea/edit.jsx
assets/js/src/form_editor/store/actions.jsx
assets/js/src/form_editor/store/reducer.jsx
assets/js/src/form_editor/store/reducers/custom_field_edited.jsx

[MAILPOET-2662]
[MAILPOET-2662]: https://mailpoet.atlassian.net/browse/MAILPOET-2662

Alert for unsaved changes in custom fields in form editor [MAILPOET-2662]

---

views/settings/advanced.html

[MAILPOET-2598]
[MAILPOET-2598]: https://mailpoet.atlassian.net/browse/MAILPOET-2598

Improve copy of transactional email settings option [MAILPOET-2598]

---

lib/Mailer/Methods/ErrorMappers/MailPoetMapper.php

[MAILPOET-2648]
[MAILPOET-2648]: https://mailpoet.atlassian.net/browse/MAILPOET-2648

Remove unused parameter [MAILPOET-2648]

---

composer.json
lib/Mailer/Methods/AmazonSES.php
lib/Mailer/Methods/SMTP.php
mailpoet_initializer.php
prefixer/composer.json
prefixer/composer.lock
prefixer/fix-swiftmailer.php
tests/unit/_bootstrap.php

[MAILPOET-2589]
[MAILPOET-2589]: https://mailpoet.atlassian.net/browse/MAILPOET-2589

Swiftmailer update [MAILPOET-2589]

---

assets/js/src/segments/form.jsx
assets/js/src/segments/list.jsx
assets/js/src/subscribers/form.jsx
assets/js/src/subscribers/list.jsx
lib/AdminPages/Pages/Segments.php
lib/AdminPages/Pages/Subscribers.php
views/layout.html
views/newsletters.html
views/segments.html
views/subscribers/subscribers.html

[MAILPOET-2626]
[MAILPOET-2626]: https://mailpoet.atlassian.net/browse/MAILPOET-2626

Subscribers limit notice on Subscribers and Lists page [MAILPOET-2626]

---

.circleci/config.yml
composer.json
tasks/phpstan/woocommerce.php

[MAILPOET-2570]
[MAILPOET-2663]

Fix nightly test jobs [MAILPOET-2570] [MAILPOET-2663]

---

assets/css/src/components/formEditor/components/_sidebar.scss
assets/css/src/formEditor.scss

[MAILPOET-2685]
[MAILPOET-2685]: https://mailpoet.atlassian.net/browse/MAILPOET-2685

Add code mirror css [MAILPOET-2685]

---

webpack.config.js

[MAILPOET-2683]
[MAILPOET-2683]: https://mailpoet.atlassian.net/browse/MAILPOET-2683

Remove unnecessary expose of html2canvas

---

lib/API/JSON/ResponseBuilders/NewslettersResponseBuilder.php
lib/API/JSON/v1/Newsletters.php
lib/Entities/NewsletterEntity.php
lib/Entities/StatisticsWooCommercePurchaseEntity.php
lib/Newsletter/Statistics/NewsletterStatistics.php
lib/Newsletter/Statistics/NewsletterStatisticsRepository.php
lib/Newsletter/Statistics/NewsletterWooCommerceRevenue.php
tests/integration/API/JSON/ResponseBuilders/NewslettersResponseBuilderTest.php
tests/integration/_bootstrap.php

[MAILPOET-2503]
[MAILPOET-2503]: https://mailpoet.atlassian.net/browse/MAILPOET-2503

Refactor Statistics to Doctrine [MAILPOET-2503]

---

lib/Util/Polyfills.php

Please test with the `mbstring` extension disabled.

Import missing functions from polyfill-mbstring [MAILPOET-2695]

---

tests/acceptance/DisplayFormBellowPostCest.php

[MAILPOET-2694]
[MAILPOET-2694]: https://mailpoet.atlassian.net/browse/MAILPOET-2694

Increase test timeout [MAILPOET-2694]

---

assets/js/src/form_editor/blocks/email/email.jsx
assets/js/src/form_editor/blocks/submit/submit.jsx
assets/js/src/form_editor/components/editor.jsx

[MAILPOET-2571]
[MAILPOET-2571]: https://mailpoet.atlassian.net/browse/MAILPOET-2571

Prevent duplication of email and submit blocks [MAILPOET-2571]

---

lib/Form/DisplayFormInWPContent.php
tests/unit/Form/DisplayFormInWPContentTest.php

[MAILPOET-2699]
[MAILPOET-2699]: https://mailpoet.atlassian.net/browse/MAILPOET-2699

Allow null content in MailPoet\Form\DisplayFormInWPContent [MAILPOET-2699]

---

lib/API/JSON/v1/Settings.php
tests/integration/API/JSON/v1/SettingsTest.php

[MAILPOET-2594]
[MAILPOET-2594]: https://mailpoet.atlassian.net/browse/MAILPOET-2594

Remove freemail override on MSS activation [MAILPOET-2594]

---

lib/Cron/Workers/Beamer.php

[MAILPOET-2704]
[MAILPOET-2704]: https://mailpoet.atlassian.net/browse/MAILPOET-2704

Reduce beamer frequency [MAILPOET-2704]

---

readme.txt

[MAILPOET-2670]
[MAILPOET-2670]: https://mailpoet.atlassian.net/browse/MAILPOET-2670

Update readme [MAILPOET-2670]

---

lib/Form/DisplayFormInWPContent.php
lib/Form/Widget.php
tests/integration/Form/WidgetTest.php
tests/unit/Form/DisplayFormInWPContentTest.php
views/form/front_end_form.html

[MAILPOET-2706]
[MAILPOET-2706]: https://mailpoet.atlassian.net/browse/MAILPOET-2706
Please test widget and below post forms actually work.

Fix rendering and assets loading for forms below page/post [MAILPOET-2706]

---

tests/unit/Form/Block/DateTest.php
tests/unit/Form/RendererTest.php

[MAILPOET-2712]
[MAILPOET-2712]: https://mailpoet.atlassian.net/browse/MAILPOET-2712

Fix nightly unit tests [MAILPOET-2712]

---

lib/Doctrine/ConnectionFactory.php
lib/Doctrine/Types/SerializedArrayType.php
lib/Entities/FormEntity.php
lib/Form/DisplayFormInWPContent.php
tests/unit/Form/DisplayFormInWPContentTest.php

[MAILPOET-2710]
[MAILPOET-2710]: https://mailpoet.atlassian.net/browse/MAILPOET-2710

Fix ConversionException in forms data [MAILPOET-2710]

---

lib/Cron/Workers/Scheduler.php
lib/Cron/Workers/SendingQueue/SendingQueue.php
tasks/phpstan/phpstan-baseline-integration-tests.neon
tests/integration/Cron/Workers/SchedulerTest.php
tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php

[MAILPOET-2705]
[MAILPOET-2705]: https://mailpoet.atlassian.net/browse/MAILPOET-2705

Check if bounce sync is scheduled within 42 hours for all emails when sending [MAILPOET-2705]

---

lib/AdminPages/Pages/Settings.php
lib/Segments/WP.php
tests/DataFactories/Settings.php
tests/acceptance/CreateNewWordPressUserCest.php
tests/integration/Segments/WPTest.php
views/settings/basics.html

[MAILPOET-2700]
[MAILPOET-2700]: https://mailpoet.atlassian.net/browse/MAILPOET-2700

Fix signup confirmation email for WP users trigger [MAILPOET-2700]

---

assets/js/src/newsletter_editor/blocks/automatedLatestContentLayout.js
assets/js/src/newsletter_editor/blocks/posts.js
lib/Newsletter/Editor/PostTransformer.php
tests/integration/Newsletter/Editor/PostContentTransformerTest.php
tests/javascript_newsletter_editor/newsletter_editor/blocks/automatedLatestContentLayout.spec.js
tests/javascript_newsletter_editor/newsletter_editor/blocks/posts.spec.js
views/newsletter/templates/blocks/automatedLatestContentLayout/settings.hbs
views/newsletter/templates/blocks/posts/settingsDisplayOptions.hbs

[MAILPOET-2491]
[MAILPOET-2491]: https://mailpoet.atlassian.net/browse/MAILPOET-2491

Featured image full post [MAILPOET-2491]

---

assets/js/src/context/getFeaturesContext.jsx
assets/js/src/context/getSegmentsContext.jsx
assets/js/src/context/getUsersContext.jsx
assets/js/src/context/index.jsx
assets/js/src/context/useFeaturesContext.jsx
assets/js/src/context/useNotices.jsx
assets/js/src/context/useSegmentsContext.jsx
assets/js/src/context/useUsersContext.jsx
assets/js/src/experimental_features/experimental_features.jsx
assets/js/src/listing/listing.jsx
assets/js/src/newsletters/automatic_emails/events_conditions.jsx
assets/js/src/newsletters/send.jsx
assets/js/src/newsletters/templates.jsx
assets/js/src/newsletters/templates/import_template.jsx
assets/js/src/newsletters/templates/template_box.jsx
assets/js/src/newsletters/types.jsx
assets/js/src/newsletters/types/notification/notification.jsx
assets/js/src/newsletters/types/standard.jsx

[MAILPOET-2391]
[MAILPOET-2391]: https://mailpoet.atlassian.net/browse/MAILPOET-2391

Remove MailPoet.Notice from React components [MAILPOET-2391]

---

assets/css/src/components/newsletterEditor/components/_blockTools.scss
tests/integration/Subscription/ThrottlingTest.php

[MAILPOET-2723]
[MAILPOET-2723]: https://mailpoet.atlassian.net/browse/MAILPOET-2723

Fix font color when deleting editor block [MAILPOET-2723]

---

lib/Mailer/Methods/AmazonSES.php
lib/Settings/Hosts.php

Added additional Amazon SES regions, which were recently added by Amazon.
Overview of all Amazon SES regions: https://docs.aws.amazon.com/general/latest/gr/ses.html

Added additional Amazon SES regions

---

mailpoet.php

[MAILPOET-2753]
[MAILPOET-2753]: https://mailpoet.atlassian.net/browse/MAILPOET-2753

Update wordpress tested version [MAILPOET-2753]

---

lib/Subscription/Manage.php

[MAILPOET-2664]
[MAILPOET-2664]: https://mailpoet.atlassian.net/browse/MAILPOET-2664

Fix unsubscribe from hidden lists [MAILPOET-2664]

---

assets/css/src/components/formEditor/components/_sidebar.scss
assets/js/src/form_editor/components/sidebar.jsx
views/form/editor.html

[MAILPOET-2735]
[MAILPOET-2735]: https://mailpoet.atlassian.net/browse/MAILPOET-2735

Remove Feedback section from form editor [MAILPOET-2735]

---

views/form/editor.html
views/forms.html

[MAILPOET-2713]
[MAILPOET-2713]: https://mailpoet.atlassian.net/browse/MAILPOET-2713

Add KB about the new form [MAILPOET-2713]

---

lib/Doctrine/Types/JsonType.php

[MAILPOET-2674]
[MAILPOET-2674]: https://mailpoet.atlassian.net/browse/MAILPOET-2674

Sanitise database values before they are decoded [MAILPOET-2674]

---

assets/js/src/form_editor/blocks/add_custom_field/add_custom_field_form.jsx
assets/js/src/form_editor/blocks/custom_text/custom_field_settings.jsx

[MAILPOET-2719]
[MAILPOET-2719]: https://mailpoet.atlassian.net/browse/MAILPOET-2719

Fix creating textarea custom field [MAILPOET-2719]

---

lib/Subscription/Pages.php

[MAILPOET-2747]
[MAILPOET-2747]: https://mailpoet.atlassian.net/browse/MAILPOET-2747

Use name as fallback label [MAILPOET-2747]

---

assets/css/src/components/newsletterEditor/components/_sidebar.scss

Remove absolute positioning [MAILPOET-2744]

---

assets/css/src/components/formEditor/components/_block_editor.scss
assets/js/src/form_editor/blocks/blocks.jsx
assets/js/src/form_editor/blocks/heading/heading.jsx
assets/js/src/form_editor/store/blocks_to_form_body.jsx
assets/js/src/form_editor/store/form_body_to_blocks.jsx
lib/DI/ContainerConfigurator.php
lib/Form/Block/Heading.php
lib/Form/BlocksRenderer.php
tests/javascript/form_editor/store/block_to_form_test_data.js
tests/javascript/form_editor/store/blocks_to_form_body.spec.js
tests/javascript/form_editor/store/form_body_to_blocks.spec.js
tests/javascript/form_editor/store/form_to_block_test_data.js
tests/unit/Form/Block/HeadingTest.php

[MAILPOET-2613]
[MAILPOET-2613]: https://mailpoet.atlassian.net/browse/MAILPOET-2613

Forms heading [MAILPOET-2613]

---

lib/API/JSON/ResponseBuilders/NewslettersResponseBuilder.php
lib/Doctrine/EntityTraits/SafeToOneAssociationLoadTrait.php
lib/Entities/NewsletterSegmentEntity.php

[MAILPOET-2793]
[MAILPOET-2793]: https://mailpoet.atlassian.net/browse/MAILPOET-2793

Fix segment error [MAILPOET-2793]

---

tests/DataFactories/Form.php
tests/acceptance/FormWithColumnsCest.php

[MAILPOET-2797]
[MAILPOET-2797]: https://mailpoet.atlassian.net/browse/MAILPOET-2797

Fix flaky acceptance test [MAILPOET-2797]

---

assets/js/src/form/fields/selection.jsx

[MAILPOET-2762]
[MAILPOET-2762]: https://mailpoet.atlassian.net/browse/MAILPOET-2762

Fix product/category fields in segments form [MAILPOET-2762]

---

lib/Models/Newsletter.php

This reverts commit 99f4a377c7b43c999ce8c9ed62f2bca8c7bb1331.
[MAILPOET-2815]

Revert "Remove functionality from old model"

---

assets/js/src/form_editor/blocks/blocks.jsx
assets/js/src/form_editor/blocks/heading/heading.jsx
assets/js/src/form_editor/blocks/paragraph/paragraph.tsx
assets/js/src/form_editor/components/form_settings/styles_settings_panel.jsx
assets/js/src/form_editor/components/preview.jsx
assets/js/src/form_editor/store/blocks_to_form_body.jsx
assets/js/src/form_editor/store/controls.jsx
assets/js/src/form_editor/store/form_body_to_blocks.jsx
assets/js/src/form_editor/store/store.jsx
lib/DI/ContainerConfigurator.php
lib/Form/Block/Paragraph.php
lib/Form/BlocksRenderer.php
tests/javascript/form_editor/store/block_to_form_test_data.js
tests/javascript/form_editor/store/blocks_to_form_body.spec.js
tests/javascript/form_editor/store/form_body_to_blocks.spec.js
tests/javascript/form_editor/store/form_to_block_test_data.js
tests/unit/Form/Block/ParagraphTest.php

[MAILPOET-2614]
[MAILPOET-2614]: https://mailpoet.atlassian.net/browse/MAILPOET-2614

Add paragraph block to the form editor [MAILPOET-2614]

---

doc/UsageExamples.md

Changed variable name of $subscriber to $getsubscriber, so the subscriber array isn't overwritten.

Update UsageExamples.md [MAILPOET-2820]

---

lib/Newsletter/ViewInBrowser/ViewInBrowserController.php
tests/integration/Newsletter/ViewInBrowser/ViewInBrowserControllerTest.php

[MAILPOET-2761]
[MAILPOET-2761]: https://mailpoet.atlassian.net/browse/MAILPOET-2761

Require that subscriber received a newsletter only for non-preview links [MAILPOET-2761]

---

assets/js/src/newsletter_editor/components/sidebar.js
assets/js/src/newsletters/send.jsx
lib/AdminPages/Pages/NewsletterEditor.php
lib/AdminPages/Pages/Newsletters.php
lib/Config/ServicesChecker.php
tests/DataFactories/Settings.php
tests/acceptance/NewsletterCreationCest.php
views/newsletter/editor.html
views/newsletter/templates/components/sidebar/preview.hbs
views/newsletters.html

[MAILPOET-2729]
[MAILPOET-2729]: https://mailpoet.atlassian.net/browse/MAILPOET-2729

Unapproved key notices [MAILPOET-2729]

---

assets/css/src/components-plugin/_browser-preview.scss

[MAILPOET-2763]
[MAILPOET-2763]: https://mailpoet.atlassian.net/browse/MAILPOET-2763

Fix mobile preview width, remove unnecessary padding [MAILPOET-2763]

---

lib/DI/ContainerConfigurator.php
lib/Newsletter/Renderer/Blocks/Text.php
lib/WooCommerce/TransactionalEmails.php
tests/integration/WooCommerce/TransactionalEmailsTest.php
tests/unit/Newsletter/Renderer/Blocks/TextTest.php

[MAILPOET-2821]
[MAILPOET-2821]: https://mailpoet.atlassian.net/browse/MAILPOET-2821

Fix WooCommerce customised emails [MAILPOET-2821]

---

assets/js/src/newsletters/listings/standard.jsx
assets/js/src/notices/transactional_emails_propose_opt_in_notice.tsx
lib/AdminPages/Pages/Newsletters.php
lib/Settings/UserFlagsController.php
views/newsletters.html

Transactional emails: propose opt-in [MAILPOET-2724]

---

assets/css/src/components-plugin/_listing-newsletters.scss
assets/css/src/mailpoet-plugin.scss

[MAILPOET-2822]
[MAILPOET-2822]: https://mailpoet.atlassian.net/browse/MAILPOET-2822

Add missing file after styles refactor [MAILPOET-2822]

---

assets/js/src/form_editor/components/preview.jsx
lib/Form/Renderer.php

[MAILPOET-2755]
[MAILPOET-2755]: https://mailpoet.atlassian.net/browse/MAILPOET-2755

Ensure honeypot field is not visible [MAILPOET-2755]

---

assets/css/src/components-form-editor/_sidebar.scss
assets/css/src/components-public/_public.scss
assets/js/src/form_editor/components/form_settings/form_placement_options/below_pages.tsx
assets/js/src/form_editor/components/form_settings/form_placement_options/form_placement_settings.tsx
assets/js/src/form_editor/components/form_settings/form_placement_options/popup.tsx
assets/js/src/form_editor/components/form_settings/form_placement_options/popup_icon.tsx
assets/js/src/form_editor/components/form_settings/form_placement_panel.jsx
assets/js/src/form_editor/store/actions.jsx
assets/js/src/form_editor/store/map_form_data_after_loading.jsx
assets/js/src/form_editor/store/map_form_data_before_saving.jsx
assets/js/src/form_editor/store/reducer.jsx
assets/js/src/form_editor/store/reducers/form_placement.jsx
assets/js/src/form_editor/store/selectors.jsx
assets/js/src/public.jsx
assets/js/src/webpack_public_index.jsx
lib/Form/DisplayFormInWPContent.php
tests/unit/Form/DisplayFormInWPContentTest.php
views/form/editor.html
views/form/front_end_form.html

[MAILPOET-2741]
[MAILPOET-2741]: https://mailpoet.atlassian.net/browse/MAILPOET-2741

Pop up form [MAILPOET-2741]

---

assets/js/src/subscribers/importExport/import/step_data_manipulation/create_new_segment.jsx
lib/Subscribers/ImportExport/ImportExportFactory.php

[MAILPOET-2795]
[MAILPOET-2795]: https://mailpoet.atlassian.net/browse/MAILPOET-2795

Fix searching in select2 when importing subscribers [MAILPOET-2795]

---

lib/Subscription/Manage.php
tests/integration/Subscription/ManageTest.php

[MAILPOET-2730]
[MAILPOET-2730]: https://mailpoet.atlassian.net/browse/MAILPOET-2730

Fix resubscribing [MAILPOET-2730]

---

assets/css/src/components-plugin/_modal.scss
assets/css/src/components-plugin/_set-from-address-modal.scss
assets/css/src/mailpoet-plugin.scss
assets/css/src/settings/_modal.scss
assets/js/src/common/modal/close_icon.jsx
assets/js/src/common/modal/frame.jsx
assets/js/src/common/modal/header.jsx
assets/js/src/common/modal/modal.jsx
assets/js/src/common/set_from_address_modal.tsx
assets/js/src/old_settings/premium_tab/premium_tab.jsx
lib/API/JSON/v1/Settings.php
lib/Mailer/Mailer.php
lib/Services/AuthorizedEmailsController.php
tests/acceptance/AddSendingKeyCest.php
tests/integration/API/JSON/v1/SettingsTest.php
tests/integration/Services/AuthorizedEmailsControllerTest.php
views/layout.html

[MAILPOET-2804]
[MAILPOET-2804]: https://mailpoet.atlassian.net/browse/MAILPOET-2804

Authorize from modal [MAILPOET-2804]

---

lib/Models/ScheduledTask.php
tasks/phpstan/phpstan-baseline-integration-tests.neon
tests/integration/Models/ScheduledTaskTest.php

[MAILPOET-2709]
[MAILPOET-2709]: https://mailpoet.atlassian.net/browse/MAILPOET-2709

Unpause up to 30 days old scheduled emails [MAILPOET-2709]

---

lib/Cron/Workers/Scheduler.php
lib/Models/Subscriber.php
lib/Segments/WooCommerce.php
lib/WooCommerce/Subscription.php
tests/acceptance/SendCategoryPurchaseEmailCest.php
tests/acceptance/SendFirstPurchaseEmailCest.php
tests/acceptance/SendProductPurchaseEmailCest.php
tests/integration/Segments/WooCommerceTest.php
tests/integration/WooCommerce/SubscriptionTest.php

[MAILPOET-2799]
[MAILPOET-2799]: https://mailpoet.atlassian.net/browse/MAILPOET-2799

Woocommerce double opt in [MAILPOET-2799]

---

assets/css/src/components-plugin/_common.scss
assets/js/src/form/fields/field.jsx
assets/js/src/form/fields/selection.jsx

[MAILPOET-2826]
This fixes:
- enables multiple categories for WC issues
- strange behaviour of list selection in subscriber form 
- padding issue of placeholder in Chrome
- contains a different fix for [MAILPOET-2762]
[MAILPOET-2826]: https://mailpoet.atlassian.net/browse/MAILPOET-2826
[MAILPOET-2762]: https://mailpoet.atlassian.net/browse/MAILPOET-2762

Fix select2 issues [MAILPOET-2826]

---

assets/js/src/common/set_from_address_modal.tsx
assets/js/src/dismissible-notice.jsx
assets/js/src/sending-paused-notices-fix-button.tsx
assets/js/src/webpack_admin_index.jsx
lib/Util/Notices/UnauthorizedEmailInNewslettersNotice.php
lib/Util/Notices/UnauthorizedEmailNotice.php
tests/acceptance/AuthorizedEmailAddressesValidationCest.php
tests/acceptance/UnauthorizedEmailNoticesCest.php
views/layout.html

[MAILPOET-2805]
[MAILPOET-2805]: https://mailpoet.atlassian.net/browse/MAILPOET-2805

Unauthorized notices [MAILPOET-2805]

---

assets/js/src/common/set_from_address_modal.tsx

[MAILPOET-2838]
[MAILPOET-2838]: https://mailpoet.atlassian.net/browse/MAILPOET-2838

Fix missing prop error [MAILPOET-2838]

---

assets/js/src/settings/components/pages_select.tsx

[MAILPOET-2840]
[MAILPOET-2840]: https://mailpoet.atlassian.net/browse/MAILPOET-2840

Use the first page when missing [MAILPOET-2840]

---

assets/js/src/form_editor/store/form_validator.jsx
tests/javascript/form_editor/store/form_validator.spec.js

[MAILPOET-2828]
[MAILPOET-2828]: https://mailpoet.atlassian.net/browse/MAILPOET-2828

Form editor: Allow saving form with segments block instead of list [MAILPOET-2828]

---

assets/js/src/form_editor/blocks/last_name/last_name.jsx

[MAILPOET-2827]
[MAILPOET-2827]: https://mailpoet.atlassian.net/browse/MAILPOET-2827

Unify name fields in form to be non-mandatory as default [MAILPOET-2827]

---

lib/API/JSON/ResponseBuilders/NewslettersResponseBuilder.php
lib/Cron/Workers/StatsNotifications/Worker.php
lib/Entities/NewsletterEntity.php
lib/Entities/NewsletterLinkEntity.php
lib/Entities/NewsletterOptionEntity.php
lib/Entities/SendingQueueEntity.php
lib/Entities/StatisticsClickEntity.php
lib/Entities/StatisticsOpenEntity.php
lib/Entities/StatisticsUnsubscribeEntity.php
lib/Entities/StatisticsWooCommercePurchaseEntity.php
lib/Entities/StatsNotificationEntity.php

[MAILPOET-2818]
[MAILPOET-2818]: https://mailpoet.atlassian.net/browse/MAILPOET-2818

Avoid entity not found errors [MAILPOET-2818]

---

assets/js/src/form_editor/blocks/segment_select/edit.jsx
assets/js/src/form_editor/store/blocks_to_form_body.jsx
assets/js/src/form_editor/store/form_body_to_blocks.jsx
lib/DI/ContainerConfigurator.php
lib/Form/Block/Segment.php
lib/Segments/SegmentsRepository.php
tests/javascript/form_editor/store/block_to_form_test_data.js
tests/javascript/form_editor/store/blocks_to_form_body.spec.js
tests/javascript/form_editor/store/form_body_to_blocks.spec.js
tests/javascript/form_editor/store/form_to_block_test_data.js
tests/unit/Form/Block/SegmentTest.php

[MAILPOET-2801]
[MAILPOET-2801]: https://mailpoet.atlassian.net/browse/MAILPOET-2801

Fix segments names in segments block [MAILPOET-2801]

---

lib/API/JSON/ResponseBuilders/NewslettersResponseBuilder.php

[MAILPOET-2842]
[MAILPOET-2842]: https://mailpoet.atlassian.net/browse/MAILPOET-2842

Optimise listings query [MAILPOET-2842]

---

assets/js/src/form_editor/blocks/custom_checkbox/custom_checkbox.jsx

[MAILPOET-2796]
[MAILPOET-2796]: https://mailpoet.atlassian.net/browse/MAILPOET-2796

Fix custom checkbox creation [MAILPOET-2796]

---

assets/css/src/settings.scss
assets/js/src/settings/pages/key_activation/key_activation.tsx
assets/js/src/settings/store/actions.ts
assets/js/src/settings/store/create_reducer.ts
assets/js/src/settings/store/make_default_state.ts
assets/js/src/settings/store/types.ts
lib/API/JSON/v1/Services.php
lib/Cron/Workers/KeyCheck/SendingServiceKeyCheck.php
tests/acceptance/AddSendingKeyCest.php
tests/integration/API/JSON/v1/ServicesTest.php
tests/integration/Cron/Workers/KeyCheck/SendingServiceKeyCheckTest.php
views/settings.html

[MAILPOET-2806]
[MAILPOET-2806]: https://mailpoet.atlassian.net/browse/MAILPOET-2806

Pending approval warning [MAILPOET-2806]

---

lib/Form/Widget.php

[MAILPOET-2836]
[MAILPOET-2836]: https://mailpoet.atlassian.net/browse/MAILPOET-2836

Send iframe header for form to allow embedding [MAILPOET-2836]

---

RoboFile.php

[MAILPOET-2853]
[MAILPOET-2853]: https://mailpoet.atlassian.net/browse/MAILPOET-2853

Fix release command [MAILPOET-2853]

---

lib/Cron/Workers/StatsNotifications/Worker.php

[MAILPOET-2855]
[MAILPOET-2855]: https://mailpoet.atlassian.net/browse/MAILPOET-2855

Check properly for stats notification entity [MAILPOET-2855]

---

lib/Config/Hooks.php

[MAILPOET-2802]
[MAILPOET-2802]: https://mailpoet.atlassian.net/browse/MAILPOET-2802

Add request feedback link to the footer [MAILPOET-2802]

---

assets/js/src/newsletters/templates.jsx
assets/js/src/newsletters/templates/template_box.jsx

[MAILPOET-2816]
[MAILPOET-2816]: https://mailpoet.atlassian.net/browse/MAILPOET-2816

Fix props warnings on templates page [MAILPOET-2816]

---

assets/js/src/form_editor/blocks/html/edit.jsx

[MAILPOET-2720]
[MAILPOET-2720]: https://mailpoet.atlassian.net/browse/MAILPOET-2720

Copy font from body to custom html block [MAILPOET-2720]

---

assets/css/src/components-form-editor/_block-editor.scss
assets/js/src/form_editor/components/editor.jsx

[MAILPOET-2813]
[MAILPOET-2813]: https://mailpoet.atlassian.net/browse/MAILPOET-2813

Make the inserter the same width as the other blocks [MAILPOET-2813]

---

tasks/phpstan/phpstan-baseline-unit-tests.neon
tests/integration/Subscribers/ImportExport/Import/MailChimpTest.php

[MAILPOET-2843]
[MAILPOET-2843]: https://mailpoet.atlassian.net/browse/MAILPOET-2843

Move the MailChimp test to integration suite [MAILPOET-2843]

---

lib/Form/Widget.php

This reverts commit 9718bd5c0a42f4d20bcf9285fc62524bfda162ee.
[MAILPOET-2836]
[MAILPOET-2836]: https://mailpoet.atlassian.net/browse/MAILPOET-2836

Revert "Send iframe header for form to allow embeding"

---

prefixer/composer.lock

[MAILPOET-2863]
[MAILPOET-2863]: https://mailpoet.atlassian.net/browse/MAILPOET-2863

Update swiftmailer/swiftmailer dependencies [MAILPOET-2863]

---

assets/js/src/subscribers/list.jsx

[MAILPOET-2731]
[MAILPOET-2731]: https://mailpoet.atlassian.net/browse/MAILPOET-2731

Remove modified on column [MAILPOET-2731]

---

assets/js/src/settings/pages/key_activation/key_activation.tsx
assets/js/src/settings/pages/key_activation/messages/key_messages.tsx
assets/js/src/settings/pages/key_activation/messages/mss_messages.tsx
assets/js/src/settings/pages/key_activation/messages/premium_messages.tsx
assets/js/src/settings/store/actions.ts
assets/js/src/settings/store/make_default_state.ts
assets/js/src/settings/store/types.ts
lib/API/JSON/v1/Services.php
lib/DI/ContainerConfigurator.php
lib/Services/CongratulatoryMssEmailController.php
tests/acceptance/AddSendingKeyCest.php
tests/integration/API/JSON/v1/ServicesTest.php
tests/integration/Cron/Workers/SchedulerTest.php
views/emails/congratulatoryMssEmail.html
views/emails/congratulatoryMssEmail.txt
views/settings.html

[MAILPOET-2831]
[MAILPOET-2831]: https://mailpoet.atlassian.net/browse/MAILPOET-2831

Congratulatory email [MAILPOET-2831]

---

lib/DI/ContainerConfigurator.php
lib/Subscription/Pages.php
tests/integration/Subscription/PagesTest.php

[MAILPOET-2847]
[MAILPOET-2847]: https://mailpoet.atlassian.net/browse/MAILPOET-2847

Allow subscribed subscriber to confirm another subscription [MAILPOET-2847]

---

assets/js/src/form_editor/store/form_body_to_blocks.jsx
tests/javascript/form_editor/store/form_body_to_blocks.spec.js

[MAILPOET-2868]
[MAILPOET-2868]: https://mailpoet.atlassian.net/browse/MAILPOET-2868

Fix custom fields in columns [MAILPOET-2868]

---

lib/Config/MP2Migrator.php
lib/Cron/CronHelper.php
lib/Cron/CronWorkerRunner.php
lib/Cron/DaemonHttpRunner.php
lib/Cron/Workers/Scheduler.php
lib/Doctrine/MetadataCache.php
lib/Entities/NewsletterSegmentEntity.php
lib/Features/FeatureFlagsController.php
lib/Form/AssetsController.php
lib/Models/ModelValidator.php
lib/Models/Newsletter.php
lib/Models/ScheduledTask.php
lib/Models/Segment.php
lib/Models/SendingQueue.php
lib/Newsletter/Renderer/Renderer.php
lib/Newsletter/Renderer/StylesHelper.php
lib/Router/Router.php
lib/Segments/WooCommerce.php
lib/Subscribers/ImportExport/Export/Export.php
lib/Subscribers/ImportExport/Import/MailChimp.php
lib/Subscription/Captcha.php
lib/Subscription/Pages.php
lib/Subscription/SubscriptionUrlFactory.php
lib/Tracy/DIPanel/DIPanel.php
lib/Tracy/DoctrinePanel/DoctrinePanel.php
lib/Util/Cookies.php
lib/Util/Url.php
tasks/phpstan/phpstan.neon

[MAILPOET-2716]
[MAILPOET-2716]: https://mailpoet.atlassian.net/browse/MAILPOET-2716

PHPStan ignore errors fix [MAILPOET-2716]

---

lib/Util/Notices/PHPVersionWarnings.php

[MAILPOET-2691]
[MAILPOET-2691]: https://mailpoet.atlassian.net/browse/MAILPOET-2691

Move beacon id to the correct link [MAILPOET-2691]

---

assets/css/src/components-plugin/_common.scss
assets/js/src/sending-paused-notices-fix-button.tsx
assets/js/src/settings/pages/send_with/other/test_sending.tsx

[MAILPOET-2871]
[MAILPOET-2871]: https://mailpoet.atlassian.net/browse/MAILPOET-2871

Settings fixes [MAILPOET-2871]

---

assets/js/src/common/subscribers_in_plan.tsx
assets/js/src/common/subscribers_limit.tsx
assets/js/src/segments/dynamic_segments_list.jsx
assets/js/src/segments/list.jsx
assets/js/src/subscribers/list.jsx
views/segments.html
views/subscribers/subscribers.html

[MAILPOET-2832]
[MAILPOET-2832]: https://mailpoet.atlassian.net/browse/MAILPOET-2832

Display number of subscribers in plan [MAILPOET-2832]

---

SUPPORT.md

[MAILPOET-2859]
[MAILPOET-2859]: https://mailpoet.atlassian.net/browse/MAILPOET-2859

Create Support.md [MAILPOET-2859]

---

assets/css/src/components-form-editor/_helpscout.scss
assets/css/src/mailpoet-form-editor.scss

[MAILPOET-2812]
[MAILPOET-2812]: https://mailpoet.atlassian.net/browse/MAILPOET-2812

Form editor: Move beacon to the left [MAILPOET-2812]

---

lib/API/MP/v1/API.php
tests/integration/API/MP/APITest.php

[MAILPOET-2864]
[MAILPOET-2864]: https://mailpoet.atlassian.net/browse/MAILPOET-2864

Fix double sending notifications [MAILPOET-2864]

---

assets/js/src/form_editor/blocks/submit/edit.jsx
lib/Form/BlockStylesRenderer.php
tests/unit/Form/BlockStylesRendererTest.php

[MAILPOET-2870]
[MAILPOET-2870]: https://mailpoet.atlassian.net/browse/MAILPOET-2870

Fix submit button border color [MAILPOET-2870]

---

readme.txt

[MAILPOET-2878]
[MAILPOET-2878]: https://mailpoet.atlassian.net/browse/MAILPOET-2878

Increment Tested WordPress version to 5.4 [MAILPOET-2878]

---

assets/js/src/form_editor/blocks/custom_checkbox/edit.jsx
lib/Form/Block/Checkbox.php
tests/unit/Form/Block/CheckboxTest.php

[MAILPOET-2803]
[MAILPOET-2803]: https://mailpoet.atlassian.net/browse/MAILPOET-2803

Allow html in checkbox [MAILPOET-2803]

---

assets/js/src/form_editor/blocks/input_styles_settings.jsx
assets/js/src/form_editor/blocks/submit/styles_settings.tsx

[MAILPOET-2886]
[MAILPOET-2886]: https://mailpoet.atlassian.net/browse/MAILPOET-2886

Set default style values [MAILPOET-2886]

---

assets/css/src/components-form-editor/_sidebar.scss

[MAILPOET-2872]
[MAILPOET-2872]: https://mailpoet.atlassian.net/browse/MAILPOET-2872

Fix form placement boxes [MAILPOET-2872]

---

lib/Form/Block/Image.php
tests/unit/Form/Block/ImageTest.php

[MAILPOET-2884]
[MAILPOET-2884]: https://mailpoet.atlassian.net/browse/MAILPOET-2884

Fix rendering image block [MAILPOET-2884]

---

lib/API/JSON/ResponseBuilders/NewslettersResponseBuilder.php
lib/API/JSON/v1/Newsletters.php
lib/DI/ContainerConfigurator.php
lib/Newsletter/Preview/SendPreviewController.php
lib/Newsletter/Preview/SendPreviewException.php
tests/integration/API/JSON/v1/NewslettersTest.php
tests/integration/Newsletter/Preview/SendPrevewControllerTest.php
tests/integration/Newsletter/Preview/SendPreviewControllerTest.php

I also added some refactoring for `sendPreview` but only a first step - we still need to refactor rendering code to be able to use Doctrine fully on that endpoint. To be continued by dedicated tasks.

Newsletter preview doctrine [MAILPOET-2646]

---

assets/css/src/generic/_typography.scss
assets/css/src/mailpoet-plugin.scss

[MAILPOET-2905]
[MAILPOET-2905]: https://mailpoet.atlassian.net/browse/MAILPOET-2905

Use the default WordPress font [MAILPOET-2905]

---

lib/AdminPages/Pages/Segments.php
lib/WP/Functions.php

[MAILPOET-2904]
[MAILPOET-2904]: https://mailpoet.atlassian.net/browse/MAILPOET-2904

Optimize produtcs loading on segments page [MAILPOET-2904]

---

views/forms.html
views/segments.html
views/subscribers/importExport/import.html

[MAILPOET-2481]
[MAILPOET-2481]: https://mailpoet.atlassian.net/browse/MAILPOET-2481

New default beacon articles [MAILPOET-2481]

---

lib/Config/Populator.php

[MAILPOET-2736]
[MAILPOET-2736]: https://mailpoet.atlassian.net/browse/MAILPOET-2736

Update migration version check for unsubscribe links [MAILPOET-2736]

---

assets/css/src/components-public/_public.scss
assets/js/src/public.jsx

[MAILPOET-2850]
[MAILPOET-2850]: https://mailpoet.atlassian.net/browse/MAILPOET-2850

Form: columns in popup form [MAILPOET-2850]

---

.circleci/config.yml

[MAILPOET-2916]
[MAILPOET-2916]: https://mailpoet.atlassian.net/browse/MAILPOET-2916

Use medium instance form build_code_and_qa job [MAILPOET-2916]

---

assets/js/src/newsletters/campaign_stats/newsletter_stats.jsx

[MAILPOET-2885]
[MAILPOET-2885]: https://mailpoet.atlassian.net/browse/MAILPOET-2885

Open article in beacon [MAILPOET-2885]

---

assets/css/src/components-plugin/_dynamic-segments.scss

[MAILPOET-2883]
[MAILPOET-2883]: https://mailpoet.atlassian.net/browse/MAILPOET-2883

Fix create segment button alignment on stats page [MAILPOET-2883]

---

assets/js/src/form_editor/components/form_styling_background.jsx

[MAILPOET-2914]
[MAILPOET-2914]: https://mailpoet.atlassian.net/browse/MAILPOET-2914

Improve form editor background style [MAILPOET-2914]

---

assets/css/src/generic/_grid.scss
assets/css/src/mailpoet-plugin.scss
assets/js/src/common/grid/_stories/grid.tsx
assets/js/src/common/grid/column.tsx
assets/js/src/common/grid/index.tsx
assets/js/src/common/grid/space_between.tsx
assets/js/src/common/grid/three_columns.tsx
assets/js/src/common/grid/two_columns.tsx
assets/js/src/common/grid/two_columns_list.tsx

[MAILPOET-2774]
[MAILPOET-2774]: https://mailpoet.atlassian.net/browse/MAILPOET-2774

Redesign - grid [MAILPOET-2774]

---

assets/css/src/components-form-editor/_block-editor.scss
assets/js/src/form_editor/components/form_styling_background.jsx

[MAILPOET-2928]
[MAILPOET-2928]: https://mailpoet.atlassian.net/browse/MAILPOET-2928

Fix nested blocks top margins in form editor [MAILPOET-2928]

---

assets/js/src/form_editor/store/map_form_data_after_loading.jsx
tests/javascript/form_editor/store/map_form_data_after_loading.spec.js

[MAILPOET-2930]
[MAILPOET-2930]: https://mailpoet.atlassian.net/browse/MAILPOET-2930

Fix form inputs padding [MAILPOET-2930]

---

assets/js/src/form_editor/blocks/custom_textarea/edit.jsx
assets/js/src/form_editor/blocks/input_styles_settings.jsx
assets/js/src/form_editor/blocks/text_input_edit.jsx
lib/Form/Block/Text.php
lib/Form/Block/Textarea.php
lib/Form/BlockStylesRenderer.php
tests/unit/Form/BlockStylesRendererTest.php

[MAILPOET-2908]
[MAILPOET-2908]: https://mailpoet.atlassian.net/browse/MAILPOET-2908

Forms: add input colour [MAILPOET-2908]

---

assets/js/src/form_editor/store/store.jsx
assets/js/src/subscribers/form.jsx
lib/Entities/CustomFieldEntity.php

[MAILPOET-2941]
[MAILPOET-2941]: https://mailpoet.atlassian.net/browse/MAILPOET-2941

Check params before accessing values [MAILPOET-2941]

---

.circleci/config.yml
RoboFile.php
lib/Doctrine/ConnectionFactory.php
lib/Doctrine/Types/BigIntType.php
lib/Entities/FormEntity.php
lib/Entities/NewsletterEntity.php
lib/Entities/NewsletterOptionEntity.php
lib/Entities/NewsletterSegmentEntity.php
lib/Entities/ScheduledTaskEntity.php
lib/Entities/SendingQueueEntity.php
lib/Entities/SettingEntity.php
lib/Entities/StatisticsClickEntity.php
lib/Entities/StatisticsNewsletterEntity.php
lib/Entities/StatisticsOpenEntity.php
lib/Entities/StatisticsUnsubscribeEntity.php
lib/Entities/SubscriberEntity.php
lib/Entities/UserFlagEntity.php
lib/Newsletter/NewsletterSaveController.php
tasks/phpstan/composer.json
tasks/phpstan/composer.lock
tasks/phpstan/create-entity-manager.php
tasks/phpstan/phpstan-baseline-integration-tests.neon
tasks/phpstan/phpstan.neon
tasks/phpstan/prefix-phpstan-doctrine.php
tests/integration/Doctrine/EventListeners/TimestampListenerTest.php
tests/integration/Doctrine/Types/JsonTypesTest.php

[MAILPOET-2945]
[MAILPOET-2945]: https://mailpoet.atlassian.net/browse/MAILPOET-2945

Code qa improvements [MAILPOET-2945]

---

lib/Newsletter/Renderer/Preprocessor.php
tests/unit/Newsletter/Renderer/PreprocessorTest.php

[MAILPOET-2887]
[MAILPOET-2887]: https://mailpoet.atlassian.net/browse/MAILPOET-2887

Fix typo [MAILPOET-2887]

---

lib/Util/Notices/UnauthorizedEmailNotice.php

[MAILPOET-2888]
[MAILPOET-2888]: https://mailpoet.atlassian.net/browse/MAILPOET-2888

Remove duplicate button [MAILPOET-2888]

---

lib/Newsletter/Editor/PostTransformer.php
tests/integration/Newsletter/Editor/PostContentTransformerTest.php

[MAILPOET-2627]
[MAILPOET-2627]: https://mailpoet.atlassian.net/browse/MAILPOET-2627

Add paragraph spaces to post excerpts [MAILPOET-2627]

---

.circleci/config.yml

[MAILPOET-2947]
[MAILPOET-2947]: https://mailpoet.atlassian.net/browse/MAILPOET-2947

Require static_analysis job before running other tests [MAILPOET-2947]

---

lib/Analytics/Reporter.php
lib/Models/Newsletter.php
lib/Models/Segment.php
lib/Newsletter/NewslettersRepository.php
lib/Segments/SegmentsRepository.php
lib/Twig/Analytics.php
tests/integration/Analytics/AnalyticsTest.php

[MAILPOET-2903]
[MAILPOET-2903]: https://mailpoet.atlassian.net/browse/MAILPOET-2903

Doctrine analytics [MAILPOET-2903]

---

assets/js/src/form_editor/components/form_settings/styles_settings_panel.jsx
assets/js/src/form_editor/store/map_form_data_after_loading.jsx
assets/js/src/form_editor/store/map_form_data_before_saving.jsx
lib/Form/Util/Styles.php
tests/unit/Form/Util/StylesTest.php
views/form/editor.html

[MAILPOET-2909]
[MAILPOET-2909]: https://mailpoet.atlassian.net/browse/MAILPOET-2909

Form messages colours [MAILPOET-2909]

---

assets/css/src/components-public/_public.scss
assets/js/src/public.jsx
lib/Form/Block/Paragraph.php
tests/unit/Form/Block/ParagraphTest.php

[MAILPOET-2926]
[MAILPOET-2926]: https://mailpoet.atlassian.net/browse/MAILPOET-2926

Form editor: fix Image block at last position [MAILPOET-2926]

---

lib/Models/Subscriber.php
lib/Models/SubscriberSegment.php
lib/Subscription/Pages.php

[MAILPOET-2950]
[MAILPOET-2950]: https://mailpoet.atlassian.net/browse/MAILPOET-2950

Set subscriber to null instead of false [MAILPOET-2950]

---

assets/js/src/settings/store/normalize_settings.ts

[MAILPOET-2952]
[MAILPOET-2952]: https://mailpoet.atlassian.net/browse/MAILPOET-2952

Disable transactional emails by default [MAILPOET-2952]

---

lib/Entities/NewsletterPostEntity.php
lib/Newsletter/AutomatedLatestContent.php
lib/Newsletter/Renderer/Blocks/Renderer.php

[MAILPOET-2960]
[MAILPOET-2960]: https://mailpoet.atlassian.net/browse/MAILPOET-2960

Fix fetching posts for ALC [MAILPOET-2960]

---

build.sh
lib/DI/ContainerFactory.php
lib/DI/ContainerWrapper.php
prefixer/composer.json
prefixer/fix-monolog.php
prefixer/fix-twig.php
tasks/strip-whitespaces.php
tests/integration/Twig/FunctionsTest.php

[MAILPOET-2692]
[MAILPOET-2692]: https://mailpoet.atlassian.net/browse/MAILPOET-2692

Reduce size of package [MAILPOET-2692]

---

doc/api_methods/AddSubscriber.md

[MAILPOET-2939]
[MAILPOET-2939]: https://mailpoet.atlassian.net/browse/MAILPOET-2939

Fix api docs for custom checkbox [MAILPOET-2939]

---

lib/DI/ContainerConfigurator.php
lib/Newsletter/Renderer/Blocks/Renderer.php
lib/WP/Functions.php
tests/integration/Newsletter/Blocks/RendererTest.php

[MAILPOET-2961]
[MAILPOET-2961]: https://mailpoet.atlassian.net/browse/MAILPOET-2961

Fix multiple post notifications [MAILPOET-2961]

---

tests/acceptance/ManageSubscriptionLinkCest.php
tests/acceptance/ReceivePostNotificationCest.php
views/newsletters.html

[MAILPOET-2929]
[MAILPOET-2929]: https://mailpoet.atlassian.net/browse/MAILPOET-2929

Replace sent to [MAILPOET-2929]

---

assets/css/src/components-public/_public.scss
lib/Form/Util/Styles.php
tests/unit/Form/Util/StylesTest.php

[MAILPOET-2924]
[MAILPOET-2924]: https://mailpoet.atlassian.net/browse/MAILPOET-2924

Update form responsiveness [MAILPOET-2924]

---

assets/js/src/public.jsx

[MAILPOET-2968]
[MAILPOET-2968]: https://mailpoet.atlassian.net/browse/MAILPOET-2968

Use container wrapper div to detect form width [MAILPOET-2968]

---

tasks/pack_translations.sh

[MAILPOET-2962]
[MAILPOET-2962]: https://mailpoet.atlassian.net/browse/MAILPOET-2962

Add formal nl translations [MAILPOET-2962]

---

lib/Doctrine/Types/JsonType.php

[MAILPOET-2935]
[MAILPOET-2935]: https://mailpoet.atlassian.net/browse/MAILPOET-2935

Add more details to a json parse error [MAILPOET-2935]

---

lib/API/JSON/v1/Newsletters.php

[MAILPOET-2969]
[MAILPOET-2969]: https://mailpoet.atlassian.net/browse/MAILPOET-2969

Fix preview in browser and template saving on utf8 columns [MAILPOET-2969]

---

assets/js/src/form_editor/components/form_settings/styles_settings_panel.jsx
assets/js/src/form_editor/store/defaults.ts
assets/js/src/form_editor/store/map_form_data_after_loading.jsx
tests/javascript/form_editor/store/map_form_data_after_loading.spec.js

[MAILPOET-2938]
[MAILPOET-2938]: https://mailpoet.atlassian.net/browse/MAILPOET-2938

Form editor: fix inconsistencies in form styles rendering [MAILPOET-2938]

---

assets/css/src/components-public/_public.scss
lib/Form/Block/Paragraph.php
tests/unit/Form/Block/ParagraphTest.php

[MAILPOET-2922]
[MAILPOET-2922]: https://mailpoet.atlassian.net/browse/MAILPOET-2922

Display paragraph padding [MAILPOET-2922]

---

assets/js/src/newsletter_editor/components/heading.js
views/newsletter/editor.html
views/newsletter/templates/components/heading.hbs

[MAILPOET-2659]
[MAILPOET-2659]: https://mailpoet.atlassian.net/browse/MAILPOET-2659

Fix silently trimming preheader [MAILPOET-2659]

---

tests/acceptance/SubscriberManageImportExportCest.php

[MAILPOET-2984](https://mailpoet.atlassian.net/browse/MAILPOET-2984)
In this pull request I want to edit existing test case but to add a new scenario of importing simple list of subscribers via paste box method.
[MAILPOET-2984]: https://mailpoet.atlassian.net/browse/MAILPOET-2984

Add scenario paste box import [MAILPOET-2984]

---

lib/Models/ScheduledTask.php
tests/integration/AutomaticEmails/WooCommerce/Events/AbandonedCartTest.php
tests/integration/Cron/Workers/SchedulerTest.php

[MAILPOET-2896]
[MAILPOET-2896]: https://mailpoet.atlassian.net/browse/MAILPOET-2896

Fix flakey scheduler test [MAILPOET-2896]

---

assets/css/src/components-editor/content-blocks/_automated-latest-content.scss
views/newsletter/templates/blocks/automatedLatestContentLayout/block.hbs

[MAILPOET-2921]
[MAILPOET-2921]: https://mailpoet.atlassian.net/browse/MAILPOET-2921

Add warning to ALC block [MAILPOET-2921]

---

lib/Form/DisplayFormInWPContent.php
tests/unit/Form/DisplayFormInWPContentTest.php

[MAILPOET-2902]
[MAILPOET-2902]: https://mailpoet.atlassian.net/browse/MAILPOET-2902

Prevent rendering forms multiple times [MAILPOET-2902]

---

assets/js/src/form_editor/form_editor.jsx
assets/js/src/form_editor/translations.ts
lib/AdminPages/Pages/FormEditor.php
lib/Config/Initializer.php
lib/DI/ContainerConfigurator.php
views/form/editor.html

[MAILPOET-2942]
[MAILPOET-2942]: https://mailpoet.atlassian.net/browse/MAILPOET-2942

Load Gutenberg JS translations for form editor [MAILPOET-2942]

---

lib/API/JSON/ResponseBuilders/NewslettersResponseBuilder.php

[MAILPOET-2936]
[MAILPOET-2936]: https://mailpoet.atlassian.net/browse/MAILPOET-2936

Optimise listings query [MAILPOET-2936]

---

assets/js/src/form_editor/blocks/submit/edit.tsx
assets/js/src/form_editor/blocks/submit/styles_settings.tsx
assets/js/src/form_editor/components/form_settings/styles_settings_panel.jsx

[MAILPOET-2989]
[MAILPOET-2989]: https://mailpoet.atlassian.net/browse/MAILPOET-2989

Fix proptypes warning in button styles component [MAILPOET-2989]

---

assets/css/src/components-public/_public.scss
assets/js/src/form_editor/form_preview.ts
assets/js/src/public.jsx
lib/Form/Util/Styles.php
views/form/editor.html

[MAILPOET-2964]
[MAILPOET-2964]: https://mailpoet.atlassian.net/browse/MAILPOET-2964

Minor form editor improvements [MAILPOET-2964]

---

tests/acceptance/EditExistingNewsletterCest.php
views/newsletters.html

[MAILPOET-2956]
[MAILPOET-2956]: https://mailpoet.atlassian.net/browse/MAILPOET-2956

Update Lists input tip on send page [MAILPOET-2956]

---

RoboFile.php
tests/DataGenerator/DataGenerator.php
tests/DataGenerator/Generators/WooCommercePastRevenues.php

[MAILPOET-2893]
[MAILPOET-2893]: https://mailpoet.atlassian.net/browse/MAILPOET-2893

Fix data generator [MAILPOET-2893]

---

lib/Mailer/WordPress/WordPressMailer.php

[MAILPOET-2970]
[MAILPOET-2970]: https://mailpoet.atlassian.net/browse/MAILPOET-2970

Fix content type detection [MAILPOET-2970]

---

lib/Mailer/WordPress/WordPressMailer.php
tests/integration/Mailer/WordPress/WordpressMailerTest.php

[MAILPOET-2875]
[MAILPOET-2875]: https://mailpoet.atlassian.net/browse/MAILPOET-2875

Add support for 'multipart/alternative' content type [MAILPOET-2875]

---

assets/css/src/components-public/_public.scss
assets/js/src/form_editor/form_preview.ts

[MAILPOET-2967]
[MAILPOET-2967]: https://mailpoet.atlassian.net/browse/MAILPOET-2967

Update form animations [MAILPOET-2967]

---

lib/Newsletter/ViewInBrowser/ViewInBrowserRenderer.php

[MAILPOET-2972]
[MAILPOET-2972]: https://mailpoet.atlassian.net/browse/MAILPOET-2972

Convert null shortcode params to false (implementations rely on false) [MAILPOET-2972]

---

tests/acceptance/AdvancedSettingsCest.php

[MAILPOET-3001](https://mailpoet.atlassian.net/browse/MAILPOET-3001)

Add Members plugin scenario in Acceptance [MAILPOET-3001]

---

lib/Subscription/Pages.php
views/subscription/confirm_unsubscribe.html

[MAILPOET-3002]
[MAILPOET-3002]: https://mailpoet.atlassian.net/browse/MAILPOET-3002

"nofollow" for confirming unsubscription [MAILPOET-3002]

---

.circleci/config.yml
README.md
mailpoet.php
readme.txt
tests/_support/AcceptanceTester.php
tests/_support/DefaultsExtension.php
tests/acceptance/CustomUnsubscribePageCest.php
tests/acceptance/SettingsArchivePageCest.php
tests/acceptance/SubscriberCountShortcodeCest.php
tests/docker/docker-compose.yml

[MAILPOET-2920]
[MAILPOET-2920]: https://mailpoet.atlassian.net/browse/MAILPOET-2920

Update supported WordPress and PHP versions [MAILPOET-2920]

---

assets/js/src/form_editor/store/blocks_to_form_body.jsx
assets/js/src/form_editor/store/form_body_to_blocks.jsx
tests/javascript/form_editor/store/blocks_to_form_body.spec.js
tests/javascript/form_editor/store/form_body_to_blocks.spec.js

[MAILPOET-3010]
[MAILPOET-3010]: https://mailpoet.atlassian.net/browse/MAILPOET-3010

Fix saving custom colors for paragraph, heading and columns blocks [MAILPOET-3010]

---

assets/js/src/subscribers/form.jsx
lib/API/JSON/v1/Subscribers.php
lib/Config/Migrator.php
lib/Entities/StatisticsUnsubscribeEntity.php
lib/Statistics/Track/Unsubscribes.php
lib/Subscription/Manage.php
lib/Subscription/Pages.php
tests/integration/API/JSON/v1/SubscribersTest.php
tests/integration/Statistics/Track/UnsubscribesTest.php
tests/integration/Subscription/ManageTest.php
views/subscribers/subscribers.html

[MAILPOET-2737]
[MAILPOET-2737]: https://mailpoet.atlassian.net/browse/MAILPOET-2737

Keep records when a subscriber unsubscribes [MAILPOET-2737]

---

lib/Twig/Analytics.php
lib/Twig/I18n.php
prefixer/composer.json
prefixer/composer.lock
prefixer/fix-twig.php

[MAILPOET-2667]
[MAILPOET-2667]: https://mailpoet.atlassian.net/browse/MAILPOET-2667

Update twig to v2 [MAILPOET-2667]

---

assets/css/src/mailpoet-form-editor.scss

[MAILPOET-2990]
[MAILPOET-2990]: https://mailpoet.atlassian.net/browse/MAILPOET-2990

Fix missing padding on popups [MAILPOET-2990]

---

assets/js/src/listing/filters.jsx
tests/acceptance/DeleteAutomaticWooCommerceEmailCest.php
tests/acceptance/DeleteNewsletterCest.php
tests/acceptance/DeleteTrashedSegmentCest.php
tests/acceptance/FormsDeletingCest.php
tests/acceptance/ManageListsCest.php
tests/acceptance/SubscriberManagementCest.php

[MAILPOET-2982]
[MAILPOET-2982]: https://mailpoet.atlassian.net/browse/MAILPOET-2982

Increase test coverage for destructive actions [MAILPOET-2982]

---

assets/css/src/components-editor/_common.scss

[MAILPOET-3011]
[MAILPOET-3011]: https://mailpoet.atlassian.net/browse/MAILPOET-3011

Remove unnecessary class from editor selectors [MAILPOET-3011]

---

lib/WooCommerce/Subscription.php
tests/_support/AcceptanceTester.php
tests/acceptance/RevenueTrackingCookieCest.php
tests/acceptance/SendFirstPurchaseEmailCest.php

[MAILPOET-2992]
[MAILPOET-2992]: https://mailpoet.atlassian.net/browse/MAILPOET-2992

Fix acceptamce wc order [MAILPOET-2992]

---

assets/css/src/components-plugin/_listing-newsletters.scss
assets/js/src/common/listings/_stories/newsletter_status.tsx
assets/js/src/common/listings/newsletter_status.tsx
views/layout.html

[MAILPOET-2999]
[MAILPOET-2999]: https://mailpoet.atlassian.net/browse/MAILPOET-2999

Add NewsletterStatus component [MAILPOET-2999]

---

tests/_support/AcceptanceTester.php
tests/acceptance/CreateNewWordPressUserCest.php
tests/acceptance/EditSignUpConfirmationEmailCest.php
tests/acceptance/ReceivePostNotificationCest.php
tests/acceptance/ReceiveStandardEmailCest.php
tests/acceptance/SendCategoryPurchaseEmailCest.php
tests/acceptance/SendProductPurchaseEmailCest.php
tests/acceptance/SubscribeOnRegistrationPageCest.php
tests/acceptance/SubscribersListingCest.php
tests/acceptance/SubscriptionFormCest.php

[MAILPOET-3019]
[MAILPOET-3019]: https://mailpoet.atlassian.net/browse/MAILPOET-3019

Fix potentially flaky tests checking email was received [MAILPOET-3019]

---

assets/js/src/form_editor/blocks/heading/heading.jsx
assets/js/src/form_editor/blocks/paragraph/paragraph.tsx
assets/js/src/form_editor/store/blocks_to_form_body.jsx
assets/js/src/form_editor/store/form_body_to_blocks.jsx
lib/Form/Block/Heading.php
lib/Form/Block/Paragraph.php
tests/javascript/form_editor/store/blocks_to_form_body.spec.js
tests/javascript/form_editor/store/form_body_to_blocks.spec.js
tests/unit/Form/Block/HeadingTest.php
tests/unit/Form/Block/ParagraphTest.php

[MAILPOET-3007]
[MAILPOET-3007]: https://mailpoet.atlassian.net/browse/MAILPOET-3007

Form editor: enable paragraph and heading typography settings [MAILPOET-3007]

---

assets/css/src/components-plugin/_settings.scss

[MAILPOET-2994]
[MAILPOET-2994]: https://mailpoet.atlassian.net/browse/MAILPOET-2994

Fix font size on settings [MAILPOET-2994]

---

tests/acceptance/SubscriberManagementCest.php

[MAILPOET-3013](https://mailpoet.atlassian.net/browse/MAILPOET-3013)

Update editing subscriber scenario [MAILPOET-3013]

---

tests/acceptance/SubscriberCountShortcodeCest.php

[MAILPOET-3021](https://mailpoet.atlassian.net/browse/MAILPOET-3021)

Improve subscribers shortcode acceptance testcase [MAILPOET-3021]

---

tests/_support/AcceptanceTester.php
tests/acceptance/DeleteTrashedSegmentCest.php
tests/acceptance/SubscriberManagementCest.php

[MAILPOET-3019]
[MAILPOET-3019]: https://mailpoet.atlassian.net/browse/MAILPOET-3019

Increase timeouts for some failing tests [MAILPOET-3019]

---

lib/API/JSON/ResponseBuilders/SubscribersResponseBuilder.php
lib/API/JSON/v1/Subscribers.php
lib/DI/ContainerConfigurator.php
lib/Entities/SubscriberCustomFieldEntity.php
lib/Entities/SubscriberEntity.php
lib/Entities/SubscriberSegmentEntity.php
lib/Subscribers/SubscriberCustomFieldRepository.php
lib/Subscribers/SubscriberSegmentRepository.php
tests/integration/API/JSON/v1/SubscribersTest.php

[MAILPOET-2653]
[MAILPOET-2653]: https://mailpoet.atlassian.net/browse/MAILPOET-2653

Rewrite Subscribers::get() to Doctrine [MAILPOET-2653]

---

views/forms.html

[MAILPOET-3023]
[MAILPOET-3023]: https://mailpoet.atlassian.net/browse/MAILPOET-3023

Update forms tip [MAILPOET-3023]

---

assets/js/src/settings/pages/key_activation/key_activation.tsx
assets/js/src/settings/store/actions/mss_and_premium.ts
lib/API/JSON/v1/Settings.php
lib/Config/ServicesChecker.php
lib/Cron/Workers/KeyCheck/SendingServiceKeyCheck.php
tests/acceptance/AddSendingKeyCest.php
tests/integration/API/JSON/v1/SettingsTest.php
tests/integration/Cron/Workers/KeyCheck/SendingServiceKeyCheckTest.php

This fixes both [MAILPOET-2991] and [MAILPOET-3006].
[MAILPOET-2991]: https://mailpoet.atlassian.net/browse/MAILPOET-2991
[MAILPOET-3006]: https://mailpoet.atlassian.net/browse/MAILPOET-3006

Settings save on verify, fix resume sending [MAILPOET-2991] [MAILPOET-3006]

---

lib/Newsletter/Listing/NewsletterListingRepository.php
tests/integration/Newsletter/Listing/NewsletterListingRepositoryTest.php

[MAILPOET-3012]
[MAILPOET-3012]: https://mailpoet.atlassian.net/browse/MAILPOET-3012

Fix filtering newsletters by segment [MAILPOET-3012]

---

assets/css/src/components-form-editor/_block-editor.scss
assets/css/src/components-form-editor/_form-title.scss

[MAILPOET-3020]
[MAILPOET-3020]: https://mailpoet.atlassian.net/browse/MAILPOET-3020

Make the width of block dynamic [MAILPOET-3020]

---

tests/DataFactories/Newsletter.php
tests/acceptance/SettingsArchivePageCest.php

[MAILPOET-3042](https://mailpoet.atlassian.net/browse/MAILPOET-3042)
Added new scenario in existing test case SettingsArchivePageCest and also updated Newsletter data factory.

Add scenario various status newsletters [MAILPOET-3042]

---

assets/css/src/components-form-editor/_sidebar-style-settings.scss

[MAILPOET-2948]
[MAILPOET-2948]: https://mailpoet.atlassian.net/browse/MAILPOET-2948

Make all headings in form settings bold [MAILPOET-2948]

---

tests/acceptance/NewsletterCreationCest.php

[MAILPOET-2841]
[MAILPOET-2841]: https://mailpoet.atlassian.net/browse/MAILPOET-2841

Skip test for public builds [MAILPOET-2841]

---

assets/css/src/components-form-editor/_preview.scss
assets/css/src/components-public/_public.scss
assets/css/src/settings/_form-editor.scss
lib/Form/Block/Divider.php
lib/Form/Block/Heading.php
lib/Form/Util/Styles.php
tests/unit/Form/Block/DividerTest.php
tests/unit/Form/Block/HeadingTest.php

[MAILPOET-3024]
[MAILPOET-3024]: https://mailpoet.atlassian.net/browse/MAILPOET-3024
Please test how heading margins in the mobile version look on different forms.

Form mobile view adjustments [MAILPOET-3024]

---

assets/js/src/listing/listing.jsx
lib/Cron/Supervisor.php
tests/DataFactories/ScheduledTask.php
tests/_support/AcceptanceTester.php
tests/_support/DefaultsExtension.php
tests/docker/docker-compose.yml

[MAILPOET-3044]
[MAILPOET-3044]: https://mailpoet.atlassian.net/browse/MAILPOET-3044

Acceptance tests fixes [MAILPOET-3044]

---

lib/Form/Util/Styles.php

[MAILPOET-3024]
[MAILPOET-3024]: https://mailpoet.atlassian.net/browse/MAILPOET-3024

Fix incorrect form media styles [MAILPOET-3024]

---

lib/AdminPages/PageRenderer.php
views/layout.html

[MAILPOET-3043]
[MAILPOET-3043]: https://mailpoet.atlassian.net/browse/MAILPOET-3043

Send mta data to template for beacon [MAILPOET-3043]

---

lib/API/JSON/v1/Newsletters.php

[MAILPOET-2824]
[MAILPOET-2824]: https://mailpoet.atlassian.net/browse/MAILPOET-2824

Add actions when newsletter is deleted [MAILPOET-2824]

---

tests/_support/DefaultsExtension.php

[MAILPOET-3048]
I run the build 3 times and it always passed so I believe this helped.
[MAILPOET-3048]: https://mailpoet.atlassian.net/browse/MAILPOET-3048

Mark all WooCommerce  cron jobs completed before running a test [MAILPOET-3048]

---

lib/API/JSON/Response.php
lib/API/JSON/SuccessResponse.php

[MAILPOET-2518]
[MAILPOET-2518]: https://mailpoet.atlassian.net/browse/MAILPOET-2518

Return array instead of null from api [MAILPOET-2518]

---

.eslintrc.ts.json
assets/css/src/components/_tooltips.scss
assets/css/src/mailpoet-plugin.scss
assets/js/src/common/tooltip/_stories/tooltip.tsx
assets/js/src/common/tooltip/tooltip.tsx
package-lock.json
package.json

[MAILPOET-2998]
[MAILPOET-2998]: https://mailpoet.atlassian.net/browse/MAILPOET-2998

Redesign Tooltip component [MAILPOET-2998]

---

tests/acceptance/SettingsPageBasicsCest.php

[MAILPOET-3051](https://mailpoet.atlassian.net/browse/MAILPOET-3051)
Update of existing test case to increase scenario coverage of subscribing while commenting a post.

Update scenario of subscribing in comments MAILPOET-3051

---

assets/js/src/common/form/checkbox/checkbox.tsx
assets/js/src/listing/header.jsx
tests/acceptance/DeleteNewsletterCest.php

[MAILPOET-3052](https://mailpoet.atlassian.net/browse/MAILPOET-3052)

Update delete newsletter scenarios [MAILPOET-3052]

---

tests/acceptance/ReceiveWelcomeEmailCest.php

[MAILPOET-3053](https://mailpoet.atlassian.net/browse/MAILPOET-3053)

Add new scenario receiving welcome email [MAILPOET-3053]

---

lib/Cron/Workers/StatsNotifications/NewsletterLinkRepository.php
tests/integration/Cron/Workers/StatsNotifications/NewsletterLinkRepositoryTest.php

[MAILPOET-3067]
[MAILPOET-3067]: https://mailpoet.atlassian.net/browse/MAILPOET-3067

Optimise query for fetching best link form stats notification email [MAILPOET-3067]

---

assets/css/src/components-plugin/_settings.scss
assets/js/src/settings/components/pages_select.tsx
assets/js/src/settings/pages/basics/unsubscribe_page.tsx
assets/js/src/settings/store/normalize_settings.ts
assets/js/src/settings/store/types.ts
lib/Settings/Pages.php
lib/Subscription/Pages.php
views/settings.html

[MAILPOET-2937]
[MAILPOET-2937]: https://mailpoet.atlassian.net/browse/MAILPOET-2937

More understandable unsubscribe page settings [MAILPOET-2937]

---

assets/js/src/settings/pages/key_activation/key_activation.tsx
assets/js/src/settings/pages/key_activation/messages/service_unavailable_messages.tsx
views/settings.html

[MAILPOET-3046]
[MAILPOET-3046]: https://mailpoet.atlassian.net/browse/MAILPOET-3046

Display learn more link for key activation error [MAILPOET-3046]

---

assets/js/src/forms/list.jsx
views/forms.html

[MAILPOET-3064]
[MAILPOET-3064]: https://mailpoet.atlassian.net/browse/MAILPOET-3064

Display the form type in the listings [MAILPOET-3064]

---

assets/js/src/common/preview/preview.jsx
views/form/editor.html

[MAILPOET-3062]
[MAILPOET-3062]: https://mailpoet.atlassian.net/browse/MAILPOET-3062

Display a warning for mobile preview [MAILPOET-3062]

---

assets/js/src/forms/list.jsx
lib/API/JSON/v1/Forms.php
views/forms.html

[MAILPOET-3065]
[MAILPOET-3065]: https://mailpoet.atlassian.net/browse/MAILPOET-3065

Forms: update created date column in forms listing [MAILPOET-3065]

---

assets/js/src/form_editor/store/reducers/save_form_done.jsx
views/form/editor.html

[MAILPOET-3063]
[MAILPOET-3063]: https://mailpoet.atlassian.net/browse/MAILPOET-3063

Update the save message [MAILPOET-3063]

---

tests/acceptance/NewsletterCreationCest.php

[MAILPOET-3070]
[MAILPOET-3070]: https://mailpoet.atlassian.net/browse/MAILPOET-3070

Fix flaky create newsletter test [MAILPOET-3070]

---

assets/css/src/components-public/_public.scss
assets/css/src/mailpoet-public.scss
assets/js/src/public.jsx
lib/DI/ContainerConfigurator.php
lib/Subscription/Manage.php
lib/Subscription/ManageSubscriptionFormRenderer.php
lib/Subscription/Pages.php
tasks/phpstan/phpstan-baseline-integration-tests.neon
tests/acceptance/ManageSubscriptionLinkCest.php
tests/integration/Config/ShortcodesTest.php
tests/integration/Subscription/ManageSubscriptionFormRendererTest.php
tests/integration/Subscription/PagesTest.php
views/subscription/manage_subscription.html

[MAILPOET-1635]
[MAILPOET-1635]: https://mailpoet.atlassian.net/browse/MAILPOET-1635

Update manage subscription [MAILPOET-1635]

---

assets/js/src/form_editor/blocks/custom_checkbox/custom_field_settings.jsx
assets/js/src/form_editor/blocks/custom_date/custom_field_settings.jsx
assets/js/src/form_editor/blocks/custom_radio/custom_field_settings.jsx
assets/js/src/form_editor/blocks/custom_text/custom_field_settings.jsx

[MAILPOET-3056]
[MAILPOET-3056]: https://mailpoet.atlassian.net/browse/MAILPOET-3056

Move custom field submit and delete buttons [MAILPOET-3056]

---

tests/integration/Subscription/ManageSubscriptionFormRendererTest.php

[MAILPOET-1635]
[Passing build](https://app.circleci.com/pipelines/github/mailpoet/mailpoet/4054/workflows/466c6a2d-fd6b-49e7-bd4b-7778106e5c1b)
[MAILPOET-1635]: https://mailpoet.atlassian.net/browse/MAILPOET-1635

Fix manage subscription integration test [MAILPOET-1635]

---

assets/js/src/newsletters/templates.jsx
lib/AdminPages/Pages/Newsletters.php
lib/NewsletterTemplates/NewsletterTemplatesRepository.php
views/newsletters.html

Fixes: #2963
[MAILPOET-2087]
[MAILPOET-2087]: https://mailpoet.atlassian.net/browse/MAILPOET-2087

Display Recently sent first in the email template selection [MAILPOET-2087]

---

assets/js/src/listing/listing.jsx
assets/js/src/listing/listing_item.jsx
assets/js/src/listing/listing_items.jsx
assets/js/src/subscribers/form.jsx
assets/js/src/subscribers/list.jsx

[MAILPOET-3054]
[MAILPOET-3054]: https://mailpoet.atlassian.net/browse/MAILPOET-3054

Remember subscriber listing filters [MAILPOET-3054]

---

lib/API/JSON/ResponseBuilders/SubscribersResponseBuilder.php
lib/API/JSON/v1/Subscribers.php
lib/DI/ContainerConfigurator.php
lib/Entities/SubscriberSegmentEntity.php
lib/Models/Subscriber.php
lib/Subscribers/SubscriberListingRepository.php
prefixer/Parser.php
prefixer/fix-doctrine.php
tests/integration/API/JSON/v1/SubscribersTest.php
tests/integration/Subscribers/SubscriberListingRepositoryTest.php
tests/integration/_bootstrap.php

[MAILPOET-2657]
[MAILPOET-2657]: https://mailpoet.atlassian.net/browse/MAILPOET-2657

Rewrite Subscriber listing to Doctrine [MAILPOET-2657]

---

lib/Models/ScheduledTaskSubscriber.php

[MAILPOET-3050]
[MAILPOET-3050]: https://mailpoet.atlassian.net/browse/MAILPOET-3050

Fix search in sending status [MAILPOET-3050]

---

assets/js/src/subscribers/importExport/import/step_data_manipulation.jsx
assets/js/src/subscribers/importExport/import/step_data_manipulation/do_import.jsx
assets/js/src/subscribers/importExport/import/step_data_manipulation/existing_subscribers_status.jsx
assets/js/src/subscribers/importExport/import/step_data_manipulation/new_subscribers_status.jsx
lib/Models/Subscriber.php
lib/Subscribers/ImportExport/Import/Import.php
tests/integration/Models/SubscriberTest.php
tests/integration/Subscribers/ImportExport/Import/ImportTest.php
views/subscribers/importExport/import.html

Fixes:#2968
[MAILPOET-2957]
[MAILPOET-2957]: https://mailpoet.atlassian.net/browse/MAILPOET-2957

Add possibility set status for new or existing users in import [MAILPOET-2957]

---

assets/js/src/newsletters/templates/tabs.jsx
tests/_support/AcceptanceTester.php
tests/acceptance/ConfirmNewsletterAutosaveCest.php
tests/acceptance/CreateWelcomeEmailCest.php
tests/acceptance/CreateWooCommerceNewsletterCest.php
tests/acceptance/EditorProductsCest.php
tests/acceptance/EditorSocialBlockCest.php
tests/acceptance/ManageSubscriptionLinkCest.php
tests/acceptance/NewsletterCreationCest.php
tests/acceptance/SaveNewsletterAsDraftCest.php
tests/acceptance/SaveNewsletterAsTemplateCest.php
tests/acceptance/SavePostNotificationEmailAsTemplateCest.php
tests/acceptance/TemplatesPagesLoadCest.php

[MAILPOET-3091]
[MAILPOET-3091]: https://mailpoet.atlassian.net/browse/MAILPOET-3091

Fix flaky newsletter template selection in tests [MAILPOET-3091]

---

tests/acceptance/ManageWelcomeEmailCest.php

Additional fix for a test I missed in [my previous PR](https://github.com/mailpoet/mailpoet/pull/2977).
[MAILPOET-3091]
[MAILPOET-3091]: https://mailpoet.atlassian.net/browse/MAILPOET-3091

Fix flaky manage welcome email test [MAILPOET-3091]

---

tests/integration/Cron/CronHelperTest.php
tests/integration/Mailer/WordPress/WordpressMailerTest.php
tests/integration/_bootstrap.php

[MAILPOET-3097]
[MAILPOET-3097]: https://mailpoet.atlassian.net/browse/MAILPOET-3097

Fix integration tests for wp 5.5 [MAILPOET-3097]

---

assets/css/src/components-public/_public.scss

[MAILPOET-3079]
[MAILPOET-3079]: https://mailpoet.atlassian.net/browse/MAILPOET-3079

Bigger h1, h2 on mobile form [MAILPOET-3079]

---

tests/acceptance/ManageWelcomeEmailCest.php
tests/acceptance/SaveNewsletterAsTemplateCest.php
tests/acceptance/SavePostNotificationEmailAsTemplateCest.php

[MAILPOET-3103]
[MAILPOET-3103]: https://mailpoet.atlassian.net/browse/MAILPOET-3103

Fix flaky newsletter template creation tests [MAILPOET-3103]

---

tests/acceptance/SettingsPageBasicsCest.php

[MAILPOET-3104]
[MAILPOET-3104]: https://mailpoet.atlassian.net/browse/MAILPOET-3104

Fix flaky settings test [MAILPOET-3104]

---

composer.json
prefixer/composer.json
prefixer/composer.lock
prefixer/fix-symfony-polyfill.php

[MAILPOET-3105]
[MAILPOET-3105]: https://mailpoet.atlassian.net/browse/MAILPOET-3105

Fix normalizer not being prefixed correctly [MAILPOET-3105]

---

lib/PostEditorBlocks/PostEditorBlock.php
lib/WP/Functions.php
readme.txt
tests/acceptance/SubscribeOnRegistrationPageCest.php
tests/docker/docker-compose.yml

[MAILPOET-3096]
[MAILPOET-3096]: https://mailpoet.atlassian.net/browse/MAILPOET-3096

Increment Tested WordPress version to 5.5 [MAILPOET-3096]

---

assets/css/src/components/_badge.scss
assets/css/src/components/_premium_required.scss
assets/css/src/mailpoet-plugin.scss
assets/js/src/common/badge/_stories/badge.tsx
assets/js/src/common/badge/badge.tsx
assets/js/src/common/premium_required/_stories/premium_required.tsx
assets/js/src/common/premium_required/premium_required.tsx

[MAILPOET-3083]
[MAILPOET-3083]: https://mailpoet.atlassian.net/browse/MAILPOET-3083

Premium banner component [MAILPOET-3083]

---

assets/css/src/components-form-editor/_form-title.scss
assets/js/src/form_editor/components/editor.jsx
assets/js/src/form_editor/components/form_settings/basic_settings_panel.jsx
assets/js/src/form_editor/components/form_title.jsx
package-lock.json
package.json
tests/acceptance/FormEditorUpdateNewFormCest.php

[MAILPOET-3086]
[MAILPOET-3086]: https://mailpoet.atlassian.net/browse/MAILPOET-3086

Move form title to sidebar [MAILPOET-3086]

---

assets/css/src/components-editor/components/_sidebar.scss

[MAILPOET-3100]
[MAILPOET-3100]: https://mailpoet.atlassian.net/browse/MAILPOET-3100

Fix arrow in email editor sidebar being misplaced [MAILPOET-3100]

---

lib/AdminPages/Pages/FormEditor.php
lib/Form/Templates/TemplateRepository.php
lib/Form/Templates/Templates/Template10BelowPages.php
lib/Form/Templates/Templates/Template10FixedBar.php
lib/Form/Templates/Templates/Template10Popup.php
lib/Form/Templates/Templates/Template10SlideIn.php
lib/Form/Templates/Templates/Template10Widget.php
lib/Form/Templates/Templates/Template6BelowPages.php
lib/Form/Templates/Templates/Template6FixedBar.php
lib/Form/Templates/Templates/Template6Popup.php
lib/Form/Templates/Templates/Template6SlideIn.php
lib/Form/Templates/Templates/Template6Widget.php

[MAILPOET-3074]
[MAILPOET-3074]: https://mailpoet.atlassian.net/browse/MAILPOET-3074

Form Templates Part 2 [MAILPOET-3074]

---

prefixer/fix-symfony-polyfill.php

[MAILPOET-3105]
[MAILPOET-3105]: https://mailpoet.atlassian.net/browse/MAILPOET-3105

Fix Normalizer polyfill prefixing [MAILPOET-3105]

---

assets/js/src/forms/list.jsx
lib/API/JSON/v1/Forms.php
lib/Entities/FormEntity.php
lib/Models/Form.php
tests/integration/API/JSON/v1/FormsTest.php
views/forms.html

[MAILPOET-3087]
[MAILPOET-3087]: https://mailpoet.atlassian.net/browse/MAILPOET-3087

Forms: add master toggle on/off of the whole form in forms listing [MAILPOET-3087]

---

lib/API/JSON/ResponseBuilders/SubscribersResponseBuilder.php

[MAILPOET-3109]
[MAILPOET-3109]: https://mailpoet.atlassian.net/browse/MAILPOET-3109

Send date as a string instead of an object [MAILPOET-3109]

---

lib/Models/Segment.php

[MAILPOET-3110]
[MAILPOET-3110]: https://mailpoet.atlassian.net/browse/MAILPOET-3110

Fix SQL error when running with ONLY_FULL_GROUP_BY [MAILPOET-3110]

---

tests/acceptance/PreviewPostNotificationNewsletterCest.php
tests/acceptance/PreviewStandardNewsletterCest.php

[MAILPOET-3118](https://mailpoet.atlassian.net/browse/MAILPOET-3118)

Add 2 new scenarios to newsletter preview testcases

---

tests/acceptance/SendCategoryPurchaseEmailCest.php

Adding new scenario in existing test case.
[MAILPOET-3114](https://mailpoet.atlassian.net/browse/MAILPOET-3114)

Add new scenario of not-opting to receive email

---

tests/acceptance/EditSignUpConfirmationEmailCest.php

More info at [MAILPOET-3119](https://mailpoet.atlassian.net/browse/MAILPOET-3119)

Update existing scenario to be more concise

---

assets/css/src/components/_steps.scss
assets/js/src/newsletter_editor/initializer.jsx
assets/js/src/newsletters/automatic_emails.jsx
assets/js/src/newsletters/automatic_emails/events_conditions.jsx
assets/js/src/newsletters/listings/heading_display.jsx
assets/js/src/newsletters/listings/heading_steps.jsx
assets/js/src/newsletters/listings/heading_steps_route.jsx
assets/js/src/newsletters/newsletters.jsx
assets/js/src/newsletters/send.jsx
assets/js/src/newsletters/templates.jsx
assets/js/src/newsletters/types/notification/notification.jsx
assets/js/src/newsletters/types/standard.jsx
assets/js/src/newsletters/types/welcome/welcome.jsx
tests/acceptance/CreateWooCommerceNewsletterCest.php
tests/acceptance/NewsletterCreationCest.php
tests/acceptance/SavePostNotificationEmailAsTemplateCest.php
tests/acceptance/TemplatesPagesLoadCest.php
views/newsletter/editor.html
views/newsletters.html

[MAILPOET-3014](https://mailpoet.atlassian.net/browse/MAILPOET-3014)

Redesign email creation steps header [MAILPOET-3014]

---

assets/css/src/components-form-editor/_form-placement.scss
views/form/editor.html

[MAILPOET-3094]
[MAILPOET-3094]: https://mailpoet.atlassian.net/browse/MAILPOET-3094

Forms: new position for shortcode [MAILPOET-3094]

---

tests/acceptance/PreviewPostNotificationNewsletterCest.php
tests/acceptance/PreviewStandardNewsletterCest.php

[MAILPOET-3123](https://mailpoet.atlassian.net/browse/MAILPOET-3123)

Fix flaky tests of Preview Newsletters

---

views/premium.html

[MAILPOET-3084]
[MAILPOET-3084]: https://mailpoet.atlassian.net/browse/MAILPOET-3084

 Update analytics description on the Premium page [MAILPOET-3084]

---

assets/js/src/newsletters/listings/notification_history.jsx
assets/js/src/newsletters/newsletters.jsx
lib/Newsletter/Listing/NewsletterListingRepository.php
tests/integration/Newsletter/Listing/NewsletterListingRepositoryTest.php

[MAILPOET-3111]
[MAILPOET-3111]: https://mailpoet.atlassian.net/browse/MAILPOET-3111

Fix displaying post notifications history [MAILPOET-3111]

---

lib/Subscribers/ImportExport/Import/Import.php

[MAILPOET-3041]
[MAILPOET-3041]: https://mailpoet.atlassian.net/browse/MAILPOET-3041

Use wordpress time when importing subscribers [MAILPOET-3041]

---

tests/acceptance/FormEditorUpdateNewFormCest.php

[MAILPOET-3124](https://mailpoet.atlassian.net/browse/MAILPOET-3124)

Update scenario of updating the form

---

tests/acceptance/SettingsPageBasicsCest.php

[MAILPOET-3125](https://mailpoet.atlassian.net/browse/MAILPOET-3125)

Fix flaky scenario test allowSubscribeInComments

---

assets/js/src/form_editor/store/controls.jsx

[MAILPOET-3113]
[MAILPOET-3113]: https://mailpoet.atlassian.net/browse/MAILPOET-3113

Fix "apply styles to all inputs" in form editor [MAILPOET-3113]

---

assets/js/src/form_editor/store/form_validator.jsx
assets/js/src/form_editor/store/reducers/save_form_started.jsx
tests/javascript/form_editor/store/form_validator.spec.js

[MAILPOET-3112]
[MAILPOET-3112]: https://mailpoet.atlassian.net/browse/MAILPOET-3112

Display an error when saving form with empty list selection block [MAILPOET-3112]

---

tests/_support/AcceptanceTester.php
tests/acceptance/SearchForNotificationCest.php
tests/acceptance/SearchForStandardNewsletterCest.php

[MAILPOET-3078]
I was not really able to replicate it so the fixed is more like guessing based on a screenshot from CI
[MAILPOET-3078]: https://mailpoet.atlassian.net/browse/MAILPOET-3078

Fix flaky search for newsletters tests [MAILPOET-3078]

---

lib/AdminPages/Pages/Newsletters.php
lib/AutomaticEmails/WooCommerce/WooCommerce.php
lib/Form/Templates/Templates/Template3SlideIn.php
lib/Subscription/CaptchaRenderer.php
lib/Util/Notices/UnauthorizedEmailNotice.php
mailpoet.php
readme.txt
views/form/editor.html
views/help.html
views/mss_pitch_translations.html
views/premium.html
views/settings.html

[MAILPOET-3121]
[MAILPOET-3121]: https://mailpoet.atlassian.net/browse/MAILPOET-3121

Update translations strings [MAILPOET-3121]

---

lib/Config/Populator.php

[MAILPOET-3072]
[MAILPOET-3072]: https://mailpoet.atlassian.net/browse/MAILPOET-3072

Update migration version check [MAILPOET-3072]

---

tests/acceptance/EditorProductsCest.php

[MAILPOET-3127](https://mailpoet.atlassian.net/browse/MAILPOET-3127)

Fix flaky scenarios in test EditorProductsCest

---

lib/Form/Util/Styles.php

[MAILPOET-3090]
[MAILPOET-3090]: https://mailpoet.atlassian.net/browse/MAILPOET-3090

Fix too much space at the end of form [MAILPOET-3090]

---

lib/Segments/WP.php
lib/Subscribers/ConfirmationEmailMailer.php
lib/Subscribers/SubscriberActions.php
lib/WooCommerce/Subscription.php
tests/integration/Subscribers/ConfirmationEmailMailerTest.php
tests/integration/WooCommerce/SubscriptionTest.php

[MAILPOET-2876]
[MAILPOET-2876]: https://mailpoet.atlassian.net/browse/MAILPOET-2876

Prevent multiple confirmation emails [MAILPOET-2876]

---

lib/Subscribers/SubscriberListingRepository.php

[MAILPOET-3136]
[MAILPOET-3136]: https://mailpoet.atlassian.net/browse/MAILPOET-3136

Fix subscribers counts in list filter in subscribers listing [MAILPOET-3136]

---

assets/css/src/components-public/_animation.scss
assets/css/src/components-public/_public.scss
assets/css/src/mailpoet-public.scss
assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/animation_settings.tsx
assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/fixed_bar_settings.tsx
assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/popup_settings.tsx
assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/slide_in_settings.tsx
assets/js/src/form_editor/form_preview.ts
assets/js/src/form_editor/store/defaults.ts
assets/js/src/form_editor/store/map_form_data_after_loading.jsx
assets/js/src/form_editor/store/map_form_data_before_saving.jsx
assets/js/src/public.jsx
lib/Form/DisplayFormInWPContent.php
lib/Form/PreviewPage.php
tests/javascript/form_editor/store/map_form_data_after_loading.spec.js
tests/javascript/form_editor/store/map_form_data_before_saving.spec.js
views/form/editor.html
views/form/front_end_form.html

[MAILPOET-3088]
[MAILPOET-3088]: https://mailpoet.atlassian.net/browse/MAILPOET-3088

Add form animations [MAILPOET-3088]

---

assets/css/src/components-form-editor/_form-placement.scss
assets/css/src/components-form-editor/_preview.scss
assets/css/src/components-plugin/_forms.scss
assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/below_posts_settings.tsx
assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/fixed_bar_settings.tsx
assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/placement_settings.tsx
assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/popup_settings.tsx
assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/slide_in_settings.tsx
assets/js/src/form_editor/store/map_form_data_after_loading.jsx
assets/js/src/form_editor/store/map_form_data_before_saving.jsx
assets/js/src/form_editor/store/selectors.jsx
assets/js/src/form_editor/store/store.jsx
lib/AdminPages/Pages/FormEditor.php
lib/Form/DisplayFormInWPContent.php
lib/WP/Functions.php
tests/acceptance/FormEditorPlaceFormOnSpecifiedPageCest.php
tests/javascript/form_editor/store/map_form_data_after_loading.spec.js
tests/javascript/form_editor/store/map_form_data_before_saving.spec.js
tests/unit/Form/DisplayFormInWPContentTest.php
views/form/editor.html

[MAILPOET-3120]
[MAILPOET-3120]: https://mailpoet.atlassian.net/browse/MAILPOET-3120

Expand display options [MAILPOET-3120]

---

tests/acceptance/CreateNewWordPressUserCest.php

[MAILPOET-3155](https://mailpoet.atlassian.net/browse/MAILPOET-3155)

Update acceptance scenario to include more checks

---

lib/Config/Env.php
lib/Config/RendererFactory.php
tests/integration/Config/EnvTest.php
tests/integration/Config/RendererFactoryTest.php

[MAILPOET-3157]
[MAILPOET-3157]: https://mailpoet.atlassian.net/browse/MAILPOET-3157

Add hooks for Twig cache path and disabling cache (for WP Engine) [MAILPOET-3157]

---

assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/placement_settings.tsx
assets/js/src/form_editor/components/form_settings/selection.jsx

[MAILPOET-3160]
[MAILPOET-3160]: https://mailpoet.atlassian.net/browse/MAILPOET-3160

Fix displaying select2 inside preview modal [MAILPOET-3160]

---

tests/acceptance/CreateNewWordPressUserCest.php

Details at [MAILPOET-3171](https://mailpoet.atlassian.net/browse/MAILPOET-3171)

Improved scenario to pass multisite testing

---

tests/acceptance/SettingsPageBasicsCest.php

[MAILPOET-3165](https://mailpoet.atlassian.net/browse/MAILPOET-3165)
I made some changes to existing scenario and now seems not flaky anymore. The problem was probably in scrolling long page specially if there are some warning messages at the top as on old wordpress or php site (like we have in nightly build).

Improved scenario to fix flakyness

---

assets/js/src/form/fields/selection.jsx

[MAILPOET-3174]
[MAILPOET-3174]: https://mailpoet.atlassian.net/browse/MAILPOET-3174

Fix select2 to support single values [MAILPOET-3174]

---

assets/js/src/newsletters/types/welcome/scheduling.jsx

[MAILPOET-3133]
[MAILPOET-3133]: https://mailpoet.atlassian.net/browse/MAILPOET-3133

Fix Welcome mail list setting [MAILPOET-3133]
