mailpoet/mailpoet

lib/Config/Migrator.php, tests/_bootstrap.php, tests/unit/Models/CustomFieldTest.php
We have two autoloaders, Free and Premium. Due to the way Composer works ([executes autoloaders from last to first](https://stackoverflow.com/questions/23647387/order-of-execution-of-multiple-composer-autoloaders#comment36320267_23647387)) the system-under-test autoloader gets overridden by the one that plugs into it later. So we essentially have a dep conflict between the two: Free uses Premium's AspectMock, Premium uses Free's library in turn. 
AspectMock by default uses an `appDir` relative to its own files so it tries to load classes from the wrong plugin's `lib` folder. I fixed that by hardcoding the correct directory in Free AM initialization, so even the wrongly located library could still look into the correct path.
Apart from that I added cache clearing as we had problems with …
=>  Fix AspectMock to work when the Premium plugin is active [MAILPOET-1585]

lib/Util/ConflictResolver.php
The CDN is provided by JetPack plugin in their "Asset CDN" beta feature.
The CDN may attempt to host default WP JS assets, which includes jQuery - something MP3 relies on.
However, due to this conflict resolution jQuery will then be prevented from loading, as its path is not from site's WP default JS asset locations, so it would be treated as a 3rd party script and thus prevented from loading on MP3 pages.
I'm not whitelisting wp.com for CSS assets, doing it only for JS assets, as at least from testing it on the test site having CSS location not whitelisted didn't have any visual impact - the WP interfaces looked normal.
Because it's whitelisting any asset loaded via wp.com, in the future this may cause problems with 3rd party plugin conflicts, as if assets of that plugin get loaded via …
=> Permit JS assets to be loaded from WP.com CDN on MP3 pages [MAILPOET-1584]

composer.json
The fix needs to be removed when we drop PHP 5.6 support and upgrade PHPUnit to 6.x+.
=> Fix code coverage on PHPUnit 5.7 and PHP 7.2 [MAILPOET-1596]

lib/Util/ConflictResolver.php
This is for the media library to work in the newsletter editor when Jetpack's "Asset CDN" is active.
=> Permit CSS assets to be loaded from WP.com CDN on MP3 pages [MAILPOET-1584]

tests/integration/API/JSON/v1/SegmentsTest.php
This is hard to debug, but the id was NULL in the previous implementation
and that sometimes returned an object instead of expected
Now the id is always a number and that will hopefully fix the flakiness.
=> Fix flaky segments test [MAILPOET-1578]

lib/DI/ContainerFactory.php
In ideal application one needs only one public service (some bootstrap) and that is why all services are private as default. Our code is not ideal yet so we have to declare services as public.
See https://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default
We don't use XML or Yaml (because of package size) so we have to define services as public one by one.
=> Make all services registered in DI public [MAILPOET-1621]

assets/css/src/newsletter_editor/components/save.styl
[MAILPOET-1630 Save and Next buttons in editor lack proper spacing](https://mailpoet.atlassian.net/browse/MAILPOET-1630)
=> Add space between save and next buttons [MAILPOET-1630]

tests/javascript/newsletter_editor/blocks/button.spec.js, views/newsletter/templates/blocks/button/settings.hbs
[MAILPOET-1633 Dropdown font selection box for button settings displays list of fonts as a single line, not selectable](https://mailpoet.atlassian.net/browse/MAILPOET-1633)
=> Fix custom fonts for buttons [MAILPOET-1633]

lib/API/API.php, lib/API/JSON/API.php, lib/API/JSON/v1/AutomatedLatestContent.php, lib/API/MP/v1/API.php, lib/Config/Initializer.php, lib/DI/ContainerFactory.php, lib/Subscription/Form.php, tests/integration/API/APITest.php, tests/integration/API/JSON/APITest.php, tests/integration/API/JSON/v1/AutomatedLatestContentTest.php, tests/integration/API/MP/APITest.php
I've just configured DI for MP API and JSON API and refactored MP API so that services which were instantiated inside are now passed via constructor.
There are still dependencies in form of static calls which we will have to address in the future (wrapping them or maybe Doctrine for models?).
For JSON API I've managed to refactor only one of its endpoints.
=> Introduce DI to plugin API [MAILPOET-1637]

assets/js/src/newsletters/listings/mixins.jsx, lib/Mailer/Methods/ErrorMappers/MailPoetMapper.php, lib/Services/Bridge/API.php, tests/integration/Mailer/Methods/ErrorMappers/MailPoetMapperTest.php
[MAILPOET-1649 Pause sending of spammer users](https://mailpoet.atlassian.net/browse/MAILPOET-1649)
In order to test this change on local, on way is to mock the response of the MSS bridge by changing the `Services\Bridge\API::sendMessages` method to return a hard coded response:
https://github.com/mailpoet/mailpoet/blob/master/lib/Services/Bridge/API.php#L77
```php
function sendMessages($message_body) {
// add the following return statement
return [
'status' => self::SENDING_STATUS_SEND_ERROR,
'message' => '...',
'code' => 403
];
$result = $this->request(
$this->url_messages,
$message_body
);
// ...
}
```
=> Pause sending of spammer users [MAILPOET-1649]

assets/js/src/newsletters/newsletters.jsx
Please check that all URL hash-modifying actions in affected routes work as expected: post notification history viewing, tab switching, sorting and filtering in email listings etc.
=> Fix routes after React Router upgrade [MAILPOET-1675]

assets/css/src/listing.styl, assets/js/src/listing/header.jsx, assets/js/src/listing/listing.jsx, assets/js/src/listing/listing_item.jsx
I don't know what was wrong. I found out that with class check-column React
handler wasn't called. Something somewhere stopped the event propagation.
I guess something in WordPress, but I am not sure. So I renamed the class
now it is working.
[MAILPOET-1681 Option to select all items across all pages in listings no longer appears](https://mailpoet.atlassian.net/browse/MAILPOET-1681)
=> Fix select all functionality

assets/js/src/subscribers/list.jsx
I could not reproduce the problem in the ticket and only fixed the console warning when choosing segment-related bulk actions. I've also removed the `api_version` parameter as it's unused.
=> Fix a warning when selecting bulk actions in the subscribers listing [MAILPOET-1669]

RoboFile.php, build.sh, composer.json, generated/.gitignore, lib/API/API.php, lib/API/JSON/API.php, lib/Config/Initializer.php, lib/DI/ContainerConfigurator.php, lib/DI/ContainerFactory.php, lib/DI/ContainerWrapper.php, lib/DI/IContainerConfigurator.php, lib/Router/Router.php, tasks/phpstan/phpstan.neon, tests/integration/API/JSON/APITest.php, tests/integration/Router/RouterTest.php, tests/unit/DI/ContainerWrapperTest.php
In order to add DI for premium, I had to make some changes also in a free plugin.
I've split ContainerFactory into ContainerFactory (responsible for building container either from dump file or using a Configurator) and [ContainerConfigurator](https://github.com/mailpoet/mailpoet/blob/premium-di/lib/DI/ContainerConfigurator.php) (responsible for a configuration of services). So that in Premium (or any other future plugin) we just create a ContainerConfigurator. ContainerConfigurator is also used for container dumps (cached containers). There is a one ContainerConfigurator for the free plugin and one for the premium plugin.
I've added a class which holds both free and also premium containers (if the premium is activated). The ContainerWrapper implements `Psr\Container\ContainerInterface` …
=> Premium Plugin DI [PREMIUM-99]

assets/js/src/newsletters/types.jsx
[MAILPOET-1674 Woo Commerce Set Up Button Should Not Show When Premium Not Active ](https://mailpoet.atlassian.net/browse/MAILPOET-1674)
=> Disable WooCommerce emails for free users [MAILPOET-1674]

assets/css/src/form_editor.styl, assets/css/src/in_app_announcements.styl, assets/css/src/modal.styl, assets/css/src/newsletter_editor/common.styl, assets/css/src/newsletter_editor/components/blockTools.styl, assets/css/src/newsletter_editor/components/dragAndDrop.styl, assets/css/src/newsletter_editor/components/resize.styl, assets/css/src/newsletter_editor/components/save.styl, assets/css/src/newsletter_editor/components/sidebar.styl, assets/css/src/newsletter_editor/contentBlocks/base.styl, assets/css/src/newsletter_editor/contentBlocks/container.styl, assets/css/src/newsletter_editor/contentBlocks/posts.styl, assets/css/src/newsletter_editor/libraryOverrides.styl, assets/css/src/newsletter_editor/mixins/border-radius.styl, assets/css/src/newsletter_editor/mixins/box-shadow.styl, assets/css/src/newsletter_editor/newsletter_editor.styl, assets/css/src/parsley.styl
Some of these prefixes will still be present in compiled CSS due to `nib` which wasn't updated for a long time. A solution may be to turn off `nib`'s vendor prefixes and use `autoprefixer` instead, but that's a bigger task for another hacking day maybe.
=> Remove outdated vendor prefixes and mixins - hacking day [MAILPOET-1695]

lib/API/JSON/v1/Newsletters.php, lib/Config/Menu.php, lib/Cron/CronHelper.php, lib/Cron/Workers/Scheduler.php, lib/Cron/Workers/SendingQueue/Migration.php, lib/Cron/Workers/SimpleWorker.php, lib/Mailer/Methods/AmazonSES.php, lib/Mailer/Methods/SendGrid.php, lib/Models/ScheduledTask.php, lib/Newsletter/Editor/PostTransformer.php, lib/Newsletter/Scheduler/Scheduler.php, lib/Newsletter/Shortcodes/Categories/Date.php, lib/Services/Bridge.php, lib/Services/Bridge/API.php, lib/Services/Release/API.php, lib/Tasks/Sending.php, lib/WP/DateTime.php, lib/WP/Functions.php, tests/integration/Cron/CronHelperTest.php, tests/integration/Cron/Workers/SendingQueue/MigrationTest.php, tests/integration/Cron/Workers/SendingQueue/Tasks/NewsletterTest.php, tests/integration/Services/BridgeTest.php, tests/integration/WP/FunctionsTest.php
- The functions on `WP\Functions` are now instance methods.
- For all classes which were calling `WPFunctions::someMethod` from an instance method, I added a property `$wp` and instanciated it on the constructor (this should be injected by DI container later).
- For all classes which were calling `WPFunctions::someMethod` from a static method, I created an instance of `WPFunctions` inside each method and called the method on it. This made it difficult to mock these instances for while testing, so I ended up adding an optional parameter to some static methods to be able to pass the WPFunctions mock instance. The bottom line is that we should start getting ride of all static methods, they make testing and DI difficult!
=> Encapsulating WP calls

webpack.config.js
Changed jsonpFunction name to avoid problems between themes or extensions who also use webpack with the default name
=> Avoid conflic between multiple WebPack config - webpack.config.js [MAILPOET-1715]

assets/js/src/segments/list.jsx, assets/js/src/subscribers/form.jsx, assets/js/src/subscribers/list.jsx, lib/API/MP/v1/API.php, lib/Config/MP2Migrator.php, lib/Config/Migrator.php, lib/Config/Populator.php, lib/Models/Segment.php, lib/Models/Subscriber.php, lib/Models/SubscriberSegment.php, lib/Segments/BulkAction.php, lib/Segments/SubscribersFinder.php, lib/Segments/SubscribersListings.php, lib/Segments/WP.php, lib/Subscribers/Source.php, lib/Subscription/Pages.php, tests/_data/acceptanceDump.sql, tests/acceptance/ListsListingCest.php, tests/acceptance/ReinstallFromScratchCest.php, tests/integration/API/MP/APITest.php, tests/integration/Config/MP2MigratorTest.php, tests/integration/Models/SubscriberSegmentTest.php, tests/integration/Models/SubscriberTest.php
The code is mostly done by analogy with the existing WP Users segment behavior, the only difference may be that WP Users list can be edited/imported and WooCommerce list can't (which may in fact be a bug of the former).
The `is_woocommerce_user` field is binary because we don't have separate customer IDs in WooCommerce.
=> Add WooCommerce customers list [MAILPOET-1721]

docker-compose.yml, tests/_support/AcceptanceTester.php
It's not so easy to get rid of tab switching since many links simply open in new tabs and there is no easy way to open them in the same one instead. This, however, seems to fix it. Build run 2 times on CircleCI, many times locally.
=> Chrome update [MAILPOET-1738]

RoboFile.php, tests/_support/AcceptanceTester.php, tests/acceptance/ConfirmNewsletterAutosaveCest.php, tests/acceptance/ConfirmNotificationAutosaveCest.php, tests/acceptance/CreateWelcomeEmailCest.php, tests/acceptance/DeleteNotificationCest.php, tests/acceptance/DuplicatePostNotificationCest.php, tests/acceptance/ExportSubscribersCest.php, tests/acceptance/ManageSubscriptionLinkCest.php, tests/acceptance/ManageWelcomeEmailCest.php, tests/acceptance/NewslettersListingCest.php, tests/acceptance/ReceiveStandardEmailCest.php, tests/acceptance/ReinstallFromScratchCest.php, tests/acceptance/SaveNewsletterAsTemplateCest.php, tests/acceptance/SaveNotificationAsDraftCest.php, tests/acceptance/SavePostNotificationEmailAsTemplateCest.php, tests/acceptance/ScheduleNewsletterCest.php, tests/acceptance/SearchForNotificationCest.php, tests/acceptance/SearchForStandardNewsletterCest.php, tests/acceptance/SettingsPageBasicsCest.php, tests/acceptance/SettingsUnsubscribePageCest.php, tests/acceptance/SubscribeToMultipleListsCest.php, tests/acceptance/SubscriberManageImportExportCest.php, tests/acceptance/SubscriberManagementCest.php, tests/acceptance/SubscribersListingCest.php, tests/acceptance/SubscriptionFormEditCest.php
Now there are three ways to set default timeouts:
* `WAIT_TIMEOUT` environment variable;
* `DEFAULT_WAIT_TIMEOUT` constant (if we need to set it for all environments);
* Leave both empty to use default timeouts for every function as specified in Codeception docs.
With these improvements, there's hopefully no need to explicitly set timeouts for individual method calls.
=> Introduce default timeout to acceptance tests, remove custom timeouts [MAILPOET-1759]

assets/js/src/announcements/feature_announcement.jsx
Two weeks ago Beamer added an auto-refresh feature (https://app.getbeamer.com/beamer/en/auto_refresh-is-now-available) which should automatically show new posts. In code, they have a timeout for 10 minutes (601 seconds to be precise) after which they call their API to see what's new. This method, however, calls our callback method (which according to their docs should be called only once) in which there is code for showing Beamer panel. 
I could find neither in docs nor in settings if auto-refresh can be turned off, so for now, fix is that we ignore calling out callback method more than once. This PR also fixes correctly setting `last_announcement_seen` setting.
MAILPOET-1720
=> Fix beamer auto-opening, because of their new auto-refresh feature

assets/js/src/newsletters/types/notification/scheduling.jsx
If a user doesn't select a day they see `1st` in the UI but
because the action is onChange which never fired
the system remembers the default value 0
=> Set default day in post notification [MAILPOET-1781]

lib/Analytics/Reporter.php, lib/Config/Hooks.php, lib/Config/Menu.php, lib/Config/Migrator.php, lib/Cron/Daemon.php, lib/Cron/Workers/WooCommerceSync.php, lib/Cron/Workers/WorkersFactory.php, lib/DI/ContainerConfigurator.php, lib/Segments/WooCommerce.php, lib/WP/Functions.php, lib/WooCommerce/Helper.php, tests/integration/Config/MenuTest.php, tests/integration/Cron/Workers/WooCommerceSyncTest.php, tests/integration/Segments/WooCommerceTest.php
WooCommerce has two types of customers: registered (WP users) and guest (only stored in order fields). Since we can't use IDs for all of them, we will use emails as identifiers.
The main idea is: to avoid conflicts, our existing WP users sync will take care of registered users and WC sync will mainly take care of guests while changing some properties for registered users too.
To trigger mass synchronization, make a PHP file in your WordPress web root, name it as you like:
```php
require_once( dirname( __FILE__ ) . '/wp-load.php' );
use MailPoet\Segments\WooCommerce as WooCommerceSegment;
$wc_segment = new WooCommerceSegment(new MailPoet\Settings\SettingsController);
$result = $wc_segment->synchronizeCustomers();
var_dump($result);
```
Run it, when you see `bool(true)`, the sync is done. …
=> Add WooCommerce customer synchronization [MAILPOET-1723]

tasks/release/ChangelogController.php
I had this error while releasing premium plugin, because release date was not specified
```
ERROR: Undefined index: releaseDate 
in /var/www/html/wp-content/plugins/mailpoet/tasks/release/ChangelogController.php:46
```
=> Fix small bug on release task

tests/integration/_bootstrap.php
Blacklist `woocommerce` and some `wp_filter` globals for integration tests to work with WooCommerce active
MAILPOET-1765
=> Integration tests with active WooCommerce 

lib/Config/Migrator.php, lib/Models/Model.php
I've initially added an index on the links table `url` column, but it can produce "key too long" errors on certain DB configurations so I've dropped it.
=> Add index to links url, make models without 'deleted_at' duplicable [PREMIUM-114]

views/settings/mta.html
The `mss_key_valid` variable gets properly assigned to the template in `Config\Menu`. 
This shouldn't break the 'Behavior changes' from [here](https://mailpoet.atlassian.net/browse/MAILPOET-1441) as `expiring` counts as valid.
=> Allow to activate MSS with an expiring key [MAILPOET-1852]

.circleci/config.yml
Each CI job in a workflow has its own build number, so if you build and deploy in different jobs you should pass the build number from one to another to be able to reference the built artifact. I've done this via a shared file in the workspace.
NB: remove the `ci-test-deploy` branch from the whitelist after a review.
=> Add test deployment CI job [MAILPOET-1845]

lib/Newsletter/Renderer/Renderer.php, lib/Util/CSS.php, tests/unit/Util/CSSTest.php
This reverts commit 6056dcd417bc5ff9996c257335d73e781e3f6576.
I can only reproduce this issue on customers' websites. Please ask supporters for access to them.
=> Revert "Get rid of double html parsing during render" [MAILPOET-1914]

lib/DI/ContainerConfigurator.php, lib/Listing/BulkActionController.php, lib/Listing/BulkActionFactory.php, lib/Models/Subscriber.php, lib/Segments/BulkAction.php, lib/Subscribers/SubscriberActions.php, tests/integration/Listing/BulkActionClassStub.php, tests/integration/Listing/BulkActionFactoryTest.php
Now `Subscriber` model has no `ConfirmationEmailMailer` dependency and we can use custom classes for bulk actions.
Note for QA: please make sure that different kinds of bulk actions work both in Free (especially "resend confirmation email" for subscribers) and Premium.
=> Move bulkSendConfirmationEmail() method out of the Subscriber model [MAILPOET-1922]

assets/css/src/components/_formEditor.scss
There has to be max-height and 'overflow: hidden' for animations to work properly. I just doubled the height, which gives spaces for 40+ possible fields, which seems like a reasonable limit.
[MAILPOET-1910]
[MAILPOET-1910]: https://mailpoet.atlassian.net/browse/MAILPOET-1910
=> Larger area for form fields [MAILPOET-1910]

assets/js/src/newsletters/types/notification/scheduling.jsx
Since value changing sends all properties, when it's called more than once, the changes will overwrite themselves. Fixed this by allowing the handle method to accept the object of changes.
=> Fix selecting monthly post notification frequency [MAILPOET-1866]

tests/_support/AcceptanceTester.php, tests/acceptance/UnauthorizedAddressCest.php
[MAILPOET-1882]
Tested on specific [group of tests](https://circleci.com/gh/mailpoet/mailpoet/27872), on which it was failing
```tests/acceptance/EditExistingNewsletterCest.php
tests/acceptance/FormsCreationCest.php
tests/acceptance/ManageWelcomeEmailCest.php
tests/acceptance/PreviewPostNotificationNewsletterCest.php
tests/acceptance/ReceiveStandardEmailCest.php
tests/acceptance/SaveNewsletterAsDraftCest.php
tests/acceptance/SaveNewsletterAsTemplateCest.php
tests/acceptance/SavePostNotificationEmailAsTemplateCest.php
tests/acceptance/SearchForNotificationCest.php
tests/acceptance/SearchForStandardNewsletterCest.php
tests/acceptance/SettingsSubscriptionPageCest.php
tests/acceptance/SubscribersListingCest.php
tests/acceptance/UnauthorizedAddressCest.php
[MAILPOET-1882]: …
```
=> Fix UnauthorizedAddress test button not being clickable

tests/DataFactories/WooCommerceCustomer.php, tests/DataFactories/WooCommerceOrder.php, tests/DataFactories/WooCommerceProduct.php, tests/_data/acceptanceDump.sql, tests/_support/AcceptanceTester.php, tests/docker/codeception/docker-entrypoint.sh
I've added WooCommerce to free plugin acceptance test same way as it is done in premium plugin.
Here is a demo test showing how to use data factories:
```php
<?php
namespace MailPoet\Test\Acceptance;
require_once __DIR__ . '/../DataFactories/WooCommerceProduct.php';
require_once __DIR__ . '/../DataFactories/WooCommerceCustomer.php';
require_once __DIR__ . '/../DataFactories/WooCommerceOrder.php';
use MailPoet\Test\DataFactories\WooCommerceCustomer;
use MailPoet\Test\DataFactories\WooCommerceOrder;
use MailPoet\Test\DataFactories\WooCommerceProduct;
class WCDemoTestCest {
function demoTest(\AcceptanceTester $I) {
$I->activateWooCommerce();
$product_factory = new WooCommerceProduct($I);
$product = $product_factory->withName('Test product')->create();
$customer_factory = new …
```
=> WooCommerce for Acceptance Tests [MAILPOET-1936]

lib/WP/Functions.php, lib/WooCommerce/Helper.php, tasks/phpstan/bootstrap.php
I rewrote the whole `WP/Functions.php` file and sorted methods alphabetically.
To review, please read the file as if it's a new one, because the diff doesn't make sense due to the reordering.
=> Rewrite WPFunctions methods [MAILPOET-1920]

lib/Config/Env.php, lib/WP/Functions.php, tests/integration/Config/EnvTest.php
This change will enable using MailPoet on sites which are using ipv6 addresses in DB_HOST
=> Use WP function to parse DB_HOST [MAILPOET-1907]

RoboFile.php, tasks/release/JiraController.php, tasks/release/ReleaseVersionController.php, tasks/release/VersionHelper.php
Now the `jira:release-version` command will automatically determine the next release version according to the "Required version increment" field of Jira tickets.
You can also check what the next version will be with `next:release-version`.
=> Automate the next release version bump [MAILPOET-1869]

views/settings/advanced.html
Fixes #1983. It was working in Chrome and Firefox but was throwing an error in Safari.
=> Fix typo in jQuery selector

composer.lock
@michelleshull This replaces a version of the library that is used to convert newsletters to the text version. It will affect link mainly. So when testing try a bunch of different links including shortcodes if that renders correctly in the text version of an email.
=> Use new version of html2text that prevents link breaking [MAILPOET-1988]

lib/Config/Hooks.php, lib/Config/Migrator.php, lib/Config/Populator.php, lib/DI/ContainerConfigurator.php, lib/Models/SubscriberSegment.php, lib/Settings/SettingsController.php, lib/Subscribers/Source.php, lib/WooCommerce/Subscription.php, tests/DataFactories/Settings.php, tests/_support/AcceptanceTester.php, tests/acceptance/WooCommerceCheckoutOptinCest.php, tests/acceptance/WooCommerceCustomerListCest.php, tests/acceptance/WooCommerceSettingsTabCest.php, tests/integration/API/JSON/v1/SetupTest.php, tests/integration/Models/SubscriberSegmentTest.php, tests/integration/Segments/WooCommerceTest.php, tests/integration/Settings/SettingsControllerTest.php, tests/integration/WooCommerce/SubscriptionTest.php, views/settings.html, views/settings/woocommerce.html
Customer synchronization is performed by the existing WC sync functionality, with this checkbox we only manage WC list subscription status and occasionally a few other fields.
=> Add WooCommerce subscription checkbox on checkout [MAILPOET-1483]

RoboFile.php, tasks/release/JiraController.php
To test this I did the following
- Created this dummy task https://mailpoet.atlassian.net/browse/MAILPOET-2048
- Created two PRs associated with it
https://github.com/mailpoet/release-notes/pull/6
https://github.com/mailpoet/mailpoet-dev-env/pull/16
- I merged the first PR and kept the second one open.
- Created a release `3.25.2` and assigned it to the dummy task
- Run `./do release:check-issues 3.25.2` which gives the error
```
Some pull request associated to task MAILPOET-2048 is not merged yet!
```
- closed the second dummy PR and tried again, have no error.
You should be able to test that by opening/closing that PR and running the command.
=> Check if all issues PRs are merged [MAILPOET-2010]

lib/Segments/SubscribersFinder.php, tests/integration/Segments/SubscribersFinderTest.php
A newsletter can have deleted segments, i.e. orphaned relations to segments (see here: https://github.com/mailpoet/mailpoet/blob/master/lib/Models/Newsletter.php#L488). Thus we should not clean up these relations but skip them during processing.
=> Skip deleted segments in SubscribersFinder [MAILPOET-2026]

lib/Models/Subscriber.php
This fixes archive newsletter URLs not working for guests if there is a subscriber with `wp_user_id = 0` in the DB. And shaves off one query.
=> Don't look up a subscriber for guest WP users [MAILPOET-2047]

assets/js/src/hooks.js, assets/js/src/newsletter_editor/initializer.jsx, assets/js/src/newsletters/listings/mixins.jsx, assets/js/src/newsletters/listings/notification_history.jsx, assets/js/src/newsletters/listings/standard.jsx, assets/js/src/newsletters/listings/welcome.jsx, package-lock.json, package.json, webpack.config.js
While working on the JS hooks library transition I've noticed a hook invocation in the `newsletter/editor.html` view (https://github.com/mailpoet/mailpoet/blob/master/views/newsletter/editor.html#L1472) didn't work unless the existing global `wp.hooks` variable was reused. This means since WP 5.0 we were actually using the hooks library bundled with WP using ours as a fallback for WP below 5.0. I wonder how did it work because as I mentioned earlier the official library has slightly different arguments for `addAction`/`addFilter` calls (namespaces added). And we were using the old function signatures till today.
Anyway, I have updated our library. When we drop support for WP < 5.0 we may try to remove it altogether.
**Note to QA:**
Please test that:
* All Free & Premium functionality …
=>  Use the official WP JS hooks library [MAILPOET-2081] 

lib/Config/Hooks.php, lib/Subscription/Registration.php
There are multiple hooks for user registration.
https://usersinsights.com/wp/wp-content/uploads/2018/07/user-registration-hooks-2.png
The `register_post` hook is executed first and
after that, there is `registration_errors`.
The captcha verification is done in `registration_errors` hook.
But because we were using `register_post` we were saved
the subscriber before the post request was verified.
=> Fix registration of rejected users [MAILPOET-2114]

lib/Mailer/Methods/PHPMail.php
Litmus test with base64: https://litmus.com/checklist/tests/13634155 (and source code https://litmus.com/checklist/tests/13634155/download.eml).
=> Enforce base64 when email encoding needed for PHPMail & mail() function [MAILPOET-2065]

assets/js/src/newsletters/listings/mixins.jsx, assets/js/src/newsletters/listings/welcome.jsx, assets/js/src/newsletters/newsletters.jsx, assets/js/src/newsletters/sending_status.jsx, lib/API/JSON/v1/Newsletters.php, lib/API/JSON/v1/SendingTaskSubscribers.php, lib/Cron/Workers/SendingQueue/SendingQueue.php, lib/DI/ContainerConfigurator.php, lib/Mailer/MailerError.php, lib/Models/Model.php, lib/Models/ScheduledTaskSubscriber.php, tests/DataFactories/Newsletter.php, tests/_data/acceptanceDump.sql, tests/acceptance/SendingStatusCest.php, tests/integration/API/JSON/v1/NewslettersTest.php, tests/integration/API/JSON/v1/SendingTaskSubscribersTest.php, tests/integration/Models/ScheduledTaskSubscriberTest.php, views/newsletters.html
[MAILPOET-1155]
Instead of writing acceptance test for every type of newsletters. I have written generic integration tests and then tested only one newsletter type on the acceptance test. The sending status page should work the same for other types. 
[MAILPOET-1155]: https://mailpoet.atlassian.net/browse/MAILPOET-1155
=> Add newsletter sending status page [MAILPOET-1155]

assets/css/src/components/_notice.scss, assets/js/src/newsletters/listings/queue_status.jsx, assets/js/src/notices/api_errors_notice.jsx, assets/js/src/notices/mailer_status_notice.jsx, assets/js/src/notices/notice.jsx, views/layout.html
The plan was:
1. Write a `Notice` React component which uses React Portals to render itself into the `#mailpoet_notices` div (which I will add to `layout.html`).
2. Replace as much instances of `MailPoet.Notice` as possible with the `Notice` component.
I started by looking into the existing `MailPoet.Notice` object. It has the following options:
- type: can be `success`, `info`, `warning` or `error`.
- message: the **HTML** content of the notice.
- static: if `true` the notice will not have a timeout.
- hideClose: if `false` the notice will closable (via a small icon on top-right).
- id: a string to identify the notice.
- positionAfter: a selector. When specified, the notice is inserted after that element.
- scroll: if `true` the view will scroll to the notice when it's shown.
- timeout: …
=> Introduce React component to replace MailPoet.Notice [MAILPOET-2156]

lib/AdminPages/PageRenderer.php, lib/AdminPages/Pages/ExperimentalFeatures.php, lib/AdminPages/Pages/FormEditor.php, lib/AdminPages/Pages/Forms.php, lib/AdminPages/Pages/Help.php, lib/AdminPages/Pages/MP2Migration.php, lib/AdminPages/Pages/NewsletterEditor.php, lib/AdminPages/Pages/Newsletters.php, lib/AdminPages/Pages/Premium.php, lib/AdminPages/Pages/RevenueTrackingPermission.php, lib/AdminPages/Pages/Segments.php, lib/AdminPages/Pages/Settings.php, lib/AdminPages/Pages/Subscribers.php, lib/AdminPages/Pages/SubscribersAPIKeyInvalid.php, lib/AdminPages/Pages/SubscribersExport.php, lib/AdminPages/Pages/SubscribersImport.php, lib/AdminPages/Pages/SubscribersLimitExceeded.php, lib/AdminPages/Pages/Update.php, lib/AdminPages/Pages/WelcomeWizard.php, lib/AdminPages/Pages/WooCommerceListImport.php, lib/Config/Menu.php, lib/DI/ContainerConfigurator.php, lib/Listing/Handler.php, lib/Listing/PageLimit.php, lib/Util/Installation.php, tests/integration/Config/MenuTest.php
I've added a new namespace `MailPoet\AdminPages` and refactored all methods used for fetching data for templates to extra classes and injected container so that a class for a particular page is instantiated when it is needed for rendering.
I would be good to go thru all MailPoet admin pages and check that all renders correctly.
Here are all pages which are handled by Menu class:
mailpoet/lib/AdminPages/Pages/ExperimentalFeatures.php
mailpoet/lib/AdminPages/Pages/FormEditor.php
mailpoet/lib/AdminPages/Pages/Forms.php
mailpoet/lib/AdminPages/Pages/Help.php
mailpoet/lib/AdminPages/Pages/MP2Migration.php
mailpoet/lib/AdminPages/Pages/NewsletterEditor.php
mailpoet/lib/AdminPages/Pages/Newsletters.php
mailpoet/lib/AdminPages/Pages/Premium.php …
=> Refactor Menu [MAILPOET-2200]

assets/js/src/subscribers/importExport/import/step_data_manipulation/match_table.jsx
I compared version before and after refactor and fixed a behaviour so that it works same way as it worked before the changes introduced in refactor.
Before refactor we were able to process CSV without first row containing column names.
Importing with column names:
Importing without column names (this one was broken):
=> Make header line in CSV optional in subscribers import [MAILPOET-2225]

lib/Cron/Workers/StatsNotifications/Scheduler.php, tests/integration/Cron/Workers/StatsNotifications/SchedulerTest.php
The problem was that we don't not actually send `notification` emails but we create and send `notification_history` emails.
=> Fix stats notification scheduling after sending a post notification [MAILPOET-2231]

lib/API/JSON/v1/SendingQueue.php, lib/Config/Migrator.php, lib/Cron/DaemonHttpRunner.php, lib/Cron/Triggers/WordPress.php, lib/Cron/Workers/KeyCheck/KeyCheckWorker.php, lib/Cron/Workers/Scheduler.php, lib/Cron/Workers/SimpleWorker.php, lib/Cron/Workers/WooCommerceSync.php, lib/Models/ScheduledTask.php, tests/integration/Cron/DaemonHttpRunnerTest.php, tests/integration/Cron/Triggers/WordPressTest.php, tests/integration/Cron/Workers/KeyCheck/KeyCheckWorkerTest.php, tests/integration/Cron/Workers/SchedulerTest.php, tests/integration/Cron/Workers/SimpleWorkerTest.php, tests/integration/Cron/Workers/WooCommerceSyncTest.php, tests/integration/Models/ScheduledTaskTest.php
Changes in this PR:
1. WordPress cron trigger now runs no often than once per 10 seconds (customizable with the `mailpoet_cron_trigger_wordpress_run_interval` hook). This is more to shave off the load during peaks of traffic. Still, any delay may not be acceptable in some cases such as immediate newsletter sending, so I've introduced the `resetRunInterval` method which has an effect of triggering cron immedately on the next request like it was before, the method should be called on certain events, e.g. when a user adds a sending job.
2. A mechanism for rescheduling tasks progressively is introduced. Depending on the `reschedule_count` task property each rescheduling will be set from 5 minutes to 24 hours in the future. All tasks that are descendants of `SimpleWorker` will be rescheduled …
=> Add fixes for cron CPU usage on SiteGround [MAILPOET-2181] [MAILPOET-2202]

assets/js/src/notice.js
Problem was (I think), that updating our JS notice was broken because it updated the last notice, not the one which should be updated. And it could cause some tests to fail because they were checking for some notice to be visible, but it was overwritten with another one (replicated on unauthorized email notice).
=> Fix flaky test [MAILPOET-2265]

lib/Config/Populator.php
I decided to not use a feature flag because we save this value on a new activation and no-one gets a chance to update the flag.
=> Add translated text for default WC checkbox [MAILPOET-2207]

assets/js/src/listing/listing.jsx
I just switched the default value of `auto_refresh` to `false`. All email listings already have `auto_refresh` set to `true`.
=> Don't auto refresh listings besides Emails [MAILPOET-2191]

lib/Config/PopulatorData/Templates/NewsletterBlank121Column.php, lib/Config/PopulatorData/Templates/NewsletterBlank12Column.php, lib/Config/PopulatorData/Templates/NewsletterBlank13Column.php
The HTML tags `<h2>`, `<h3>` and `<p>` should be removed from the translation strings.
**Why?**
1. We did the same in WordPress core.
2. If the HTML tag is inside the translation string, the translator can accidentally change it from `<h2>` to let's say `<h1>`, or even worse, to forget to properly close the tag and break the code.
3. In RTL languages it's hard to translate strings with HTML code inside. The string is in RTL but the HTML tags are LTR. Very hard to translate this way.
**The Solution**
The best practice is to avoid using HTML tags in translation strings if possible.
=> i18n: avoid using HTML tags in translation strings

lib/Util/Notices/UnauthorizedEmailNotice.php
The string has one `<b>` tag and two `</b>` tags. This PR removes the second closing tag.
=> i18n: remove redundant HTML tag

assets/js/src/common/sender_email_address_warning.jsx, lib/Util/Notices/UnauthorizedEmailInNewslettersNotice.php, lib/Util/Notices/UnauthorizedEmailNotice.php, views/layout.html
The current translation strings use `%subject`, `%email1`, and `%email2` placeholders.
Those custom placeholders are not recognized by Transifex, making it harder to translate the strings.
This PR updates the placeholders to the standard `%s`, `%1$s`, `%2$s` placeholders used by WordPress core.
Original PR #2280
=> i18n: use WordPress `%s` placeholders

lib/API/JSON/v1/Mailer.php, lib/API/JSON/v1/Newsletters.php, lib/Cron/Workers/SendingQueue/SendingQueue.php, lib/Cron/Workers/StatsNotifications/AutomatedEmails.php, lib/Cron/Workers/StatsNotifications/Worker.php, lib/Cron/Workers/WorkersFactory.php, lib/DI/ContainerConfigurator.php, lib/Mailer/MetaInfo.php, lib/Mailer/Methods/MailPoet.php, lib/Mailer/WordPress/WordPressMailer.php, lib/Mailer/WordPress/WordpressMailerReplacer.php, lib/Subscribers/ConfirmationEmailMailer.php, lib/Subscribers/NewSubscriberNotificationMailer.php, tests/integration/API/JSON/v1/MailerTest.php, tests/integration/API/JSON/v1/NewslettersTest.php, tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php, tests/integration/Cron/Workers/StatsNotifications/AutomatedEmailsTest.php, tests/integration/Cron/Workers/StatsNotifications/WorkerTest.php, tests/integration/Mailer/MetaInfoTest.php, tests/integration/Mailer/Methods/MailPoetAPITest.php, tests/integration/Mailer/WordPress/WordpressMailerTest.php, tests/integration/Subscribers/ConfirmationEmailMailerTest.php, tests/integration/Subscribers/NewSubscriberNotificationMailerTest.php, tests/unit/Mailer/MetaInfoTest.php
[MAILPOET-2333]
I added the following email types that were not mentioned in the specs:
**The sending method test email** 
```
email_type = 'sending_test'
subscriber_status = 'unknown'
subscriber_source = 'administrator'
```
**Preview email**
```
email_type = 'preview'
subscriber_status = 'unknown'
subscriber_source = 'administrator'
```
I have also used `administrator` as `subscriber_source` for stats notifications, new subscriber notifications, and WordPress transactional emails.
[MAILPOET-2333]: https://mailpoet.atlassian.net/browse/MAILPOET-2333
=> Send meta to mss [MAILPOET-2333]

lib/Util/Notices/InactiveSubscribersNotice.php
Replace `[number]` with `%s` using `sprintf()` function.
**Old string:**
`Good news! MailPoet won’t send emails to your [number] inactive subscribers. This is a standard practice to maintain good deliverability and open rates. But if you want to disable it, you can do so in settings. [link]Read more.[/link]`
**New string:**
`Good news! MailPoet won’t send emails to your %s inactive subscribers. This is a standard practice to maintain good deliverability and open rates. But if you want to disable it, you can do so in settings. [link]Read more.[/link]`
=> i18n: use %s placeholder instead of [number]

lib/Config/Hooks.php, lib/DI/ContainerConfigurator.php, lib/WooCommerce/Settings.php, tests/acceptance/WooCommerceSettingsTabCest.php, views/woocommerce/settings_overlay.html
There is a bit of a difference from specs - I'm not using `woocommerce_email_settings_after` hook as suggested, because it's a hook for specific email settings. Instead, I'm using `woocommerce_settings_start` (which is called on every settings page) and then filtering in MailPoet which tab is shown. 
It's done without JS so the positioning of buttons is fixed and not calculated. It may break if they change the settings page layout, but that might break even if JS would be included. 
[MAILPOET-2283]
[MAILPOET-2283]: https://mailpoet.atlassian.net/browse/MAILPOET-2283
=> Disable WooCommerce plugin's email settings [MAILPOET-2283]

assets/css/src/components/newsletterEditor/_libraryOverrides.scss
I didn't find any option in docs to set offset for the fixed TinyMCE toolbar. So the "solution" here is, that it's shown above the WordPress menu.
[MAILPOET-2404]
[MAILPOET-2404]: https://mailpoet.atlassian.net/browse/MAILPOET-2404
=> Show TinyMCE toolbar above WP menu [MAILPOET-2404]

lib/Cron/Workers/UnsubscribeTokens.php, lib/Util/Security.php
Changes: 
* Each entry is processed only once by keeping track of the last processed ID in the task's `meta` field, so no endless cycle if we're unable to save a particular model;
* Unnecessary scheduling of new tasks is removed, one task is enough to do the job if it returns its boolean completion status correctly;
* Some code duplication is avoided by replacing `while` with `do ... while`.
=> Process each entry only once in unsubscribe tokens worker [MAILPOET-2447]

lib/API/JSON/v1/Newsletters.php, lib/Cron/Workers/SendingQueue/Tasks/Newsletter.php, lib/DI/ContainerConfigurator.php, lib/Models/Newsletter.php, lib/Models/SendingQueue.php, lib/Newsletter/ViewInBrowser.php, lib/Router/Endpoints/ViewInBrowser.php, lib/WP/Emoji.php, tests/integration/API/JSON/v1/NewslettersTest.php, tests/integration/Cron/Workers/SendingQueue/Tasks/NewsletterTest.php, tests/integration/Models/SendingQueueTest.php, tests/integration/Newsletter/ViewInBrowserTest.php, tests/integration/Router/Endpoints/ViewInBrowserTest.php, tests/integration/WP/EmojiTest.php
Since emoji handling is now decoupled from models, we need to put it anywhere newsletter source/rendered body is saved to the database or retrieved for rendering. Hope I didn't miss such cases.
=> Refactor emoji encoding/decoding out of models [MAILPOET-2460]

lib/Newsletter/Editor/PostTransformer.php, lib/Newsletter/Editor/PostTransformerContentsExtractor.php, tests/integration/Newsletter/Editor/PostContentTransformerTest.php
This is done as suggested in the ticket:  
> We could extract functionality for getting post data and building data structure and create PostContetsExtractor and mock this class.
=> Remove AspectMock usage from PostContentTransformerTest [MAILPOET-2454]

assets/js/src/newsletters/types.jsx, lib/API/JSON/v1/Settings.php, lib/AdminPages/Pages/NewsletterEditor.php, lib/AdminPages/Pages/Newsletters.php, lib/Config/Populator.php, lib/WooCommerce/Settings.php, tests/acceptance/WooCommerceEmailCustomizationCest.php, tests/integration/API/JSON/v1/SettingsTest.php, tests/integration/API/JSON/v1/SetupTest.php, tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php, tests/integration/Cron/Workers/SendingQueue/Tasks/MailerTest.php, tests/integration/Newsletter/ShortcodesTest.php, tests/integration/Subscription/UrlTest.php
The template is now created on the 'Activate & Customize' button click.
=> Create WC transactional email only when it's first invoked [MAILPOET-2514]

lib/AdminPages/Pages/Newsletters.php, lib/Cron/Workers/StatsNotifications/Worker.php, tests/integration/Cron/Workers/StatsNotifications/WorkerTest.php
When an unauthenticated user comes to any page they are redirected
to the login screen. After they authenticate they are redirected
to the original page. But the # part of the URL is ignored.
So we have to use regular query params from the email and
redirect the user to the canonical URL later.
[MAILPOET-2554]
[MAILPOET-2554]: https://mailpoet.atlassian.net/browse/MAILPOET-2554
=> Fix stats redirect [MAILPOET-2554]

tasks/makepot/node_modules/grunt-wp-i18n/vendor/wp-i18n-tools/add-textdomain.php, tasks/makepot/node_modules/grunt-wp-i18n/vendor/wp-i18n-tools/makepot.php, tasks/makepot/node_modules/grunt-wp-i18n/vendor/wp-i18n-tools/not-gettexted.php, tasks/makepot/node_modules/grunt-wp-i18n/vendor/wp-i18n-tools/pomo/entry.php, tasks/makepot/node_modules/grunt-wp-i18n/vendor/wp-i18n-tools/pomo/po.php, tasks/makepot/node_modules/grunt-wp-i18n/vendor/wp-i18n-tools/pomo/streams.php, tasks/makepot/node_modules/grunt-wp-i18n/vendor/wp-i18n-tools/pomo/translations.php
Please check that functions were refactored correctly, e.g. you can compare a POT file generated on `master` and in this branch so they match.
=> Fix deprecated functions in the makepot command [MAILPOET-2523]

assets/js/src/newsletters/campaign_stats/premium_banner.jsx, lib/Util/License/Features/Subscribers.php
There is an accompanying Premium PR too.
**For QA:**
Please check that all possible combinations of the following conditions display correct banners or data tables on the stats page:
* Premium plugin active / inactive;
* API key is valid / expiring (still valid) / not valid or empty;
* Subscribers limit is reached / not reached.
=> Update stats page banners for new free plan limit [MAILPOET-2492]

lib/Tasks/State.php
[MAILPOET-2623]
[MAILPOET-2623]: https://mailpoet.atlassian.net/browse/MAILPOET-2623
=> Ensure consistend order for tasks with equal timestamp (fixes flaky test) [MAILPOET-2623]

prefixer/fix-swiftmailer.php
[MAILPOET-2722]
[MAILPOET-2722]: https://mailpoet.atlassian.net/browse/MAILPOET-2722
The new code produces the following in Swiftmailer's autoloader:
```
// Don't interfere with other autoloaders
if (0 !== \strpos($class, 'MailPoetVendor\\Swift_')) {
return;
}
$path = __DIR__ . '/' . \str_replace('_', '/', str_replace('MailPoetVendor\\', '', $class)) . '.php';
```
The `MailPoetVendor\\` is kept in the IF condition which means it should never interfere with non-MailPoetVendor classes.
=> Fix Swiftmailer autoloader to handle only Swift_* classes in MailPoetVendor namespace [MAILPOET-2722]

lib/Newsletter/Shortcodes/Shortcodes.php
Wordpress as well doesn't use those modifiers
[MAILPOET-2660]
[MAILPOET-2660]: https://mailpoet.atlassian.net/browse/MAILPOET-2660
=> Shortcodes cannot spread to multiple lines [MAILPOET-2660]

lib/Models/Newsletter.php, lib/Models/SendingQueue.php, tests/integration/Models/NewsletterTest.php
[MAILPOET-2819]
I was not able to find another case apart from deleting where a newsletter switches to an incorrect state.
I've added a commit (https://github.com/mailpoet/mailpoet/commit/ff15116fe69020b7e371ec4ddef7d0507ab9ad50) to ensure the correct state when a user resumes sending.
[MAILPOET-2819]: https://mailpoet.atlassian.net/browse/MAILPOET-2819
=> Restore newsletters trashed when sending as paused [MAILPOET-2819]

lib/Config/Populator.php, lib/Cron/Workers/SendingQueue/SendingQueue.php, lib/Cron/Workers/SendingQueue/Tasks/Links.php, lib/DI/ContainerConfigurator.php, lib/Entities/StatisticsUnsubscribeEntity.php, lib/Models/NewsletterLink.php, lib/Newsletter/Links/Links.php, lib/Newsletter/Sending/SendingQueuesRepository.php, lib/Newsletter/Shortcodes/Categories/Link.php, lib/Router/Endpoints/Subscription.php, lib/Statistics/StatisticsUnsubscribesRepository.php, lib/Statistics/Track/Unsubscribes.php, lib/Subscription/Pages.php, lib/Subscription/SubscriptionUrlFactory.php, tests/acceptance/ManageSubscriptionLinkCest.php, tests/integration/API/JSON/v1/NewslettersTest.php, tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php, tests/integration/Cron/Workers/SendingQueue/Tasks/LinksTest.php, tests/integration/Newsletter/Links/LinksTest.php, tests/integration/Newsletter/ShortcodesTest.php, tests/integration/Router/Endpoints/SubscriptionTest.php, tests/integration/Statistics/Track/UnsubscribesTest.php, tests/integration/Subscription/PagesTest.php, tests/integration/Subscription/UrlTest.php, views/subscription/confirm_unsubscribe.html
[MAILPOET-2736]
**Note for QA:**
Old unsubscribe links from newsletters sent prior upgrading to this version should unsubscribe a subscriber just by opening the link.
[MAILPOET-2736]: https://mailpoet.atlassian.net/browse/MAILPOET-2736
=> Add confirm unsubscribe page [MAILPOET-2736]

lib/Form/AssetsController.php
[MAILPOET-2894]
vendor.js is an admin script. This was left in frontend assets probably because historically we used to enqueue FE and backend assets for both FE and backend (widgets page) altogether.
Oxygen Gutenberg integration loads all assets for any shortcode placed within their special Gutenberg block. They do so on every admin page. This resulted in vendor.js being loaded twice and causing conflict with itself.
This change is related to FE assets for MailPoet forms. Please check it doesn't break subscription forms functionality. 
[MAILPOET-2894]: https://mailpoet.atlassian.net/browse/MAILPOET-2894
=> Oxygen Gutenberg conflict fix [MAILPOET-2894]

lib/Models/CustomField.php, tests/integration/Models/SubscriberTest.php
We had hardcoded formats for `year_month_day` (MM/DD/YYYY) and `year_month` (MM/YYYY) in the code, values having different order (e.g. DD/MM/YYYY) were stored incorrectly.
=> Fix storing custom field dates in different formats [MAILPOET-2881]

assets/js/src/ajax.js, assets/js/src/newsletter_editor/components/save.js, lib/API/JSON/API.php, tests/javascript_newsletter_editor/newsletter_editor/components/save.spec.js, views/newsletter/editor.html
*Note to QA:* to test nonce expiration, you can add this code to your theme's `functions.php`:
```php
add_filter('nonce_life', function () {
return 60; //seconds
});
```
Then a nonce will expire every minute. Prior to this fix, newsletter saving would stop working.
=> Fix newsletter saving after nonce expiration, add new error message [MAILPOET-2839]

assets/js/src/form_editor/components/form_settings/styles_settings_panel.jsx
The problem originated [in this commit](https://github.com/mailpoet/mailpoet/pull/2634/commits/c455dcfd062450ee9902abc9a3e5c08cb96f7a47#diff-572a8b4d8a2a72bbe46586df88bd3c52) while trying to fix another issue with color picker (Gutenberg's custom color picker resets other form styles because it is not rerendered when the `onChange` callback is updated with a new state, so its callback holds a stale state): https://github.com/mailpoet/mailpoet/pull/2634#pullrequestreview-374972553
The problem above was solved with `useRef` so all `onChange` callbacks referred to the same mutable state value. But this also caused the form styles panel state to be detached from everything else, and when it updated the global state it was undoing all changes made outside of it (e.g. basic and placement …
=> Fix form style changes resetting other form settings [MAILPOET-2932]

lib/Form/Util/Styles.php, tests/unit/Form/Util/StylesTest.php
The border rendering was already fixed in [MAILPOET-2811] so this PR only adjusts border radius for slide-in form.
[MAILPOET-2912]
[MAILPOET-2811]: https://mailpoet.atlassian.net/browse/MAILPOET-2811
[MAILPOET-2912]: https://mailpoet.atlassian.net/browse/MAILPOET-2912
=> Form: Adjust form borders rendering [MAILPOET-2912]

lib/Mailer/Methods/PHPMail.php, lib/Mailer/WordPress/PHPMailerLoader.php, lib/Mailer/WordPress/WordPressMailer.php, tasks/phpstan/bootstrap.php, tasks/phpstan/phpstan-baseline.neon
[MAILPOET-3040](https://mailpoet.atlassian.net/browse/MAILPOET-3040)
**To QA:**
Please test this in both WP 5.4 and 5.5 beta (install the latter using the [WordPress Beta Tester](https://wordpress.org/plugins/wordpress-beta-tester/) plugin). Enable `WP_DEBUG`, set the sending method to "Your web host" and check that the following actions work without errors:
* "Test the sending method" button in the bottom of "Send with... > Other";
* Newsletter editor preview sending;
* Standard newsletter sending;
* WordPress transactional email sending (e.g. changing admin email).
=> Prepare for PHPMailer upgrade in WP 5.5 [MAILPOET-3040]

lib/DI/ContainerConfigurator.php, lib/Doctrine/ConnectionFactory.php, lib/Models/Newsletter.php, tests/integration/Config/DatabaseTest.php, tests/integration/Doctrine/ConnectionFactoryTest.php
[MAILPOET-2630]
It seems that we added the removal of ONLY_FULL_GROUP_BY for our DB connection as a hotfix after it was added to MySQL. 
see https://mailpoet.atlassian.net/browse/MAILPOET-739 and https://mailpoet.slack.com/archives/G0A1L2KHV/p1481209868000199
We have fixed knows issues and we want to get rid of this hotfix. It probably doesn't work on some third part MySQL distribution like Percona server.
[MAILPOET-2630]: https://mailpoet.atlassian.net/browse/MAILPOET-2630
=> Allow ONLY_FULL_GROUP_BY MySQL mode [MAILPOET-2630]

lib/Segments/WP.php, tests/integration/Segments/WPTest.php
Fixes:#2960
[MAILPOET-3016]
[MAILPOET-3016]: https://mailpoet.atlassian.net/browse/MAILPOET-3016
=> Fix subscriber status resetting on WP user creation [MAILPOET-3016]

tests/acceptance/NewsletterCreationCest.php
[MAILPOET-3106](https://mailpoet.atlassian.net/browse/MAILPOET-3106)
Updating of the existing test case NewsletterCreationCest and its scenario createStandardNewsletter to include verification of recently sent newsletter tab and if newsletter has been sent at the end.
Note: We had change in recent pull requests that after user send one newsletter, next time Recently sent tab will be the first tab when choosing which template to select.
=> Update existing scenario newsletter creation

lib/Models/Subscriber.php, lib/Subscribers/SubscriberListingRepository.php, tests/integration/Subscribers/SubscriberListingRepositoryTest.php
[MAILPOET-3132]
The fix reintroduces a behaviour that subscribers who unsubscribed from a list are still counted as members of the list. I did that so that numbers in refactored part of listing match numbers coming from old code.
I've also updated [the subsequent issue](https://mailpoet.atlassian.net/browse/MAILPOET-3077) with a note about that.
[MAILPOET-3132]: https://mailpoet.atlassian.net/browse/MAILPOET-3132
=> Subscribers listing hotfix [MAILPOET-3132]

lib/Util/Notices/HeadersAlreadySentNotice.php, lib/Util/Notices/PermanentNotices.php, lib/WP/Notice.php, tests/integration/Util/Notices/HeadersAlreadySentNoticeTest.php
[MAILPOET-2983](https://mailpoet.atlassian.net/browse/MAILPOET-2983)
I formatted the captcha message as a separate sentence for easier translation.
**For QA:**
To test this, try adding `?>` followed by some whitespace at the end of theme's `functions.php` or in some 3rd-party plugin files.
=> Detect whitespace in output that can break tracking images and captcha [MAILPOET-2983]

prefixer/fix-symfony-polyfill.php
Please double-check that all necessary cases are prefixed now.
*For QA:*
If possible, please test this on a host where Intl extension functions are missing to make sure errors do not occur. Test with WooCommerce enabled.
=> Fix Normalizer prefixing [MAILPOET-3148]

tests/acceptance/EditorProductsCest.php, tests/acceptance/ManageListsCest.php, tests/acceptance/SettingsPageBasicsCest.php
[MAILPOET-3153](https://mailpoet.atlassian.net/browse/MAILPOET-3153)
In this task I will fix flaky tests that keep failing in nightly build.
Flaky tests:
- EditorProductsCest:filterProducts (keep failing because warning message for PHP update is present)
- SettingsPageBasicsCest:allowSubscribeInComments (failing because require additional scroll)
- ManageListsCest:editTrashRestoreAndDeleteExistingList (failing because we redesigned fields recently)
=> Fixed three flaky tests

assets/css/src/components-form-editor/_preview.scss
The issue was with the box sizing.
The Gutenberg component expects the box sizing to be set to border-box
that is done on the newsletter editor by Gutenberg styles.
But that rule was not applied on the preview page so I added it there.
[MAILPOET-3126]
[MAILPOET-3126]: https://mailpoet.atlassian.net/browse/MAILPOET-3126
=> Fix radio button displaying [MAILPOET-3126]

RoboFile.php, lib/Cron/CronHelper.php, lib/Cron/Workers/SendingQueue/Tasks/Posts.php, lib/DI/ContainerConfigurator.php, lib/Doctrine/ConfigurationFactory.php, lib/Doctrine/Types/JsonType.php, lib/Entities/SubscriberSegmentEntity.php, lib/Form/Widget.php, lib/Models/Model.php, lib/Models/Newsletter.php, lib/Settings/SettingsRepository.php, prefixer/composer.json, prefixer/composer.lock, prefixer/fix-doctrine.php, tasks/phpstan/composer.json, tasks/phpstan/composer.lock, tasks/phpstan/phpstan-tests.neon, tasks/phpstan/phpstan.neon, tests/integration/Cron/Workers/SendingQueue/Tasks/NewsletterTest.php, tests/integration/Doctrine/EventListeners/EmojiEncodingListenerTest.php, tests/integration/Form/FormFactoryTest.php, tests/integration/Newsletter/NewsletterRepositoryTest.php, tests/unit/Form/HtmlParser.php, tests/unit/Form/RendererTest.php
[MAILPOET-3146]
[MAILPOET-3146]: https://mailpoet.atlassian.net/browse/MAILPOET-3146
This covers upgrades of Doctrine and PHPStan. More packages will come in [subsequent task](https://mailpoet.atlassian.net/browse/MAILPOET-3203)
I [ran a premium build with this branch](https://app.circleci.com/pipelines/github/mailpoet/mailpoet-premium/513/workflows/d2ecc23c-f4f8-46f4-aee0-b6f5376f3935) and it seems to work correctly.
=> Update PHP dependencies to PHP 7.1 - Part 1 [MAILPOET-3146]

.circleci/config.yml, .circleci/setup.bash, tests/docker/codeception/docker-entrypoint.sh
Successful build example:
https://app.circleci.com/pipelines/github/mailpoet/mailpoet/4749/workflows/ed97e9f8-dad9-4ed2-bb18-2a5a875fe8e4
You can check that Premium is active during each of the `with_premium` jobs.
=> Add tests with Premium plugin active in Free nightly build [MAILPOET-1601]

tests/_support/AcceptanceTester.php
[MAILPOET-3245](https://mailpoet.atlassian.net/browse/MAILPOET-3245)
I also thought at first that the issue was with 10s of waiting time, so I have increased that to 20s but again issue has occured.
The problem was that it needed a bit of waiting time in order to focus and click on Place Order button.
Test results:
- With added waitForText: Passed 20 out of 20 tries
- Without added waitForText: Failed 2 out of 10 tries
=> Fix flakiness in Acceptance Tester [MAILPOET-3245]

lib/AdminPages/Pages/FormEditor.php, lib/Form/Renderer.php, lib/Form/Util/Styles.php, lib/Form/Widget.php
This PR adds handling of corrupted serialized form settings data, that can't be unserialized.
1.  Prevents rendering such a form on the front end
2. Uses initial form's settings as fallback value for form editor
[MAILPOET-3294]
[MAILPOET-3294]: https://mailpoet.atlassian.net/browse/MAILPOET-3294
=> Handling corrupted form settings data [MAILPOET-3294]

lib/Mailer/Methods/AmazonSES.php, lib/Settings/Hosts.php
New AWS accounts in US East are automatically assigned to the region "us-east-2", which corresponds to "US East (Ohio)".
This PR adds the corresponding strings where there are AWS regions listed in the code. Editing "US East (N. Virginia)" in place is not sufficient.
=> Add "US East (Ohio)" region to Amazon SES options

assets/css/src/components-plugin/_listing.scss, assets/js/src/form/form.jsx
[MAILPOET-3347]
There are actually two bugs in one. Loading not shown is easy, we just forgot to update CSS for it during the redesign.
The second issue (new sub/list forms cleared on save) needs some explanation. The line that triggers the problematic form clearing is this one: 
https://github.com/mailpoet/mailpoet/blob/c3cca1b040fd69d43c22cbe420929f3ac226e8de/assets/js/src/form/form.jsx#L34
It appeared more than 5 years ago in one of the first commits to MP3:
https://github.com/mailpoet/mailpoet/commit/e471d45827e4e27fee2d67e3a3a0c52addd35a3e#diff-e90b4aa64ac86af261543916331c172d6f2741cab3c53f7a5431480484475a17R56
At some point the method it was invoked in was changed from `componentWillReceiveProps` to `componentDidUpdate`:
https://github.com/mailpoet/mailpoet/commit/65653b458943cdfd424 …
=> Don't clear new sub/list forms on save, fix loading opacity [MAILPOET-3347]

assets/js/src/listing/listing_column.jsx, tests/acceptance/ManageSegmentsCest.php
The test was flaky because default sorting is done using created_at and all users created in the test have the same date.
Fixed by reordering subscribers by email during the test.
[MAILPOET-3365]
[MAILPOET-3365]: https://mailpoet.atlassian.net/browse/MAILPOET-3365
=> Fix flaky ManageSegmentsCest [MAILPOET-3365]

lib/Form/AssetsController.php
When using a subscription form as an iframe, our CSP catched up that the reCAPTCHA API was included despite MailPoet being configured to use its internal CAPTCHA. The following change will only output the relevant <script> tag when MailPoet uses reCAPTCHA.
=> Source reCAPTCHA API only when needed [MAILPOET-3363]

README.md
This PR makes three minor adjustments to the portion of the README.md file that details how to setup a MailPoet development environment:
- Removes docker and docker compose as requirements as they are used to run the acceptance tests but not MailPoet itself
- Adds composer as a MailPoet requirement
- Adds a note making it explicit that the instructions assume that there is already a working WP dev environment configured on the machine.
Since I'm new to MailPoet there is a high chance that I'm missing something and that the changes that I'm suggesting don't make sense for some reason. If that is the case, just let me know :-)
=> Minor updates to the instructions on how to setup a MailPoet development environment

.env.sample
The .env.sample file contained a few comments using `//`. The problem is that `//` is not supported by vlucas/phpdotenv and this was resulting in the following fatal error when following the dev environment setup instructions and running `./do install`:
```
ERROR: Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file due to unexpected whitespace. Failed at ["" // URL of your site (used for multisite env and equals to DOMAIN_CURRENT_SITE from wp-config.php)]. in /srv/www/mailpoet/public_html/wp-content/plugins/mailpoet/vendor/vlucas/phpdotenv/src/Parser.php:148
```
To fix this problem, this commit replaces all instances of `//` in .env.sample with the `#` (see
https://github.com/vlucas/phpdotenv#comments).
Quick test show that `//` doesn't work and `#` does:
```
>>> …
```
=> Fix a syntax issue in .env.sample

doc/Readme.md
This PR removes a reference to the minimum required PHP version (which is presumably outdated as it mentions PHP 5.6) from the MailPoet API documentation.
I'm assuming that the minimum required version to use the API is the same as the one to run MailPoet. If that is the case, I don't see a reason to mention it in the API documentation, and removing it has the benefit of reducing the maintenance burden when the minimum required version is updated.
As usual please let me know if I'm missing something and this change doesn't make sense as I'm still a MailPoet newbie.
=> Remove minimum required PHP version

assets/js/src/newsletters/automatic_emails/listings.jsx
[MAILPOET-3318]
[MAILPOET-3318]: https://mailpoet.atlassian.net/browse/MAILPOET-3318
=> Fix missing statistics link in WooCommerce listing [MAILPOET-3318]

assets/css/src/generic/_typography.scss
[MAILPOET-3305]
[MAILPOET-3305]: https://mailpoet.atlassian.net/browse/MAILPOET-3305
=> Override #wpbody color to default for form-editor [MAILPOET-3305]

prefixer/fix-carbon.php
[MAILPOET-3240]
PHPScoper was updated with PR for composer v2.
[MAILPOET-3240]: https://mailpoet.atlassian.net/browse/MAILPOET-3240
=> Remove patching for ternary operators warnigns [MAILPOET-3240]

tests/integration/Segments/WPTest.php
[MAILPOET-3367]
[MAILPOET-3367]: https://mailpoet.atlassian.net/browse/MAILPOET-3367
=> Use timestamp for DateTime compare in Segments WPTest [MAILPOET-3367]

views/premium.html
In the page admin.php?page=mailpoet-premium, we display six reviews that customers gave us. In three of those reviews, we were displaying the name of the username of the customer twice. This PR simply removes the duplicate usernames.
Related issue: https://mailpoet.atlassian.net/browse/MAILPOET-3392
=> Remove duplicated username from user reviews in the premium page [MAILPOET-3392]

mailpoet.php, readme.txt
This PR bumps the "Tested up to" tag in the readme.txt file to 5.6 and it also removes the same tag from mailpoet.php. See bf24a8b commit message for an explanation on why I believe we can remove the tag from mailpoet.php.
[MAILPOET-3394]
[MAILPOET-3394]: https://mailpoet.atlassian.net/browse/MAILPOET-3394
=> Bump "Tested up to" tag in readme.txt and remove it from mailpoet.php [MAILPOET-3394]

assets/js/src/subscribers/importExport/import/step_data_manipulation/generate_segment_selection.jsx
[MAILPOET-3423]
The bug was introduced [in this commit](https://github.com/mailpoet/mailpoet/pull/3278/commits/31e0be8feabe3e21beb2e36c545d92b3b3e06c10) that caused that `segment.text` property was not set. We don't use `segment.text` property in our code, but it is needed inside select2 for search.
[MAILPOET-3423]: https://mailpoet.atlassian.net/browse/MAILPOET-3423
=> Fix searching segments in subscribers import [MAILPOET-3423]

assets/js/src/settings/store/actions/mss_and_premium.ts
I fixed the saving of settings so that it doesn't "forget" other mta properties. It copies [the same logic that is used in send with tab](https://github.com/mailpoet/mailpoet/blob/master/assets/js/src/settings/pages/send_with/send_with_choice.tsx#L26-L29).
I was thinking about refactoring it to some specific action + reducer but for some reason, we need to save data on API and then we set the data from API response to the store and replace all settings. I think this is needed to prevent setting an invalid MSS key to the store.
[MAILPOET-3401]
[MAILPOET-3401]: https://mailpoet.atlassian.net/browse/MAILPOET-3401
=> Keep old sending settings when activating MSS via key validation [MAILPOET-3401]

RoboFile.php, package.json, tasks/code_sniffer/MailPoet/ruleset.xml
This PR adds PHPCS checks, using `./do qa:code-sniffer`, to the pre-commit hook. To be able to do this, I had to modify `./do
qa:code-sniffer` to call PHPCS only once and change its signature to accept an optional parameter with the list of files to check. If this parameter is not passed, all files are checked.
As discussed with the rest of the team, before we were calling PHPCS multiple times to be able to check for compatibility with different versions of PHP, but as far as we can tell this is not necessary, and we can check for compatibility with PHP >= 7.1 for all files.
As far as I know, changing the signature of RoboFile::qaCodeSniffer() is not a problem and I updated the only instance where this method is called. But it would be good if someone with more experience with this part …
=> Add PHPCS checks to the pre-commit hook [MAILPOET-3439]

.github/SECURITY.md
This PR updates the SECURITY.md file to point security researchers to HackerOne. I copied the SECURITY.md file from WooCommerce and made some minor changes to reflect MailPoet specificities.
[MAILPOET-3410]
[MAILPOET-3410]: https://mailpoet.atlassian.net/browse/MAILPOET-3410
=> Update SECURITY.md to point security researchers to HackerOne [MAILPOET-3410]

README.md
This PR updates the documentation of some Robo commands that were using `:` instead of `-` to separete words for commands with more than two words resulting in command not found errors. Simply replacing the aforementioned character fixes the commands.
For two release related commands, it was also necessary to add the `release` prefix.
[MAILPOET-3444]
[MAILPOET-3444]: https://mailpoet.atlassian.net/browse/MAILPOET-3444
=> Update documentation of some Robo commands [MAILPOET-3444]

lib/AdminPages/PageRenderer.php, views/layout.html
This PR fixes a problem in the logic used to decide whether or not the HelpScout chat should be available on the MailPoet admin pages. Before, we were displaying the chat for plans that include premium support and access to MSS. But we also have plans, like the Blogger plan, that include premium support, and should see the chat, but don't include access to MSS. Those plans were not seeing the chat.
This was happening because the code was checking just for `mailpoet_api_key_state.data.support_tier == 'premium'`. The mailpoet_api_key_state setting is added to the database based on the response from the bridge.mailpoet.com/me endpoint. This endpoint returns a 403 error for plans that don't include the sending service.
In this PR to fix this problem, the code now checks for both …
=> Display the HelpScout chat for all plans with premium support [MAILPOET-3438]

.circleci/config.yml, .circleci/setup.bash, package.json, tests/integration/Subscribers/ImportExport/Import/ImportTest.php, tests/integration/_bootstrap.php
[MAILPOET-3412]
[MAILPOET-3411]
There wasn't only one reason why the tests became flaky, but it was a combination of 2 things:
I've added some logging into the test run and you can [see in the output](https://115581-38753514-gh.circle-artifacts.com/0/codeception/cronLog.txt) that both WP Cron and MailPoet Cron run during tests (look for `wp-cron.php` and `mailpoet_router&endpoint=cron_daemon&action=run`).
Either WP Cron or MailPoet cron triggers the plugin initialization for every run and this combined with the fact that we truncate various tables during tests may cause e.g. that Populator runs and add some data into tables. Overall these background initialization may cause random issues and failures.
To fix that I've disabled WP cron in wp-config used on CI and added scheduled tasks …
=> Fix flaky integration tests [MAILPOET-3412][MAILPOET-3411]

lib/AutomaticEmails/WooCommerce/Events/PurchasedInCategory.php, tests/integration/AutomaticEmails/WooCommerce/Events/PurchasedInCategoryTest.php
The "Purchased In This Category" email was not working for variable products. This was happening because MailPoet calls
WC_Product::get_category_ids() to get the list of WooCommerce categories associated with a given product, but this method doesn't work for product variations (see https://github.com/woocommerce/woocommerce/issues/12942).
In this PR, I'm implementing a workaround. I changed the code to check if the product is a product variation and, if so, get the
categories from the parent product instead of the product itself. But I also plan to raise this issue with the WooCommerce team as, in my opinion, it is odd that WC_Product::get_category_ids() doesn't work with product variations and fails silently.
Testing instructions in the Jira issue.
[MAILPOET-3416]
[MAILPOET-3416]: …
=> Fix "Purchased In This Category" email for product variations [MAILPOET-3416]

lib/WooCommerce/TransactionalEmailHooks.php, tests/integration/WooCommerce/TransactionalEmailHooksTest.php, tests/integration/_bootstrap.php
This PR changes the WC action that MailPoet uses to hook into WC and customize the footer and the header of WC e-mails. Before, MailPoet was using the woommerce_init action. The problem with using this action to customize the e-mails is that it runs on every request. Furthermore, since we were calling WC->mailer() inside the callback, we were instantiating WC_Emails on every single request (WooCommerce instantiate this class only when needed).
Replacing woocommerce_init with woocommerce_email means that our code will run only when needed (right after WooCommerce adds callbacks to the actions woocommerce_email_header and woocommerce_email_footer) and that we won't be unnecessarily instantiating WC_Emails ourselves. We get the singleton instance of this class as a parameter.
I'm not …
=> Use the woocommerce_email action to customize WC emails [MAILPOET-3421]

lib/AutomaticEmails/WooCommerce/Events/AbandonedCart.php
Some users were getting the PHP notice below when using the user-switching (https://wordpress.org/plugins/user-switching/) plugin to switch to a different user.
```
PHP Notice: get_cart was called incorrectly. Get cart should not be called before the wp_loaded action.
```
This notice is generated by WooCommerce when `WC_Cart::get_cart()` is called before the `wp_loaded` action. user-switching calls a WooCommerce method to empty the user session and the cart when switching users, and this happens before wp_loaded. MailPoet hooks into the woocommerce_cart_emptied action (https://github.com/mailpoet/mailpoet/blob/c9ca134d300f788bb14bf7475b98e1126a07264a/lib/AutomaticEmails/WooCommerce/Events/AbandonedCart.php#L118) to decide whether it should schedule or cancel an abandoned cart email. When …
=> Fix PHP notice when the plugin user-switching is active [MAILPOET-3374]

lib/Segments/WP.php, tests/integration/Segments/WPTest.php
MailPoet syncs users from wp_users to wp_mailpoet_subscribers. The problem is that WP stores first and last names in a longtext field, and MP uses a varchar(255) field. This was causing a fatal error when synchronizing names over 255 characters. This commit fixes this problem by using SUBSTRING() to make sure that the 255 characters limit is enforced when adding values to the columns first_name and last_name of the wp_mailpoet_subscribers table. This should get rid of the fatal error, and it shouldn't be a problem to most users as it is unlikely that a real user has a first or last name that is longer than 255 characters.
@NeosinneR, you mentioned in the issue description performance concerns with SUBSTRING(). As far as I can tell, this should not impact the query in any meaningful way …
=> Truncate first and last names before adding to wp_mailpoet_subscribers [MAILPOET-3246]

lib/Config/Initializer.php
This PR makes sure that MailPoet tables are dropped when a site is deleted in a multisite install. It uses the filter `wpmu_drop_tables` to add the list of MailPoet tables to the list of tables that WP drops whenever a site is deleted in a multisite install.
This will only work if MailPoet is network active. If it is not, MailPoet code is not executed inside the WP network admin panel, and thus our filter is not added to `wpmu_drop_tables`, and MP tables are not deleted.
**How to test this PR**
- On a multisite install, network activate MailPoet and create a few sites.
- Open the dashboard of the new sites so that MP tables are created.
- Delete one of the new sites and check that MP tables for the correct site were deleted.
Important: if there is a bug in this code, we have the potential …
=> Drop MailPoet tables when a site is deleted in a multisite install [MAILPOET-3265]

assets/js/src/subscribers/importExport/export.ts
[MAILPOET-3458]
I duplicate a property `name` as `text` because Select2 needs properties `id` and `text`.
Maybe it would be a better solution to refactor our code for using the property `text` instead of `name`. When I have tried it then didn't work correctly import. I don't want to spend more time with it but if you think that it's worth it. I don't think because we want to remove Select2 in the future.
[MAILPOET-3458]: https://mailpoet.atlassian.net/browse/MAILPOET-3458
=> Duplicate the name property as the text for Select2 search [MAILPOET-3458]

assets/js/src/settings/store/actions/mss_and_premium.ts
This PR fixes a bug in the code where a user could override their key if, after validating a new key, they went to a different settings tab and clicked "Save settings". When reloading the page, they would see the old key instead of the new one.
This was happening because the function verifyPremiumKey() was updating the key in the backend but was not updating the settings object in the frontend. So when the user switched to another settings tab and clicked on the "Save settings" button, the function saveSettings() was saving to the backend a settings object containing the old key instead of the new one.
To fix this problem, this PR updates the settings object with the new premium key whenever a new key is validated.
Please note that I'm fairly new to modern JS and React development so …
=> Preserve new key when saving settings [MAILPOET-3447]

tests/docker/codeception/docker-entrypoint.sh
WordPress core auto-update process running during tests bootstrap collides with WPCLI calls and that causes unexpected errors during the bootstrap.
[MAILPOET-3475]
[MAILPOET-3475]: https://mailpoet.atlassian.net/browse/MAILPOET-3475
=> Disable WP core autoupdate in tests [MAILPOET-3475]

tests/integration/Subscribers/SubscriberListingRepositoryTest.php
This PR attempts to fix the integration test SubscriberListingRepositoryTest::testReturnsCorrectCountForSubscribersInDynamicSegment() that was failing sometimes on CircleCI. My theory is that the test was failing because we were using created_at to order the subscribers in the query that is used to get subscribers in a given dynamic segment. Still, there is a chance the the value of this field is the same for all three subscribers that are created in this test. As this could lead to a situation where the order of the returned subscribers changes, causing the test to fail. To work around that, I changed the test to order the results by ID. This way, we should always get the subscribers in the same order, and I don't expect that the test will fail again.
Running this particular test a few …
=> Attempt to fix a flaky integration test [MAILPOET-3451]

.circleci/config.yml
This revert the previous [hotfix](https://github.com/mailpoet/mailpoet/pull/3392). The issue was fixed by the CirceCI team.
[MAILPOET-3497]
[MAILPOET-3497]: https://mailpoet.atlassian.net/browse/MAILPOET-3497
=> Use mysql8.0 latest in integration tests [MAILPOET-3497]

lib/Newsletter/Shortcodes/Categories/Link.php, lib/Newsletter/Shortcodes/Shortcodes.php, lib/WP/Functions.php, tests/integration/Newsletter/ShortcodesTest.php
[MAILPOET-3465]
We already had limited support for arguments: it was using a different syntax than WordPress (`[category:action | argument:argument_value]`), supported only one argument per shortcode and that argument was not passed to custom shortcode functions.
I have added support for WP-style shortcodes with multiple arguments (`[category:action arg1="value1" arg2="value2"]`), they are now passed to custom functions. The support for MailPoet-style shortcodes is retained for backwards compatibility.
One thing to be aware of is that the shortcode string passed to a custom function can be full (with arguments) or stripped of arguments depending on the `tracking.enabled` setting value. So if arguments are used in a custom function, the check for a proper shortcode inside it should verify …
=> Add support for arguments in custom shortcodes [MAILPOET-3465]

lib/Util/ConflictResolver.php
[Allowing loading Jetpack JS](https://github.com/mailpoet/mailpoet/pull/3362) introduced an issue with a broken image library due to some JS conflict. This PR disallows the loading of Jetpacks JS files on MailPoet admin pages and keeps allowed only Jetpack's CSS.
[MAILPOET-3504]
[MAILPOET-3504]: https://mailpoet.atlassian.net/browse/MAILPOET-3504
=> Disallow jetpack JS on mailpoet admin pages [MAILPOET-3504]

assets/js/src/segments/list.jsx, assets/js/src/segments/segments.jsx, lib/API/JSON/v1/DynamicSegments.php, lib/API/JSON/v1/Segments.php
[MAILPOET-3490]
The Lists tab had no hash assigned to it (`/`), this caused URL hash tab navigation to be broken. I assigned a hash to the tab, this led to the disappearance of the `params` argument from the request which caused constraints not being applied to listings, i.e. both simple and dynamic segments shown on either tab. So I brought this dummy parameter back on the server side.
**For QA:**
Please verify that all listing functions (sorting, searching, filtering, pagination etc.) work on both Lists page tabs and data is displayed properly.
[MAILPOET-3490]: https://mailpoet.atlassian.net/browse/MAILPOET-3490
=> Redirect to segments listing after segment editing [MAILPOET-3490]

lib/Subscribers/SubscriberSegmentRepository.php
When we update subscriber segment status via executeUpdate,
we have to refresh the state from the DB.
[MAILPOET-3551]
[MAILPOET-3551]: https://mailpoet.atlassian.net/browse/MAILPOET-3551
=> Fix reset subscriptions in SegmentsRepository [MAILPOET-3551]

lib/Entities/NewsletterEntity.php, lib/Listing/Handler.php, lib/Newsletter/Renderer/Blocks/Footer.php, lib/Newsletter/Renderer/Blocks/Header.php, tasks/phpstan/composer.json, tasks/phpstan/composer.lock, tasks/phpstan/php-version-dependent-config-libs.php, tests/integration/Models/SubscriberTest.php, tests/unit/Newsletter/Renderer/Blocks/FooterTest.php, tests/unit/Newsletter/Renderer/Blocks/HeaderTest.php
This PR updates PHPStan to version 0.12.83 to fix a problem that we had where it was not possible to run PHPStan with PHP > 8.0.0. For more information, see this thread: https://github.com/phpstan/phpstan/discussions/4762.
Please note that I'm running Composer 2, and thus when I used to update PHPStan, it also updated the value of the field `plugin-api-version` in `composer.lock`. I'm not sure if this is a problem or not and if we have a reason to want to keep using Composer 1.
[MAILPOET-3491]
[MAILPOET-3491]: https://mailpoet.atlassian.net/browse/MAILPOET-3491
=> Update PHPStan to 0.12.83 [MAILPOET-3491]

lib/API/JSON/v1/Forms.php, lib/DI/ContainerConfigurator.php, lib/Form/FormSaveController.php, lib/Form/FormsRepository.php, tests/integration/API/JSON/v1/FormsTest.php, tests/integration/Form/FormSaveControllerTest.php, tests/integration/Form/FormsRepositoryTest.php
This PR was created based on the branch of #3431. Please review #3431 first and once it is merged, review this PR.
[MAILPOET-3039]
[MAILPOET-3039]: https://mailpoet.atlassian.net/browse/MAILPOET-3039
=> Refactor Forms::trash(), Forms::restore() and Forms::delete() to use Doctrine [MAILPOET-3039]

lib/API/JSON/v1/DynamicSegments.php
Users creating a product based WooCommerce segment without specifying a product were getting an error message asking them to select a category, and the inverse was happening for users creating a category based WooCommerce segment. This PR simply makes sure the proper error message is displayed.
[MAILPOET-3561]
[MAILPOET-3561]: https://mailpoet.atlassian.net/browse/MAILPOET-3561
=> Error messages for product and category segments were inverted [MAILPOET-3561]

.circleci/config.yml, RoboFile.php, assets/js/src/segments/dynamic/dynamic_segments_filters/woocommerce_subscription.tsx, assets/js/src/segments/dynamic/form.tsx, assets/js/src/segments/dynamic/form_filter_fields.tsx, assets/js/src/segments/dynamic/segment_form_data.ts, assets/js/src/segments/dynamic/subscribers_counter.tsx, assets/js/src/segments/dynamic/types.ts, lib/AdminPages/Pages/Segments.php, lib/DI/ContainerConfigurator.php, lib/Entities/DynamicSegmentFilterData.php, lib/Segments/DynamicSegments/FilterDataMapper.php, lib/Segments/DynamicSegments/FilterHandler.php, lib/Segments/DynamicSegments/Filters/WooCommerceSubscription.php, lib/Segments/SegmentDependencyValidator.php, lib/WP/AutocompletePostListLoader.php, tasks/GithubClient.php, tasks/phpstan/custom-stubs.php, tasks/phpstan/function-stubs.php, tasks/phpstan/phpstan-tests.neon, tests/DataFactories/WooCommerceProduct.php, tests/DataFactories/WooCommerceSubscription.php, tests/_support/AcceptanceTester.php, tests/_support/PluginsExtension.php, tests/acceptance.suite.yml, tests/acceptance/WooCommerceSubscriptionsSegmentCest.php, tests/docker/codeception/docker-entrypoint.sh, tests/unit/Segments/DynamicSegments/FilterDataMapperTest.php, views/segments.html
This PR adds a new dynamic segment for active WooCommerce subscriptions.
I tried using [wcs_get_subsciptions](https://github.com/wp-premium/woocommerce-subscriptions/blob/master/wcs-functions.php#L425) for the implementation of the subscriber filter but since it does additional 3 queries per subscriber I decided to go with direct SQL.
The PR also adds a basic infrastructure for working with 3rd party plugins.
[MAILPOET-3471]
[MAILPOET-3471]: https://mailpoet.atlassian.net/browse/MAILPOET-3471
=> Woo Subscriptions Segment [MAILPOET-3471]

tests/DataFactories/WooCommerceOrder.php
After debugging I found that the test failed when ran after [WooCommerceSetupPageCest:: setupPageRedirectionTest](https://github.com/mailpoet/mailpoet/blob/master/tests/acceptance/WooCommerceSetupPageCest.php#L94). 
It seems that updating order using `wp_update_post` causes that we are not able to use
`wc_get_product` (it returns false) and probably some other functions from WooCommerce.
We needed `wp_update_post` for updating post_created_at in order to create some older orders. I replaced `wp_update_post` with a DB query and it fixed the issue.
[MAILPOET-3577]
[MAILPOET-3577]: https://mailpoet.atlassian.net/browse/MAILPOET-3577
=> Fix flaky Woo Subscriptions test [MAILPOET-3577]

.circleci/config.yml, .gitignore, README.md, RoboFile.php, tasks/GithubClient.php, tests/DataFactories/WooCommerceSubscription.php, tests/acceptance/FormEditorAddNamesCest.php, tests/acceptance/FormWithColumnsCest.php, tests/acceptance/ManageSegmentsCest.php, tests/acceptance/SubscriberManageImportExportCest.php, tests/docker/codeception/docker-entrypoint.sh, tools/install.php
This PR contains a few more changes.
- I've refactored download the WooCommerce plugin so that it uses the same mechanism as WooCommere Subscriptions
- Changed directory where we download the 3rd party plugins
- Updated version of the image we use on Circle CI machine executor for acceptance tests. The image version refers to AWS Ami that is available. We were using some old default Ubuntu 14 with a quite old docker version.
- Fixed a couple of flaky acceptance test I run into during testing
[MAILPOET-3482]
[MAILPOET-3482]: https://mailpoet.atlassian.net/browse/MAILPOET-3482
=> WooCommerce versions in test [MAILPOET-3482]

lib/Subscribers/InactiveSubscribersController.php
There are 2 optimizations in the PR. The first optimization is that the sub query for checking that a newsletter associated with a task has something tracked was moved from where clause to join so that it runs only once instead of for every line. The second was the removal `created_at` condition from the subquery.
We don’t necessarily need to use where `created_at` for statics open since we already restrict the sending task by the `processed_at` date and it is the `created_at` that forces the DB to scan multiple rows. It is impossible for a standard newsletter or post notification to have a record in opens stats before it was sent.  Automated and welcome emails have some opens logged further in the past so the check might not work correctly for sites using welcome emails that turned off …
=> Optimise tasks SQL query in inactive subscribers detection [MAILPOET-3582]

lib/Newsletter/ApiDataSanitizer.php, tests/integration/Newsletter/ApiDataSanitizerTest.php
I've fixed this by modifying API data sanitiser for newsletter so that it fixes text property only for specific blocks, that are using TinyMCE for editing.
[MAILPOET-3538]
[MAILPOET-3538]: https://mailpoet.atlassian.net/browse/MAILPOET-3538
=> Fix double escaped button in newsletter [MAILPOET-3538]

lib/Cron/Workers/SubscribersEngagementScore.php, lib/Segments/SegmentsRepository.php, lib/Statistics/StatisticsOpensRepository.php, lib/Statistics/Track/Opens.php
[MAILPOET-3633]
The solution has three steps:
1. I removed the unnecessary problematic query because the check is solved in the subscriber's score calculation, and the aggregation function doesn't compute with null values.
2. I dropped the segment's score calculation from the tracking.
3. The segment score is outdated after a day.
[MAILPOET-3633]: https://mailpoet.atlassian.net/browse/MAILPOET-3633
=> Fix performance trouble in segment score calculation [MAILPOET-3633]

assets/js/src/post_editor_block/subscription_form/form_block.jsx
In the latest Gutenberg right after fetching the data
are sanitised using `__experimentalSanitizeBlockAttributes`
that is trying to get block from the store
but our block was not registered in the store.
[MAILPOET-3609]
[MAILPOET-3609]: https://mailpoet.atlassian.net/browse/MAILPOET-3609
=> Fix the post block in the latest Gutenberg [MAILPOET-3609]

lib/Config/Env.php, lib/Doctrine/ConnectionFactory.php, tests/integration/Config/EnvTest.php, tests/integration/Doctrine/ConnectionFactoryTest.php
[MAILPOET-3580]
[MAILPOET-3580]: https://mailpoet.atlassian.net/browse/MAILPOET-3580
=> Use WP connection db port if missing in config [MAILPOET-3580]

lib/DI/ContainerConfigurator.php, lib/Newsletter/Renderer/Blocks/Placeholder.php, lib/Newsletter/Renderer/Blocks/Renderer.php, lib/Newsletter/Renderer/Preprocessor.php, lib/WooCommerce/TransactionalEmails/ContentPreprocessor.php, lib/WooCommerce/TransactionalEmails/Renderer.php, tests/integration/WooCommerce/TransactionalEmails/RendererTest.php, tests/unit/Newsletter/Renderer/PreprocessorTest.php
[MAILPOET-3638]
I found out that we need to wrap the WC content with another table. The reason is that WC [use another padding](https://github.com/woocommerce/woocommerce/blob/trunk/templates/emails/email-styles.php#L110-L116)
[MAILPOET-3638]: https://mailpoet.atlassian.net/browse/MAILPOET-3638
=> Wrap WC content with table [MAILPOET-3638]

lib/AdminPages/Pages/NewsletterEditor.php, lib/Config/Initializer.php, lib/Entities/NewsletterEntity.php, lib/WooCommerce/TransactionalEmailHooks.php, tests/integration/WooCommerce/TransactionalEmailHooksTest.php
[MAILPOET-3645]
I found out that the problematic behavior was added as a feature in [https://mailpoet.atlassian.net/browse/MAILPOET-2569](https://mailpoet.atlassian.net/browse/MAILPOET-2569). The feature added[ sync between global styles of the email template used for WooCommerce emails and WooCommerce email settings](https://github.com/mailpoet/mailpoet/pull/2493/files#diff-e5a46d48bf0c8cf527ad3a169576582428411a4f8522342fbe7ca46fd502d8a6R136-R151). Side effect of this feature was that every time a user saved the WooCoommece template it overwrote WooCommerce settings.
The reason why the sync was added was:
> After testing the WC Email customizer with Bruna, we realized that the UX was not great because when we modified global styles, those new styles were not applied to the WC Email …
=> Refactor woo email global styles settings [MAILPOET-3645]

assets/js/src/public.jsx
Hey there!
Here is Matthew, the developer behind [Real Cookie Banner](https://wordpress.org/plugins/real-cookie-banner/). We have now several requests to make a service template for MailPoet. Yesterday, we started to create a compatibility with Real Cookie Banner + MailPoet. Unfortunately, there is some sort of double execution of `jQuery.ready`. This does currently not allow us to block MailPoet forms until the user has given consent to it.
Real Cookie Banner (_RCB_) modifies the way `jQuery.ready` work. Before transforming content back (_in other words: A user has given consent and wants to unblock MailPoet forms_), RCB puts all the "unblocks" into transactions and the `jQuery.ready` is modified in that way, that it waits for the transaction has complete and executes the passed handler. …
=> fix: avoid double execution of `jQuery.ready`

lib/Subscribers/SubscriberSubscribeController.php
The issue was caused by [the refactoring subscribing to Doctrine](https://github.com/mailpoet/mailpoet/pull/3440).
The reason is that we stored the segment ids as unconfirmed data. After that, a user clicked on the confirmation link, and the method createOrUpdate called the method resetSubscriptions that unsubscribe the user from the old segments.
[MAILPOET-3663]
[MAILPOET-3663]: https://mailpoet.atlassian.net/browse/MAILPOET-3663
=> Remove segment ids from unconfirmed data on subscribe [MAILPOET-3663]

lib/Statistics/Track/Opens.php
We count subscriber score based on tracked opens. There is no need to recalculate it when a new open wasn't _added._
[MAILPOET-3669]
[MAILPOET-3669]: https://mailpoet.atlassian.net/browse/MAILPOET-3669
=> Recalculate subscriber score only when a new open was tracked [MAILPOET-3669]

lib/Doctrine/Repository.php, lib/Doctrine/TablePrefixMetadataFactory.php, lib/Entities/NewsletterEntity.php, lib/Entities/NewsletterLinkEntity.php, lib/Entities/SegmentEntity.php, lib/Entities/StatisticsClickEntity.php, lib/Entities/SubscriberEntity.php, lib/Newsletter/Renderer/Blocks/AbandonedCartContent.php, lib/Segments/SegmentsRepository.php, lib/Subscribers/ImportExport/ImportExportRepository.php, lib/Tasks/Subscribers/BatchIterator.php, lib/Tracy/ApiPanel/ApiPanel.php, tasks/phpstan/phpstan-tests.neon, tasks/phpstan/phpstan.neon, tests/integration/AutomaticEmails/WooCommerce/Events/AbandonedCartPageVisitTrackerTest.php, tests/integration/AutomaticEmails/WooCommerce/Events/AbandonedCartTest.php, tests/integration/Newsletter/NewsletterSaveControllerTest.php, tests/unit/Form/HtmlParser.php
In this PR, I have changed phpstan.neon and phpstan-tests.neon and removed the lines that were added to skip the following checks: checkGenericClassInNonGenericObjectType, checkMissingVarTagTypehint, and checkMissingTypehints. I have also fixed all the errors that PHPStan reported after I changed its configuration files.
Please note that before working on this, I was not familiar with those specific PHPStan checks, so there is a chance that I missed something.
Also, each commit contains all the relevant changes for a specific PHPStan check. It might be easier to review this PR commit by commit.
[MAILPOET-3236]
[MAILPOET-3236]: https://mailpoet.atlassian.net/browse/MAILPOET-3236
=> Fix some PHPStan errors and update PHPStan configuration accordingly [MAILPOET-3236]

lib/API/JSON/v1/Segments.php, lib/Form/FormsRepository.php, lib/Segments/SegmentsRepository.php, tests/acceptance/Lists/ManageListsCest.php, tests/integration/API/JSON/v1/SegmentsTest.php
When a user tries to trash a list that is attached to a form, we show a message instead of allowing them to trash the list:
`List cannot be deleted because it’s used for {$formName} form`
Follows the same behavior as when deleting a list if attached to a newsletter.
[MAILPOET-3661] 
[MAILPOET-3661]: https://mailpoet.atlassian.net/browse/MAILPOET-3661
=> Prevent deleting a list if attached to a form [MAILPOET-3661] 

lib/Subscribers/ImportExport/Import/Import.php, tests/integration/Subscribers/ImportExport/Import/ImportTest.php
Allow import subscribers with empty `confirmed_ip` or `subscribed_ip` when one of the columns is selected in the last step of the import.
Don't allow importing invalid IP addresses - still import the subscriber but remove the invalid IP address.
[MAILPOET-3665]
[MAILPOET-3665]: https://mailpoet.atlassian.net/browse/MAILPOET-3665
=> Allow import subscribers with empty IP address [MAILPOET-3665]

package-lock.json, package.json, tests/javascript_newsletter_editor/mochaTestHelper.js
This PR updates jsdom to version 16.7.0. It also updates tests/javascript_newsletter_editor/mochaTestHelper.js to use the new jsdom API as the old API was removed.
As usual, please note that I'm not an experienced JS developer, so I'm unsure if my approach to this update, especially the changes to mochaTestHelper.js, is correct. After creating this PR, I will add some inline comments with more details about some of the changes that I made.
@costasovo, in the ticket description, you mentioned that after updating jsdom, we might be able to remove some things from mochaTestHelper.js. I removed everything that it seemed to me that it wouldn't break the tests. Was there anything else on your mind?
Also, it seems to me that we are using jsdom in a way that is not recommended …
=> Update jsdom to version 16.7.0

.git-blame-ignore-revs
This is subsequent PR [to the dependencies update PR](https://github.com/mailpoet/mailpoet/pull/3583)
Updating lint name generate many changed lines. This PR adds the commit to the ignore list for the git blame tool.
[MAILPOET-3658]
[MAILPOET-3658]: https://mailpoet.atlassian.net/browse/MAILPOET-3658
=> Ignore lint rule name update in git blame [MAILPOET-3658]

lib/Newsletter/Renderer/Renderer.php, lib/Newsletter/Renderer/StylesHelper.php
This PR protects the code that renders styles for e-mails against a fatal error that could happen if the variable $styles passed to Renderer::renderStyles() is not an array of arrays. To do that, the code will now check if each value of the array is an array. If not, we move on to the next value instead of calling StylesHelper::setStyle(). I also added type hints to StylesHelper::setStyle() and some of the methods that it calls to make it more explicit what it expects to receive and what it returns.
See related Jira ticket for testing instructions.
[MAILPOET-3731]
[MAILPOET-3731]: https://mailpoet.atlassian.net/browse/MAILPOET-3731
=> Protect against fatal error when rendering e-mail styles [MAILPOET-3731]

package-lock.json, package.json
To test that this update doesn't break anything, I followed the instructions on the related ticket and tested that running `npm run test` and `./do t:newsletter-editor` still works. I'm not aware of any other place where we are using mocha.
The ticket also mentions updating jsdom, but I will leave this other package to another PR as it seems it will be a more involved process, and updating mocha was fairly straightforward.
[MAILPOET-3678]
[MAILPOET-3678]: https://mailpoet.atlassian.net/browse/MAILPOET-3678
=> Update mocha to the latest version [MAILPOET-3678]

lib/Config/Migrator.php, lib/Entities/StatisticsClickEntity.php, lib/Entities/StatisticsOpenEntity.php, lib/Entities/UserAgentEntity.php, lib/Newsletter/Statistics/NewsletterStatisticsRepository.php, lib/Statistics/StatisticsClicksRepository.php, lib/Statistics/Track/Clicks.php, lib/Statistics/Track/Opens.php, tests/integration/Statistics/Track/ClicksTest.php, tests/integration/Statistics/Track/OpensTest.php
[MAILPOET-3736]
I tried to test the performance on my local with an old mailpoet.com export. It looked fine, but I'm still slightly afraid about recreating indexes in bigger databases. Also, I had to add deleting old indexes because our migration tool doesn't support it.
[MAILPOET-3736]: https://mailpoet.atlassian.net/browse/MAILPOET-3736
=> Differentiate machine opens and clicks [MAILPOET-3736]

lib/Config/PersonalDataExporters.php, lib/DI/ContainerConfigurator.php, lib/Models/StatisticsClicks.php, lib/Models/StatisticsOpens.php, lib/Statistics/StatisticsClicksRepository.php, lib/Statistics/StatisticsOpensRepository.php, lib/Subscribers/ImportExport/PersonalDataExporters/NewsletterClicksExporter.php, lib/Subscribers/ImportExport/PersonalDataExporters/NewsletterOpensExporter.php, lib/Subscribers/ImportExport/PersonalDataExporters/NewsletterStatsBaseExporter.php, tests/integration/Subscribers/ImportExport/PersonalDataExporters/NewsletterClicksExporterTest.php, tests/integration/Subscribers/ImportExport/PersonalDataExporters/NewsletterOpensExporterTest.php
This PR adds a new "User-Agent" field to e-mail clicks data and it also adds a new section with e-mail opens when the WordPress' Export Personal Data tool is used. I also did some refactoring in the code that generates data for e-mail clicks to avoid duplicating it to add the new e-mail opens section. In the process, since I didn't want to add code that interacts with Paris for e-mail opens, I changed parts of the e-mail clicks code to use Doctrine. I meant to refactor the tests to use Doctrine instead of Paris as well but ran out of time.
[MAILPOET-3738]
[MAILPOET-3738]: https://mailpoet.atlassian.net/browse/MAILPOET-3738
=> Include open and click user agents in Export Personal Data tool [MAILPOET-3738]

lib/Mailer/WordPress/WordPressMailer.php, tests/integration/Mailer/WordPress/WordpressMailerTest.php
This PR makes sure that the reply-to set for WP e-mails is preserved when MailPoet is used to send them. Before this change, MailPoet would ignore whatever was set for the reply-to field for WP e-mails and use the same address as the one used for the sender instead.
I'm not super happy with the solution proposed here. I couldn't find an easy way to simply set the reply-to address in the Mailer class, and that is why I'm calling Mailer::init() inside WordPressMailer. There was some discussion in an early PR (#3632) that I created to get feedback, and Pavel proposed using `->setShared(false)` in the ContainerConfigurator to make sure that a new instance of the Mailer class would be created every time we try to get this service. This would solve the problem that I described …
=> Fix reply-to address when sending WP e-mails [MAILPOET-3707]

lib/Newsletter/ViewInBrowser/ViewInBrowserController.php, lib/Newsletter/ViewInBrowser/ViewInBrowserRenderer.php, tests/DataFactories/Newsletter.php, tests/integration/Newsletter/ViewInBrowser/ViewInBrowserControllerTest.php, tests/integration/Newsletter/ViewInBrowser/ViewInBrowserRendererTest.php
Use `NewsletterEntity` and `NewslettersRepository` instead of `MailPoet\Models\Newsletter`.
To test: Edit a Newsletter and preview in browser. Things should work as before
2 integration tests have been also updated to use the Entities instead of the old models.
Run them on the Docker env with:
`./do --test "test:integration --file=tests/integration/Newsletter/ViewInBrowser/ViewInBrowserControllerTest.php"
`
`./do --test "test:integration --file=tests/integration/Newsletter/ViewInBrowser/ViewInBrowserRendererTest.php"
`
I have a question about a function that has a comment saying the function could be removed after the refactoring. Doesn't look like it, see comment on the file below.
[MAILPOET-3637]
[MAILPOET-3637]: https://mailpoet.atlassian.net/browse/MAILPOET-3637
=> Refactor lib/Newsletter/ViewInBrowser to Doctrine [MAILPOET-3637]

lib/Config/Hooks.php, lib/Config/HooksWooCommerce.php, lib/Config/Migrator.php, lib/Config/Populator.php, lib/Cron/Daemon.php, lib/Cron/Triggers/WordPress.php, lib/Cron/Workers/SubscribersLastEngagement.php, lib/Cron/Workers/WorkersFactory.php, lib/DI/ContainerConfigurator.php, lib/Entities/SubscriberEntity.php, lib/Statistics/Track/Clicks.php, lib/Statistics/Track/Opens.php, lib/Subscribers/SubscribersRepository.php, lib/Util/DBCollationChecker.php, lib/WooCommerce/SubscriberEngagement.php, tests/integration/Cron/DaemonHttpRunnerTest.php, tests/integration/Cron/DaemonTest.php, tests/integration/Cron/Workers/SubscribersLastEngagementTest.php, tests/integration/Statistics/Track/ClicksTest.php, tests/integration/Statistics/Track/OpensTest.php, tests/integration/WooCommerce/SubscriberEngagementTest.php
[MAILPOET-3762]
[MAILPOET-3762]: https://mailpoet.atlassian.net/browse/MAILPOET-3762
**Note for QA**
For testing filling of last engagement dates for existing older subscribers, create some engagement data (opens, clicks, and orders) with the current version of the plugin and then install the zip with this feature. The background job is scheduled during plugin activation/update. The last engagement dates are no visible anywhere in UI. You need to install Adminer or PHPMyAdmin and inspect `wp_mailpoet_subscribers` table.
=> Save last subscriber's engagement [MAILPOET-3762]

lib/Segments/DynamicSegments/Filters/EmailAction.php, lib/Segments/DynamicSegments/Filters/MailPoetCustomFields.php
I found that in two filters  the $parameterPrefix for SQL query parameters was not created correctly when called for filter which was not saved.
[MAILPOET-3761]
[MAILPOET-3761]: https://mailpoet.atlassian.net/browse/MAILPOET-3761
=> Fix incorrect counts in dynamic segments form [MAILPOET-3761]

lib/Subscription/Throttling.php, tests/integration/Subscription/ThrottlingTest.php
Skips IP throttling check only for WordPress users with roles administrator or editor. 
Uses a similar [implementation as for captcha](https://github.com/mailpoet/mailpoet/blob/master/lib/Subscription/Captcha.php#L82-L89).
Adds a filter `mailpoet_subscription_throttling_exclude_roles` allowing to set which roles will be allowed to skip the throttling.
Test with:
`./do --test "test:integration --file=tests/integration/Subscription/ThrottlingTest.php"
`
[MAILPOET-3790]
[MAILPOET-3790]: https://mailpoet.atlassian.net/browse/MAILPOET-3790
=> Throttling also for logged-in users [MAILPOET-3790]

lib/WooCommerce/Subscription.php
I couldn't find some nice way of telling WooCommerce to use "standard" checkbox classes so I'm passing them via related options.
[MAILPOET-3498]
[MAILPOET-3498]: https://mailpoet.atlassian.net/browse/MAILPOET-3498
=> Add classes to Woo checkout opt-in to match other checkboxes [MAILPOET-3498]

lib/Subscription/Captcha.php, tests/integration/Subscription/CaptchaTest.php
With this PR, subscription forms will always display CAPTCHA, if enabled.
The filter `mailpoet_subscription_captcha_recipient_limit` can be used to enable previous behavior if set to a value > 0.
To test:
1. Enable CAPTCHA
2. Create a signup form that is displayed on the site
3. View the site with a user that is not subscribed, that is not an admin or editor, and verify you see the CAPTCHA.
Integration test:
`./do --test "test:integration --file=tests/integration/Subscription/CaptchaTest.php"
`
[MAILPOET-3788]
[MAILPOET-3788]: https://mailpoet.atlassian.net/browse/MAILPOET-3788
=> Show CAPTCHA from first signup [MAILPOET-3788]

tests/integration/Statistics/Track/ClicksTest.php
The test was failing because it was missing to pass the `subscribersRepository` with the mocked `WPFunctions` to the `Opens` class.
So we were using the mocked function and the real function when getting `currentTime`.
If the test was fast enough, this would be invisible.
If the second call to currentTime was a second away, the test would fail because it would return the actual time instead of the mocked time.
If you wanted to test how it failed before the changes, add `sleep(2);` after `$now = Carbon::now();` in `testItUpdatesSubscriberEngagementForHumanAgent` and in `testItUpdatesSubscriberEngagementForUnknownAgent`.
To run the updated tests:
```
./do --test "test:integration --file=tests/integration/Statistics/Track/ClicksTest.php::testItUpdatesSubscriberEngagementForHumanAgent"
./do …
```
=> Fix subscribers clicks stats test [MAILPOET-3796]

assets/js/src/help/tasks_list/tasks_list_data_row.jsx, lib/Tasks/State.php, tests/integration/Tasks/StateTest.php
This PR changes the logic to display the updated_at field for tasks in the system status page to use the site timezone.
[MAILPOET-3692]
[MAILPOET-3692]: https://mailpoet.atlassian.net/browse/MAILPOET-3692
=> Display the updated_at field using the site timezone [MAILPOET-3692]

RoboFile.php
Instead of detecting the test environment, I tried to approach the problem from the other side. The idea is that a developer can mark an environment as "development site" and by doing so the environment will get protection against accidentally running DB cleanup within integration tests. Not everyone uses the MailPoet Dev Environment so I think that this way all developers could set it and use this protection.
There is a related [PR in MailPoet Dev Environment repository that adds the variable for the dev site container](https://github.com/mailpoet/mailpoet-dev-env/pull/43).
[MAILPOET-3755]
[MAILPOET-3755]: https://mailpoet.atlassian.net/browse/MAILPOET-3755
=> Add confirmation before running integration tests on the dev site [MAILPOET-3755]

lib/Mailer/Methods/ErrorMappers/SMTPMapper.php, tests/unit/Mailer/Methods/ErrorMappers/SMTPMapperTest.php
Modify SMTP error mapper so that it handles also  `\MailPoetVendor\Swift_TransportException`
Mark an error as soft  if the error code from SMTP is not 500-504.
I was not able to reproduce getting 500-504 messages but it is covered by the unit test.
A soft transport error can be reproduced by entering the SMTP details correctly on _MailPoet > Settings > Send With_ but having a sender address that is not owned by the SMTP account on _MailPoet > Settings > Basic_ , From field.
Note: I used [our own Titan email as outgoing SMTP server](https://support.titan.email/hc/en-us/articles/900000215446-Configure-Titan-on-other-apps-using-IMAP-POP).
[MAILPOET-3717]
[MAILPOET-3717]: https://mailpoet.atlassian.net/browse/MAILPOET-3717
=> Handle recipient related errors from SMTP mailer as soft errors [MAILPOET-3717]

RoboFile.php
This change is necessary to make sure we are running PHPCS with the same parameters in both CircleCI and the pre-commit hook. For more information see the description of the related Jira ticket.
[MAILPOET-3831]
[MAILPOET-3831]: https://mailpoet.atlassian.net/browse/MAILPOET-3831
=> Change `./do qa:code-sniffer` to include warnings by default [MAILPOET-3831]

RoboFile.php
This PR adds a call to the command 'codecept build' before running PHPStan checks inside the command './do qa:phpstan'. This is needed to make sure that the PHPStan checks don't fail with the error bellow because of missing test support files that are autogenerated by Codeception:
```
Bootstrap file tests/_support/_generated/AcceptanceTesterActions.php does not exist.
```
To test:
- On the master branch, remove the files inside tests/_support/_generated and see the error above when running `./do qa:phpstan`.
- Switch to this branch and run `./do qa:phpstan` again. Check that the deleted files were created again and that the PHPStan checks passed.
[MAILPOET-3552]
[MAILPOET-3552]: https://mailpoet.atlassian.net/browse/MAILPOET-3552
=> Run 'codecept build' before runninng PHPStan checks [MAILPOET-3552]

lib/Newsletter/Scheduler/AutomaticEmailScheduler.php, lib/Newsletter/Scheduler/Scheduler.php, lib/Newsletter/Scheduler/WelcomeScheduler.php, tests/integration/Newsletter/Scheduler/AutomaticEmailTest.php, tests/integration/Newsletter/Scheduler/WelcomeTest.php
If the tests took too long to execute, they would fail because `Scheduler::getScheduledTimeWithDelay` would have a different time than the time set in the test. 
The tests could be made to fail consistently by inserting `sleep(60)` in between the function execution and the time we were setting `currentTime` within the test.
To solve this, I have added `WPFunctions` to the constructor, as an optional argument, so that we can mock `currentTime` inside of the tests.
The issue was originally to fix: `tests/integration/Newsletter/Scheduler/AutomaticEmailTest.php::testItSchedulesAutomaticEmailWhenConditionMatches`
I have also modified `WelcomeScheduler` class and the tests in `tests/integration/Newsletter/Scheduler/WelcomeTest.php`
[MAILPOET-3793]
[MAILPOET-3793]: …
=> Fix flaky tests using  Scheduler::getScheduledTimeWithDelay [MAILPOET-3793]

lib/Mailer/Methods/MailPoet.php, tests/integration/Mailer/Methods/MailPoetAPITest.php
When transactional emails are enabled with MSS, some plugins might create headers that contain a reply-to address but do not have a reply-to name. 
We would then be sending an empty reply-to name and MSS would reply with a Bad request error:
`\"reply_to\":{\"name\":\"name must be a string or name must be boolean\"`
In this PR, we remove the reply-to name from the request to MSS if it is empty.
This is not easy to test from the UI, the plugin where the problem was found is a paid plugin.
I have verified the emails are sent without the reply-to name by manually modifying the code that generates the reply-to data, and sending the emails.
There is also an integration test.
[MAILPOET-3812]
[MAILPOET-3812]: https://mailpoet.atlassian.net/browse/MAILPOET-3812
=> Allow reply-to with only address when using MSS [MAILPOET-3812]

lib/Mailer/WordPress/PHPMailerLoader.php
[MAILPOET-3836]
I'm not sure how to reproduce the original problem, but this fix seems to be the most logical solution.
[MAILPOET-3836]: https://mailpoet.atlassian.net/browse/MAILPOET-3836
=> Fix "Class 'PHPMailer\PHPMailer\Exception' not found" error [MAILPOET-3836]

lib/Cron/CronWorkerInterface.php, lib/Cron/CronWorkerRunner.php, lib/Cron/Workers/Bounce.php, lib/Cron/Workers/SendingQueue/Migration.php, lib/Cron/Workers/SimpleWorker.php, lib/Cron/Workers/SubscribersCountCacheRecalculation.php, lib/Models/ScheduledTask.php, lib/Newsletter/Sending/ScheduledTasksRepository.php, lib/Tasks/Bounce.php, tests/DataFactories/ScheduledTask.php, tests/integration/Cron/Workers/BounceTest.php, tests/integration/Cron/Workers/SendingQueue/MigrationTest.php, tests/integration/Models/ScheduledTaskTest.php, tests/integration/Newsletter/Sending/ScheduledTasksRepositoryTest.php
This PR is a continuation of #3699. It should be reviewed only after #3699 is merged otherwise GitHub will display here all the commits from that PR as well. I decided to create this PR now in case #3699 is merged before I start my day tomorrow.
This PR changes the method prepareTaskStrategy() in SimpleWorker and all its child classes to use ScheduledTaskEntity instead of ScheduledTask. To do that, I also moved the method findCompletedByType() from ScheduledTask to ScheduledTaskEntity (as it is used in one of the modified child classes) and created a helper method for the tests to create ScheduledTaskEntity objects.
[MAILPOET-3842]
[MAILPOET-3842]: https://mailpoet.atlassian.net/browse/MAILPOET-3842
=> Change SimpleWorker::prepareTaskStrategy() to use Doctrine [MAILPOET-3842]

lib/Cron/CronWorkerInterface.php, lib/Cron/CronWorkerRunner.php, lib/Cron/Workers/AuthorizedSendingEmailsCheck.php, lib/Cron/Workers/Beamer.php, lib/Cron/Workers/Bounce.php, lib/Cron/Workers/ExportFilesCleanup.php, lib/Cron/Workers/InactiveSubscribers.php, lib/Cron/Workers/KeyCheck/KeyCheckWorker.php, lib/Cron/Workers/SendingQueue/Migration.php, lib/Cron/Workers/SimpleWorker.php, lib/Cron/Workers/StatsNotifications/AutomatedEmails.php, lib/Cron/Workers/SubscriberLinkTokens.php, lib/Cron/Workers/SubscribersCountCacheRecalculation.php, lib/Cron/Workers/SubscribersEngagementScore.php, lib/Cron/Workers/SubscribersLastEngagement.php, lib/Cron/Workers/UnsubscribeTokens.php, lib/Cron/Workers/WooCommercePastOrders.php, lib/Cron/Workers/WooCommerceSync.php, lib/Entities/ScheduledTaskEntity.php, tests/integration/Cron/Workers/AuthorizedSendingEmailsCheckTest.php, tests/integration/Cron/Workers/BounceTest.php, tests/integration/Cron/Workers/ExportFilesCleanupTest.php, tests/integration/Cron/Workers/InactiveSubscribersTest.php, tests/integration/Cron/Workers/KeyCheck/KeyCheckWorkerTest.php, tests/integration/Cron/Workers/SendingQueue/MigrationTest.php, tests/integration/Cron/Workers/SubscribersLastEngagementTest.php, tests/integration/Cron/Workers/UnsubscribeTokensTest.php, tests/integration/Cron/Workers/WooCommerceSyncTest.php
This PR is a continuation of #3705. It should be reviewed only after #3705 is merged and it will be necessary to rebase it to update the hashes of the commits from #3705.
This PR changes the method processTaskStrategy() in SimpleWorker and all its child classes to use ScheduledTaskEntity instead of ScheduledTask.
[MAILPOET-3843]
[MAILPOET-3843]: https://mailpoet.atlassian.net/browse/MAILPOET-3843
=> Change SimpleWorker::processTaskStrategy() to use Doctrine [MAILPOET-3843]

lib/Segments/SegmentsRepository.php
Method getSingleScalarResult throws an exception when a query returns no rows.
I used the method getOneOrNullResult instead.
[MAILPOET-3902]
[MAILPOET-3902]: https://mailpoet.atlassian.net/browse/MAILPOET-3902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix getting segment count with multiple filters for empty table [MAILPOET-3902]

prefixer/fix-doctrine.php
WordPress plugin repository prevents committing files that contain syntax introduced in PHP8.
[MAILPOET-3904]
[MAILPOET-3904]: https://mailpoet.atlassian.net/browse/MAILPOET-3904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Replace PHP8 version of TypedCacheItem class with PHP7 compatible code [MAILPOET-3904]

lib/Newsletter/Editor/PostTransformerContentsExtractor.php, tests/integration/Newsletter/RendererTest.php, tests/integration/Newsletter/RendererTestALCdata.json
With this PR I am removing the function sanitizeTitle that replaces quotes with Unicode quotes on the ALC post titles.
This function was added to fix an issue where the post content would not be rendered in the newsletter sent. The Unicode quotes add spaces to the title.
I have not been able to reproduce the original issue after removing the function from the title.
I have tested with the following titles (and other combinations):
`"This is a 'test"
`
`This "is 'a" test
` -> These are the quotes that were reported to cause issues.
`This "is 'a test
`
I have added a test case for a scenario where a newsletter contains an ALC (Automated Latest Content-Latest posts) block and the post has a title with the quotes, a featured image and content. The test verifies the post content is present in …
=> Fix Unicode quotes in ALC titles [MAILPOET-3660]

lib/Config/Updater.php, tests/integration/Config/UpdaterTest.php
[MAILPOET-3921]
[MAILPOET-3921]: https://mailpoet.atlassian.net/browse/MAILPOET-3921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix 'Enable auto-updates' link missing when Premium is up-to-date

assets/js/src/common/thumbnail.ts, assets/js/src/newsletter_editor/components/save.js, assets/js/src/newsletters/send.jsx, assets/js/src/newsletters/templates/template_box.jsx, lib/API/JSON/v1/NewsletterTemplates.php, lib/Config/Migrator.php, lib/Config/Populator.php, lib/Cron/Daemon.php, lib/Cron/Triggers/WordPress.php, lib/Cron/Workers/NewsletterTemplateThumbnails.php, lib/Cron/Workers/WorkersFactory.php, lib/DI/ContainerConfigurator.php, lib/Doctrine/Repository.php, lib/Entities/NewsletterTemplateEntity.php, lib/NewsletterTemplates/NewsletterTemplatesRepository.php, lib/NewsletterTemplates/ThumbnailSaver.php, lib/WP/Functions.php, tests/integration/Cron/DaemonHttpRunnerTest.php, tests/integration/Cron/DaemonTest.php, tests/integration/NewsletterTemplates/NewsletterTemplatesRepositoryTest.php, tests/integration/NewsletterTemplates/ThumbnailSaverTest.php
I added comments into commit messages and code. I recommend reviewing by commits. 
Before updating to this build import a couple of templates and send a couple of newsletters so that you have some template images to migrate after updating to the build.
With the new version, all newsletter templates images should be loaded from image files and the newsletter templates page should display faster.
I also altered how we take screenshots on retina screens so you can try saving a couple of newsletters as templates on a Mac (it is important that the browser window is opened on the retina screen) and check the quality of templates.
[MAILPOET-2686]
[MAILPOET-2686]: https://mailpoet.atlassian.net/browse/MAILPOET-2686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
=> Refactor saving newsletter template images [MAILPOET-2686]

assets/js/src/form_editor/blocks/map_custom_field_form_data.jsx, lib/Form/Block/Select.php, tests/unit/Form/Block/SelectTest.php
See  [MAILPOET-3894](https://mailpoet.atlassian.net/browse/MAILPOET-3894)  for more information
* Fixed managed subscription page showing multiple selected option
* Fixed default select form field uncheck not saving
* From wp-admin, visit the form editor and create a new **Select Custom Field**
* Add a field name and multiple options
* Set **one** of the options as the default by clicking on the checkbox by the side
* Visit the managed subscription page
* Notice the default selected option has been automatically selected.
* From the form editor page, select a new default option, save (Click on _Update custom field_)
* Reload the managed subscription page and notice the default selected option has been automatically updated.
* Select a new option and click on save
* Inspect the page HTML …
=> Fix/custom select default value on manage page - [MAILPOET-3894]

assets/js/src/analytics_event.js, assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/other_settings.tsx, assets/js/src/form_editor/store/controls.jsx, assets/js/src/form_editor/templates/store/actions.ts, assets/js/src/forms/heading.jsx, assets/js/src/newsletter_editor/components/save.js, assets/js/src/newsletters/automatic_emails/events_conditions.jsx, assets/js/src/newsletters/listings/heading.jsx, assets/js/src/newsletters/listings/utils.jsx, assets/js/src/newsletters/newsletters.jsx, assets/js/src/newsletters/send.jsx, assets/js/src/newsletters/send/ga_tracking.jsx, assets/js/src/newsletters/templates/import_template.jsx, assets/js/src/newsletters/templates/template_box.jsx, assets/js/src/newsletters/types.tsx, assets/js/src/newsletters/types/automatic_emails/events_list.jsx, assets/js/src/segments/dynamic/store/actions.ts, assets/js/src/segments/form.jsx, assets/js/src/settings/settings.tsx, assets/js/src/settings/store/actions/mss_and_premium.ts, assets/js/src/settings/store/controls.ts, assets/js/src/subscribers/form.jsx, assets/js/src/subscribers/importExport/export.ts, assets/js/src/subscribers/importExport/import/step_method_selection.jsx, views/forms.html, views/premium.html
To make it easier to test, you can enable the Mixpanel debug mode (https://developer.mixpanel.com/docs/javascript#debug-mode) by changing the code in the place where we initialize it: https://github.com/mailpoet/mailpoet/blob/master/assets/js/lib/analytics.js#L9
[MAILPOET-3885]
[MAILPOET-3885]: https://mailpoet.atlassian.net/browse/MAILPOET-3885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Track MailPoet free and premium versions in all events [MAILPOET-3885]

lib/Config/Populator.php, lib/Cron/Workers/SendingQueue/Tasks/Links.php, lib/Cron/Workers/StatsNotifications/Worker.php, lib/Doctrine/Repository.php, lib/Entities/NewsletterLinkEntity.php, lib/Models/NewsletterLink.php, lib/Newsletter/Links/Links.php, lib/Newsletter/Shortcodes/ShortcodesHelper.php, tests/DataGenerator/Generators/WooCommercePastRevenues.php, tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php, tests/integration/Cron/Workers/SendingQueue/Tasks/LinksTest.php, tests/integration/Cron/Workers/SendingQueue/Tasks/NewsletterTest.php, tests/integration/Cron/Workers/StatsNotifications/WorkerTest.php, tests/integration/Newsletter/Links/LinksTest.php, tests/integration/Router/Endpoints/TrackTest.php
This is a draft PR to get feedback on an issue before I dive deep into it. In this PR, I replaced the remaining places where NewsletterLink was still used with NewsletterLinkEntity and deprecated the old model class.
The problem is that the integration test `testItLogsErrorWhenNewlyRenderedNewsletterBodyIsInvalid` is failing due to a change in behavior (https://app.circleci.com/pipelines/github/mailpoet/mailpoet/7812/workflows/2eb5dc19-9746-4e5b-80eb-fa21f618a598/jobs/148114/tests#failed-test-0). This test, sets an invalid `newsletter_rendered_body` to make sure that the code in \MailPoet\Cron\Workers\SendingQueue\Tasks\Newsletter::preProcessNewsletter() works correctly to detect an invalid body and stop processing the newsletter …
=> Remove remaining usages of NewsletterLink and deprecate class [MAILPOET-3816]

lib/Subscribers/ImportExport/Import/Import.php, lib/Util/DateConverter.php, tests/integration/Subscribers/ImportExport/Import/ImportTest.php, tests/unit/Util/DateConverterTest.php
With this PR, when a site is using the `d/m/Y` format, we will parse `created_at` and `confirmed_at` using `datetime` and `d/m/Y` formats, then select the one with fewer errors.
When no errors parsing with both formats (or same amount of errors) we give preference to `datetime` format, for backwards compatibility.
We assume this will not be accurate in some cases, where dates could be parsed with both formats. For example 01/02/2021 could be first of February with d/m/Y or second of January with datetime. 
To test:
- Set the date on your site to d/m/Y format
- Create a subscribers import file using that format and dates that would be wrong using datetime. For example 31/12/2021
- Import the file, don't forget to select at least one field with dates to be imported as confirmation time …
=> Attempt to convert dates using d/m/Y on imports [MAILPOET-3747]

assets/css/src/components-public/_resets.scss, assets/css/src/mailpoet-public.scss, lib/DI/ContainerConfigurator.php, lib/Form/Util/CustomFonts.php, lib/Form/Widget.php, views/form/iframe.html
See  [MAILPOET-3871](https://mailpoet.atlassian.net/browse/MAILPOET-3871)  for more information
* Added default styles
* Added support for custom fonts
* Fixed iframe styling errors
**Before:**
**After:**
* Create a form using any of the available form templates
* Save the form and copy iframe code
* Place the iframe to some other site. (Note you might need to update with or height attributes)
* Observe the fonts and other styles 
[MAILPOET-3871](https://mailpoet.atlassian.net/browse/MAILPOET-3871)
=> Fixed CSS is not applied when using form iframe - [MAILPOET-3871]

lib/Doctrine/EventListeners/TimestampListener.php, tests/integration/Doctrine/EventListeners/TimestampListenerTest.php
Besides changing TimestampListener to create copies of the Carbon object before passing them to the entities, in a separate, commit I also removed a few unused imports that existed in this class.
[MAILPOET-3870]
[MAILPOET-3870]: https://mailpoet.atlassian.net/browse/MAILPOET-3870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TimestampListener should not use the same time object for different entities [MAILPOET-3870]

lib/DI/ContainerConfigurator.php, lib/Doctrine/EventListeners/LastSubscribedAtListener.php, tests/integration/Doctrine/EventListeners/EventListenersBaseTest.php, tests/integration/Doctrine/EventListeners/LastSubscribedAtTest.php, tests/integration/Doctrine/EventListeners/TimestampListenerTest.php
This PR is similar to #3793 in that it applies the same change but to LastSubscribedAtListener instead of TimestampListener. On a separate commit, I created some basic integration tests for LastSubscribedAtListener as there were none.
[MAILPOET-3946]
[MAILPOET-3946]: https://mailpoet.atlassian.net/browse/MAILPOET-3946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LastSubscribedAtListener should not use the same time object for different entities [MAILPOET-3946]

lib/Segments/DynamicSegments/Filters/WooCommerceSubscription.php
There was an issue in the old query used to get subscribers of the "has WooCommerce subscription" segment. When getting the IDs of the users that purchased a given subscription, it would get all the entries from wp_woocommerce_order_items without checking the value of ordem_item_type.
The problem is that wp_woocommerce_order_items contains entries for the purchased product, but also other things like shipping and tax information. The WooCommerce Subscriptions extension uses wp_woocommerce_order_items to store data when a user switches from one subscription to another. This was causing users to be included in the "has WooCommerce subscription" segment even after they had switched from the subscription that belonged to the segment to another one.
This problem was fixed by adding another …
=> Fix query to get subscribers of the "has WC subscription" segment [MAILPOET-3898]

tests/integration/Subscribers/InactiveSubscribersControllerTest.php
This refactor was already done on this PR: https://github.com/mailpoet/mailpoet/pull/3695
It was only missing a few constants on the test.
To test:
Run `./do --test "test:integration --file=tests/integration/Subscribers/InactiveSubscribersControllerTest.php"`
[MAILPOET-3820]
[MAILPOET-3820]: https://mailpoet.atlassian.net/browse/MAILPOET-3820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Refactor \MailPoet\Subscribers\InactiveSubscribersController to Doctrine 

lib/Newsletter/Shortcodes/Categories/Link.php, lib/Subscription/SubscriptionUrlFactory.php, tests/integration/Newsletter/ShortcodesTest.php, tests/integration/Subscription/SubscriptionUrlFactoryTest.php
There is an acceptance test failing but it doesn't seem to be related to this change.
[MAILPOET-3976]
[MAILPOET-3976]: https://mailpoet.atlassian.net/browse/MAILPOET-3976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add code to process the new link:subscription_re_engage_url shortcode [MAILPOET-3976]

.circleci/config.yml
I added a step in which CI only pulls docker images for acceptance tests and added 3 retries for this step.
I also updated the machine image to the latest available Ubuntu 20.04
[MAILPOET-3991]
[MAILPOET-3991]: https://mailpoet.atlassian.net/browse/MAILPOET-3991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add retry for pulling docker images on CI [MAILPOET-3991]

lib/PostEditorBlocks/WooCommerceBlocksIntegration.php
When opt-in is disabled it fails to validate checkout data, because it expects
`mailpoet.optin` to be present. In this PR I added a condition so that it skips extending checkout data schema in case
the opt-in is disabled.
[MAILPOET-4004]
[MAILPOET-4004]: https://mailpoet.atlassian.net/browse/MAILPOET-4004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix WooCommerce block's checkout error when opt-in is disabled [MAILPOET-4004]

tests/integration/Doctrine/EventListeners/TimestampListenerTest.php
The problem was that the listener was replaced in the EntityManager only
in the first test case. For other test cases, replaceListeners didn't replace
anything because the original listener was not set.
[MAILPOET-3983]
[MAILPOET-3983]: https://mailpoet.atlassian.net/browse/MAILPOET-3983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix flaky TimestampListenerTest [MAILPOET-3983]

lib/Segments/DynamicSegments/FilterFactory.php
There was a bug that was making the code use the wrong filter and thus the wrong SQL query for the "# number of machine opens" segment. Resulting in the wrong subscribers being associated with this segment.
The email() method of the FilterFactory was using the wrong check to decide which filter to use for this segment (the filter should be EmailOpensAbsoluteCountAction and the factory was using EmailAction).
[MAILPOET-4011]
[MAILPOET-4011]: https://mailpoet.atlassian.net/browse/MAILPOET-4011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix "# number of machine opens" segment [MAILPOET-4011]

lib/API/JSON/v1/Subscribers.php, lib/API/MP/v1/API.php, lib/Mailer/Mailer.php, lib/Mailer/MetaInfo.php, lib/Segments/WP.php, lib/Subscribers/ConfirmationEmailMailer.php, lib/Subscribers/SubscriberActions.php, lib/WooCommerce/Subscription.php, tests/DataFactories/Subscriber.php, tests/integration/API/MP/APITest.php, tests/integration/Mailer/MailerTest.php, tests/integration/Mailer/MetaInfoTest.php, tests/integration/Segments/WPTest.php, tests/integration/Subscribers/ConfirmationEmailMailerTest.php
@brezocordero, I'm assigning this PR to you as you mentioned that you were working on another task to refactor API::subscribeToLists() to Doctrine. I believe I might need to make some adjustments to the changes that I made to this method depending on what you did.
The code changed here is used in a few places to send a confirmation email to a subscriber (not an exhaustive list):
- When an admin clicks on the link to resend the confirmation email on the page that lists all subscribers of a given list.
- When a WC customer purchase a new product and select the checkbox to subscribe to the WC list.
- When a new WP user is created.
When removing Subscriber::setError() as we discussed in the Slack channel, I opted to replace it with a call to `throw`. There are some disadvantages to this …
=> Refactor ConfirmationEmailMailer to Doctrine

lib/API/JSON/ResponseBuilders/SubscribersResponseBuilder.php, lib/API/MP/v1/API.php, lib/API/MP/v1/Subscribers.php, lib/DI/ContainerConfigurator.php, tests/integration/API/MP/APITest.php, tests/integration/API/MP/SubscribersTest.php
This PR refactors 
- \MailPoet\API\MP\v1\API::subscribeToList 
- \MailPoet\API\MP\v1\API::subscribeToLists 
The methods are now in a new class `lib/API/MP/v1/Subscribers.php`
Tests have been moved and refactored from `tests/integration/API/MP/APITest.php` to `tests/integration/API/MP/SubscribersTest.php`
I have reused the class `lib/API/JSON/ResponseBuilders/SubscribersResponseBuilder.php` to build the response replacing 
`->withCustomFields()->withSubscriptions()->asArray();`
I have added a parameter to the function 'build' to add more data on subscriptions if we are calling it from MPAPI. 
This information is redundant but I wanted to avoid modifying current MPAPI response, [as documented here](https://github.com/mailpoet/mailpoet/blob/master/doc/api_methods/GetSubscriber.md).
There are …
=> Refactor MPAPI subscribeToLists to Doctrine [MAILPOET-3813]

lib/Form/Block/BlockRendererHelper.php, lib/Form/Block/Checkbox.php, lib/Form/Block/Date.php, lib/Form/Block/Radio.php, lib/Form/Block/Segment.php, lib/Form/BlocksRenderer.php, lib/Form/Renderer.php, lib/Subscription/CaptchaRenderer.php, lib/Subscription/ManageSubscriptionFormRenderer.php, tests/unit/Form/Block/BlockRendererHelperTest.php, tests/unit/Form/Block/CheckboxTest.php, tests/unit/Form/Block/DateTest.php, tests/unit/Form/Block/RadioTest.php, tests/unit/Form/Block/SegmentTest.php, tests/unit/Form/RendererTest.php
[MAILPOET-3875]
[MAILPOET-3875]: https://mailpoet.atlassian.net/browse/MAILPOET-3875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Testing Instructions:
1. Go to WP Admin > MailPoet > Forms
2. Click to Add New Form
3. Click `Skip, start with a blank form` button
4. Click Plus (black) button and search for `List Selection` block to insert it
5. On the right sidebar, insert a few available lists under `Select the segment that you want to add` dropdown
6. Click to `Form`, then `Form Placements` tab
7. Then click Popup and then click Enable switcher
8. Click the switcher for `Display on all pages`
9. Change the `Display with a delay of` time from 15sec to 0sec
10. Click Save to save the form
11. Now, go back to Forms page
12. Click to duplicate …
=> Make form error containers unique by form id [MAILPOET-3875]

assets/js/src/segments/dynamic/dynamic_segments_filters/subscriber.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/subscriber_wordpress_role.tsx, assets/js/src/segments/dynamic/types.ts, lib/API/JSON/ResponseBuilders/DynamicSegmentsResponseBuilder.php, lib/Segments/DynamicSegments/FilterDataMapper.php, lib/Segments/DynamicSegments/Filters/UserRole.php, tests/acceptance/Segments/ManageSegmentsCest.php, tests/integration/API/JSON/ResponseBuilders/DynamicSegmentsResponseBuilderTest.php, tests/integration/Segments/DynamicSegments/Filters/UserRoleTest.php, tests/integration/Segments/DynamicSegments/SegmentSaveControllerTest.php, tests/unit/Segments/DynamicSegments/FilterDataMapperTest.php, views/segments.html
[MAILPOET-3955]
[MAILPOET-3955]: https://mailpoet.atlassian.net/browse/MAILPOET-3955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Go to WP Admin > MailPoet > Lists
2. Click on Segments tab
3. Click to `+ New Segment` button at the top
4. From there, test the segment creation and modification according to [MAILPOET-3955](https://mailpoet.atlassian.net/browse/MAILPOET-3955) specs in Jira ticket.
5. Make sure you follow the specs and that it behaves according to the specification.
=> Allow multiple values in "WordPress user role" segment [MAILPOET-3955]

assets/js/src/newsletter_editor/initializer.jsx, assets/js/src/newsletters/automatic_emails/listings.jsx, assets/js/src/newsletters/listings/notification.jsx, assets/js/src/newsletters/listings/re_engagement.jsx, assets/js/src/newsletters/listings/utils.jsx, assets/js/src/newsletters/listings/welcome.jsx, views/newsletter/editor.html, views/newsletters.html
[MAILPOET-3960](https://mailpoet.atlassian.net/browse/MAILPOET-3960)
1. Go to WP Admin > MailPoet > Emails
2. Click to Add New Newsletter
3. Select First Purchase for example
4. Proceed further and activate it at the end (feel free to chose any data, options etc)
5. Once activated, from that point, hover over it and click Edit link
6. Check the specification in Jira ticket above (MAILPOET-3960) and verify you see proper dialog with text etc)
=> Feat/deactivate automatic emails on edit - MAILPOET-3960

assets/js/src/segments/dynamic/subscribers_counter.tsx, views/segments.html
[MAILPOET-3493](https://mailpoet.atlassian.net/browse/MAILPOET-3493)
1. Go to WP Admin > MailPoet > Lists
2. Click on Add New Segment button
3. Try to add as much as possible segment variations with AND and AND and AND... until you see message at the bottom saying "Calculating segment size..." taking for more than 15 seconds. Then you'll see this warning that it taking too long to display... If you don't see it but you see calculating segment size.. try adding more segment variations and you'll see it.
4. Verify that the link Learn more is present and it leads to opening a Beacon article on the bottom-right corner. Verify the proper article is shown.
=> Add the “Learn more” link when calculating size times out. - MAILPOET-3493

assets/js/src/form_editor/store/map_form_data_after_loading.jsx, tests/javascript/form_editor/store/map_form_data_after_loading.spec.js
[MAILPOET-3263] (testing instructions are inside the ticket)
This fixes a bug where the animation setting ("Show animation on display") was not being displayed properly for previously-saved slide-in forms immediately after loading the form in the editor.
The value was coming through as either 'right' or 'left' because the `position` value was being referenced instead of `animation`.
Because 'right' and 'left' don't correspond to a slide-in animation value, it always looked like the "Show animation on display" setting was "No Animation" even if a different value was saved in the database.
This bug only affected the editor and only affected the display of the value, not the ability to save a setting (the `animation` property was always correctly referenced in …
=> Fix slide-in animation value displayed in editor on form load [MAILPOET-3263]

assets/js/src/segments/dynamic/dynamic_segments_filters/email.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/email_statistics.tsx, assets/js/src/segments/dynamic/privacy_protection_notice.tsx, assets/js/src/segments/dynamic/types.ts, lib/API/JSON/ResponseBuilders/DynamicSegmentsResponseBuilder.php, lib/Analytics/Reporter.php, lib/DI/ContainerConfigurator.php, lib/Segments/DynamicSegments/FilterDataMapper.php, lib/Segments/DynamicSegments/FilterFactory.php, lib/Segments/DynamicSegments/Filters/EmailAction.php, lib/Segments/DynamicSegments/Filters/EmailActionClickAny.php, tests/integration/Segments/DynamicSegments/Filters/EmailActionClickAnyTest.php, tests/integration/Segments/DynamicSegments/Filters/EmailActionTest.php, tests/unit/Segments/DynamicSegments/FilterDataMapperTest.php, views/segments.html
There is a lot of code shared with the "clicked" segment. But that is in a different [ticket](https://mailpoet.atlassian.net/browse/MAILPOET-3951). So I left some code in which will be deleted/refactored in an upcoming ticket.
[MAILPOET-3950]
[MAILPOET-3950]: https://mailpoet.atlassian.net/browse/MAILPOET-3950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Go to WP Admin > MailPoet > Lists
2. Click to Add New Segment
3. Select `opened` segment type
4. Compare results from your testing with the specification from Jira ticket above (MAILPOET-3950)
5. Verify you see all the new improvements and that creating such segmentation works
=> Allow multiple values in "opened" segment [MAILPOET-3950]

assets/js/src/segments/dynamic/dynamic_segments_filters/woocommerce.tsx
The QA JS job is failing on master because we have an unused import in the WooCommerce component.
=> Remove unused import from WooCommerce component

lib/API/JSON/v1/DynamicSegments.php, lib/API/JSON/v1/Segments.php, lib/Segments/DynamicSegments/SegmentSaveController.php, lib/Segments/SegmentSaveController.php, lib/Segments/SegmentsRepository.php, tests/integration/Segments/DynamicSegments/SegmentSaveControllerTest.php, tests/integration/Segments/SegmentSaveControllerTest.php, tests/integration/Segments/SegmentsRepositoryTest.php
This PR adds a check directly in [SegmentRepository](https://github.com/mailpoet/mailpoet/blob/90d479fdc7e25c42da3e15264c48f1f488ac8e2b/lib/Segments/SegmentsRepository.php) to verify that a given segment name is unique before attempting to persist a new segment to the database. It's important to have this check because the `mailpoet_segments` table has a [unique key constraint](https://github.com/mailpoet/mailpoet/blob/158d70dc7a43d5185c84db4493a66fa53cccd087/lib/Config/Migrator.php#L107) on the `name` column.
We were previously checking for uniqueness through the save controllers ([regular](https://github.com/mailpoet/mailpoet/blob/90d479fdc7e25c42da3e15264c48f1f488ac8e2b/lib/Segments/SegmentSaveController.php#L30) and [dynamic](https://github.com/mailpoet/mailpoet/blob/90d479fdc7e25c42da …
=> Add check for unique name when creating segment [MAILPOET-3998]

lib/Segments/DynamicSegments/Filters/WooCommerceProduct.php
The non-unique count parameter name was causing that when more conditions
used "all of" operands the count parameter was overrode in the final combined query.
[MAILPOET-4010]
[MAILPOET-4010]: https://mailpoet.atlassian.net/browse/MAILPOET-4010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Go to MailPoet > Lists
2. Click to add New Segment
3. Select `purchased product` as the segment type
4. Select All of from the second dropdown
5. and Select `1 month subscription` product from the third dropdown
6. You should see 1 subscriber as the result of the calculation
7. Click to add new additional segment by clicking `Add a condition` link
8. Select again `purchased product` type and then `All of` and then select a few …
=> Fix segment with multiple purchased product conditions with all of [MAILPOET-4010]

assets/js/src/segments/dynamic/dynamic_segments_filters/woocommerce.tsx, lib/Segments/DynamicSegments/Filters/WooCommerceNumberOfOrders.php, lib/Segments/DynamicSegments/Filters/WooCommerceTotalSpent.php, tests/acceptance/Segments/ManageSegmentsCest.php, tests/integration/Segments/DynamicSegments/Filters/WooCommerceNumberOfOrdersTest.php, tests/integration/Segments/DynamicSegments/Filters/WooCommerceTotalSpentTest.php, views/segments.html
[MAILPOET-4007]
[MAILPOET-4007]: https://mailpoet.atlassian.net/browse/MAILPOET-4007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Go to MailPoet > Lists > Segments tab
2. Click to add New Segment
3. Select `# of orders` segment type
4. Make sure you see a new option and renamed existing option (check Jira specification on what has been changed)
4. Then select `total spent` segment type
5. Make sure you see new options there (check Jira specification to see what new options were added)
6. Make sure they are calculating properly. If you want to add new data, you will need to buy some items in order to see new data. Also consider creating a new customer user and then purchasing some items, that's another way to add new …
=> Add more comparison options for WooCommerce segments [MAILPOET-4007]

assets/js/src/segments/dynamic/dynamic_segments_filters/woocommerce_subscription.tsx, assets/js/src/segments/dynamic/types.ts, lib/Config/Migrator.php, lib/Segments/DynamicSegments/FilterDataMapper.php, lib/Segments/DynamicSegments/Filters/WooCommerceSubscription.php, tests/acceptance/Segments/WooCommerceSubscriptionsSegmentCest.php, tests/unit/Segments/DynamicSegments/FilterDataMapperTest.php, views/segments.html
[MAILPOET-3956]
[MAILPOET-3956]: https://mailpoet.atlassian.net/browse/MAILPOET-3956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Go to MailPoet > Lists
2. Click to add a New Segment
3. Select `has an active subscription segment` from the first dropdown
4. Follow the specs from the Jira ticket above and make sure everything is made according to Specification
5. After everything's tested and verified, try to disable `WooCommerce Subscription` plugin in My Plugins section and then to go back to MailPoet > Lists > Segments Tab... to check if you see this message "Activate the WooCommerce Subscriptions plugin to see the number of subscribers and enable the editing of this segment.". Because this message should be present …
=> Add/multiple woo subscription segment [MAILPOET-3956]

assets/js/src/subscribers/importExport/import/step_data_manipulation/generate_column_selection.jsx, lib/Subscribers/ImportExport/ImportExportFactory.php, tests/integration/Subscribers/ImportExport/ImportExportFactoryTest.php
[MAILPOET-3958](https://mailpoet.atlassian.net/browse/MAILPOET-3958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
Check the testing instructions inside Jira ticket.
This fixes a bug where the search at the top of columns on the subscriber import page weren't doing anything.
It also includes a fix for a [bug with the latest version of select2 and jQuery](https://github.com/select2/select2/issues/5993) where the search inputs weren't receiving focus when clicked.
Before:
https://user-images.githubusercontent.com/8656640/146259444-9aac664b-b094-4932-bdf8-3103963b6e16.mov
After:
https://user-images.githubusercontent.com/8656640/146259461-4e200002-74be-429c-b936-8630235a0436.mov
I believe this issue may have originally been caused by removing the …
=> Fix import subscribers column header search [MAILPOET-3958]

doc/Readme.md, doc/api_methods/IsSetupComplete.md, lib/API/MP/v1/API.php, lib/Config/Changelog.php, tests/integration/API/MP/APITest.php, tests/integration/API/MP/SubscribersTest.php
[MAILPOET-4042]
@costasovo I didn't add the new endpoint to public API docs because I don't think this is something other plugins should use. But I don't have a strong opinion on this, so if you think we should document it, I can do that.
For QA - this PR also includes a slight refactor for showing the welcome wizard, WooCommerce setup (when someone installs WC after MP is already set up), and MP2 migration step, so please make sure all are still working as they should.
[MAILPOET-4042]: https://mailpoet.atlassian.net/browse/MAILPOET-4042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Create API endpoint to check if MailPoet welcome wizard is finished [MAILPOET-4042]

tests/acceptance/Subscribers/SubscriberCookieCest.php
The test is failing because of an error in the UI:
Usernames can only contain lowercase letters (a-z) and numbers.
=> Fix a test that is broken on multisite

tests/acceptance/Segments/WooCommerceDynamicSegmentsCest.php
We were trying to run "regenerate_product_lookup_tables" in the acceptance tests
but the tables we actually use are for customers and orders and those are not
regenerated by the used command. The current fix forces action scheduler to run
which synces any queued order and customer data.
[MAILPOET-4059]
[MAILPOET-4059]: https://mailpoet.atlassian.net/browse/MAILPOET-4059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix lookup table regeneration in tests [MAILPOET-4059]

assets/js/src/segments/dynamic/dynamic_segments_filters/email_opens_absolute_count.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/subscriber.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/subscriber_subscribed_date.tsx, lib/Segments/DynamicSegments/Filters/EmailOpensAbsoluteCountAction.php, lib/Segments/DynamicSegments/Filters/SubscriberSubscribedDate.php, tests/integration/Segments/DynamicSegments/Filters/EmailOpensAbsoluteCountActionTest.php, tests/integration/Segments/DynamicSegments/Filters/SubscriberSubscribedDateTest.php, views/segments.html
Noting that it won't be possible to test the changes to the "# of machine-opens" segment until #3853 is merged. #3853 fixes a bug in this segment that is preventing it from working properly.
[MAILPOET-3614]
[MAILPOET-3614]: https://mailpoet.atlassian.net/browse/MAILPOET-3614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Go to MailPoet > Lists
2. Click to add New Segment
3. Select appropriate segment from the Jira Specification in order to test the new options
4. Make sure calculation is working along with date selector
=> Add more comparison options to three different segments [MAILPOET-3614]

lib/PostEditorBlocks/WooCommerceBlocksIntegration.php, lib/WooCommerce/Subscription.php
[MAILPOET-4026]
[MAILPOET-4026]: https://mailpoet.atlassian.net/browse/MAILPOET-4026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Go to MailPoet > Settings > WooCommerce tab
2. Make sure to select at least 2 lists from the select lists dropdown
3. Remember what lists you selected
4. Go to the shop (front-end) and purchase some product/s (but make sure to also check the checkbox in the checkout for opting-in for these lists)
5. Confirm subscription when received email (with the email entered during checkout)
6. Go to MailPoet > Subscribers
7. Make sure the new subscriber is subscribed to all necessary lists
8. Perform again checkout using the same email address and this time unchecking the checkbox during checkout
9. …
=> Opt out on WC checkout from configured segments [MAILPOET-4026]

assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/fixed_bar_settings.tsx, assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/popup_settings.tsx, assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/slide_in_settings.tsx
[MAILPOET-3575]
I believe this is a pretty straightforward change unless I've missed some tests that should be updated.
When configuring fixed bar, popup, or slide in form placement settings, the options `2` `5` `10` and `45` should now be available for the `Display with a delay of` setting.
[MAILPOET-3575]: https://mailpoet.atlassian.net/browse/MAILPOET-3575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Testing Instructions:
1. Go to MailPoet > Forms
2. Edit existing or add a new form
3. In the form editor, collapse Form Placement tab from the right sidebar
4. Click on any form placement like Pop-up, make sure it is enabled/activated properly
5. Check if you see the new delay options 2s, 5s, 10s and 45s as available options under "Display …
=> Add more form delay options [MAILPOET-3575]

tasks/phpstan/fix-WPStubs-for-PHP-8_1.php, tasks/phpstan/phpstan-7-baseline.neon, tasks/phpstan/phpstan-8-baseline.neon, tasks/phpstan/phpstan-8.1-baseline.neon
We updated PHPStan to use a new Error level (Level 9).
Fixing current static analysis errors on master
=> Updated baseline files [MAILPOET-3932]

lib/Cron/Workers/WooCommerceSync.php, lib/Segments/WooCommerce.php, tests/integration/Cron/Workers/WooCommerceSyncTest.php
[MAILPOET-4065]
[MAILPOET-4065]: https://mailpoet.atlassian.net/browse/MAILPOET-4065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove exact comparison with last order id in WooCommerce sync [MAILPOET-4065]

.circleci/config.yml, RoboFile.php, tasks/WPOrgPluginDownloader.php
We updated the command (`./do download:woo-commerce-zip`) to download the WooCommerce plugin from the WordPress.org directory instead of pulling it from Github.
We updated the WooCommerce plugin version used for acceptance tests on CircleCI from **5.2.2** to **6.0.0**
Testing
* Run the command: `./do download:woo-commerce-zip 4.0.0` (this would download WooCommerce version 4.0.0)
* Check the content of _tests/plugins/woocommerce.zip-info_. it should contain ***/woocommerce.4.0.0.zip
* You may choose to reconfirm this by unzipping _tests/plugins/woocommerce.zip_ and checking the plugin version
[MAILPOET-4046](https://mailpoet.atlassian.net/browse/MAILPOET-4046)
=> Use WP plugins repo for downloading WooCommerce plugin - [MAILPOET-4046]

mailpoet/tests/integration/Mailer/MailerTest.php, mailpoet/tests/integration/Mailer/Methods/AmazonSESTest.php, mailpoet/tests/integration/Mailer/Methods/MailPoetAPITest.php, mailpoet/tests/integration/Mailer/Methods/PHPMailTest.php, mailpoet/tests/integration/Mailer/Methods/SMTPTest.php, mailpoet/tests/integration/Mailer/Methods/SendGridTest.php
Previously this test was using random email addresses in the form of
`bin2hex(random_bytes(7)) . '@example.com'`, the default address
generated by `\MailPoet\Test\DataFactories\Subscriber`. This was causing
the staff@mailpoet.com account to get banned by the MSS due to
`bad-domain-discard`s. Using the mailinator email address instead, like
the other sending tests, should prevent this from occurring.
[MAILPOET-4064]
[MAILPOET-4064]: https://mailpoet.atlassian.net/browse/MAILPOET-4064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prevent tests from emailing [randomhex]@example.com [MAILPOET-4064]

mailpoet/assets/js/src/common/listings/newsletter_status.tsx, mailpoet/views/layout.html, mailpoet/views/newsletters.html
[MAILPOET-3560]
On the Emails listing page, if the newsletter is scheduled to send
either today or tomorrow, the status column will now display "Today" or
"Tomorrow" respectively.
A user may still see the full date if desired by hovering their mouse
over the text, which will show the full date as a tooltip.
Testing Instructions:
1. Go to MailPoet > Emails
2. Create a new newsletter and schedule it for sending tomorrow (anytime tomorrow)
3. Create another new newsletter and schedule it for sending today (anytime but today)
4. Make sure you're on MailPoet > Emails page
5. Observe that you see Tomorrow and Today labels for those 2 scheduled newsletters
6. Hover over them and make sure you see dates as in the below video example
https://user-images.githubusercontent.com/8656640/147689762-20026 …
=> Use "today" or "tomorrow" status when applicable [MAILPOET-3560]

mailpoet/assets/js/src/form_editor/store/actions.ts, mailpoet/assets/js/src/form_editor/store/store.jsx
[MAILPOET-3877]
⏫ Testing Instructions are inside this Jira ticket, please open it and test it.
[MAILPOET-3877]: https://mailpoet.atlassian.net/browse/MAILPOET-3877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
This PR prevents newly-created forms from inheriting preview settings of the last unsaved form that was previewed. 
The bug was occurring because we use local storage to remember the preview settings for previously-previewed forms, and those settings are saved using a key based on the ID of the form. In the case of new, unsaved forms, these settings were always being saved and loaded with the key `mailpoet_form_preview_settingsnull`. 
That meant that whatever preview settings were stored for the last unsaved form a user was working on …
=> Prevent unintended re-use of preview settings [MAILPOET-3877]

mailpoet/lib/Segments/DynamicSegments/Filters/WooCommerceCategory.php, mailpoet/lib/Segments/DynamicSegments/Filters/WooCommerceProduct.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/WooCommerceCategoryTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/WooCommerceProductTest.php
With this PR, when 'none' is selected, subscribers that never placed an order are also included on segments Purchased Products or Purchased in Category.
To test:
1. Go to MailPoet > Lists > Segment tab
2. Create a new segment
3. Select "purchased product", "none of" and a product (select one from your wish)
4. Save the segment
5. Create another segment
6. Select "purchased in category", "none of" and a category (any but remember which one you selected)
7. Save the segment
8. Now you have 2 segments that counts all subscribers who didn't purchase specific product or in specific category
9. Go and purchase some product (the one you selected) and make sure the subscriber is not counted in the segment list
10. Go and purchase some product (the one in category you selected) and make sure the …
=> Count non-customers in "none of" option of purchased product/in category segments [MAILPOET-4021]

mailpoet/assets/js/src/settings/pages/key_activation/key_activation.tsx, mailpoet/lib/AdminPages/Pages/Help.php, mailpoet/lib/Helpscout/Beacon.php, mailpoet/tests/_support/AcceptanceTester.php, mailpoet/tests/acceptance/Settings/AddSendingKeyCest.php, mailpoet/tests/integration/Helpscout/BeaconTest.php
This PR reverts the commits from #3804 and implements logic to mask half of the API key when it is displayed on the System Info page. There is also a bonus commit replacing the old Subscriber model used in an updated integration tests file with the Doctrine equivalent.
[MAILPOET-4009]
[MAILPOET-4009]: https://mailpoet.atlassian.net/browse/MAILPOET-4009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Go to MailPoet > Settings
2. Click on Key Activation tab
3. Verify the key is visible in full (without ***)
4. Then, go to MailPoet > Help
5. Click on System Info tab
6. Verify you see your key in half visible and half *** such as: `MailPoet Premium/MSS key: 12345678910111213****************`
=> Mask the API key when displayed in the info page

.circleci/config.yml, mailpoet/RoboFile.php
This PR includes a PHP lint job for `vendor` and `vendor-prefixed` folders that are included in the final build.
From the links below, WordPress.org plugin directory pre-commit hook lints on PHP7.4
Sources:
https://meta.trac.wordpress.org/ticket/3791#comment:36
https://wordpress.slack.com/archives/C02QB8GMM/p1619603847340700
The added job uses MailPoet WordPress 7.4 image. 
The lint function includes the files/folders that are present on the final build.
I have used [build.sh](https://github.com/mailpoet/mailpoet/blob/master/build.sh) as reference to exclude files/folders from the vendor-prefixed linted files.
[MAILPOET-3905]
[MAILPOET-3905]: https://mailpoet.atlassian.net/browse/MAILPOET-3905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add a check of production vendor packages for PHP 7 compatibility

mailpoet/lib/Config/Migrator.php
After the emergency release, we need to update the version check in migration.
[MAILPOET-3951]
[MAILPOET-3951]: https://mailpoet.atlassian.net/browse/MAILPOET-3951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update migration check for email action segments data migration [MAILPOET-3951]

mailpoet/lib/API/JSON/ResponseBuilders/CustomFieldsResponseBuilder.php, mailpoet/lib/API/JSON/ResponseBuilders/FormsResponseBuilder.php, mailpoet/lib/API/JSON/ResponseBuilders/NewsletterTemplatesResponseBuilder.php, mailpoet/lib/API/JSON/ResponseBuilders/NewslettersResponseBuilder.php, mailpoet/lib/API/JSON/ResponseBuilders/SegmentsResponseBuilder.php, mailpoet/lib/API/JSON/ResponseBuilders/SubscribersResponseBuilder.php, mailpoet/lib/AdminPages/Pages/Logs.php, mailpoet/lib/AdminPages/Pages/NewsletterEditor.php, mailpoet/lib/Cron/Workers/WooCommercePastOrders.php, mailpoet/lib/Doctrine/EntityTraits/CreatedAtTrait.php, mailpoet/tests/integration/Doctrine/EventListeners/TimestampListenerTest.php, mailpoet/tests/integration/Logging/LogHandlerTest.php, mailpoet/tests/integration/Subscribers/SubscriberActionsTest.php
Because we use the trait for `createdAt` in all Doctrine entities, and some have this column nullable. I wanted to prevent a similar issue in the future, so I changed the return type in the trait to `DateTimeInterface|null`. PHPStan will help to catch this error now.
[MAILPOET-4067]
[MAILPOET-4067]: https://mailpoet.atlassian.net/browse/MAILPOET-4067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add check that createdAt is not null [MAILPOET-4067]

mailpoet/assets/js/src/listing/filters.jsx, mailpoet/assets/js/src/segments/dynamic/dynamic_segments_filters/email_statistics_clicks.tsx
This PR adds a couple of automation_ids used in an acceptance test in the premium plugin. See [related PR](https://github.com/mailpoet/mailpoet-premium/pull/533).
[PREMIUM-173]
[PREMIUM-173]: https://mailpoet.atlassian.net/browse/PREMIUM-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix stats create segment [PREMIUM-173]

mailpoet/RoboFile.php, mailpoet/assets/js/src/segments/dynamic/dynamic_segments_filters/woocommerce_membership.tsx, mailpoet/assets/js/src/segments/dynamic/form_filter_fields.tsx, mailpoet/assets/js/src/segments/dynamic/store/all_available_filters.ts, mailpoet/assets/js/src/segments/dynamic/store/selectors.ts, mailpoet/assets/js/src/segments/dynamic/store/store.ts, mailpoet/assets/js/src/segments/dynamic/types.ts, mailpoet/assets/js/src/segments/dynamic/validator.ts, mailpoet/lib/AdminPages/Pages/Segments.php, mailpoet/lib/Analytics/Reporter.php, mailpoet/lib/DI/ContainerConfigurator.php, mailpoet/lib/Entities/DynamicSegmentFilterData.php, mailpoet/lib/Entities/SegmentEntity.php, mailpoet/lib/Models/Segment.php, mailpoet/lib/Segments/DynamicSegments/Exceptions/InvalidFilterException.php, mailpoet/lib/Segments/DynamicSegments/FilterDataMapper.php, mailpoet/lib/Segments/DynamicSegments/FilterFactory.php, mailpoet/lib/Segments/DynamicSegments/Filters/WooCommerceMembership.php, mailpoet/lib/Segments/SegmentDependencyValidator.php, mailpoet/lib/WP/AutocompletePostListLoader.php, mailpoet/tests/DataFactories/WooCommerceMembership.php, mailpoet/tests/_support/AcceptanceTester.php, mailpoet/tests/_support/PluginsExtension.php, mailpoet/tests/acceptance/Segments/WooCommerceMembershipsSegmentCest.php, mailpoet/views/segments.html
[MAILPOET-3880]
[MAILPOET-3880]: https://mailpoet.atlassian.net/browse/MAILPOET-3880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Go to Products and create a new product called `1-month membership` (add some $ value)
2. Go to WooCommerce > Memberships
3. Create one more membership plan and name it whatever (can be named `1-month membership` as well)
4. Make sure to add the length `1 month` and also to include created product `1-month membership` from the first step
5. Now that you have `1-month membership` plan and product created, go and purchase it with a few accounts (can be even a guest order)
6. Purchase also the one already created called `1-week membership` with some account
7. Now that you have purchased at …
=> Add Woo memberships segment [MAILPOET-3880]

dev/xdebug.ini
In order to test the change proposed here, it is necessary to stop the dev environment, rebuild the wordpress service (`docker-compose build wordpress`), start the environment again, and check phpinfo() to confirm that `develop` is included in `xdebug.mode`. 
[MAILPOET-4098]
[MAILPOET-4098]: https://mailpoet.atlassian.net/browse/MAILPOET-4098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Enable Xdebug develop mode

mailpoet/tests/_support/DefaultsExtension.php, mailpoet/tests/acceptance/Forms/EditorAddDividerCest.php, mailpoet/tests/acceptance/Forms/EditorButtonStylesCest.php, mailpoet/tests/docker/codeception/docker-entrypoint.sh, mailpoet/tests/docker/docker-compose.yml
This PR upgrades the acceptance tests to use PHP8.0 for the running environment and WP-5.9-PHP8.0 for the WordPress image.
Uses the new images from:
https://github.com/mailpoet/wordpress-images/pull/28
https://github.com/mailpoet/wordpress-images/pull/29
A few tests have been updated to work both also with `seleniarm/standalone-chromium`, using `assertCssProperty`
The theme 2019 is no longer present on WP5.9. On this PR we conditionally load 2021 or 2019 depending on the CircleCI job.
To update your local tests:
Before running the new tests `./do d:d` and delete the  file `mailpoet/tests/_data/acceptancebackup.sql`
[MAILPOET-4014]
[MAILPOET-4014]: https://mailpoet.atlassian.net/browse/MAILPOET-4014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> Upgrade acceptance tests environment

.circleci/config.yml, mailpoet/tests/docker/docker-compose.yml
Fixes acceptance_oldest that I broke here: https://github.com/mailpoet/mailpoet/pull/3942
This PR adds a variable for the Codeception image so that we can use a different image for acceptance_oldest tests.
Follows what we do for the WordPress image.
Tested [here](https://app.circleci.com/pipelines/github/mailpoet/mailpoet/8695/workflows/2e073d73-ab15-45bc-a92b-461b23590dd7). I temporarily added the job to this branch.
[MAILPOET-4014]
[MAILPOET-4014]: https://mailpoet.atlassian.net/browse/MAILPOET-4014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix acceptance oldest

.circleci/config.yml, mailpoet/tasks/GithubClient.php, mailpoet/tests/DataFactories/WooCommerceMembership.php, mailpoet/tests/acceptance/Segments/WooCommerceMembershipsSegmentCest.php, mailpoet/tests/docker/codeception/docker-entrypoint.sh
This PR fixes a few issues with acceptance tests:
- a missing plugin WooCommerce Memberships
- incorrect arguments in the membership data factory
- inconsistency in prepared data in an acceptance test
=> Fix failing acceptance tests [MAILPOET-4095]

docker-compose.override.macos-sample.yml, docker-compose.yml
This PR exposes the Storybook port number to the Docker host to make the Storybook accessible [Mailpoet-4078]
- Run `./do storybook:watch`
- Confirm storybook is accessible under localhost:8083 
[MAILPOET-4078]
[MAILPOET-4078]: https://mailpoet.atlassian.net/browse/MAILPOET-4078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Storybook is not accessible in browser when ran on container [MAILPOET-4078]

mailpoet/lib/Config/Populator.php
For instances where plugin is not activated normally via WP admin (like for example when making Jurassic.ninja pre-install and activate MailPoet or throw [WP-CLI](https://wp-cli.org/)) the properties of `WP_User` are not correctly set thus incorrect values (false since it's the fallback for these fields) end up in `mailpoet_settings` table as `sender` default settings and the user sees these values when they initially see the MailPoet wizard.
1. Deactivate MailPoet plugin if it's active
2. Remove all MailPoet tables from you db
3. Activate the plugin by taking ssh to `wordpress` container using `./do ssh`
4. While in the `wordpress` container run `wp plugin activate mailpoet` to activate the plugin
5. Please note that activating the plugin via a none-UI method is the key to reproduce the …
=> Wizard displays 'false' on From Name and From Address MAILPOET-4062

README.md, dev/xdebug.ini
It seems that on some machines (maybe Macs?), enabling the Xdebug develop mode significantly impacts the performance of the WP site. On a quick investigation, our impression is that this is related to the DI container that we use. So for now, we are opting to revert this change. It is possible to enable the develop mode when needed using an environment variable that can be added to docker-compose.override.yml.
For more information, see this Slack thread: p1643895995581989-slack-C01G2EDTMQF
Reverts mailpoet/mailpoet#3945
[MAILPOET-4121]
[MAILPOET-4121]: https://mailpoet.atlassian.net/browse/MAILPOET-4121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert "Enable Xdebug develop mode" [MAILPOET-4121]

mailpoet/lib/Subscribers/SubscriberSubscribeController.php, mailpoet/tests/integration/API/JSON/v1/SubscribersTest.php, mailpoet/tests/unit/Subscribers/SubscriberSubscribeControllerUnitTest.php
Fixes [MAILPOET-3632]
This PR adds the `mailpoet_subscription_before_subscribe` in the SubscriberSubscribeController just before the subscriber gets stored. This hook could e.g. be used to validate the new subscriber by 3rd parties. A possible implementation could be
```
add_action(
'mailpoet_subscription_before_subscribe',
function(array $data, array $segmentIds, FormEntity $form) {
if ($form->id() !== 10) {
return
}
if ($data['some_custom_field'] === 'wrong') {
throw new \MailPoet\UnexpectedValueException("You can not use 'wrong' in the some_custom_field.");
}
},
10,
3
);
```
I took the opportunity to add some unit tests for the SubscriberSubscribeController
[MAILPOET-3632]: https://mailpoet.atlassian.net/browse/MAILPOET-3632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
=> Add mailpoet_subscription_before_subscribe hook [MAILPOET-3632]

mailpoet/lib/Cron/Workers/SendingQueue/SendingQueue.php, mailpoet/tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php
Fixes [MAILPOET-3943](https://mailpoet.atlassian.net/browse/MAILPOET-3943)
Fixes #3803
When processing the Queue in Cron/Workers/SendingQueue/SendingQueue, there are two distinct methods to do so: `bulk` and `individual`.
We loop through all subscribers and gather the individualized data like newsletter body for each subscriber. Those are stored in several arrays.
In case the processing method is `individual`, we send the newsletter immediately and resetting the mentioned arrays.
`$metas` did not get reset which resulted in #3803.
This PR adds a test to ensure the correct data gets send and resets the `$metas` array like the other arrays get resetted.
=> Incorrect use of $metas index in SendingQueue [MAILPOET-3943]

mailpoet/lib/Cron/Workers/StatsNotifications/Worker.php, mailpoet/lib/Twig/Functions.php, mailpoet/tests/integration/Cron/Workers/StatsNotifications/WorkerTest.php, mailpoet/views/emails/statsNotification.html, mailpoet/views/emails/statsNotification.txt, mailpoet/views/emails/statsNotificationAutomatedEmails.html
One of the first commits that I made in this PR was one to fix indentation issues in statsNotification.html. This might make it more convenient to review the changes in this PR commit by commit instead of everything at once.
I wasn't sure what is the best way to trigger a stats notification e-mail to test the changes that I implemented here. What I did was I changed the visibility of the method \MailPoet\Cron\Workers\StatsNotifications\Worker::constructNewsletter() to public and then I created a test in the WorkerTest.php file that would send the email and also write its contents to an HTML file. I also needed to change the constructor of the test class to define `$this->newsletterEntity = $newsletterEntity;`. Below is the snippet that I used for the test. Let me know if there is a better …
=> Update stats email to reflect redesign [MAILPOET-3324]

mailpoet/lib/AutomaticEmails/WooCommerce/Events/PurchasedInCategory.php, mailpoet/lib/AutomaticEmails/WooCommerce/Events/PurchasedProduct.php, mailpoet/lib/Newsletter/Scheduler/AutomaticEmailScheduler.php, mailpoet/tests/integration/AutomaticEmails/WooCommerce/Events/PurchasedInCategoryTest.php, mailpoet/tests/integration/AutomaticEmails/WooCommerce/Events/PurchasedProductTest.php
[MAILPOET-3518] please check testing instructions for 2 test cases inside Jira ticket.
This PR changes the way meta data is stored for automatic emails sent when a customer purchases a specified WooCommerce product or a product in a particular category. Previously we were storing all the product or category IDs associated with the order even if they weren't the IDs that triggered the newsletter. With this change, we only store the IDs that actually triggered the email, meaning the following scenario can occur:
1. There is an automatic email set up to send when a user purchases product ID 10
2. A customer makes a purchase that includes product IDs 10 and 15
3. The user receives the automatic email
4. The site admin updates the automatic email to be triggered when product ID 10 OR 15 is …
=> Only store relevant meta for WooCommerce emails [MAILPOET-3518]

mailpoet/build.sh, mailpoet/tests/integration/WP/FunctionsTest.php, mailpoet/uninstall.php
Fixes [MAILPOET-3961](https://mailpoet.atlassian.net/browse/MAILPOET-3961)
When you delete the plugin through the WordPress admin interface, you currently see the following prompt:
MailPoet ships with an _uninstall.php_. The purpose of this file is e.g. to delete database tables, options etc. when deinstalling the plugin ([docs](https://developer.wordpress.org/plugins/plugin-basics/uninstall-methods/)). But currently our _uninstall.php_ does nothing of that sort (see d988c04), therefore the message is misleading.
This PR removes the _uninstall.php_, which then results in the following prompt:
Currently, we do not have a proper uninstall route, but it is unlikely we would use the _uninstall.php_ as reinstalling the plugin from scratch is a way often used by our users to troubleshoot. …
=> Remove uninstall.php [MAILPOET-3961]

mailpoet/lib/Subscription/ManageSubscriptionFormRenderer.php, mailpoet/tests/integration/Subscription/ManageSubscriptionFormRendererTest.php
Change to make the meaning of the sentence more clear.
[MAILPOET-4068]
[MAILPOET-4068]: https://mailpoet.atlassian.net/browse/MAILPOET-4068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Go to MailPoet > Emails
2. Create and send one simple newsletter to yourself
3. Click on Manage Subscription link inside the newsletter
4. Confirm the updated sentence (check the specs in Jira)
=> Update a string displayed in the manage subscriptions page [MAILPOET-4068]

mailpoet/assets/js/src/common/premium_banner_with_upgrade/premium_banner_with_upgrade.tsx, mailpoet/assets/js/src/mailpoet.js, mailpoet/assets/js/src/mailpoet_com_url_factory.js, mailpoet/assets/js/src/newsletters/campaign_stats/premium_banner.jsx, mailpoet/assets/js/src/segments/dynamic/premium_banner.tsx, mailpoet/assets/js/src/subscribers/stats/no_access_info.tsx, mailpoet/assets/js/src/subscribers/stats/opened_email_stats.tsx, mailpoet/lib/AdminPages/Pages/Newsletters.php, mailpoet/lib/AdminPages/Pages/Segments.php, mailpoet/lib/AdminPages/Pages/Subscribers.php, mailpoet/lib/Config/Installer.php, mailpoet/lib/Config/ServicesChecker.php, mailpoet/views/newsletters.html, mailpoet/views/segments.html, mailpoet/views/shared_config.html, mailpoet/views/subscribers/subscribers.html
Offer to download or activate the premium plugin or upgrade plan in premium banner
[MAILPOET-3971](https://mailpoet.atlassian.net/browse/MAILPOET-3971)
Related to https://github.com/mailpoet/shop/pull/669
1. Make sure to downgrade Premium plugin to be 3.77.0 in order to test this pull request as this PR is on 3.77.0. Please head over [to this page to download](https://github.com/mailpoet/mailpoet-premium/releases) and upload 3.77.0 build. After that follow the next steps.
2. Go to MailPoet > Emails page
3. Click on statistics link for any of the sent newsletters to access the statistics page
4. On this page you could see the banner that is mentioned in the Jira ticket above. Please follow all three cases from the [Jira …
=> Offer to download or activate the premium plugin - MAILPOET-3971

mailpoet/readme.txt
I tested just a few of the main MailPoet pages and confirmed that they are working. I'm trusting the acceptance tests would have caught issues if there are any. I also read the [WP 5.9 field guide](https://make.wordpress.org/core/2022/01/10/wordpress-5-9-field-guide/) and couldn't find anything highlighted there with the potential to impact us.
[MAILPOET-4085]
[MAILPOET-4085]: https://mailpoet.atlassian.net/browse/MAILPOET-4085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump WP tested up to tag to 5.9

mailpoet/lib/Cron/Workers/StatsNotifications/AutomatedEmails.php, mailpoet/lib/Twig/Functions.php, mailpoet/views/emails/statsNotificationAutomatedEmails.html, mailpoet/views/emails/statsNotificationAutomatedEmails.txt
This PR should be reviewed after #3949 as it expands upon it. It is likely that it will be necessary to rebase this branch. Feel free to do it or ask me to do it.
Again, I was not sure what was the best way to trigger this e-mail to test the changes, so I created a hack using an integration test. I had to make the methods \MailPoet\Cron\Workers\StatsNotifications\AutomatedEmails::getNewsletters() and \MailPoet\Cron\Workers\StatsNotifications\AutomatedEmails::constructNewsletter() public and then used the following code in AutomatedEmailsTest.php:
```php
public function testItSendsEmail() {
Newsletter::createOrUpdate([
'id' => 8763,
'subject' => 'Subject',
'type' => 'welcome',
'status' => 'active',
]);
$this->createQueue(8763, 10);
$this->createClicks(8763, 5);
$this->createOpens(8763, 2); …
```
=> Update montly stats email to reflect redesign [MAILPOET-4102]

mailpoet/lib/Newsletter/Shortcodes/Shortcodes.php, mailpoet/tests/integration/Newsletter/ShortcodesTest.php
Fixes [MAILPOET-4151]
[MAILPOET-4151]: https://mailpoet.atlassian.net/browse/MAILPOET-4151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix action_argument_value of shortcode will be string if empty [MAILPOET-4151]

mailpoet/assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/cookie_settings.tsx
There was an issue in argument type in the string replace function. Also, it seems that after changes introduced in [update eslint PR](https://github.com/mailpoet/mailpoet/pull/3968) we need to declare components using the function keyword see https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/function-component-definition.md.
[MAILPOET-4159]
[MAILPOET-4159]: https://mailpoet.atlassian.net/browse/MAILPOET-4159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Typescript and eslint warnings in cookie_settings.tsx [MAILPOET-4159]

mailpoet/assets/js/src/public.jsx
Fix a selector that was missing the closing bracket on the context.
No JS errors or any issues with the newer versions but it was failing on acceptance oldest.
To test:
I have run the acceptance_oldest tests with this branch, (temporarily modifying the CircleCI config), results here: 
https://app.circleci.com/pipelines/github/mailpoet/mailpoet/8929/workflows/7191214d-ca64-4a44-bf64-9cb7f6397596
[MAILPOET-4161]
[MAILPOET-4161]: https://mailpoet.atlassian.net/browse/MAILPOET-4161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix acceptance_oldest tests

mailpoet/lib/Twig/I18n.php
I found that this is already fixed by translators. In order to replicate the issue, you need to use the mailpoet-tr_TR.mo.zip unzip it to `mailpoet/langs` folder, and switch your site to use the Turkish language.
[MAILPOET-4153]
[mailpoet-tr_TR.mo.zip](https://github.com/mailpoet/mailpoet/files/8131430/mailpoet-tr_TR.mo.zip)
[MAILPOET-4153]: https://mailpoet.atlassian.net/browse/MAILPOET-4153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Turkish translation issue

mailpoet/lib/Segments/DynamicSegments/Filters/WooCommerceSubscription.php, mailpoet/tests/_support/Helper/Database.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/WooCommerceSubscriptionTest.php
Fixes [MAILPOET-4109]
When a subscriber cancels her subscription, we still need to consider this subscription active until the current period expires. The WooCommerce Subscriptions plugin uses for those subscriptions the post_status "wc-pending-cancel".
I have added an integration test, which tests the WooCommerceSubscription filter. Since there is currently no other setup for 3rd party plugins in integration tests, I follow the current model and create the necessary tables and data structures in the test itself.
How to test:
1. Go To WooCommerce > Subscriptions
2. Add Subscription to some of the existing subscribers, make sure to select Active status and to add the subscription product item when adding a subscription
3. Go To MailPoet > Lists and create a new segment that counts active …
=> Add pending cancel subscriptions to dynamic segment [MAILPOET-4109]

eslint-config/.eslintrc.ts.json, mailpoet/assets/js/src/date.ts, mailpoet/assets/js/src/form/types/field.ts, mailpoet/assets/js/src/form/types/fieldType.ts, mailpoet/assets/js/src/form/types/index.ts, mailpoet/assets/js/src/global.d.ts, mailpoet/assets/js/src/newsletters/models/index.ts, mailpoet/assets/js/src/newsletters/models/newsletter.ts, mailpoet/assets/js/src/newsletters/send.jsx, mailpoet/assets/js/src/newsletters/send/automatic.jsx, mailpoet/assets/js/src/newsletters/send/ga_tracking.tsx, mailpoet/assets/js/src/newsletters/send/notification.jsx, mailpoet/assets/js/src/newsletters/send/standard.tsx, mailpoet/assets/js/src/newsletters/send/welcome.jsx, mailpoet/lib/AdminPages/Pages/Newsletters.php, mailpoet/tests/acceptance/Newsletters/ScheduleNewsletterCest.php, mailpoet/tests/javascript/utilities/date.spec.ts, mailpoet/tsconfig.json, mailpoet/views/newsletters.html
This PR initially makes some cleanup and then applies the fix as follows:
- Define NewsLetter type
- Define component props type
- Add acceptance test for past/future time
- Pick a newsletter and visit `Edit` page
- Visit the `Send` page by clicking `Next` on the the editor page
- Toggle the `schedule` option on
- Verify that the primary submit button this page reads `Send` for past dates/times and `Schedule` for future dates/times, note that time is calculated based on the time show in `Your website’s time is {time}`
[MAILPOET-4163]
[MAILPOET-4163]: https://mailpoet.atlassian.net/browse/MAILPOET-4163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Button says "Send" instead of "Schedule" even if the schedule time is in the future MAILPOET-4163

mailpoet/lib/Statistics/Track/Clicks.php, mailpoet/lib/Statistics/Track/Opens.php, mailpoet/lib/Subscribers/InactiveSubscribersController.php, mailpoet/lib/Subscribers/SubscribersRepository.php, mailpoet/tests/integration/Statistics/Track/ClicksTest.php, mailpoet/tests/integration/Statistics/Track/OpensTest.php, mailpoet/tests/integration/Subscribers/InactiveSubscribersControllerTest.php
This PR changes the inactive subscriber criteria to:
d) The subscriber has not clicked or opened any emails in X months (as specified in settings), human or machine. Currently, we discard machine opens/clicks. (updated condition)
b) The subscriber has received at least 3 emails in the last X months (setting value) (updated condition)
It also removes old code on the tests and comments that were no longer true.
(c), (e), (f), and (g) are already implemented and covered by existing tests on: 
tests/integration/Statistics/Track/SubscriberActivityTrackerTest.php and tests/integration/Subscribers/InactiveSubscribersControllerTest.php
[MAILPOET-4081]
[MAILPOET-4081]: https://mailpoet.atlassian.net/browse/MAILPOET-4081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
=> Expand inactive subscriber criteria

mailpoet/tests/acceptance/Segments/WooCommerceDynamicSegmentsCest.php
Fixes [MAILPOET-4169]
This PR applies the `--force` parameter to the CLI calls in the acceptance tests, which run the action scheduler.
This will result in the CLI returning a warning instead of an error [#](https://github.com/woocommerce/action-scheduler/blob/2d58fd29e9a17725009d78a029b0550112437a26/classes/WP_CLI/ActionScheduler_WPCLI_QueueRunner.php#L57-L63).
As far as I understand, the problem with having multiple concurrent runs can be server resources [#](https://actionscheduler.org/perf/#increasing-concurrent-batches). I did some test runs in CircleCI and so far the tests never failed. I think, we need to see, if server resources would be a problem for us, but I do not expect so.
[MAILPOET-4169]: https://mailpoet.atlassian.net/browse/MAILPOET-4169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
=> Force action scheduler in acceptance tests to run [MAILPOET-4169]

mailpoet/lib/AdminPages/Pages/Help.php, mailpoet/lib/Mailer/MailerLog.php, mailpoet/tasks/phpstan/phpstan-7-baseline.neon, mailpoet/tasks/phpstan/phpstan-8-baseline.neon, mailpoet/tests/integration/API/JSON/v1/MailerTest.php, mailpoet/tests/integration/Cron/Workers/SendingQueue/Tasks/MailerTest.php, mailpoet/tests/integration/Cron/Workers/SendingQueue/Tasks/NewsletterTest.php, mailpoet/tests/integration/Mailer/MailerLogTest.php, mailpoet/tests/integration/Services/AuthorizedEmailsControllerTest.php
Fixes [MAILPOET-4122]
Before this PR, MailPoet was able to send more emails than the settings allowed for.
Before this PR, we calculated whether the sending limit was reached in a data model, which consisted out of the number of emails sent since a fixed timestamp. So, once we started a new "series", we would set the timestamp and then just count up until the limit was reached. Once the limit was reached, we would check if the timestamp we had was outdated, in which case we would reset the number of emails, set a new timestamp and continue sending.
This model had some flaws:
1. Example: Limit is 100 emails, allowed timespan is 1 minute. Lets say our last "series" consisted of 50 emails. This left 50 unused "spots". Before we would check whether the timestamp was outdated (hence, we were …
=> Prevent sending more emails than allowed [MAILPOET-4122]

mailpoet/lib/Analytics/Reporter.php, mailpoet/lib/Helpscout/Beacon.php, mailpoet/tests/integration/Helpscout/BeaconTest.php
This PR adds the transactional sending method advanced setting to the system info tab on the Help page, as well as to the data we collect for analytics.
`/wp-admin/admin.php?page=mailpoet-settings#/advanced`
`/wp-admin/admin.php?page=mailpoet-help#/systemInfo`
Viewing analytics data requires that the "Share anonymous data" advanced setting is set to `Yes`
The easiest way I found to inspect the analytics data was by looking at the `mailpoet_analytics_data` variable in the browser console.
However, this variable is not populated on every page load. It's created periodically whenever analytics are due to be sent in. You can make the plugin believe that it's time to send analytics again by deleting the `analytics_last_sent` setting from `wp_mailpoet_settings`.
[MAILPOET-4148]
[MAILPOET-4148]: …
=> Add transactional sending method to system info [MAILPOET-4148]

mailpoet/lib/Segments/DynamicSegments/Filters/WooCommerceCategory.php, mailpoet/lib/Segments/DynamicSegments/Filters/WooCommerceProduct.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/WooCommerceCategoryTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/WooCommerceProductTest.php
Fixes [MAILPOET-4127]
To test:
1. Create Pending payment and On-hold orders.
2. Create a “Purchased this product” segment with this product
3. Customers should not appear in the segment
4. Create a “Purchased in category” segment with this product
5. Customers should not appear in the segment
[MAILPOET-4127]: https://mailpoet.atlassian.net/browse/MAILPOET-4127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Exclude orders not payed and on hold from calculating purchase segments [MAILPOET-4127]

mailpoet/assets/js/src/listing/listing.jsx, mailpoet/lib/Subscribers/SubscriberListingRepository.php, mailpoet/tasks/phpstan/phpstan-7-baseline.neon, mailpoet/tasks/phpstan/phpstan-8-baseline.neon
Fixes [MAILPOET-3535]
In order to update the tab count, we need to perform the count query with the restrictions of the current search in place. This is what happens in f2e5a81. This of course has impacts on the performance as these are more detailed SQL queries, we need to run.
I tested a bit between master and this PR (having ~1950 subscribers in the database), the loading difference for a normal request (without e.g. a specific search query) are on average < 100ms, the same goes for queries with a specific search term.
5eb02c8 prevents the resetting of the filters and search terms, when switching between the tabs.
[MAILPOET-3535]: https://mailpoet.atlassian.net/browse/MAILPOET-3535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Testing …
=> Update counts on tabs when searching [MAILPOET-3535]

mailpoet/lib/Newsletter/ViewInBrowser/ViewInBrowserController.php, mailpoet/tests/integration/Newsletter/ViewInBrowser/ViewInBrowserControllerTest.php
Fixes [MAILPOET-4190]
The problem in MAILPOET-4190 is we try to render the shortcode without a subscriber set, which just returns the plain shortcode [#](https://github.com/mailpoet/mailpoet/blob/9ea484c972000f861cfff3b9f613428a04aadd42/mailpoet/lib/Newsletter/Shortcodes/Categories/Subscriber.php#L37-L39). We rely on this behavior, as in some processes, we run our newsletter through the shortcode processes to prepare them and then again with the actual subscriber.
Therefore this PR proposes to use an empty `SubscriberEntity` when rendering the BrowserView and we do not have a subscriber at hand.
This PR also proposes to move all "find the subscriber"-logic into the `ViewInBrowserController::getSubscriber()`. So in case of no subscriber is found but we are in the preview mode, we try to …
=> Set an empty subscriber when no Subscriber found for ViewInBrowser

mailpoet/lib/Settings/Hosts.php
[MAILPOET-4196]
[MAILPOET-4196]: https://mailpoet.atlassian.net/browse/MAILPOET-4196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Steps:
1. Go to MailPoet > Settings > Send With tab
2. Click to configure custom sending method
3. Set to send with own host
4. Click the dropdown and make sure you see `IONOS by 1&1` on the list and that you don't see `1&1`.
=> Update name of 1and1 web host in settings [MAILPOET-4196]

mailpoet/lib/API/JSON/v1/SendingQueue.php, mailpoet/lib/Cron/Workers/Scheduler.php, mailpoet/lib/Entities/ScheduledTaskSubscriberEntity.php, mailpoet/lib/Models/ScheduledTaskSubscriber.php, mailpoet/lib/Segments/SubscribersFinder.php, mailpoet/tests/DataFactories/Segment.php, mailpoet/tests/DataFactories/Subscriber.php, mailpoet/tests/integration/API/JSON/v1/SendingQueueTest.php, mailpoet/tests/integration/Cron/Workers/SchedulerTest.php, mailpoet/tests/integration/Segments/SubscribersFinderTest.php
[MAILPOET-3925]
[MAILPOET-3925]: https://mailpoet.atlassian.net/browse/MAILPOET-3925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Steps:
1. Go to MailPoet > Lists > Segments tab
2. Make sure you see some segment that counts at least 3 subscribers (or make a new segment instead)
3. Send simple newsletter to that segment and make sure they have received newsletter
=> Refactor SubscribersFinder to use Doctrine instead of Paris [MAILPOET-3925]

.circleci/config.yml, mailpoet/lib/PostEditorBlocks/WooCommerceBlocksIntegration.php
Fixes [MAILPOET-4206]
The `woocommerce_blocks_checkout_update_order_from_request` hook is deprecated, but the implementation of the deprecation contains a bug (see https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/6133). We can not jump to the latest iteration of the hook as we want to stay compatible for a while with older plugin versions of the Woo blocks plugin.
This PR falls back to the `__experimental_woocommerce_blocks_checkout_update_order_from_request` hook, which allows us to quickly circle around this issue for now until we can safely upgrade the hook.
[MAILPOET-4206]: https://mailpoet.atlassian.net/browse/MAILPOET-4206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix critical error in woo checkout block [MAILPOET-4206]

mailpoet/lib/Analytics/Reporter.php, mailpoet/lib/Listing/ListingDefinition.php
Fixes [MAILPOET-4204]
This PR adds the subscriber counts to our MixPanel data. Example: 
It utilizes the SubscriberListingRepository and therefore uses the same data source, the JSON API uses to display those data for the user.
The PR extends the constructor of the ListingDefintion by assigning some default values. The values chosen are the ones, which are used when visiting the Subscriber Listing page and not changing any value.
[MAILPOET-4204]: https://mailpoet.atlassian.net/browse/MAILPOET-4204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add subscriber counts to MixPanel [MAILPOET-4204]

mailpoet/lib/Form/Util/Styles.php, mailpoet/lib/Subscription/CaptchaRenderer.php, mailpoet/tests/unit/Form/Util/StylesTest.php
Fixes [MAILPOET-4134]
This PR utilizes the `Form\Util\Styles` class to apply the custom styles defined in a form also to the captcha form, thus rendering the error and success messages in the correct colors.
[MAILPOET-4134]: https://mailpoet.atlassian.net/browse/MAILPOET-4134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Testing Instructions:
1. Go to MailPoet > Forms
2. Edit one of the forms and make sure to set `Success Message Color` / `Error Message Color` colors to something like Black / Purple. Save the form at the end. Setting these colors can be found under Styles tab on the right.
3. Open Private window and go to front-end to trigger such form
4. Fill everything required and submit the form
5. When redirected to a new page to fill …
=> Add custom styles to CaptchaRenderer [MAILPOET-4134]

mailpoet/readme.txt
This PR adds information to the file Readme.txt about the use of 3rd party services in the plugin. This change was requested by the WP.org plugin team.
Compared to the original text in the Jira ticket, I have capitalized the title and modified the periods on the list to be consistent with the other lists' punctuation.
[MAILPOET-4229]
[MAILPOET-4229]: https://mailpoet.atlassian.net/browse/MAILPOET-4229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Readme.txt to include information on 3rd party

mailpoet/lib/Doctrine/CacheOnlyMappingDriver.php, mailpoet/lib/Doctrine/ConfigurationFactory.php, mailpoet/prefixer/composer.json, mailpoet/prefixer/composer.lock, mailpoet/prefixer/fix-doctrine.php, mailpoet/tests/docker/codeception/docker-entrypoint.sh
This PR updates doctrine packages (after [the original update commit was reverted due to issues](https://github.com/mailpoet/mailpoet/pull/4042)) and fixes the issues.
In the production environment, we used to rely on Metadata MappingDriver not being used at all when all metadata are cached. The recent changes in `doctrine/orm` revealed that it is not the case and the driver is used in a [couple](https://github.com/doctrine/persistence/blob/b07e347a24e7a19a2b6462e00a6dff899e4c2dd2/src/Persistence/Mapping/AbstractClassMetadataFactory.php#L478) [of](https://github.com/doctrine/persistence/blob/b07e347a24e7a19a2b6462e00a6dff899e4c2dd2/src/Persistence/Mapping/AbstractClassMetadataFactory.php#L336) places regardless there is some cache. 
We were a bit lucky that we hadn't run into these issues …
=> Fix doctrine metadata loading errors [MAILPOET-4218]

mailpoet/RoboFile.php
This PR changes the Robo command release:publish to use the mailpoet.pot file that is present in the zip file in the release branch of the CircleCI build. Before we were using the mailpoet.pot file present in the local repository, which meant it could contain undesired local changes that should not be included when creating a new MailPoet release.
A new Robo command was created to get the zip file from CircleCI called translations:get-pot-file-from-circle-ci. The old translations:build was preserved as it is used inside mailpoet/build.sh.
To test the changes here, I suggest commenting out all the commands that are called inside \RoboFile::releasePublish() after \RoboFile::translationsGetPotFileFromCircleCI() and then running `./do release:publish`. You can try the `release:publish` …
=> Update release:publish to use mailpoet.pot file from CircleCI [MAILPOET-4173]

mailpoet/lib/API/JSON/API.php, mailpoet/lib/Form/DisplayFormInWPContent.php, mailpoet/lib/Form/Widget.php, mailpoet/lib/Util/Security.php, mailpoet/tests/integration/API/JSON/APITest.php, mailpoet/tests/integration/Subscription/FormTest.php
This is a refactor to inline `Security::genreateToken`. The only thing Security::generateToken was providing was a default value for the $action, which created a pattern of using the same $action everywhere, which may not be the best way to go. It was obfuscating what we were really doing under the hood.
This is a followup to #4025, which we decided wouldn't make sense to implement.
[MAILPOET-2030]: https://mailpoet.atlassian.net/browse/MAILPOET-2030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Inline Security::generateToken for clarity [MAILPOET-2030]

mailpoet/lib/Services/Bridge/API.php, mailpoet/tests/integration/Services/BridgeApiTest.php
1. Go to MailPoet > Settings > Key Activation tab
2. Enter an invalid Key (anything really)
3. Go to `/wp-admin/admin.php?page=mailpoet-logs` and look for logs with `mss.ERROR: key-validation.failed`
4. Verify they contain `"home_url":"https://gs.qawp.net",` info
[MAILPOET-4051]
[MAILPOET-4051]: https://mailpoet.atlassian.net/browse/MAILPOET-4051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add logging of failed mss and premium key validations on API [MAILPOET-4051]

mailpoet/assets/js/src/listing/notices.jsx, mailpoet/lib/Mailer/MailerError.php, mailpoet/lib/Mailer/Methods/ErrorMappers/MailPoetMapper.php, mailpoet/lib/Util/Helpers.php, mailpoet/tests/unit/Mailer/Methods/ErrorMappers/MailPoetMapperTest.php
This PR adds a separate message to the Emails listing page ( see attachment ) if the user's account is pending approval.
1. Make sure you have MSS as sending method at `MailPoet` > `Settings` > `Send With` tab
2. Now go to `Plugins` > `Plugin File Editor` and make sure you see `MailPoet 3 (New)` as selected plugin.
Now locate the file [API.php](https://github.com/mailpoet/mailpoet/blob/9b71a7804cd7d3c8724c9ac877cc62def4d3a697/mailpoet/lib/Services/Bridge/API.php) under `Plugin Files` on the right sidebar, it should be under `lib` > `Services` > `Bridge` > `API.php` and add the following code into the beginning of the method [sendMessages](https://github.com/mailpoet/mailpoet/blob/9b71a7804cd7d3c8724c9ac877cc62def4d3a697/mailpoet/lib/Services/Bridge/API.php#L103) (exactly under "public …
=> Mailpoet 3992 to show a specific error message for pending approval users

mailpoet/lib/Subscription/Registration.php, mailpoet/tests/acceptance/Subscribers/SubscriberCookieCest.php
Fixes [MAILPOET-4060]
In a multisite, the tracking cookie is not set when you sign up to the site and you checked the newsletter checkbox. The problem is that at that point in the process the headers are already sent, so we can not send the Cookie from the server:
This PR alters the test and checks for the cookie once the user follows the link to wp-activate.php (at which point, the cookie will be set) and prevents the attempt to set a cookie.
[MAILPOET-4060]: https://mailpoet.atlassian.net/browse/MAILPOET-4060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Alter CookieCest test for multisite [MAILPOET-4060]

mailpoet/lib/Segments/WooCommerce.php
Split the` INSERT ON DUPLICATE KEY UPDATE` query into two queries to avoid this bug: https://jira.mariadb.org/browse/MDEV-28310
I don't know how to test that the replication bug is not happening.
Automated tests using the modified query are still passing.
[MAILPOET-4248]
[MAILPOET-4248]: https://mailpoet.atlassian.net/browse/MAILPOET-4248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Change INSERT ON DUPLICATE KEY UPDATE query

mailpoet/tests/DataFactories/Settings.php, mailpoet/tests/acceptance/Subscribers/SubscriberCookieCest.php
I found 2 issues:
1) The account activation email was not delivered to MailHog, and clicking on the activation link was not working. Fixed in the first commit. Please see the info in the commit message.
2) The cookie was not set on the activation page. After discussing it with @JanJakes I fixed the test by adding logging and verifying the cookie after logging in. Please see more info in the commit message of the second commit.
I temporarily activated the multisite test on this branch. Here is [a passing test run](https://app.circleci.com/pipelines/github/mailpoet/mailpoet/9553/workflows/5928a457-d433-436e-aa8d-b501cfb4b180/jobs/174950).
[MAILPOET-4249]
[MAILPOET-4249]: https://mailpoet.atlassian.net/browse/MAILPOET-4249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …
=> Fix acceptance subscriber cookie test [MAILPOET-4249]

mailpoet/lib/API/JSON/v1/AutomatedLatestContent.php, mailpoet/lib/DI/ContainerConfigurator.php, mailpoet/lib/Newsletter/AutomatedLatestContent.php, mailpoet/lib/Newsletter/BlockPostQuery.php, mailpoet/lib/Newsletter/Renderer/Blocks/AutomatedLatestContentBlock.php, mailpoet/lib/Util/APIPermissionHelper.php, mailpoet/tasks/phpstan/phpstan-7-baseline.neon, mailpoet/tasks/phpstan/phpstan-8-baseline.neon, mailpoet/tasks/phpstan/phpstan-8.1-baseline.neon, mailpoet/tests/integration/Newsletter/AutomatedLatestContentAPITest.php, mailpoet/tests/integration/Newsletter/AutomatedLatestContentTest.php, mailpoet/tests/integration/Newsletter/Blocks/AbandonedCartContentTest.php, mailpoet/tests/integration/Subscription/SubscriptionUrlFactoryTest.php, mailpoet/tests/integration/_bootstrap.php
Reverts mailpoet/mailpoet#4068
Testing:
Note: This pull request doesn't have simple steps to test it. This change is directly affecting Post Notifications part of the plugin. Please test that it is working as expected, here are some tips to test it:
1. Go to Posts and make a 1-2 posts and make sure you have received Post Notification email about the latest posts on site
2. Go to MailPoet > Emails > Post Notifications tab
3. Edit the existing or create a new post notification email but make sure to test ALC (Automatic Latest Content) block and its settings in the right sidebar (click the block to see the right sidebar and then click `Display Options` link to see full settings of the block)
4. Test receiving PN email after you make some changes/tests of that ALC block
=> Revert "Revert "Process arguments better when querying posts for automated latest content [MAILPOET-4082]""

mailpoet/lib/Segments/SegmentsRepository.php, mailpoet/tests/integration/Segments/SegmentsRepositoryTest.php
This PR ensures that we run our own check for uniqueness on a segment's name when updating an existing segment so users don't end up seeing a doctrine exception if they attempt to update a segment's name to a name that already exists.
Throwing our own `ConflictException` means that  we'll display a more user-friendly message, one that we're already using and have translations for, because [we catch that exception](http://github.com/mailpoet/mailpoet/blob/f4e30789afc2ef66ab4fcf8a091f8c33000e47eb/mailpoet/lib/API/JSON/v1/Segments.php#L128-L132).
It's worth noting that the `ConflictException` message itself, which refers to creating a new segment, is never displayed to the user.
Before:
After:
[MAILPOET-4199]
[MAILPOET-4199]: https://mailpoet.atlassian.net/browse/MAILPOET-4199?atlOrigin=eyJpI …
=> Check for uniqueness when updating segment name [MAILPOET-4199]

mailpoet/tests/integration/Newsletter/AutomatedLatestContentAPITest.php
The issue was that on the CI we are switching the blog to a blog with id other than 1 when testing on MU.
Since we are not fully supporting MU a switch to blog_id = 1 was added to run the MU test only against the first blog.
[[MAILPOET-4082]]
[MAILPOET-4082]: https://mailpoet.atlassian.net/browse/MAILPOET-4082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix failing tests of AutomatedLatestContent::getPosts in MU

mailpoet/lib/API/JSON/v1/Newsletters.php, mailpoet/lib/API/JSON/v1/SendingQueue.php, mailpoet/lib/AutomaticEmails/WooCommerce/Events/FirstPurchase.php, mailpoet/lib/AutomaticEmails/WooCommerce/Events/PurchasedInCategory.php, mailpoet/lib/AutomaticEmails/WooCommerce/Events/PurchasedProduct.php, mailpoet/lib/Cron/Workers/Scheduler.php, mailpoet/lib/DI/ContainerConfigurator.php, mailpoet/lib/Newsletter/NewsletterSaveController.php, mailpoet/lib/Newsletter/Scheduler/AutomaticEmailScheduler.php, mailpoet/lib/Newsletter/Scheduler/PostNotificationScheduler.php, mailpoet/lib/Newsletter/Scheduler/Scheduler.php, mailpoet/lib/Newsletter/Scheduler/WelcomeScheduler.php, mailpoet/tests/integration/API/JSON/v1/NewslettersTest.php, mailpoet/tests/integration/API/JSON/v1/SendingQueueTest.php, mailpoet/tests/integration/AutomaticEmails/WooCommerce/Events/AbandonedCartTest.php, mailpoet/tests/integration/Cron/Workers/SchedulerTest.php, mailpoet/tests/integration/Newsletter/Blocks/AbandonedCartContentTest.php, mailpoet/tests/integration/Newsletter/NewsletterSaveControllerTest.php, mailpoet/tests/integration/Newsletter/Scheduler/AutomaticEmailTest.php, mailpoet/tests/integration/Newsletter/Scheduler/PostNotificationTest.php, mailpoet/tests/integration/Newsletter/Scheduler/SchedulerTest.php, mailpoet/tests/integration/Newsletter/Scheduler/WelcomeTest.php, mailpoet/tests/unit/Newsletter/Scheduler/SchedulerTest.php
Fixes [MAILPOET-4252]
[MAILPOET-4252]: https://mailpoet.atlassian.net/browse/MAILPOET-4252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Test steps:
1. Go to MailPoet > Emails
2. Schedule a new simple newsletter to be sent to your email today (remember the date/time)
3. Go to MailPoet Debug, copy the password shown and click Adminer link
4. Paste the password and click Login
5. Click [wp_mailpoet_scheduled_tasks](https://gs.qawp.net/wp-content/plugins/mailpoet-debug-trunk/adminer.php?server=localhost&username=admin_gsqawpuser&db=admin_gsqawpdb&table=wp_mailpoet_scheduled_tasks) table when inside
6. Click Select data link
7. Click twice time `scheduled_at` row to sort it to the last newsletter
8. You need to find your scheduled newsletter …
=> Non-static scheduler

mailpoet/prefixer/fix-twig.php
I searched for all occurrences of twig_compare calls and replaced occurrences in strings that are used in generated code with namespace prefixed twig_compare.
Note the fix is applied within composer installation so you need to run `./do install` when testing locally.
The [older build from master](https://app.circleci.com/pipelines/github/mailpoet/mailpoet/9662/workflows/36881a03-1533-4ffb-8100-24fef45f6ad0/jobs/176220/artifacts) was not working on PHP7.4 and below.
[MAILPOET-4279]
[MAILPOET-4279]: https://mailpoet.atlassian.net/browse/MAILPOET-4279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix twig_compare function in prefixed version of twig [MAILPOET-4279]

mailpoet/lib/Cron/CronHelper.php, mailpoet/lib/Cron/Triggers/WordPress.php
Part of [MAILPOET-4267]
This PR reduces two SQL inserts which happen on every request. Currently we write the last time we did run the cron, so we can compare whether we need to run it now. As by default we compare like `time() - $lastRun >= -1`, we always run and always write to the database. In case we would check against `-1` we therefore can `return true;` early and prevent the SQL write.
The second part of this PR is concerned with the deactivation of the daemon, which is also a SQL write. The basic conclusion is, we do not need to deactivate an inactive daemon and could save this write, which otherwise will occur on most of the requests:
https://github.com/mailpoet/mailpoet/blob/c08bde077b684c72d12bc1e2de94b6df17772d19/mailpoet/lib/Cron/Triggers/WordPress.php#L73-L80
The `run()` …
=> Prevent unnecessary SQL inserts [MAILPOET-4267]

mailpoet/lib/API/JSON/v1/Subscribers.php, mailpoet/tests/integration/API/JSON/v1/SubscribersTest.php
[MAILPOET-4149]
[MAILPOET-4149]: https://mailpoet.atlassian.net/browse/MAILPOET-4149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Use a third-party sending method in `MailPoet` > `Settings` > `Send With…` (can be Your Host)
2. Disable signup confirmation in `MailPoet` > `Settings` > `Sign-up Confirmation`
3. Go to Subscribers page and try to `resend email confirmation` for any `Unconfirmed` subscriber (in case you don't have, edit one and set it to be unconfirmed status)
4. Verify that you see the error message correctly, test the link inside the sentence and make sure it leads to the settings page
Note: Additionally, enable the Sign-up Confirmation in the settings and try to resent the confirmation, make sure you …
=> Improve message for confirmation emails [MAILPOET-4149]

mailpoet/lib/API/JSON/v1/AutomatedLatestContent.php
Fixes [MAILPOET-4278]
[MAILPOET-4278]: https://mailpoet.atlassian.net/browse/MAILPOET-4278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Testing instr.:
1. Create a new post at All Posts and schedule it for sending for any date in the future
2. Create a new post and save it as a draft
3. Go to Newsletter Editor
4. Try to add a Posts block but set to show Scheduled posts, then click Insert button to add your scheduled post, make sure you see it added... send the newsletter to yourself and check if you see it.
5. Try to add a Posts block but set to show Drafts posts, then click Insert button to add your drafted post, make sure you see it added... send the newsletter to yourself and check if you see it.
6. Make some tests around the Posts block …
=> Correctly set `dynamic` arg false for Posts block requests

mailpoet/assets/js/src/help-tooltip-helper.js, mailpoet/assets/js/src/mailpoet.ts, mailpoet/assets/js/src/newsletters/templates/import_template.jsx
Fixes [MAILPOET-4288]
- Having js/ts (x) files with same name caused wrong imports, this is mitigated by making the file names different.
[MAILPOET-4288]: https://mailpoet.atlassian.net/browse/MAILPOET-4288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix HelpTooltip component import MAILPOET-4288

mailpoet/RoboFile.php
This PR introduces a new command `./do cleanup:cached-files` that removes all files from the `generated` folder and PHPStan cached files. It also adds the command as the last step of `./do install` command. 
The idea behind this is that after updating dependencies often the generated files become outdated and may cause strange and confusing errors.
[MAILPOET-4262]
[MAILPOET-4262]: https://mailpoet.atlassian.net/browse/MAILPOET-4262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cleanup cached files in dev env on install [MAILPOET-4262]

mailpoet/lib/PostEditorBlocks/WooCommerceBlocksIntegration.php, mailpoet/tasks/phpstan/phpstan.neon, mailpoet/tests/integration/PostEditorBlocks/WooCommerceBlocksIntegrationTest.php
Fixes [MAILPOET-4276] and [MAILPOET-4208]
The `ExtendRestApi::class` is deprecated since WooCommerce Blocks  version 7.2.0 [#](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/e192c1d378c57a5dec459d653334c3f0969775ba/src/Domain/Bootstrap.php#L288-L294).
Since we want to remain compatible also with older versions of the WooCommerce Blocks plugin, this PR introduces a PluginHelper class with which we can easily check the version of a currently installed plugin.
Depending on this version, we load either the `ExtendRestApi::class` or the `ExtendSchema::class`.
[MAILPOET-4276]: https://mailpoet.atlassian.net/browse/MAILPOET-4276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAILPOET-4208]: …
=> Introduce switch to use ExtendSchema for newer WooCommerce block installations  [MAILPOET-4276]

mailpoet/lib/API/JSON/ResponseBuilders/NewslettersResponseBuilder.php, mailpoet/lib/Newsletter/Sending/SendingQueuesRepository.php, mailpoet/tests/integration/API/JSON/ResponseBuilders/NewslettersResponseBuilderTest.php, mailpoet/tests/integration/API/JSON/v1/NewslettersTest.php, mailpoet/tests/integration/Newsletter/Sending/SendingQueuesRepositoryTest.php
This PR removes all uses of the old Paris model from the class NewslettersResponseBuilder and its corresponding integration test class. To do that it was necessary to create a new method in SendingQueuesRepository to count queues based on newsletter and task status.
To test manually, I checked that the number of scheduled tasks for a welcome email that is displayed under "Status" in /wp-admin/admin.php?page=mailpoet-newsletters#/welcome matched after and before the changes proposed here.
[MAILPOET-4138]
[MAILPOET-4138]: https://mailpoet.atlassian.net/browse/MAILPOET-4138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Please test Welcome emails (creating, receiving...)
=> Refactor NewslettersResponseBuilder to Doctrine [MAILPOET-4138]

mailpoet/lib/Config/Hooks.php, mailpoet/lib/Newsletter/Scheduler/WelcomeScheduler.php, mailpoet/lib/Segments/WP.php, mailpoet/tests/integration/Segments/WPTestUser.php, mailpoet/tests/integration/Segments/WPUserWithExtraProps.php, mailpoet/tests/integration/Segments/WooCommerceTest.php
Fixes [MAILPOET-2834]
Current behavior:
When an administrator changes the role of a user on the profile page, we synchronize the user which means, we send an welcome email, if for the role a welcome email exists.
When a plugin updates a user using either `$user->add_role()` or `$user->set_role()` we do not synchronize the user and thus not send the welcome email.
This PR enables us, to listen for those changes as well.
Notes:
00c34867da8eabeea4bec177e3798ef839c64014 We use `$user->add_role()` in our tests which lead to side effects (where e.g. a WooCommerce user is now a WordPress user). The commit extends the `\WPUserWithExtraProps` we use in our integration tests and overwrites the default `add_role()` and does not fire the hook. Question to me would be, if we should rename …
=> Add user role hook [MAILPOET-2834]

mailpoet/lib/Models/DynamicSegmentFilter.php, mailpoet/lib/Models/StatisticsClicks.php, mailpoet/lib/Models/StatisticsNewsletters.php, mailpoet/lib/Models/StatisticsOpens.php, mailpoet/lib/Models/StatisticsWooCommercePurchases.php, mailpoet/tests/DataGenerator/Generators/WooCommercePastRevenues.php, mailpoet/tests/integration/Cron/Workers/StatsNotifications/AutomatedEmailsTest.php, mailpoet/tests/integration/Cron/Workers/StatsNotifications/WorkerTest.php, mailpoet/tests/integration/Statistics/Track/ClicksTest.php, mailpoet/tests/integration/Statistics/Track/OpensTest.php, mailpoet/tests/integration/Subscribers/ImportExport/PersonalDataExporters/NewslettersExporterTest.php
This PR removes usages from test classes and then deprecates the following models:
- MailPoet\Models\DynamicSegmentFilter: simply deprecated as it was already not being used.
- MailPoet\Models\StatisticsClicks: calls in the test classes replaced with Doctrine code and model deprecated.
- MailPoet\Models\StatisticsOpens: calls in the test classes replaced with Doctrine code and model deprecated.
- MailPoet\Models\StatisticsWooCommercePurchases: calls in the test classes replaced with Doctrine code and model deprecated.
This PR is the first in a few that I plan to create to deprecate all the models that are used only in the tests and are listed in the ticket [MAILPOET-4150]. I'm opting to split this ticket into multiple PRs to make reviewing the code changes easier.
[MAILPOET-4150] …
=> Deprecate some Paris models [MAILPOET-4150]

mailpoet/lib/API/JSON/v1/Newsletters.php, mailpoet/lib/API/JSON/v1/SendingQueue.php, mailpoet/lib/DI/ContainerConfigurator.php, mailpoet/lib/Newsletter/NewsletterValidator.php, mailpoet/lib/Newsletter/Validator.php, mailpoet/tasks/phpstan/phpstan-7-baseline.neon, mailpoet/tasks/phpstan/phpstan-8-baseline.neon, mailpoet/tasks/phpstan/phpstan-8.1-baseline.neon, mailpoet/tests/DataFactories/Newsletter.php, mailpoet/tests/integration/API/JSON/v1/NewslettersTest.php, mailpoet/tests/integration/API/JSON/v1/SendingQueueTest.php, mailpoet/tests/integration/Newsletter/NewsletterValidatorTest.php, mailpoet/tests/integration/_bootstrap.php
This PR prevents a user from activating an automatic email (e.g. Welcome emails, post notification emails) from the email listing page if the newsletter is not valid for some reason. These reasons include:
1. There is no content
2. Emails are set to be sent through MSS and the newsletter does not include an unsubscribe link or URL
3. It is a re-engagement email and it doesn't include the `[link:subscription_re_engage_url]` shortcode
4. It is a re-engagement email and click tracking is disabled
5. It is a post notification email and it doesn't include an "Automated Latest Content" widget
Currently we are not checking for any of these things when toggling the status of a newsletter on a listing page like the following:
I decided to extract validation into its own service so that we can be …
=> [MAILPOET-4236] Prevent activation of invalid automatic newsletters

mailpoet/lib/Form/Block/Text.php, mailpoet/tests/integration/Subscription/ManageSubscriptionFormRendererTest.php
[Here](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#browser_compatibility) is a list of supported browsers.
The main issue was not working autocomplete for the email field when a form does not contain other text fields.
How to test
1. Create a form with the email field only
2. Disable Chrome browser extensions that can affect native autocomplete as 1Password
3. Visit a page with the form and test the autocomplete functionality
[MAILPOET-4284]
[MAILPOET-4284]: https://mailpoet.atlassian.net/browse/MAILPOET-4284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add autocomplete attribute for text inputs in forms [MAILPOET-4284]

.circleci/config.yml, .circleci/mailpoet_php.ini, README.md, do, mailpoet/.env.sample, mailpoet/RoboFile.php, mailpoet/lib/Segments/WooCommerce.php, mailpoet/tests/acceptance/Forms/GutenbergFormBlockCest.php, mailpoet/tests/acceptance/Forms/SubscribeToMultipleListsCest.php, mailpoet/tests/acceptance/Forms/SubscriptionFormCest.php, mailpoet/tests/docker/codeception/docker-entrypoint.sh, mailpoet/tests/docker/docker-compose.override.macos-sample.yml, mailpoet/tests/docker/docker-compose.yml, mailpoet/tests/integration/API/JSON/v1/AutomatedLatestContentTest.php, mailpoet/tests/integration/Cron/CronHelperTest.php, mailpoet/tests/integration/_bootstrap.php
Uses the setup and the docker image used to run acceptance tests to run integration tests for single and multi-site installs as well. In doing so the Robofile is adjusted, some failing tests have been fixed, new docker images have been generated and used, the docker-compose config is adjusted and CircleCI config has been update.
- Make sure the tests pass for on CI for single and multi-site
- Verify the Xdebug debugging experience is acceptable by following the setup description added to the README.md file
[MAILPOET-4251]
[MAILPOET-4251]: https://mailpoet.atlassian.net/browse/MAILPOET-4251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adjust used Docker container to run integration tests [MAILPOET-4251]

mailpoet/assets/js/src/form_editor/store/store.ts
[MAILPOET-4381]
**Testing:**
1. Install production's build (you can delete the existing MailPoet plugin and search plugins for MailPoet to install it
2. Create a new form and in editor click to preview it as `below pages` (check below screenshot as example)
2. Save the form and go back to Forms
3. Install the build from this PR
4. Go to edit the same form, it should not crash, and in the preview screen the `below pages` option should be pre-checked.
[MAILPOET-4381]: https://mailpoet.atlassian.net/browse/MAILPOET-4381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix form editor crash with old "below_post" value [MAILPOET-4381]

mailpoet/lib/CustomFields/CustomFieldsRepository.php, mailpoet/lib/Subscribers/ImportExport/ImportExportFactory.php, mailpoet/tests/DataFactories/CustomField.php, mailpoet/tests/integration/Subscribers/ImportExport/ImportExportFactoryTest.php
This PR removes all Paris code from the classes ImportExportFactory and ImportExportFactoryTest and replaces it with Doctrine code. In the process, it was necessary to create a new CustomFieldsRepository::findAllAsArray() method to replace CustomField::findArray(). I'm unsure if the way that I implemented CustomFieldsRepository::findAllAsArray() is the best way as I don't have much experience with Doctrine.
[MAILPOET-4139]
[MAILPOET-4139]: https://mailpoet.atlassian.net/browse/MAILPOET-4139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Go to MailPoet > Subscribers
2. Please test Import/Export, it should work as expected... this PR touches the whole import/export process
=> Refactor ImportExportFactory to Doctrine [MAILPOET-4139]

mailpoet/lib/Segments/WP.php, mailpoet/lib/Segments/WooCommerce.php, mailpoet/lib/Subscribers/ImportExport/Import/Import.php, mailpoet/tests/integration/Segments/DynamicSegments/DynamicSegmentFilterRepositoryTest.php, mailpoet/tests/integration/Segments/SegmentSaveControllerTest.php, mailpoet/tests/integration/Segments/SegmentsSimpleListRepositoryTest.php, mailpoet/tests/integration/Segments/WPTest.php, mailpoet/tests/integration/Segments/WPTestUser.php, mailpoet/tests/integration/Segments/WooCommerceTest.php
Testing instructions for GlobalStep:
1. Go to MailPoet > Lists > Segment tab
2. Please perform some testing around segments to ensure there are no issues
---- 
This continues the work from https://github.com/mailpoet/mailpoet/pull/4138
It can be merged separately.
This PR removes some of the following PHPStan level 6 errors from MailPoet\Segments:
To test you can modify the level6 exclusion rule on phpstan.neon file to this:
- '/(Method|Property|Function) (?!(MailPoet\\Automation\\)|(MailPoet\\Segments\\)|(MailPoet\\Test\\Segments\\)).*has no (return )?type specified/'
- '/(Method|Function) (?!(MailPoet\\Automation\\)|(MailPoet\\Segments\\)|(MailPoet\\Test\\Segments\\)).*has parameter (\$[_A-Z]{1}[_a-z]+)? with no type (specified)?/i'
run `./do qa:phpstan` and check that the committed …
=> Remove some PHPStan Level 6 errors - 2

mailpoet/lib/Segments/DynamicSegments/DynamicSegmentsListingRepository.php, mailpoet/lib/Segments/DynamicSegments/FilterFactory.php, mailpoet/lib/Segments/DynamicSegments/Filters/EmailAction.php, mailpoet/lib/Segments/DynamicSegments/Filters/WooCommerceCategory.php, mailpoet/lib/Segments/SegmentsRepository.php, mailpoet/tests/integration/Segments/DynamicSegments/FilterHandlerTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/EmailActionClickAnyTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/EmailActionTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/EmailOpensAbsoluteCountActionTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/MailPoetCustomFieldsTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/SubscriberScoreTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/SubscriberSegmentTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/SubscriberSubscribedDateTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/UserRoleTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/WooCommerceCategoryTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/WooCommerceCountryTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/WooCommerceNumberOfOrdersTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/WooCommerceProductTest.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/WooCommerceSubscriptionTest.php, mailpoet/tests/integration/Segments/DynamicSegments/SegmentSaveControllerTest.php, mailpoet/tests/integration/Segments/SegmentsRepositoryTest.php, mailpoet/tests/unit/Segments/DynamicSegments/FilterDataMapperTest.php
This PR removes the following PHPStan level 6 errors from `MailPoet\Segments\DynamicSegments` (first and second commit) and from `MailPoet\Segments\SegmentsRepository` (third commit)
```
(Method|Property|Function) has no (return )?type specified.
(Method|Function) has parameter with no type (specified)
```
To test you can modify the level6 exclusion rule on phpstan.neon file to this:
```
- '/(Method|Property|Function) (?!(MailPoet\\Automation\\)|(MailPoet\\Segments\\DynamicSegments\\)|(MailPoet\\Segments\\SegmentsRepository)).*has no (return )?type specified/'
- '/(Method|Function) (?!(MailPoet\\Automation\\)|(MailPoet\\Segments\\DynamicSegments\\)|(MailPoet\\Segments\\SegmentsRepository)).*has parameter (\$[_A-Z]{1}[_a-z]+)? with no type (specified)?/i'
```
and run `./do qa:phpstan` …
=> Remove some PHPStan Level 6 errors

mailpoet/lib/Subscribers/ImportExport/Import/Import.php, mailpoet/lib/Subscribers/ImportExport/Import/MailChimp.php, mailpoet/tests/integration/Subscribers/ImportExport/Import/ImportTest.php, mailpoet/tests/integration/Subscribers/ImportExport/Import/MailChimpTest.php
This continues the work from https://github.com/mailpoet/mailpoet/pull/4141 and https://github.com/mailpoet/mailpoet/pull/4138
It can be merged separately.
This PR removes some of the following PHPStan level 6 errors from Subscribers\ImportExport\Import:
To test you can modify the level6 exclusion rule on phpstan.neon file to this:
```
- '/(Method|Property|Function) (?!(MailPoet\\Automation\\)|(MailPoet\\Test\\Subscribers\\ImportExport\\Import\\)|(MailPoet\\Subscribers\\ImportExport\\Import\\)).*has no (return )?type specified/'
- '/(Method|Function) (?!(MailPoet\\Automation\\)|(MailPoet\\Subscribers\\ImportExport\\Import\\)|(MailPoet\\Test\\Subscribers\\ImportExport\\Import\\)).*has parameter (\$[_A-Z]{1}[_a-z]+)? with no type (specified)?/i'
```
run ./do qa:phpstan and check there are …
=> Remove some PHPStan Level 6 errors - 3

mailpoet/tests/integration/Mailer/Methods/AmazonSESTest.php
We need to prevent sending from CI so that we are not blocked on AWS. We will revert
this commit when we find a proper fix.
[MAILPOET-4394]
[MAILPOET-4394]: https://mailpoet.atlassian.net/browse/MAILPOET-4394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Temporarily removing test that sends emails to AWS

mailpoet/tests/integration/AutomaticEmails/WooCommerce/Events/AbandonedCartTest.php
This PR fixes the flaky test errors on AbandonedCartTest when checking the scheduled time:
```
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'2022-05-02 16:13:24'
+'2022-05-02 16:13:25'
```
If you want to reproduce the test errors locally, you can add a `sleep(5);` after [$abandonedCartEmail->init();](https://github.com/mailpoet/mailpoet/blob/75eb7f6900dac5865f58b6040246106e8a516af2/mailpoet/tests/integration/AutomaticEmails/WooCommerce/Events/AbandonedCartTest.php#L167) on any test in the file that checks the scheduled time.
The PR changes the test so that `AutomaticEmailScheduler` uses the mocked `currentTime`
[MAILPOET-4286]
[MAILPOET-4286]: https://mailpoet.atlassian.net/browse/MAILPOET-4286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
=> Fix flaky integration test AbandonedCartTest

mailpoet/lib/Mailer/Methods/SMTP.php, mailpoet/tests/integration/Mailer/Methods/SMTPTest.php
[MAILPOET-4398]
[MAILPOET-4398]: https://mailpoet.atlassian.net/browse/MAILPOET-4398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Go to MailPoet > Settings > Send with and set custom sending method (SMTP) and save it
2. Send a newsletter and make sure it has been sent
3. Subscribe to a form and make sure you have received confirmation email
=> Fix condition for authentication [MAILPOET-4398]

mailpoet/lib/API/JSON/v1/ImportExport.php, mailpoet/lib/API/JSON/v1/Subscribers.php, mailpoet/lib/Subscribers/SubscriberSaveController.php, mailpoet/tests/integration/API/JSON/v1/SubscribersTest.php, mailpoet/tests/integration/Subscribers/SubscriberSaveControllerTest.php
With this PR, it throws an exception and displays a friendlier message if the new email already exists.
To test:
- Go to MailPoet>Subscribers>Edit a subscriber
- Enter an email that already exists and click save
- Check you see the message: `A subscriber with E-mail '{$email}' already exists.` instead of the DB exception
When working on this issue I found a tiny bug and fixed it:
To test:
- Go to MailPoet>Subscribers>Import>Proceed>Paste data
- Enter data for 1 subscriber `mary@jane.com, mary, jane` (doesn't really matter) click next.
- Click on 'Create a new list', enter the name of a list that already exists.
- Check that instead of seeing `An unknown error has occurred` you see `Another record already exists. Please specify a different "name".`
[MAILPOET-4259]
[MAILPOET-4259]: …
=> Verify that new email is unique when editing a subscriber MAILPOET-4259

mailpoet/lib/Segments/WP.php, mailpoet/tests/integration/Segments/WPTest.php
Fixes [MAILPOET-4241]
Source of the reported problem in MAILPOET-4241 can be found here:
https://github.com/WordPress/WordPress/blob/f6412575c890bf651cdaa8a2d60365c19f0d4173/wp-includes/default-filters.php#L21-L25
[MAILPOET-4241]: https://mailpoet.atlassian.net/browse/MAILPOET-4241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Add a new WordPress user and make sure in the first name you've added & symbol (check Jira for more info)
2. Check in MailPoet > Subscribers how the name has shown
3. Check when receiving a newsletter with added `Hi [subscriber:firstname | default:Subscriber]` in the title or somewhere in the newsletter content
=> HTML entities in WP_User properties MAILPOET-4241

mailpoet/lib/Mailer/MailerFactory.php, mailpoet/lib/Mailer/Methods/AmazonSES.php, mailpoet/tests/integration/Mailer/Methods/AmazonSESTest.php, mailpoet/tests/integration/_bootstrap.php
Currently .env variables are not picked up for integration tests, this PR enables this.
[MAILPOET-4394]
[MAILPOET-4394]: https://mailpoet.atlassian.net/browse/MAILPOET-4394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Stop integration test from sending real email via AmazonSES MAILPOET-4394

mailpoet/tests/acceptance/Misc/SwitchingLanguagesCest.php
[MAILPOET-4147](https://mailpoet.atlassian.net/browse/MAILPOET-4147)
[MAILPOET-4604]
Please don't mind I used different languages from the Jira specs. In case we must use Japanese, Portuguese please let me know. I used French (Canada), German and Greek instead.
[MAILPOET-4604]: https://mailpoet.atlassian.net/browse/MAILPOET-4604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> E2E Acceptance - New test switching languages
