tests/acceptance/CreateNewWordPressUserCest.php
[MAILPOET-3179](https://mailpoet.atlassian.net/browse/MAILPOET-3179)
=> Fixed scenario for checking default list on multisite [MAILPOET-3179]

tests/_support/IntegrationTester.php, tests/integration/API/JSON/v1/SubscribersTest.php, tests/integration/DynamicSegments/Filters/UserRoleTest.php, tests/integration/DynamicSegments/Persistence/Loading/SubscribersCountTest.php, tests/integration/Models/SubscribersInDynamicSegmentTest.php, tests/integration/Segments/DynamicSegments/Filters/UserRoleTest.php, tests/integration/Segments/SegmentSubscribersRepositoryTest.php, tests/integration/Subscribers/SubscriberListingRepositoryTest.php, tests/integration/_bootstrap.php
[MAILPOET-3077]
[MAILPOET-3077]: https://mailpoet.atlassian.net/browse/MAILPOET-3077
=> Fix multisite integration tests

.circleci/config.yml, RoboFile.php, composer.json, composer.lock, lib/Util/Notices/PHPVersionWarnings.php, mailpoet-cron.php, mailpoet.php, prefixer/composer.json, prefixer/composer.lock, readme.txt, tests/integration/Util/Notices/PHPVersionWarningsTest.php
[MAILPOET-3144]
[MAILPOET-3144]: https://mailpoet.atlassian.net/browse/MAILPOET-3144
=> Drop php 7.0 [MAILPOET-3144]

lib/Newsletter/NewslettersRepository.php
[MAILPOET-3183]
[MAILPOET-3183]: https://mailpoet.atlassian.net/browse/MAILPOET-3183
=> Add a log for trashing newsletters [MAILPOET-3183]

mailpoet.php
[MAILPOET-3176]
[MAILPOET-3176]: https://mailpoet.atlassian.net/browse/MAILPOET-3176
=> Update supported WordPress version

assets/js/src/form_editor/form_preview.ts
[MAILPOET-3175]
[MAILPOET-3175]: https://mailpoet.atlassian.net/browse/MAILPOET-3175
=> Forbid animation in preview while changing form width [MAILPOET-3175]

tests/acceptance/ManageListsCest.php, tests/acceptance/SettingsPageBasicsCest.php
[MAILPOET-3188](https://mailpoet.atlassian.net/browse/MAILPOET-3188)
=> Fix two flaky tests in acceptance [MAILPOET-3188]

lib/AdminPages/Pages/FormEditor.php
[MAILPOET-3187]
[MAILPOET-3187]: https://mailpoet.atlassian.net/browse/MAILPOET-3187
=> Prevent loading whole posts on form editor page [MAILPOET-3187]

lib/Form/Templates/Templates/Template10BelowPages.php, lib/Form/Templates/Templates/Template10Popup.php, lib/Form/Templates/Templates/Template10SlideIn.php, lib/Form/Templates/Templates/Template10Widget.php, lib/Form/Templates/Templates/Template1FixedBar.php, lib/Form/Templates/Templates/Template1Popup.php, lib/Form/Templates/Templates/Template1SlideIn.php, lib/Form/Templates/Templates/Template1Widget.php
[MAILPOET-3156]
[MAILPOET-3156]: https://mailpoet.atlassian.net/browse/MAILPOET-3156
=> Unify privacy policy label text in form templates [MAILPOET-3156]

.eslintrc.es5.json, .eslintrc.es6.json, .eslintrc.ts.json, CONTRIBUTING.md
[MAILPOET-3172]
[MAILPOET-3172]: https://mailpoet.atlassian.net/browse/MAILPOET-3172
=> Disable rule import/prefer-default-export [MAILPOET-3172]

lib/API/JSON/ResponseBuilders/FormsResponseBuilder.php, lib/API/JSON/v1/Forms.php, lib/DI/ContainerConfigurator.php, tests/integration/API/JSON/ResponseBuilders/FormsResponseBuilderTest.php
[MAILPOET-3035]
[MAILPOET-3035]: https://mailpoet.atlassian.net/browse/MAILPOET-3035
=> Forms::get() API refactored to Doctrine [MAILPOET-3035]

assets/js/src/newsletter_editor/behaviors/MediaManagerBehavior.js
[MAILPOET-3028]
[MAILPOET-3028]: https://mailpoet.atlassian.net/browse/MAILPOET-3028
=> Add debounce for image url input [MAILPOET-3028]

lib/API/JSON/ResponseBuilders/SegmentsResponseBuilder.php, lib/API/JSON/v1/Segments.php, lib/DI/ContainerConfigurator.php, tests/integration/API/JSON/ResponseBuilders/SegmentsResponseBuilderTest.php
[MAILPOET-3166]
[MAILPOET-3166]: https://mailpoet.atlassian.net/browse/MAILPOET-3166
=> Refactor Segment::get() to Doctrine [MAILPOET-3166]

views/layout.html, views/newsletters.html
[MAILPOET-3101]
[MAILPOET-3101]: https://mailpoet.atlassian.net/browse/MAILPOET-3101
=> Move Satismeter's translations to the main layout template [MAILPOET-3101]

lib/API/JSON/v1/Forms.php, lib/DI/ContainerConfigurator.php, lib/Doctrine/EntityManagerFactory.php, lib/Doctrine/EventListeners/EmojiEncodingListener.php, lib/Form/Templates/Templates/Template1FixedBar.php, lib/Form/Templates/Templates/Template7BelowPages.php, lib/Form/Templates/Templates/Template7FixedBar.php, lib/Form/Templates/Templates/Template7Popup.php, lib/Form/Templates/Templates/Template7SlideIn.php, lib/Form/Templates/Templates/Template7Widget.php, lib/WP/Emoji.php, tests/integration/Doctrine/EventListeners/EmojiEncodingListenerTest.php, tests/integration/Doctrine/EventListeners/TimestampListenerTest.php, tests/integration/Doctrine/EventListeners/ValidationTest.php, tests/integration/Doctrine/Types/JsonTypesTest.php
[MAILPOET-3196]
[MAILPOET-3196]: https://mailpoet.atlassian.net/browse/MAILPOET-3196
=> Fix emojis in forms [MAILPOET-3196]

assets/js/src/form_editor/form_preview.ts
[MAILPOET-3191]
[MAILPOET-3191]: https://mailpoet.atlassian.net/browse/MAILPOET-3191
=> Replay animation only when changing form position or animation type [MAILPOET-3191]

tests/acceptance/SaveNotificationAsDraftCest.php
[MAILPOET-3202](https://mailpoet.atlassian.net/browse/MAILPOET-3202)
=> Fixed flaky scenario saveNotificationAsDraft [MAILPOET-3202]

views/subscribers/importExport/import.html
[MAILPOET-3181]
[MAILPOET-3181]: https://mailpoet.atlassian.net/browse/MAILPOET-3181
=> Better explain import options [MAILPOET-3181]

RoboFile.php, tasks/release/GitHubController.php, tasks/release/JiraController.php, tasks/release/ReleaseVersionController.php
[MAILPOET-3152]
[MAILPOET-3152]: https://mailpoet.atlassian.net/browse/MAILPOET-3152
=> Match free and premium versions [MAILPOET-3152]

.circleci/config.yml
[MAILPOET-3194]
[MAILPOET-3194]: https://mailpoet.atlassian.net/browse/MAILPOET-3194
=> Update the oldest image with PHP 7.1 [MAILPOET-3194]

lib/Subscription/Pages.php
[MAILPOET-2958]
[MAILPOET-2958]: https://mailpoet.atlassian.net/browse/MAILPOET-2958
=> Fix duplicate title when subscriber not found [MAILPOET-2958]

RoboFile.php, tasks/release/JiraController.php, tasks/release/ReleaseVersionController.php
[PREMIUM-147]
[PREMIUM-147]: https://mailpoet.atlassian.net/browse/PREMIUM-147
=> Change getting next release version [PREMIUM-147]

assets/js/src/listing/listing.jsx, assets/js/src/listing/listing_item.jsx, assets/js/src/listing/listing_items.jsx, assets/js/src/subscribers/list.jsx, lib/API/JSON/v1/Subscribers.php, lib/Segments/WP.php, lib/Segments/WooCommerce.php, lib/Subscribers/SubscribersRepository.php, tests/integration/Segments/WPTest.php, tests/integration/Segments/WooCommerceTest.php, tests/integration/Subscribers/SubscribersRepositoryTest.php
[MAILPOET-3138]
[MAILPOET-3138]: https://mailpoet.atlassian.net/browse/MAILPOET-3138
=> Permit trashing of WP User subscribers [MAILPOET-3138]

build.sh, lib/Cron/Workers/Beamer.php, lib/Cron/Workers/SendingQueue/SendingQueue.php, lib/Logging/LogHandler.php, lib/Newsletter/NewsletterSaveController.php, lib/Twig/Functions.php, prefixer/composer.json, prefixer/composer.lock, prefixer/fix-carbon.php, tests/integration/Cron/Workers/SchedulerTest.php, tests/integration/Logging/LogHandlerTest.php, tests/integration/Newsletter/Blocks/AbandonedCartContentTest.php, tests/integration/Subscription/PagesTest.php, tools/install.php
[MAILPOET-3232]
[MAILPOET-3232]: https://mailpoet.atlassian.net/browse/MAILPOET-3232
=> Update carbon [MAILPOET-3232]

tests/acceptance.suite.yml, tests/acceptance/ManageSubscriptionLinkCest.php, tests/acceptance/_bootstrap.php
[MAILPOET-3092]
[MAILPOET-3092]: https://mailpoet.atlassian.net/browse/MAILPOET-3092
=> Increase acceptance tests timeouts [MAILPOET-3092]

tests/integration/Cron/CronHelperTest.php
[MAILPOET-3232]
[MAILPOET-3232]: https://mailpoet.atlassian.net/browse/MAILPOET-3232
=> Fix integration tests for multisite [MAILPOET-3203]

build.sh, lib/DI/ContainerConfigurator.php, prefixer/composer.json, prefixer/composer.lock, prefixer/fix-symfony-di.php, tests/integration/Newsletter/Blocks/AutomatedLatestContentBlockTest.php
[MAILPOET-3239]
[MAILPOET-3239]: https://mailpoet.atlassian.net/browse/MAILPOET-3239
=> Update symfony/dependency-injection [MAILPOET-3239]

assets/js/src/form_editor/components/editor.jsx
[MAILPOET-3211]
[MAILPOET-3211]: https://mailpoet.atlassian.net/browse/MAILPOET-3211
=> Fix missing custom colour option in form editor [MAILPOET-3211]

lib/AdminPages/Pages/Newsletters.php, lib/AutomaticEmails/WooCommerce/Events/FirstPurchase.php, lib/AutomaticEmails/WooCommerce/Events/PurchasedInCategory.php, lib/AutomaticEmails/WooCommerce/Events/PurchasedProduct.php, lib/DI/ContainerConfigurator.php, lib/Entities/ScheduledTaskEntity.php, lib/Models/Newsletter.php, lib/Newsletter/AutomaticEmailsRepository.php, tasks/phpstan/phpstan-baseline-integration-tests.neon, tests/integration/AutomaticEmails/WooCommerce/Events/PurchasedInCategoryTest.php, tests/integration/AutomaticEmails/WooCommerce/Events/PurchasedProductTest.php
[MAILPOET-2335] [MAILPOET-2334]
[MAILPOET-2335]: https://mailpoet.atlassian.net/browse/MAILPOET-2335
[MAILPOET-2334]: https://mailpoet.atlassian.net/browse/MAILPOET-2334
=> Change purchased product trigger [MAILPOET-2335] [MAILPOET-2334]

tests/acceptance.suite.yml
Trying to fix this error: https://app.circleci.com/pipelines/github/mailpoet/mailpoet/4879/workflows/6b9cd12d-0f0d-4eb2-8c98-3b9025e5e5c1/jobs/103026
=> Remove pageload timeout

assets/js/src/form/fields/selection.jsx, assets/js/src/segments/dynamic_segments_filters/email.jsx
[MAILPOET-3193]
[MAILPOET-3193]: https://mailpoet.atlassian.net/browse/MAILPOET-3193
=> Fix segments updating [MAILPOET-3193]

assets/css/src/components-form-editor/_template-selection.scss
[MAILPOET-3213]
[MAILPOET-3213]: https://mailpoet.atlassian.net/browse/MAILPOET-3213
=> Add space to the bottom of form template list [MAILPOET-3213]

tests/acceptance/EditorSocialBlockCest.php
[MAILPOET-3251](https://mailpoet.atlassian.net/browse/MAILPOET-3251)
=> Fix flaky scenario addSocialBlock [MAILPOET-3251]

assets/css/src/components-form-editor/_form-placement.scss, assets/css/src/mailpoet-form-editor.scss
[MAILPOET-3161]
[MAILPOET-3161]: https://mailpoet.atlassian.net/browse/MAILPOET-3161
=> Change font-size for select2 in forms [MAILPOET-3161]

tests/acceptance/EditorSpacerBlockCest.php
[MAILPOET-3250](https://mailpoet.atlassian.net/browse/MAILPOET-3250)
=> Fix flaky scenario addSpacer [MAILPOET-3250]

tests/acceptance/EditorHeaderBlockCest.php
[MAILPOET-3216](https://mailpoet.atlassian.net/browse/MAILPOET-3216)
=> Fix flaky scenario addHeader [MAILPOET-3216]

lib/API/JSON/ResponseBuilders/NewslettersResponseBuilder.php, lib/API/JSON/v1/Newsletters.php, lib/DI/ContainerConfigurator.php, lib/Entities/NewsletterEntity.php, lib/Entities/NewsletterOptionFieldEntity.php, lib/Newsletter/NewsletterSaveController.php, lib/Newsletter/NewslettersRepository.php, lib/Newsletter/Scheduler/PostNotificationScheduler.php, lib/Util/Security.php, tasks/phpstan/phpstan-baseline-integration-tests.neon, tests/integration/API/JSON/ResponseBuilders/NewslettersResponseBuilderTest.php, tests/integration/API/JSON/v1/NewslettersTest.php, tests/integration/Entities/NewsletterEntityTest.php, tests/integration/Newsletter/NewsletterSaveControllerTest.php, tests/integration/Newsletter/Scheduler/PostNotificationTest.php
[MAILPOET-2946]
[MAILPOET-2946]: https://mailpoet.atlassian.net/browse/MAILPOET-2946
=> Rewrite remaining Newsletter-editing endpoints to Doctrine [MAILPOET-2946]

assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/below_posts_settings.tsx
[MAILPOET-3159]
[MAILPOET-3159]: https://mailpoet.atlassian.net/browse/MAILPOET-3159
=> Add a description for a form of type Bellow pages [MAILPOET-3159]

assets/css/src/components-form-editor/_preview.scss
[MAILPOET-3163]
[MAILPOET-3163]: https://mailpoet.atlassian.net/browse/MAILPOET-3163
=> Make scrollable sidebar in the preview screen [MAILPOET-3163]

lib/Subscribers/SubscriberListingRepository.php, tests/integration/Subscribers/SubscriberListingRepositoryTest.php
[MAILPOET-3197]
[MAILPOET-3197]: https://mailpoet.atlassian.net/browse/MAILPOET-3197
=> Fix filtering subscribers without a segment [MAILPOET-3197]

assets/css/src/components-form-editor/_template-selection.scss, assets/js/src/form_editor/templates/selection.tsx, tests/acceptance/FormEditorCreateBlankFormCest.php, views/form/template_selection.html
[MAILPOET-3207]
[MAILPOET-3207]: https://mailpoet.atlassian.net/browse/MAILPOET-3207
=> Add create blank form option to form template selection [MAILPOET-3207]

assets/js/src/form_editor/components/editor.jsx, assets/js/src/form_editor/components/sidebar/sidebar_header.tsx
[MAILPOET-2794]
[MAILPOET-2794]: https://mailpoet.atlassian.net/browse/MAILPOET-2794
=> Improvement useability on small devices [MAILPOET-2794]

assets/css/src/components-form-editor/_header.scss, assets/js/src/form_editor/components/editor.jsx, assets/js/src/form_editor/components/feature_toggle.tsx, assets/js/src/form_editor/components/fullscreen.tsx, assets/js/src/form_editor/components/header.jsx, assets/js/src/form_editor/store/actions.ts, assets/js/src/form_editor/store/reducer.jsx, assets/js/src/form_editor/store/reducers/toggle_fullscreen.ts, assets/js/src/form_editor/store/selectors.jsx, assets/js/src/form_editor/store/store.jsx
[MAILPOET-3205]
[MAILPOET-3205]: https://mailpoet.atlassian.net/browse/MAILPOET-3205
=> Enable full screen mode [MAILPOET-3205]

assets/js/src/forms/list.jsx, tests/acceptance/FormsListingCest.php
[MAILPOET-3272](https://mailpoet.atlassian.net/browse/MAILPOET-3272)
=> Update scenario to cover form new button [MAILPOET-3272]

.circleci/config.yml, .gitignore, RoboFile.php, lib/Config/Migrator.php, lib/Entities/NewsletterEntity.php, lib/Entities/NewsletterTemplateEntity.php, lib/Entities/ScheduledTaskEntity.php, lib/Entities/SendingQueueEntity.php, lib/Entities/SubscriberEntity.php, tasks/phpstan/bootstrap.php, tasks/phpstan/phpstan-tests.neon, tasks/phpstan/phpstan-wp-source.neon, tasks/phpstan/phpstan.neon, tests/integration/Config/RendererTest.php, tests/unit/_bootstrap.php
[MAILPOET-3029]
[MAILPOET-3029]: https://mailpoet.atlassian.net/browse/MAILPOET-3029
=> PHPStan static reflection [MAILPOET-3029]

lib/API/JSON/v1/Segments.php, lib/API/JSON/v1/Subscribers.php, lib/Config/Hooks.php, lib/Config/Populator.php, lib/DI/ContainerConfigurator.php, lib/Entities/NewsletterEntity.php, lib/Newsletter/Scheduler/WelcomeScheduler.php, lib/Newsletter/Sending/ScheduledTasksRepository.php, lib/Segments/SegmentsRepository.php, lib/Segments/WP.php, lib/Segments/WooCommerce.php, tests/integration/API/JSON/v1/SetupTest.php, tests/integration/API/JSON/v1/SubscribersTest.php, tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php, tests/integration/Cron/Workers/SendingQueue/Tasks/MailerTest.php, tests/integration/Newsletter/Scheduler/WelcomeTest.php, tests/integration/Newsletter/ShortcodesTest.php, tests/integration/Segments/WPTest.php, tests/integration/Subscription/UrlTest.php, tests/integration/WooCommerce/SubscriptionTest.php
Sorry for such a big PR. I believe that going through commit by commit should be ok.
[MAILPOET-3141]
[MAILPOET-3141]: https://mailpoet.atlassian.net/browse/MAILPOET-3141
=> Synchronise WP users to disabled WP Segment [MAILPOET-3141] 

assets/js/src/settings/pages/basics/unsubscribe_page.tsx, tests/acceptance/SettingsSubscriptionPageCest.php, tests/acceptance/SettingsUnsubscribePageCest.php
[MAILPOET-3283](https://mailpoet.atlassian.net/browse/MAILPOET-3283)
=> Added new scenarios for custom unsubscribe pages [MAILPOET-3283]

assets/js/src/newsletters/automatic_emails/listings.jsx, assets/js/src/newsletters/listings/notification.jsx, assets/js/src/newsletters/listings/standard.jsx, assets/js/src/newsletters/listings/welcome.jsx, assets/js/src/newsletters/types.jsx
[MAILPOET-3266]
[MAILPOET-3266]: https://mailpoet.atlassian.net/browse/MAILPOET-3266
=> Fix spacing on listing when no emails are present (not even in trash) [MAILPOET-3266]

assets/css/src/components/_categories.scss, assets/js/src/newsletters/campaign_stats/newsletter_stats_info.tsx, assets/js/src/newsletters/listings/queue_status.jsx
[MAILPOET-3277]
[MAILPOET-3277]: https://mailpoet.atlassian.net/browse/MAILPOET-3277
=> Redesign safari fixes [MAILPOET-3277]

lib/AdminPages/Pages/NewsletterEditor.php, lib/Cron/Workers/SendingQueue/Tasks/Newsletter.php, lib/Cron/Workers/SendingQueue/Tasks/Shortcodes.php, lib/DI/ContainerConfigurator.php, lib/Doctrine/Repository.php, lib/Entities/SubscriberEntity.php, lib/Newsletter/Links/Links.php, lib/Newsletter/Preview/SendPreviewController.php, lib/Newsletter/Shortcodes/Categories/CategoryInterface.php, lib/Newsletter/Shortcodes/Categories/Date.php, lib/Newsletter/Shortcodes/Categories/Link.php, lib/Newsletter/Shortcodes/Categories/Newsletter.php, lib/Newsletter/Shortcodes/Categories/Subscriber.php, lib/Newsletter/Shortcodes/Shortcodes.php, lib/Newsletter/Shortcodes/ShortcodesHelper.php, lib/Newsletter/ViewInBrowser/ViewInBrowserRenderer.php, lib/Router/Endpoints/Track.php, lib/Statistics/Track/Clicks.php, lib/Statistics/Track/Opens.php, tests/integration/Cron/Workers/SendingQueue/Tasks/ShortcodesTest.php, tests/integration/Newsletter/Preview/SendPreviewControllerTest.php, tests/integration/Newsletter/ShortcodesHelperTest.php, tests/integration/Newsletter/ShortcodesTest.php, tests/integration/Newsletter/ViewInBrowser/ViewInBrowserRendererTest.php, tests/integration/Router/Endpoints/TrackTest.php, tests/integration/Statistics/Track/ClicksTest.php, tests/integration/Statistics/Track/OpensTest.php
[MAILPOET-2993]
[MAILPOET-2993]: https://mailpoet.atlassian.net/browse/MAILPOET-2993
=> Shortcodes to Doctrine [MAILPOET-2993]

tests/acceptance/EditorHeaderBlockCest.php
[MAILPOET-3233](https://mailpoet.atlassian.net/browse/MAILPOET-3233)
=> Fixed flaky scenario addHeader [MAILPOET-3233]

assets/css/src/components-editor/components/_heading.scss, assets/css/src/components/_steps.scss, assets/js/src/common/steps/content_wrapper_fix.tsx, assets/js/src/common/steps/steps.tsx, webpack.config.js
[MAILPOET-3257]
[MAILPOET-3257]: https://mailpoet.atlassian.net/browse/MAILPOET-3257
=> Always have <Steps> component on top of the page and notices below [MAILPOET-3257]

assets/css/src/components-public/_public.scss, assets/js/src/public.jsx, lib/Form/Util/Styles.php
[MAILPOET-3195]
[MAILPOET-3195]: https://mailpoet.atlassian.net/browse/MAILPOET-3195
=> Improve success message design [MAILPOET-3195]

assets/js/src/common/listings/newsletter_status.tsx
[MAILPOET-3256]
[MAILPOET-3256]: https://mailpoet.atlassian.net/browse/MAILPOET-3256
=> Format numbers in email status [MAILPOET-3256]

assets/js/src/forms/heading.jsx
[MAILPOET-3249]
[MAILPOET-3249]: https://mailpoet.atlassian.net/browse/MAILPOET-3249
=> Fix listing reload when creating new form [MAILPOET-3249]

assets/css/src/components-plugin/_notice.scss, lib/Util/Notices/BlackFridayNotice.php
[MAILPOET-3289]
[MAILPOET-3289]: https://mailpoet.atlassian.net/browse/MAILPOET-3289
=> Black Friday banner [MAILPOET-3289]

assets/css/src/components-plugin/_newsletter-templates.scss, assets/css/src/components-plugin/_notice.scss, assets/css/src/components/_tabs.scss, assets/css/src/components/_template_box.scss, assets/js/src/newsletters/automatic_emails/listings.jsx, assets/js/src/newsletters/templates/template_box.jsx, assets/js/src/notices/notice.tsx
[MAILPOET-3284]
[MAILPOET-3284]: https://mailpoet.atlassian.net/browse/MAILPOET-3284
=> Redesign UI fixes [MAILPOET-3284]

tests/acceptance/SaveNewsletterAsDraftCest.php, tests/acceptance/SaveNotificationAsDraftCest.php
[MAILPOET-3290](https://mailpoet.atlassian.net/browse/MAILPOET-3290)
=> Update existing save as draft tests to be more precise [MAILPOET-3290]

lib/API/JSON/v1/ImportExport.php, lib/Subscribers/ImportExport/Import/Import.php, tests/integration/Subscribers/ImportExport/Import/ImportTest.php
[MAILPOET-3298]
[MAILPOET-3298]: https://mailpoet.atlassian.net/browse/MAILPOET-3298
=> Fix importing WP users as subscribers [MAILPOET-3298]

assets/css/src/components-editor/_common.scss, assets/css/src/mailpoet-editor.scss
[MAILPOET-3276]
[MAILPOET-3276]: https://mailpoet.atlassian.net/browse/MAILPOET-3276
=> Fix error in email editor overflowing [MAILPOET-3276]

tests/acceptance/FormEditorAddNamesCest.php
[MAILPOET-3299](https://mailpoet.atlassian.net/browse/MAILPOET-3299)
=> Update scenario to cover modifying of the blocks [MAILPOET-3299]

lib/Form/Util/Styles.php
[MAILPOET-3306]
[MAILPOET-3306]: https://mailpoet.atlassian.net/browse/MAILPOET-3306
=> Remove bottom padding from class .mailpoet_message [MAILPOET-3306]

lib/API/JSON/v1/Forms.php, lib/Form/DisplayFormInWPContent.php, tests/unit/Form/DisplayFormInWPContentTest.php
[MAILPOET-3300]
[MAILPOET-3300]: https://mailpoet.atlassian.net/browse/MAILPOET-3300
=> Fix forms displaying on post pages [MAILPOET-3300]

lib/API/JSON/v1/Newsletters.php, lib/Newsletter/NewsletterSaveController.php, tests/integration/Newsletter/NewsletterSaveControllerTest.php
[MAILPOET-3275]
[MAILPOET-3275]: https://mailpoet.atlassian.net/browse/MAILPOET-3275
=> Fix blank newsletter preview [MAILPOET-3275]

assets/css/src/components-plugin/_listing-newsletters.scss, assets/css/src/components-plugin/_listing.scss, assets/css/src/components-plugin/_stats.scss, assets/css/src/components/_tooltips.scss, assets/css/src/generic/_forms-input.scss, assets/css/src/generic/_grid.scss, assets/css/src/generic/_typography.scss, assets/js/src/common/index.ts, assets/js/src/common/listings/newsletter_stats/badge.tsx, assets/js/src/common/listings/newsletter_stats/stats.tsx, assets/js/src/common/remove_wrap_margin/remove_wrap_margin.tsx, assets/js/src/newsletters/campaign_stats/newsletter_general_stats.tsx, assets/js/src/newsletters/campaign_stats/newsletter_stats_info.tsx, assets/js/src/newsletters/campaign_stats/page.tsx, assets/js/src/newsletters/campaign_stats/premium_banner.jsx
[PREMIUM-146]
[PREMIUM-146]: https://mailpoet.atlassian.net/browse/PREMIUM-146
=> Redesign email stats [PREMIUM-146]

assets/js/src/form_editor/blocks/segment_select/edit.jsx, assets/js/src/form_editor/blocks/segment_select/settings.jsx, assets/js/src/form_editor/components/sidebar/default_sidebar.tsx, tests/acceptance/FormEditorAddListSelectionCest.php
[MAILPOET-3309](https://mailpoet.atlassian.net/browse/MAILPOET-3309)
=> Add new testcase for list selection block in form editor [MAILPOET-3309]

tasks/code_sniffer/composer.json, tasks/code_sniffer/composer.lock
[MAILPOET-3192]
[MAILPOET-3192]: https://mailpoet.atlassian.net/browse/MAILPOET-3192
=> Use a replacement for PHP Parallel Linter [MAILPOET-3192]

lib/Newsletter/Shortcodes/Shortcodes.php
[MAILPOET-3312]
[MAILPOET-3312]: https://mailpoet.atlassian.net/browse/MAILPOET-3312
=> Fix some newsletter shortcodes not being interpreted [MAILPOET-3312]

assets/js/src/form_editor/components/editor.jsx, assets/js/src/form_editor/components/form_settings/basic_settings_panel.jsx, assets/js/src/form_editor/components/form_settings/codemirror_wrap.jsx, assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/placement_settings.tsx, assets/js/src/form_editor/components/form_settings/selection.jsx, assets/js/src/form_editor/components/header.jsx, assets/js/src/form_editor/components/history_redo.tsx, assets/js/src/form_editor/components/history_undo.tsx, assets/js/src/form_editor/components/size_settings.tsx, assets/js/src/form_editor/store/actions.ts, assets/js/src/form_editor/store/reducer.jsx, assets/js/src/form_editor/store/reducers/history_record.ts, assets/js/src/form_editor/store/selectors.jsx, assets/js/src/form_editor/store/store.jsx, package.json, tests/acceptance/FormEditorUndoAndRedoCest.php, tests/javascript/form_editor/store/reducers/history_record.spec.js, tests/javascript/form_editor/store/selectors.spec.js
[MAILPOET-3085]
[MAILPOET-3085]: https://mailpoet.atlassian.net/browse/MAILPOET-3085
=> Add undo&redo to the Form editor [MAILPOET-3085]

assets/js/src/newsletters/listings/queue_status.jsx
[MAILPOET-3304]
[MAILPOET-3304]: https://mailpoet.atlassian.net/browse/MAILPOET-3304
=> Correctly parse date in email status [MAILPOET-3304]

assets/js/src/form_editor/blocks/custom_checkbox/custom_field_settings.jsx, assets/js/src/form_editor/blocks/custom_checkbox/edit.jsx, assets/js/src/form_editor/blocks/custom_date/custom_field_settings.jsx, assets/js/src/form_editor/blocks/custom_radio/edit.jsx, assets/js/src/form_editor/blocks/custom_text/custom_field_settings.jsx, assets/js/src/form_editor/blocks/custom_textarea/edit.jsx, tests/acceptance/FormEditorCreateCustomFieldCest.php
[MAILPOET-3310](https://mailpoet.atlassian.net/browse/MAILPOET-3310)
=> Add new scenarios to form editor's block custom field [MAILPOET-3310]

tests/acceptance/EditorSettingsBehaviourCest.php
[MAILPOET-3323](https://mailpoet.atlassian.net/browse/MAILPOET-3323)
=> Fix unable to click on a button in the test [MAILPOET-3323]

tests/acceptance/EditorHeaderBlockCest.php, tests/acceptance/EditorSocialBlockCest.php, views/newsletter/templates/blocks/social/settings.hbs
[MAILPOET-3322](https://mailpoet.atlassian.net/browse/MAILPOET-3322)
=> Fix flakyness addSocial and addHeader blocks [MAILPOET-3322]

assets/js/src/common/modal/modal.tsx, assets/js/src/form_editor/components/editor.jsx, assets/js/src/form_editor/components/tutorial.tsx, assets/js/src/form_editor/store/actions.ts, assets/js/src/form_editor/store/controls.jsx, assets/js/src/form_editor/store/reducer.jsx, assets/js/src/form_editor/store/reducers/tutorial_dismiss.ts, assets/js/src/form_editor/store/selectors.jsx, assets/js/src/form_editor/store/store.jsx, assets/js/src/mailpoet.js, lib/AdminPages/Pages/FormEditor.php, lib/Settings/UserFlagsController.php, tests/DataFactories/UserFlags.php, tests/acceptance/FormEditorTutorialCest.php, views/form/editor.html
[MAILPOET-3206]
[MAILPOET-3206]: https://mailpoet.atlassian.net/browse/MAILPOET-3206
=> Form editor tutorial [MAILPOET-3206]

assets/js/src/form_editor/components/font_family_settings.tsx, assets/js/src/form_editor/store/map_form_data_before_saving.jsx
[MAILPOET-3288]
[MAILPOET-3288]: https://mailpoet.atlassian.net/browse/MAILPOET-3288
=> Fix switching to default format [MAILPOET-3288]

assets/css/src/components-editor/_common.scss, package-lock.json
[MAILPOET-3130]
[MAILPOET-3130]: https://mailpoet.atlassian.net/browse/MAILPOET-3130
=> Fix editor lists [MAILPOET-3130]

assets/js/src/form_editor/blocks/divider/edit.tsx, tests/acceptance/FormEditorAddDividerCest.php
[MAILPOET-3325](https://mailpoet.atlassian.net/browse/MAILPOET-3325)
=> Add new acceptance test case divider block [MAILPOET-3325]

tests/acceptance/FormEditorTextInputStylesCest.php
[MAILPOET-3328](https://mailpoet.atlassian.net/browse/MAILPOET-3328)
Check the Jira ticket for more info , if needed.
=> Update scenario to include heading and paragraph [MAILPOET-3328]

tests/docker/codeception/docker-entrypoint.sh, tests/docker/docker-compose.yml, tools/install.php
[MAILPOET-3321]
[MAILPOET-3321]: https://mailpoet.atlassian.net/browse/MAILPOET-3321
=> Use curl for download Woocommerce plugin [MAILPOET-3321]

tests/acceptance/ManageListsCest.php, tests/acceptance/SubscribersListingCest.php
[MAILPOET-3335](https://mailpoet.atlassian.net/browse/MAILPOET-3335)
=> Fix flaky tests in acceptance [MAILPOET-3335]

assets/js/src/newsletters/automatic_emails/events/event_options.jsx, assets/js/src/newsletters/automatic_emails/events/event_options.tsx, assets/js/src/newsletters/automatic_emails/events_conditions.jsx, assets/js/src/newsletters/automatic_emails/send_event_conditions.jsx, assets/js/src/segments/dynamic_segments_filters/woocommerce.jsx, lib/AdminPages/Pages/FormEditor.php, lib/AdminPages/Pages/Newsletters.php, lib/AdminPages/Pages/Segments.php, lib/AutomaticEmails/WooCommerce/Events/PurchasedInCategory.php, lib/AutomaticEmails/WooCommerce/Events/PurchasedProduct.php, lib/DI/ContainerConfigurator.php, lib/WP/AutocompletePostListLoader.php, views/newsletters.html, views/segments.html
[MAILPOET-2553]
[MAILPOET-2553]: https://mailpoet.atlassian.net/browse/MAILPOET-2553
=> Update woocommerce types search [MAILPOET-2553]

lib/Cron/Workers/SendingQueue/Tasks/Shortcodes.php, lib/Entities/NewsletterEntity.php, lib/Entities/SendingQueueEntity.php, lib/Entities/SubscriberEntity.php, lib/Newsletter/Shortcodes/Categories/Subscriber.php, lib/Newsletter/Shortcodes/Shortcodes.php, lib/Util/Notices/DeprecatedShortcodeNotice.php, lib/Util/Notices/PermanentNotices.php, tasks/phpstan/phpstan-tests.neon, tests/integration/Newsletter/ShortcodesTest.php, tests/unit/Entities/SubscriberEntityTest.php
[MAILPOET-3333]
[MAILPOET-3333]: https://mailpoet.atlassian.net/browse/MAILPOET-3333
=> Fix shortcodes errors [MAILPOET-3333]

lib/API/JSON/v1/Segments.php, lib/DI/ContainerConfigurator.php, lib/Segments/SegmentSaveController.php, lib/Segments/SegmentsRepository.php, tasks/phpstan/phpstan-baseline-integration-tests.neon, tests/integration/API/JSON/v1/NewslettersTest.php, tests/integration/API/JSON/v1/SegmentsTest.php, tests/integration/Entities/NewsletterEntityTest.php, tests/integration/Newsletter/Scheduler/WelcomeTest.php, tests/integration/Segments/SegmentSubscribersRepositoryTest.php, tests/integration/Subscribers/SubscriberListingRepositoryTest.php, tests/integration/Subscribers/SubscribersRepositoryTest.php
[MAILPOET-3167]
[MAILPOET-3167]: https://mailpoet.atlassian.net/browse/MAILPOET-3167
=> Use Doctrine in Segments::save() [MAILPOET-3167]

tests/acceptance/EditorSettingsBehaviourCest.php
[MAILPOET-3341](https://mailpoet.atlassian.net/browse/MAILPOET-3341)
=> Fix flaky test EditorSettingsBehavior [MAILPOET-3341]

assets/js/src/ajax.js
[MAILPOET-3342]
[MAILPOET-3342]: https://mailpoet.atlassian.net/browse/MAILPOET-3342
=> Fix ajax issues [MAILPOET-3342]

lib/Segments/SegmentSaveController.php, lib/Segments/SegmentsRepository.php
[MAILPOET-3343]
[MAILPOET-3343]: https://mailpoet.atlassian.net/browse/MAILPOET-3343
=> Fix update segment when the name is the same [MAILPOET-3343]

views/form/editor.html, views/form/template_selection.html, views/forms.html, views/newsletters.html
[MAILPOET-3302]
[MAILPOET-3302]: https://mailpoet.atlassian.net/browse/MAILPOET-3302
=> Update default Beacon articles [MAILPOET-3302]

tests/acceptance/EditorProductsCest.php
[MAILPOET-3349]
[MAILPOET-3349]: https://mailpoet.atlassian.net/browse/MAILPOET-3349
=> Replace broken placeholder images in tests [MAILPOET-3349]

lib/Util/Notices/DeprecatedShortcodeNotice.php
[MAILPOET-3345](https://mailpoet.atlassian.net/browse/MAILPOET-3345)
=> Fix button link in deprecated shortcodes notice [MAILPOET-3345]

views/subscribers/importExport/import/step_data_manipulation.html
[MAILPOET-3348]
[MAILPOET-3348]: https://mailpoet.atlassian.net/browse/MAILPOET-3348
=> Fix new segment form in subscribers import [MAILPOET-3348]

assets/js/src/form_editor/components/history_redo.tsx, assets/js/src/form_editor/components/history_undo.tsx
[MAILPOET-3320]
[MAILPOET-3320]: https://mailpoet.atlassian.net/browse/MAILPOET-3320
=> Register undo/redo shortcuts only once [MAILPOET-3320]

lib/API/JSON/v1/Forms.php, lib/API/JSON/v1/Subscribers.php, lib/Entities/FormEntity.php, lib/Form/BlocksRenderer.php, lib/Form/Renderer.php, lib/Models/Form.php, tasks/phpstan/phpstan-baseline-integration-tests.neon, tests/integration/API/JSON/v1/FormsTest.php, tests/integration/API/JSON/v1/SubscribersTest.php, tests/unit/Entities/FormEntityTest.php
[MAILPOET-3297]
[MAILPOET-3297]: https://mailpoet.atlassian.net/browse/MAILPOET-3297
=> Fix list selection in form when placed in column block [MAILPOET-3297]

lib/Listing/ListingRepository.php, lib/Subscribers/SubscriberListingRepository.php, tests/integration/Subscribers/SubscriberListingRepositoryTest.php
[MAILPOET-3319]
[MAILPOET-3319]: https://mailpoet.atlassian.net/browse/MAILPOET-3319
=> Fix subscriber listing when dynamic segment filter [MAILPOET-3319]

lib/Util/Security.php
[MAILPOET-1899]
[MAILPOET-1899]: https://mailpoet.atlassian.net/browse/MAILPOET-1899
=> Update code [MAILPOET-1899]

RoboFile.php
[MAILPOET-3262]
[MAILPOET-3262]: https://mailpoet.atlassian.net/browse/MAILPOET-3262
=> Fix a warning when running release command [MAILPOET-3262]

assets/js/src/segments/dynamic_segments_filters/email.jsx
Please make sure saving and editing clicked links in dynamic segments works properly.
=> Fix saving clicked links in dynamic segments [MAILPOET-3292]

lib/WooCommerce/Helper.php, lib/WooCommerce/Subscription.php, tests/integration/WooCommerce/SubscriptionTest.php
[MAILPOET-2925]
[MAILPOET-2925]: https://mailpoet.atlassian.net/browse/MAILPOET-2925
=> Use woocommerce_form_field() for WC checkout opt-in [MAILPOET-2925]

assets/js/src/listing/listing.jsx, assets/js/src/listing/listing_item.jsx, assets/js/src/listing/listing_items.jsx, assets/js/src/segments/list.jsx, lib/API/JSON/v1/Segments.php, lib/Models/Segment.php, lib/Newsletter/Segment/NewsletterSegmentRepository.php, lib/Subscribers/SubscribersRepository.php, tests/DataFactories/User.php, tests/acceptance/ManageListsCest.php, tests/acceptance/ManageSegmentsCest.php, views/segments.html
[MAILPOET-3142]
[MAILPOET-3142]: https://mailpoet.atlassian.net/browse/MAILPOET-3142
=> Add enabling and disabling WP Users List [MAILPOET-3142]

tests/_support/AcceptanceTester.php, tests/acceptance/ReceiveStandardEmailCest.php
[MAILPOET-3354](https://mailpoet.atlassian.net/browse/MAILPOET-3354)
=> Update scenario to cover interpreting shortcodes [MAILPOET-3354]

tests/acceptance/SubscriberManageImportExportCest.php
[MAILPOET-3352](https://mailpoet.atlassian.net/browse/MAILPOET-3352)
=> Update scenario to cover import list description [MAILPOET-3352]

tests/acceptance/SubscriberManageImportExportCest.php
[MAILPOET-3355](https://mailpoet.atlassian.net/browse/MAILPOET-3355)
=> Add new scenario covering import WP users as subscribers [MAILPOET-3355]

lib/API/JSON/ResponseBuilders/SegmentsResponseBuilder.php, lib/API/JSON/v1/Segments.php, lib/DI/ContainerConfigurator.php, lib/Models/Segment.php, lib/Newsletter/Segment/NewsletterSegmentRepository.php, lib/Segments/SegmentListingRepository.php, lib/Segments/SegmentSubscribersRepository.php, lib/Segments/WooCommerce.php, lib/Subscribers/SubscribersRepository.php, tests/integration/API/JSON/ResponseBuilders/SegmentsResponseBuilderTest.php, tests/integration/Models/SegmentTest.php, tests/integration/Segments/SegmentSubscribersRepositoryTest.php
[MAILPOET-3168]
[MAILPOET-3168]: https://mailpoet.atlassian.net/browse/MAILPOET-3168
=> Refactor segments listings to doctrine [MAILPOET-3168]

tests/acceptance/ManageSegmentsCest.php
[MAILPOET-3353](https://mailpoet.atlassian.net/browse/MAILPOET-3353)
=> Update scenario to cover dynamic segment pagination [MAILPOET-3353]

assets/js/src/newsletters/automatic_emails/listings.jsx, assets/js/src/newsletters/listings/notification.jsx, assets/js/src/newsletters/listings/standard.jsx, assets/js/src/newsletters/listings/welcome.jsx, assets/js/src/newsletters/newsletters.jsx, assets/js/src/newsletters/types.jsx
[MAILPOET-3313]
[MAILPOET-3313]: https://mailpoet.atlassian.net/browse/MAILPOET-3313
=> Remove closing button on listings pages [MAILPOET-3313]

lib/Router/Endpoints/ViewInBrowser.php, lib/Statistics/Track/Clicks.php
[MAILPOET-3311]
[MAILPOET-3311]: https://mailpoet.atlassian.net/browse/MAILPOET-3311
=> Fix rendering 404 page [MAILPOET-3311]

tests/acceptance/ManageSegmentsCest.php
[MAILPOET-3359]
[MAILPOET-3359]: https://mailpoet.atlassian.net/browse/MAILPOET-3359
=> Make the email addresses more unique [MAILPOET-3359]

lib/Cron/Workers/SendingQueue/Tasks/Shortcodes.php, tests/integration/Cron/Workers/SendingQueue/Tasks/ShortcodesTest.php
[MAILPOET-3356]
[MAILPOET-3356]: https://mailpoet.atlassian.net/browse/MAILPOET-3356
=> Set newsletter Entity when stdClass instance given [MAILPOET-3356]

lib/Listing/ListingRepository.php, lib/Subscribers/SubscriberListingRepository.php, tests/integration/Subscribers/SubscriberListingRepositoryTest.php
[MAILPOET-3285]
[MAILPOET-3285]: https://mailpoet.atlassian.net/browse/MAILPOET-3285
=> Fix getting subscribers without a list [MAILPOET-3285]

lib/Config/MP2Migrator.php, lib/Mailer/Mailer.php, tests/integration/Config/MP2MigratorTest.php, tests/integration/Mailer/MailerTest.php
[MAILPOET-2933]
[MAILPOET-2933]: https://mailpoet.atlassian.net/browse/MAILPOET-2933
=> Check invalid bounce email address [MAILPOET-2933]

lib/Config/Populator.php
=> Missing i18n namespace in checkout optin label [MAILPOET-3360]

lib/API/JSON/ResponseBuilders/DynamicSegmentsResponseBuilder.php, lib/API/JSON/v1/DynamicSegments.php, lib/DI/ContainerConfigurator.php, lib/Segments/DynamicSegments/DynamicSegmentsListingRepository.php, lib/Segments/SegmentListingRepository.php, tests/integration/API/JSON/v1/DynamicSegmentsTest.php
[MAILPOET-3361]
[MAILPOET-3361]: https://mailpoet.atlassian.net/browse/MAILPOET-3361
=> Refactor dynamic segments listings to doctrine [MAILPOET-3361]

tests/acceptance/ManageSegmentsCest.php
[MAILPOET-3362]
[MAILPOET-3362]: https://mailpoet.atlassian.net/browse/MAILPOET-3362
=> Fix flakey test [MAILPOET-3362]

assets/js/src/common/subscribers_in_plan.tsx, assets/js/src/mailpoet.js, assets/js/src/notices/subscribers_limit_notice.jsx, assets/js/src/segments/heading.jsx, assets/js/src/segments/list.jsx, assets/js/src/subscribers/list.jsx, assets/js/src/subscribers/stats/opened_email_stats.tsx, lib/AdminPages/PageRenderer.php, lib/AdminPages/Pages/Newsletters.php, lib/AdminPages/Pages/Premium.php, lib/AdminPages/Pages/Segments.php, lib/AdminPages/Pages/Subscribers.php, lib/AdminPages/Pages/WelcomeWizard.php, lib/Analytics/Reporter.php, lib/Config/ServicesChecker.php, lib/Entities/SegmentEntity.php, lib/Helpscout/Beacon.php, lib/Models/Subscriber.php, lib/Services/Bridge.php, lib/Subscribers/SubscribersRepository.php, lib/Util/License/Features/Subscribers.php, tests/unit/Util/License/Features/SubscribersTest.php, views/layout.html, views/segments.html, views/subscribers/subscribers.html
[MAILPOET-3143]
[MAILPOET-3143]: https://mailpoet.atlassian.net/browse/MAILPOET-3143
=> Unify subscribers counts [MAILPOET-3143]

tasks/fix-full-path-disclosure.php
[MAILPOET-3364]
[MAILPOET-3364]: https://mailpoet.atlassian.net/browse/MAILPOET-3364
=> Fix full path disclosure script [MAILPOET-3364]

tests/acceptance/FormEditorPlaceFormOnSpecifiedPageCest.php
[MAILPOET-3366](https://mailpoet.atlassian.net/browse/MAILPOET-3366)
=> Update test to cover recent bug of form's placement [MAILPOET-3366]

.circleci/config.yml
[MAILPOET-3357]
[MAILPOET-3357]: https://mailpoet.atlassian.net/browse/MAILPOET-3357
=> Add Circle.CI notifications to Slack [MAILPOET-3357]

lib/Cron/Workers/KeyCheck/KeyCheckWorker.php, tests/integration/Cron/Workers/KeyCheck/KeyCheckWorkerTest.php, tests/integration/Cron/Workers/KeyCheck/SendingServiceKeyCheckTest.php
[MAILPOET-3271]
[MAILPOET-3271]: https://mailpoet.atlassian.net/browse/MAILPOET-3271
=> Check API key cron jobs more randomly in time [MAILPOET-3271]

assets/js/src/newsletter_editor/components/config.jsx, assets/js/src/newsletter_editor/webpack_index.jsx
[MAILPOET-3295]
[MAILPOET-3295]: https://mailpoet.atlassian.net/browse/MAILPOET-3295
=> Add check that newsletter body is not empty [MAILPOET-3295]

tests/acceptance/ManageListsCest.php
[MAILPOET-3373](https://mailpoet.atlassian.net/browse/MAILPOET-3373)
=> Fix flaky test for managing lists [MAILPOET-3373]

assets/js/src/listing/listing.jsx, assets/js/src/listing/pages.jsx
[MAILPOET-3247]
[MAILPOET-3247]: https://mailpoet.atlassian.net/browse/MAILPOET-3247
=> Fix double id on listings pages [MAILPOET-3247]

tests/acceptance/CreateWooCommerceNewsletterCest.php
[MAILPOET-3377](https://mailpoet.atlassian.net/browse/MAILPOET-3377)
Fixed flakiness and updated test case to be more maintenance-friendly.
=> Fix flaky test and update test case structure [MAILPOET-3377]

tests/integration/Segments/WPTest.php
[MAILPOET-3336]
[MAILPOET-3336]: https://mailpoet.atlassian.net/browse/MAILPOET-3336
=> Fix flakey integration test [MAILPOET-3336]

lib/Models/SendingQueue.php, lib/Newsletter/Renderer/Renderer.php, lib/WooCommerce/TransactionalEmailHooks.php, lib/WooCommerce/TransactionalEmails/Renderer.php
[MAILPOET-3329]
[MAILPOET-3329]: https://mailpoet.atlassian.net/browse/MAILPOET-3329
=> Use email heading from Woo for the title in transactional emails [MAILPOET-3329]

lib/API/JSON/v1/Segments.php, lib/Entities/SegmentEntity.php, lib/Segments/SegmentSaveController.php, tests/integration/Segments/SegmentSaveControllerTest.php
[MAILPOET-3170]
[MAILPOET-3170]: https://mailpoet.atlassian.net/browse/MAILPOET-3170
=> Refactor Segments::duplicate() to Doctrine [MAILPOET-3170]

.circleci/config.yml, tests/docker/docker-compose.yml
[MAILPOET-3151]
[MAILPOET-3339]
[MAILPOET-3151]: https://mailpoet.atlassian.net/browse/MAILPOET-3151
[MAILPOET-3339]: https://mailpoet.atlassian.net/browse/MAILPOET-3339
=> Use PHP 8.0 images in Circle CI [MAILPOET-3151][MAILPOET-3339]

assets/js/src/form_editor/blocks/map_custom_field_form_data.jsx
[MAILPOET-3381]
[MAILPOET-3381]: https://mailpoet.atlassian.net/browse/MAILPOET-3381
=> Change value for disabling in custom field form mapping [MAILPOET-3381]

.circleci/config.yml
[MAILPOET-3398]
[MAILPOET-3398]: https://mailpoet.atlassian.net/browse/MAILPOET-3398
=> Update WP image for acceptance_oldest job to v5.3 [MAILPOET-3398]

assets/css/src/components-form-editor/_sidebar-style-settings.scss, assets/css/src/components-form-editor/_typography.scss, assets/css/src/mailpoet-form-editor.scss, assets/js/src/form_editor/blocks/submit/styles_settings.tsx, assets/js/src/form_editor/components/color_gradient_settings.tsx, assets/js/src/form_editor/components/color_settings.tsx, assets/js/src/form_editor/components/font_family_settings.tsx, assets/js/src/form_editor/components/font_size_settings.tsx, assets/js/src/form_editor/components/form_settings/styles_settings_panel.jsx, assets/js/src/form_editor/rich_text/font_selection_format.tsx
[MAILPOET-3382]
[MAILPOET-3382]: https://mailpoet.atlassian.net/browse/MAILPOET-3382
=> Form editor fixes [MAILPOET-3382]

.circleci/config.yml, RoboFile.php, composer.json, composer.lock
[MAILPOET-3327]
[MAILPOET-3327]: https://mailpoet.atlassian.net/browse/MAILPOET-3327
=> Remove PHP security check, it doesn't work any more [MAILPOET-3327]

lib/API/JSON/v1/Segments.php, lib/Segments/SegmentsRepository.php
[MAILPOET-3169]
[MAILPOET-3169]: https://mailpoet.atlassian.net/browse/MAILPOET-3169
=> Refactor Segments::bulkAction, trash, restore, delete endpoints to Doctrine [MAILPOET-3169]

lib/Segments/SegmentsRepository.php
[MAILPOET-3400]
[MAILPOET-3400]: https://mailpoet.atlassian.net/browse/MAILPOET-3400
=> Use Carbon from MailPoetVendor namespace in SegmentsRepository [MAILPOET-3400]

assets/js/src/newsletters/automatic_emails/listings.jsx
[MAILPOET-3371]
[MAILPOET-3371]: https://mailpoet.atlassian.net/browse/MAILPOET-3371
=> Replace subject after update status of automatic email [MAILPOET-3371]

assets/js/src/newsletter_editor/blocks/abandonedCartContent.js
[MAILPOET-3278]
[MAILPOET-3278]: https://mailpoet.atlassian.net/browse/MAILPOET-3278
=> Remove show settings after render abandoned cart [MAILPOET-3278]

lib/API/MP/v1/API.php, tests/integration/API/MP/APITest.php
[MAILPOET-3307]
[MAILPOET-3307]: https://mailpoet.atlassian.net/browse/MAILPOET-3307
=> Allow re-subscribe functionality in third party API [MAILPOET-3307]

tests/acceptance/ManageListsCest.php
[MAILPOET-3402](https://mailpoet.atlassian.net/browse/MAILPOET-3402)
=> Fixed flaky scenario of moving a list to trash [MAILPOET-3402]

lib/Mailer/WordPress/WordpressMailerReplacer.php
[MAILPOET-3403]
[MAILPOET-3403]: https://mailpoet.atlassian.net/browse/MAILPOET-3403
=> Fix crashes on multisite installations [MAILPOET-3403]

assets/js/src/public.jsx, lib/Form/AssetsController.php
[MAILPOET-3390]
[MAILPOET-3390]: https://mailpoet.atlassian.net/browse/MAILPOET-3390
=> Stop using onload callback after loading reCaptcha v2 [MAILPOET-3390]

prefixer/fix-carbon.php, prefixer/fix-doctrine.php, tasks/fix-phpunit.php
[MAILPOET-3395]
[MAILPOET-3395]: https://mailpoet.atlassian.net/browse/MAILPOET-3395
=> Fix errors in during installation of PHP dependencies [MAILPOET-3395]

lib/Segments/SegmentListingRepository.php
[MAILPOET-3372]
[MAILPOET-3372]: https://mailpoet.atlassian.net/browse/MAILPOET-3372
=> Add type casting for counts in groups of segments [MAILPOET-3372]

lib/Form/Block/BlockRendererHelper.php, lib/Newsletter/Shortcodes/Categories/Subscriber.php, tests/integration/Newsletter/ShortcodesTest.php, tests/integration/Subscription/ManageSubscriptionFormRendererTest.php
=> [MAILPOET-3408]

tests/integration/Cron/CronHelperTest.php
[MAILPOET-3413]
[MAILPOET-3413]: https://mailpoet.atlassian.net/browse/MAILPOET-3413
=> Add tries when CronHelpes ping ends with timeout [MAILPOET-3413]

assets/js/src/settings/components/segments_select.tsx, assets/js/src/settings/pages/basics/shortcode.tsx, assets/js/src/settings/store/selectors.ts, assets/js/src/settings/store/types.ts, lib/AdminPages/Pages/Settings.php
[MAILPOET-3419]
[MAILPOET-3419]: https://mailpoet.atlassian.net/browse/MAILPOET-3419
=> Allow WooCommerce and WP segments in shortcodes settings [MAILPOET-3419]

assets/js/src/subscribers/importExport/import/sanitize_csv_data.jsx
[MAILPOET-3407]
[MAILPOET-3407]: https://mailpoet.atlassian.net/browse/MAILPOET-3407
=> Make better entity decode [MAILPOET-3407]

lib/Form/Block/BlockRendererHelper.php
[MAILPOET-3415]
[MAILPOET-3415]: https://mailpoet.atlassian.net/browse/MAILPOET-3415
=> Fix form input validations [MAILPOET-3415]

lib/Form/ApiDataSanitizer.php, lib/Form/Block/Checkbox.php, tests/integration/Form/ApiDataSanitizerTest.php
[MAILPOET-3433]
[MAILPOET-3433]: https://mailpoet.atlassian.net/browse/MAILPOET-3433
=> Fix links in form checkbox label [MAILPOET-3433]

lib/Cron/Workers/SendingQueue/Tasks/Shortcodes.php, lib/Newsletter/Shortcodes/Categories/Link.php, tests/integration/Newsletter/ShortcodesTest.php
[MAILPOET-3434]
[MAILPOET-3434]: https://mailpoet.atlassian.net/browse/MAILPOET-3434
=> Fix view in browser [MAILPOET-3434]

assets/js/src/segments/list.jsx, lib/API/JSON/ResponseBuilders/SegmentsResponseBuilder.php, lib/Newsletter/Segment/NewsletterSegmentRepository.php
[MAILPOET-3417]
[MAILPOET-3417]: https://mailpoet.atlassian.net/browse/MAILPOET-3417
=> Prevent deleting lists with emails that are being sent [MAILPOET-3417]

lib/API/JSON/v1/ImportExport.php, lib/DI/ContainerConfigurator.php, lib/Doctrine/Repository.php, lib/Entities/CustomFieldEntity.php, lib/Entities/SubscriberEntity.php, lib/Models/CustomField.php, lib/Newsletter/Options/NewsletterOptionsRepository.php, lib/Subscribers/ImportExport/Import/Import.php, lib/Subscribers/ImportExport/ImportExportRepository.php, lib/Subscribers/SubscribersRepository.php, tests/integration/Subscribers/ImportExport/Import/ImportTest.php, tests/integration/Subscribers/ImportExport/ImportExportRepositoryTest.php
[MAILPOET-3378]
[MAILPOET-3378]: https://mailpoet.atlassian.net/browse/MAILPOET-3378
=> Refactor subscribers import functionality to Doctrine [MAILPOET-3378]

lib/Subscribers/SubscribersRepository.php
[MAILPOET-3445]
[MAILPOET-3445]: https://mailpoet.atlassian.net/browse/MAILPOET-3445
=> Fix join parameters in SubscribersRepository [MAILPOET-3445]

lib/Form/Block/BlockRendererHelper.php, tests/DataFactories/Form.php, tests/acceptance/GutenbergFormBlockCest.php, tests/integration/Subscription/ManageSubscriptionFormRendererTest.php
[MAILPOET-3440]
[MAILPOET-3440]: https://mailpoet.atlassian.net/browse/MAILPOET-3440
=> Fix broken validation in form placed via Gutenberg block [MAILPOET-3440]

assets/js/src/notices/notice.tsx
[MAILPOET-3435]
[MAILPOET-3435]: https://mailpoet.atlassian.net/browse/MAILPOET-3435
=> Fix missing close button for success notice [MAILPOET-3435]

tests/docker/codeception/docker-entrypoint.sh
[MAILPOET-3330]
Check this build for the oldest acceptance test: https://app.circleci.com/pipelines/github/mailpoet/mailpoet/5767/workflows/70afbf10-a487-4cee-bc95-08ee6c855966
[MAILPOET-3330]: https://mailpoet.atlassian.net/browse/MAILPOET-3330
=> WooCommerce stable version [MAILPOET-3330]

lib/API/JSON/v1/NewsletterTemplates.php, lib/DI/ContainerConfigurator.php, lib/Newsletter/ApiDataSanitizer.php, lib/Newsletter/NewsletterHtmlSanitizer.php, lib/Newsletter/NewsletterSaveController.php, tests/integration/Newsletter/ApiDataSanitizerTest.php, tests/integration/Newsletter/NewsletterHtmlSanitizerTest.php
[MAILPOET-3430]
[MAILPOET-3430]: https://mailpoet.atlassian.net/browse/MAILPOET-3430
=> Fix template rendering issue [MAILPOET-3430]

assets/js/src/subscribers/importExport/import/step_method_selection/method_mailchimp.jsx, lib/Subscribers/ImportExport/Import/MailChimp.php, lib/Subscribers/ImportExport/Import/MailChimpDataMapper.php, tests/integration/Subscribers/ImportExport/Import/MailChimpTest.php, views/subscribers/importExport/import.html
[MAILPOET-3404]
[MAILPOET-3404]: https://mailpoet.atlassian.net/browse/MAILPOET-3404
=> Exclude disengaged subscribers in MailChimp import [MAILPOET-3404]

assets/js/src/subscribers/importExport/export.ts, assets/js/src/webpack_admin_index.jsx, lib/Subscribers/ImportExport/ImportExportFactory.php
[MAILPOET-3393]
[MAILPOET-3393]: https://mailpoet.atlassian.net/browse/MAILPOET-3393
=> Export subscription consent evidence [MAILPOET-3393]

views/premium.html
[MAILPOET-3384]
[MAILPOET-3384]: https://mailpoet.atlassian.net/browse/MAILPOET-3384
=> Fix link to buy the agency license of MailPoet Premium [MAILPOET-3384]

lib/Config/Shortcodes.php, lib/Segments/SegmentSubscribersRepository.php
[MAILPOET-3424]
[MAILPOET-3424]: https://mailpoet.atlassian.net/browse/MAILPOET-3424
=> Fix count returned from shortcode mailpoet_subscribers_count [MAILPOET-3424]

lib/Models/ModelValidator.php, lib/Subscribers/ImportExport/Import/Import.php, lib/Subscribers/ImportExport/ImportExportFactory.php, tests/integration/Subscribers/ImportExport/Import/ImportTest.php, tests/integration/Subscribers/ImportExport/ImportExportFactoryTest.php
[MAILPOET-3389]
[MAILPOET-3389]: https://mailpoet.atlassian.net/browse/MAILPOET-3389
=> Add support for import subscription consent evidence [MAILPOET-3389]

assets/js/src/listing/search.jsx, assets/js/src/newsletter_editor/initializer.jsx, assets/js/src/newsletters/listings/heading_display.jsx, assets/js/src/newsletters/listings/heading_steps.tsx, assets/js/src/newsletters/listings/heading_steps_route.jsx, assets/js/src/newsletters/send/congratulate/success.jsx, assets/js/src/newsletters/send/congratulate/success_pitch_mss.tsx, views/newsletter/editor.html, views/newsletters.html
[MAILPOET-3436]
[MAILPOET-3436]: https://mailpoet.atlassian.net/browse/MAILPOET-3436
=> Sending wording update [MAILPOET-3436]

assets/js/src/newsletters/listings/notification_history.jsx, assets/js/src/newsletters/listings/standard.jsx
[MAILPOET-3346]
[MAILPOET-3346]: https://mailpoet.atlassian.net/browse/MAILPOET-3346
=> Use sentAt instead of updatedAt in newsletters listing [MAILPOET-3346]

lib/Models/Segment.php, lib/Segments/SegmentSubscribersRepository.php, lib/Segments/SegmentsSimpleListRepository.php, lib/Subscribers/ImportExport/ImportExportRepository.php, lib/Subscribers/SubscriberListingRepository.php, tests/integration/Models/SegmentTest.php, tests/integration/Subscribers/ImportExport/ImportExportRepositoryTest.php
[MAILPOET-3462]
[MAILPOET-3462]: https://mailpoet.atlassian.net/browse/MAILPOET-3462
=> Unify exported subscribers not in list [MAILPOET-3462]

lib/Newsletter/Shortcodes/Categories/Date.php, tests/integration/Newsletter/ShortcodesTest.php
[MAILPOET-3375]
[MAILPOET-3375]: https://mailpoet.atlassian.net/browse/MAILPOET-3375
=> Use newsletter sent at in dates shortcodes [MAILPOET-3375]

assets/js/src/help/tasks_list/tasks_list_data_row.jsx, lib/Tasks/State.php
[MAILPOET-3441]
[MAILPOET-3441]: https://mailpoet.atlassian.net/browse/MAILPOET-3441
=> Make dates in newsletter listings and help consistent [MAILPOET-3441]

lib/Form/Renderer.php, lib/Subscription/ManageSubscriptionFormRenderer.php
[MAILPOET-3459]
[MAILPOET-3459]: https://mailpoet.atlassian.net/browse/MAILPOET-3459
=> Hide recaptcha in manage subscription form [MAILPOET-3459]

tests/_support/IntegrationTester.php
[MAILPOET-3478]
[MAILPOET-3478]: https://mailpoet.atlassian.net/browse/MAILPOET-3478
=> Include WP multisite function in IntegrationTester [MAILPOET-3478]

lib/API/JSON/v1/Settings.php, lib/Config/Populator.php, lib/Settings/SettingsController.php, tests/DataFactories/Form.php, tests/_support/AcceptanceTester.php, tests/integration/Models/FormTest.php, tests/integration/Settings/SettingsControllerTest.php
[MAILPOET-3034]
[MAILPOET-3034]: https://mailpoet.atlassian.net/browse/MAILPOET-3034
=> Remove old model from Settings endpoint [MAILPOET-3034]

lib/Util/ConflictResolver.php
[MAILPOET-3456]
[MAILPOET-3456]: https://mailpoet.atlassian.net/browse/MAILPOET-3456
=> Allow Jetpack styles in ConflictResolver [MAILPOET-3456]

lib/Newsletter/Renderer/Blocks/Text.php, lib/Newsletter/Renderer/StylesHelper.php, tests/unit/Newsletter/Renderer/Blocks/TextTest.php
[MAILPOET-3473]
[MAILPOET-3473]: https://mailpoet.atlassian.net/browse/MAILPOET-3473
=> Fix text align [MAILPOET-3473]

lib/AdminPages/Pages/NewsletterEditor.php, lib/Config/Shortcodes.php, lib/Models/Subscriber.php, lib/Newsletter/Preview/SendPreviewController.php, lib/Newsletter/ViewInBrowser/ViewInBrowserController.php, lib/Newsletter/ViewInBrowser/ViewInBrowserRenderer.php, lib/Segments/SegmentsRepository.php, lib/Subscribers/SubscribersRepository.php, lib/WooCommerce/Subscription.php, tests/integration/Newsletter/ViewInBrowser/ViewInBrowserControllerTest.php, tests/integration/Newsletter/ViewInBrowser/ViewInBrowserRendererTest.php, tests/integration/WooCommerce/SubscriptionTest.php
[MAILPOET-3268]
[MAILPOET-3268]: https://mailpoet.atlassian.net/browse/MAILPOET-3268
=> Refactor Subscriber::getCurrentWPUser to Doctrine [MAILPOET-3268]

assets/js/src/segments/dynamic_segments_list.jsx, tests/acceptance/ManageSegmentsCest.php
[MAILPOET-3351]
[MAILPOET-3351]: https://mailpoet.atlassian.net/browse/MAILPOET-3351
=> Add bulk actions to segments listing [MAILPOET-3351]

assets/css/src/components-plugin/_forms.scss, assets/js/src/ajax.js, assets/js/src/segments/dynamic_segments_filters/email.jsx, assets/js/src/segments/dynamic_segments_filters/woocommerce.jsx, assets/js/src/segments/dynamic_segments_filters/wordpress_role.jsx, assets/js/src/segments/dynamic_segments_form.jsx, assets/js/src/segments/subscribers_calculator.ts, assets/js/src/segments/subscribers_counter.tsx, lib/API/JSON/v1/DynamicSegments.php, lib/Segments/SegmentSubscribersRepository.php, tests/acceptance/ManageSegmentsCest.php, views/layout.html, views/segments.html
[MAILPOET-3219]
[MAILPOET-3219]: https://mailpoet.atlassian.net/browse/MAILPOET-3219
=> Show number of subscribers when editing and creating segments [MAILPOET-3219]

.circleci/config.yml
Hotfix for failing builds.
[MAILPOET-3494]
[MAILPOET-3494]: https://mailpoet.atlassian.net/browse/MAILPOET-3494
=> Switch Circle CI mysql:8.0 to an older version [MAILPOET-3494]

assets/js/src/segments/dynamic_segments_form.jsx, assets/js/src/segments/subscribers_calculator.ts
[MAILPOET-3495]
[MAILPOET-3495]: https://mailpoet.atlassian.net/browse/MAILPOET-3495
=> Fix failing oldest acceptance tests [MAILPOET-3495]

tests/acceptance/ReinstallFromScratchCest.php
[MAILPOET-3496]
[MAILPOET-3496]: https://mailpoet.atlassian.net/browse/MAILPOET-3496
=> Add wait in the test to make sure users are synchronised [MAILPOET-3496]

assets/js/src/subscribers/importExport/export.ts, package-lock.json, package.json
[MAILPOET-3486]
[MAILPOET-3486]: https://mailpoet.atlassian.net/browse/MAILPOET-3486
=> Minor fix to custom fields [MAILPOET-3486]

lib/Subscribers/ImportExport/ImportExportRepository.php
[MAILPOET-3505]
[MAILPOET-3505]: https://mailpoet.atlassian.net/browse/MAILPOET-3505
=> Remove distinct statement from export query [MAILPOET-3505]

lib/Entities/SegmentEntity.php, lib/Segments/DynamicSegments/FilterHandler.php, lib/Segments/DynamicSegments/Filters/EmailAction.php, lib/Segments/DynamicSegments/Filters/Filter.php, lib/Segments/DynamicSegments/Filters/UserRole.php, lib/Segments/DynamicSegments/Filters/WooCommerceCategory.php, lib/Segments/DynamicSegments/Filters/WooCommerceProduct.php, lib/Segments/SegmentSubscribersRepository.php, lib/Subscribers/ImportExport/ImportExportRepository.php, lib/Subscribers/SubscriberListingRepository.php, tests/_support/IntegrationTester.php, tests/integration/Segments/DynamicSegments/FilterHandlerTest.php, tests/integration/Segments/DynamicSegments/Filters/EmailActionTest.php, tests/integration/Segments/DynamicSegments/Filters/UserRoleTest.php
[MAILPOET-3212]
[MAILPOET-3212]: https://mailpoet.atlassian.net/browse/MAILPOET-3212
=> Connecting segments [MAILPOET-3212]

tasks/release/JiraController.php
[MAILPOET-3510]
[MAILPOET-3510]: https://mailpoet.atlassian.net/browse/MAILPOET-3510
=> Add sort versions from Jira by release date [MAILPOET-3510]

lib/Config/Populator.php, lib/Entities/NewsletterEntity.php, lib/Entities/SendingQueueEntity.php, tests/integration/API/JSON/v1/SetupTest.php, tests/integration/Entities/NewsletterEntityTest.php
[MAILPOET-3481]
[MAILPOET-3481]: https://mailpoet.atlassian.net/browse/MAILPOET-3481
=> Disable scheduled tasks when pausing email [MAILPOET-3481]

tests/acceptance/ReinstallFromScratchCest.php
[MAILPOET-3513](https://mailpoet.atlassian.net/browse/MAILPOET-3513)
=> Fix flaky counter in test ReinstallFromScratch [MAILPOET-3513]

assets/js/src/form_editor/rich_text/font_selection_format.tsx, assets/js/src/form_editor/store/blocks_to_form_body.jsx, assets/js/src/form_editor/store/form_body_to_blocks.jsx, tests/javascript/form_editor/store/blocks_to_form_body.spec.js, tests/javascript/form_editor/store/form_body_to_blocks.spec.js
[MAILPOET-3512]
[MAILPOET-3512]: https://mailpoet.atlassian.net/browse/MAILPOET-3512
=> Fix align saving in the form editor [MAILPOET-3512]

.circleci/config.yml
[MAILPOET-3521]
[MAILPOET-3521]: https://mailpoet.atlassian.net/browse/MAILPOET-3521
=> Add job for qa running on oldest php [MAILPOET-3521]

lib/AutomaticEmails/WooCommerce/Events/PurchasedProduct.php, tests/integration/AutomaticEmails/WooCommerce/Events/PurchasedProductTest.php
[MAILPOET-3254]
[MAILPOET-3254]: https://mailpoet.atlassian.net/browse/MAILPOET-3254
=> Fix duplicate automatic email for same product if ordered with another one [MAILPOET-3254]

lib/Segments/SegmentSubscribersRepository.php, tests/integration/Segments/SegmentSubscribersRepositoryTest.php
[MAILPOET-3425]
[MAILPOET-3425]: https://mailpoet.atlassian.net/browse/MAILPOET-3425
=> Add dynamic segments support to count shortcode [MAILPOET-3425]

assets/css/src/components-editor/content-blocks/_automated-latest-content.scss
[MAILPOET-3529]
[MAILPOET-3529]: https://mailpoet.atlassian.net/browse/MAILPOET-3529
=> Increased width to fit two digits [MAILPOET-3529]

lib/API/JSON/ResponseBuilders/SubscribersResponseBuilder.php, lib/API/JSON/v1/Subscribers.php, lib/DI/ContainerConfigurator.php, lib/Doctrine/EntityManagerFactory.php, lib/Doctrine/EventListeners/LastSubscribedAtListener.php, lib/Doctrine/EventListeners/TimestampListener.php, lib/Entities/SubscriberCustomFieldEntity.php, lib/Entities/SubscriberEntity.php, lib/Subscribers/SubscriberCustomFieldRepository.php, lib/Subscribers/SubscriberSaveController.php, lib/Subscribers/SubscriberSegmentRepository.php, lib/Util/Security.php, tests/integration/API/JSON/v1/SubscribersTest.php, tests/integration/Doctrine/EventListeners/TimestampListenerTest.php, tests/integration/Doctrine/EventListeners/ValidationTest.php, tests/integration/Doctrine/Types/JsonTypesTest.php, tests/integration/Subscribers/SubscriberSaveControllerTest.php, tests/unit/Entities/SubscriberCustomFieldEntityTest.php
[MAILPOET-3031]
[MAILPOET-3031]: https://mailpoet.atlassian.net/browse/MAILPOET-3031
=> Refactor Subscribers::save to Doctrine [MAILPOET-3031]

package.json
[MAILPOET-3522]
[MAILPOET-3522]: https://mailpoet.atlassian.net/browse/MAILPOET-3522
=> Prevent running old eslint for newer tests [MAILPOET-3522]

lib/API/JSON/API.php, lib/AdminPages/PageRenderer.php, lib/Doctrine/EntityManagerFactory.php
[MAILPOET-3420]
[MAILPOET-3420]: https://mailpoet.atlassian.net/browse/MAILPOET-3420
=> Check existence panels when creating debugger [MAILPOET-3420]

assets/js/src/newsletters/send.jsx
[MAILPOET-3460]
[MAILPOET-3460]: https://mailpoet.atlassian.net/browse/MAILPOET-3460
=> Remove duplicate warning [MAILPOET-3460]

lib/Tasks/State.php, tests/integration/Tasks/StateTest.php
[MAILPOET-3489]
[MAILPOET-3489]: https://mailpoet.atlassian.net/browse/MAILPOET-3489
=> Fix flakey integration test [MAILPOET-3489]

CONTRIBUTING.md
[MAILPOET-3531]
[MAILPOET-3531]: https://mailpoet.atlassian.net/browse/MAILPOET-3531
=> Add linting rules to contributing.md [MAILPOET-3531]

assets/js/src/form_editor/rich_text/font_selection_format.tsx
[MAILPOET-3519]
[MAILPOET-3519]: https://mailpoet.atlassian.net/browse/MAILPOET-3519
=> Change type for value in font selection format [MAILPOET-3519]

tests/acceptance/ManageSegmentsCest.php
[MAILPOET-3541](https://mailpoet.atlassian.net/browse/MAILPOET-3541)
=> Add clearField to fix the segment's test [MAILPOET-3541]

lib/AdminPages/Pages/Newsletters.php, lib/Config/Menu.php, lib/Config/Router.php, lib/DI/ContainerConfigurator.php, tests/integration/Config/MenuTest.php
[MAILPOET-3536]
[MAILPOET-3536]: https://mailpoet.atlassian.net/browse/MAILPOET-3536
=> Move calling newsletters redirect to the menu [MAILPOET-3536]

lib/Segments/WooCommerce.php
[MAILPOET-3543]
[MAILPOET-3543]: https://mailpoet.atlassian.net/browse/MAILPOET-3543
=> Add missing column collation detection for single sync [MAILPOET-3543]

lib/Config/Router.php
[MAILPOET-3550]
[MAILPOET-3550]: https://mailpoet.atlassian.net/browse/MAILPOET-3550
=> Add check that GET array key exists [MAILPOET-3550]

lib/Cron/Workers/SendingQueue/SendingQueue.php, lib/Util/Notices/EmailWithInvalidListNotice.php, lib/Util/Notices/EmailWithInvalidSegmentNotice.php, lib/Util/Notices/PermanentNotices.php, tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php
[MAILPOET-3418]
[MAILPOET-3418]: https://mailpoet.atlassian.net/browse/MAILPOET-3418
=> Pause emails with deleted/trashed lists [MAILPOET-3418]

lib/API/JSON/v1/Forms.php, lib/DI/ContainerConfigurator.php, lib/Form/FormSaveController.php, tests/integration/API/JSON/v1/FormsTest.php, tests/integration/Form/FormSaveControllerTest.php
[MAILPOET-3038]
[MAILPOET-3038]: https://mailpoet.atlassian.net/browse/MAILPOET-3038
=> Refactor Forms::duplicate() to use Doctrine instead of Paris [MAILPOET-3038]

assets/js/src/segments/dynamic/dynamic_segments_filters/woocommerce.tsx, lib/WP/AutocompletePostListLoader.php, tests/acceptance/ManageSegmentsCest.php
[MAILPOET-3555]
[MAILPOET-3555]: https://mailpoet.atlassian.net/browse/MAILPOET-3555
=> Fix woo category segment edit [MAILPOET-3555]

assets/js/src/form/form.jsx, assets/js/src/segments/dynamic/form.tsx, assets/js/src/segments/dynamic/list.jsx, lib/API/JSON/ResponseBuilders/DynamicSegmentsResponseBuilder.php, lib/DI/ContainerConfigurator.php, lib/Segments/DynamicSegments/FilterHandler.php, lib/Segments/SegmentDependencyValidator.php, tests/acceptance/WooCommerceDynamicSegmentsCest.php, tests/integration/Segments/SegmentDependencyValidatorTest.php, views/segments.html
[MAILPOET-3477]
[MAILPOET-3477]: https://mailpoet.atlassian.net/browse/MAILPOET-3477
=> Add validation that required plugin for dynamic segment is active [MAILPOET-3477]

lib/Segments/WP.php, lib/Segments/WooCommerce.php
[MAILPOET-3558]
[MAILPOET-3558]: https://mailpoet.atlassian.net/browse/MAILPOET-3558
=> Fix exhausted memory during WooCommerce sync [MAILPOET-3558]

assets/js/src/settings/store/actions/settings.ts
[MAILPOET-3480]
[MAILPOET-3480]: https://mailpoet.atlassian.net/browse/MAILPOET-3480
=> Trim settings values before saving [MAILPOET-3480]

lib/Form/Block/Date.php, tests/unit/Form/Block/DateTest.php
[MAILPOET-3470]
[MAILPOET-3470]: https://mailpoet.atlassian.net/browse/MAILPOET-3470
=> Fix pre-selecting date value [MAILPOET-3470]

readme.txt
[MAILPOET-3567]
[MAILPOET-3567]: https://mailpoet.atlassian.net/browse/MAILPOET-3567
=> Bump "Tested up to" version to 5.7 [MAILPOET-3567]

lib/Segments/WooCommerce.php, tests/integration/Segments/WooCommerceTest.php, tests/integration/_bootstrap.php
[MAILPOET-3565]
[MAILPOET-3565]: https://mailpoet.atlassian.net/browse/MAILPOET-3565
=> Update customer names on checkout using model [MAILPOET-3565]

lib/Config/Hooks.php, lib/Config/HooksWooCommerce.php, lib/DI/ContainerConfigurator.php
[MAILPOET-3563]
[MAILPOET-3563]: https://mailpoet.atlassian.net/browse/MAILPOET-3563
=> Prevent breaking WooCommerce in hooks [MAILPOET-3563]

assets/css/src/components-plugin/_dynamic-segments.scss, assets/css/src/mailpoet-plugin.scss, assets/js/src/common/button/button.tsx, assets/js/src/common/form/react_select/react_select.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/email.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/woocommerce.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/wordpress_role.tsx, assets/js/src/segments/dynamic/form.tsx
[MAILPOET-3569]
[MAILPOET-3569]: https://mailpoet.atlassian.net/browse/MAILPOET-3569
=> Fix double borders in segment form [MAILPOET-3569]

lib/Subscribers/ImportExport/Import/Import.php
[MAILPOET-3570]
[MAILPOET-3570]: https://mailpoet.atlassian.net/browse/MAILPOET-3570
=> Calculate batch size for import custom fields [MAILPOET-3570]

assets/js/src/segments/dynamic/dynamic_segments_filters/email_opens_absolute_count.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/woocommerce.tsx, tests/acceptance/ManageSegmentsCest.php
[MAILPOET-3574]
[MAILPOET-3574]: https://mailpoet.atlassian.net/browse/MAILPOET-3574
=> Fix UI issues in dynamic segment forms [MAILPOET-3574]

assets/css/src/components-editor/3rd-party-overrides/_overrides.scss, lib/Config/AssetsLoader.php, lib/Config/Initializer.php, lib/DI/ContainerConfigurator.php, views/form/editor.html
[MAILPOET-3556]
[MAILPOET-3556]: https://mailpoet.atlassian.net/browse/MAILPOET-3556
=> Fix sidebar overlaps on the newsletter/form editor page [MAILPOET-3556]

assets/js/src/subscribers/importExport/import/step_data_manipulation.jsx, assets/js/src/subscribers/importExport/import/step_data_manipulation/consent_description.tsx, assets/js/src/subscribers/importExport/import/step_data_manipulation/existing_subscribers_status.tsx, assets/js/src/subscribers/importExport/import/step_data_manipulation/new_subscribers_status.tsx, assets/js/src/subscribers/importExport/import/step_results.jsx, views/subscribers/importExport/import.html
[MAILPOET-3526]
[MAILPOET-3526]: https://mailpoet.atlassian.net/browse/MAILPOET-3526
=> Mention Consent and Suppression lists in Subscriber Import [MAILPOET-3526]

lib/Doctrine/ConnectionFactory.php
[MAILPOET-3579]
[MAILPOET-3579]: https://mailpoet.atlassian.net/browse/MAILPOET-3579
=> Turn off ansi quotes directive [MAILPOET-3579]

assets/js/src/listing/bulk_actions.jsx, tests/acceptance/ManageSegmentsCest.php
[MAILPOET-3584]
[MAILPOET-3584]: https://mailpoet.atlassian.net/browse/MAILPOET-3584
=> Fix flaky ManageSegmentsCest [MAILPOET-3584]

tests/acceptance/Newsletters/EditorProductsCest.php
[MAILPOET-3587]
[MAILPOET-3587]: https://mailpoet.atlassian.net/browse/MAILPOET-3587
=> Replace dummyimage.com by local image [MAILPOET-3587]

assets/js/src/segments/dynamic/dynamic_segments_filters/email.tsx, assets/js/src/segments/dynamic/types.ts, lib/Segments/DynamicSegments/FilterDataMapper.php, lib/Segments/DynamicSegments/Filters/EmailAction.php, tests/integration/Segments/DynamicSegments/Filters/EmailActionTest.php, tests/unit/Segments/DynamicSegments/FilterDataMapperTest.php, views/segments.html
[MAILPOET-3223]
[MAILPOET-3223]: https://mailpoet.atlassian.net/browse/MAILPOET-3223
=> Segment clicked any [MAILPOET-3223]

tests/_support/AcceptanceTester.php, tests/acceptance/Newsletters/EditorProductsCest.php, tests/acceptance/Settings/BasicsPageCest.php, tests/acceptance/Settings/CreateNewWordPressUserCest.php, tests/acceptance/Settings/SubscribeOnRegistrationPageCest.php
[MAILPOET-3594]
[MAILPOET-3594]: https://mailpoet.atlassian.net/browse/MAILPOET-3594
=> Fix flaky editor products test [MAILPOET-3594]

tests/acceptance/Newsletters/EditorProductsCest.php
[MAILPOET-3594]
[MAILPOET-3594]: https://mailpoet.atlassian.net/browse/MAILPOET-3594
=> Reintroduce second attempt for filtering products in test [MAILPOET-3594]

lib/Config/Hooks.php, lib/Config/HooksWooCommerce.php, lib/Segments/WP.php, lib/Segments/WooCommerce.php, lib/Subscription/Registration.php, tests/integration/Segments/WPTest.php
[MAILPOET-3483]
[MAILPOET-3483]: https://mailpoet.atlassian.net/browse/MAILPOET-3483
=> Add opt-in checkbox to WooCommerce registration form [MAILPOET-3483]

lib/Config/Migrator.php, lib/Config/Populator.php, lib/Cron/Workers/SimpleWorker.php, lib/Cron/Workers/SubscribersEngagementScore.php, lib/Statistics/StatisticsOpensRepository.php, lib/Subscribers/SubscribersRepository.php, tests/integration/Statistics/StatisticsOpensRepositoryTest.php
[MAILPOET-3585]
[MAILPOET-3585]: https://mailpoet.atlassian.net/browse/MAILPOET-3585
=> Fix subscribers score calculation [MAILPOET-3585]

lib/Segments/DynamicSegments/FilterDataMapper.php
[MAILPOET-3573]
[MAILPOET-3573]: https://mailpoet.atlassian.net/browse/MAILPOET-3573
=> Allow saving a segment with 0 opens [MAILPOET-3573]

assets/js/src/segments/dynamic/dynamic_segments_filters/subscriber.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/subscriber_subscribed_date.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/subscriber_wordpress_role.tsx, assets/js/src/segments/dynamic/form.tsx, assets/js/src/segments/dynamic/form_filter_fields.tsx, assets/js/src/segments/dynamic/subscribers_calculator.ts, assets/js/src/segments/dynamic/subscribers_counter.tsx, assets/js/src/segments/dynamic/types.ts, assets/js/src/segments/dynamic/validator.ts, lib/DI/ContainerConfigurator.php, lib/Segments/DynamicSegments/Exceptions/InvalidFilterException.php, lib/Segments/DynamicSegments/FilterDataMapper.php, lib/Segments/DynamicSegments/FilterHandler.php, lib/Segments/DynamicSegments/Filters/SubscriberSubscribedDate.php, tests/integration/Segments/DynamicSegments/Filters/SubscriberSubscribedDateTest.php, tests/unit/Segments/DynamicSegments/FilterDataMapperTest.php, views/segments.html
[MAILPOET-3222]
[MAILPOET-3222]: https://mailpoet.atlassian.net/browse/MAILPOET-3222
=> Subscribed date dynamic segment [MAILPOET-3222]

lib/Cron/Workers/SendingQueue/SendingErrorHandler.php, lib/Cron/Workers/SendingQueue/SendingQueue.php, lib/Cron/Workers/SendingQueue/SendingThrottlingHandler.php, lib/DI/ContainerConfigurator.php, lib/Logging/LoggerFactory.php, lib/Mailer/MailerLog.php, tests/integration/Cron/Workers/SendingQueue/SendingErrorHandlerTest.php, tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php, tests/integration/Cron/Workers/SendingQueue/SendingThrottlingHandlerTest.php
[MAILPOET-3588]
[MAILPOET-3588]: https://mailpoet.atlassian.net/browse/MAILPOET-3588
=> Add throttling for a sending batch size [MAILPOET-3588]

tests/docker/docker-compose.yml
[MAILPOET-3453]
[MAILPOET-3453]: https://mailpoet.atlassian.net/browse/MAILPOET-3453
=> Use the latest version of chrome [MAILPOET-3453]

lib/Form/Renderer.php, views/form/front_end_form.html
[MAILPOET-3596]
[MAILPOET-3596]: https://mailpoet.atlassian.net/browse/MAILPOET-3596
=> Fix form CSS rendering [MAILPOET-3596]

.circleci/config.yml, RoboFile.php, build.sh
[MAILPOET-3604]
[MAILPOET-3604]: https://mailpoet.atlassian.net/browse/MAILPOET-3604
=> Doctrine metadata fix [MAILPOET-3604]

lib/Util/ConflictResolver.php
[MAILPOET-3461]
[MAILPOET-3461]: https://mailpoet.atlassian.net/browse/MAILPOET-3461
=> Allow css for debug bar on WP.com [MAILPOET-3461]

lib/Cron/Workers/Bounce.php
[MAILPOET-3592]
[MAILPOET-3592]: https://mailpoet.atlassian.net/browse/MAILPOET-3592
=> Spread bounce check in time [MAILPOET-3592]

views/form/templatesLegacy/settings/field_form.hbs
[MAILPOET-3540]
[MAILPOET-3540]: https://mailpoet.atlassian.net/browse/MAILPOET-3540
=> Fix creating custom field in subscribers import [MAILPOET-3540]

assets/css/src/components-plugin/_listing-newsletters.scss, assets/js/src/segments/list.jsx, assets/js/src/subscribers/list.jsx, assets/js/src/subscribers/listings_engagement_score.tsx, assets/js/src/subscribers/stats.tsx, assets/js/src/subscribers/stats/summary.tsx, lib/API/JSON/ResponseBuilders/SegmentsResponseBuilder.php, lib/API/JSON/v1/Settings.php, lib/AdminPages/Pages/Segments.php, lib/Config/Migrator.php, lib/Cron/Workers/SubscribersEngagementScore.php, lib/Doctrine/MetadataCache.php, lib/Entities/SegmentEntity.php, lib/Segments/SegmentListingRepository.php, lib/Segments/SegmentsRepository.php, lib/Statistics/StatisticsOpensRepository.php, lib/Statistics/Track/Opens.php, tests/acceptance.suite.yml, tests/integration/API/JSON/v1/SettingsTest.php, tests/integration/Statistics/StatisticsOpensRepositoryTest.php, views/segments.html, views/subscribers/subscribers.html
[MAILPOET-3533]
I have added as a part of this PR some small UI changes discussed with Tautvidas.
[MAILPOET-3533]: https://mailpoet.atlassian.net/browse/MAILPOET-3533
=> Add list score [MAILPOET-3533]

lib/WooCommerce/TransactionalEmails/Renderer.php
[MAILPOET-3485]
[MAILPOET-3485]: https://mailpoet.atlassian.net/browse/MAILPOET-3485
=> Add missing div element with ID for WooCommerce emails [MAILPOET-3485]

lib/Segments/DynamicSegments/Filters/EmailOpensAbsoluteCountAction.php, tests/integration/Segments/DynamicSegments/Filters/EmailOpensAbsoluteCountActionTest.php
[MAILPOET-3612]
[MAILPOET-3612]: https://mailpoet.atlassian.net/browse/MAILPOET-3612
=> Fix calculating email opens for dynamic segments [MAILPOET-3612]

lib/Subscription/Manage.php, tests/integration/Subscription/ManageTest.php
[MAILPOET-2496]
[MAILPOET-2496]: https://mailpoet.atlassian.net/browse/MAILPOET-2496
=> Use SubscribersActions for subscribe via manage subscriptions [MAILPOET-2496]

readme.txt
[MAILPOET-3617]
[MAILPOET-3617]: https://mailpoet.atlassian.net/browse/MAILPOET-3617
=> Remove wysija as MP3 plugin author [MAILPOET-3617]

assets/js/src/segments/dynamic/dynamic_segments_filters/custom_fields/checkbox.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/custom_fields/date.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/custom_fields/select.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/custom_fields/text.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/subscriber.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/subscriber_mailpoet_custom_field.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/subscriber_subscribed_date.tsx, assets/js/src/segments/dynamic/segment_form_data.ts, assets/js/src/segments/dynamic/types.ts, lib/AdminPages/Pages/Segments.php, lib/DI/ContainerConfigurator.php, lib/Segments/DynamicSegments/FilterDataMapper.php, lib/Segments/DynamicSegments/FilterFactory.php, lib/Segments/DynamicSegments/Filters/MailPoetCustomFields.php, tests/DataFactories/CustomField.php, tests/acceptance/Segments/MailPoetCustomFieldSegmentCest.php, tests/acceptance/Segments/ManageSegmentsCest.php, tests/integration/Segments/DynamicSegments/Filters/MailPoetCustomFieldsTest.php, views/segments.html
[MAILPOET-3220]
[MAILPOET-3220]: https://mailpoet.atlassian.net/browse/MAILPOET-3220
=> Segment MailPoet custom field [MAILPOET-3220]

lib/API/JSON/v1/Forms.php, tests/integration/API/JSON/v1/FormsTest.php
[MAILPOET-3037]
[MAILPOET-3037]: https://mailpoet.atlassian.net/browse/MAILPOET-3037
=> Forms doctrine refactor [MAILPOET-3037]

lib/Cron/Workers/SendingQueue/SendingQueue.php
[MAILPOET-3608]
[MAILPOET-3608]: https://mailpoet.atlassian.net/browse/MAILPOET-3608
=> Use the inProgress flag for lock sending task [MAILPOET-3608]

.babelrc, package-lock.json, package.json
[MAILPOET-3622]
[MAILPOET-3622]: https://mailpoet.atlassian.net/browse/MAILPOET-3622
=> Drop ie [MAILPOET-3622]

lib/Form/DisplayFormInWPContent.php, tests/unit/Form/DisplayFormInWPContentTest.php
[MAILPOET-3385]
[MAILPOET-3385]: https://mailpoet.atlassian.net/browse/MAILPOET-3385
=> Use a filter for form display [MAILPOET-3385]

lib/Config/Activator.php, lib/Config/Initializer.php, tests/integration/API/JSON/v1/SetupTest.php
[MAILPOET-3537]
[MAILPOET-3537]: https://mailpoet.atlassian.net/browse/MAILPOET-3537
=> Use WP transient for lock running migrations [MAILPOET-3537]

assets/js/src/newsletters/listings/heading_steps.tsx
[MAILPOET-3615]
[MAILPOET-3615]: https://mailpoet.atlassian.net/browse/MAILPOET-3615
=> Fix warnings on the newsletter editor page [MAILPOET-3615]

lib/Newsletter/AutomatedLatestContent.php
[MAILPOET-3542]
[MAILPOET-3542]: https://mailpoet.atlassian.net/browse/MAILPOET-3542
=> Fix getting automated content for type media [MAILPOET-3542]

lib/Services/Bridge/API.php
[MAILPOET-3621]
[MAILPOET-3621]: https://mailpoet.atlassian.net/browse/MAILPOET-3621
=> Add curl error logging for MSS messages api calls [MAILPOET-3621]

assets/css/src/components-editor/content-blocks/_unknown_block_fallback.scss, assets/css/src/mailpoet-editor.scss, assets/js/src/newsletter_editor/blocks/unknownBlockFallback.js, assets/js/src/newsletter_editor/components/content.js, assets/js/src/newsletter_editor/webpack_index.jsx, lib/Newsletter/Renderer/Blocks/Renderer.php, lib/Newsletter/Renderer/Columns/Renderer.php, views/newsletter/editor.html, views/newsletter/templates/blocks/unknownBlockFallback/block.hbs, views/newsletter/templates/blocks/unknownBlockFallback/widget.hbs
[MAILPOET-3437]
[MAILPOET-3437]: https://mailpoet.atlassian.net/browse/MAILPOET-3437
=> Gracefully handle unsupported Email Editor blocks [MAILPOET-3437]

lib/API/JSON/v1/Forms.php, lib/Form/FormsRepository.php
[MAILPOET-3630]
[MAILPOET-3630]: https://mailpoet.atlassian.net/browse/MAILPOET-3630
=> Refactor form bulk action to Doctrine [MAILPOET-3630]

assets/css/src/components-public/_public.scss
[MAILPOET-3611]
[MAILPOET-3611]: https://mailpoet.atlassian.net/browse/MAILPOET-3611
Note for QA:
Please check if this change doesn't break images in form templates in some favorite themes.
=> Add max-width for form images [MAILPOET-3611]

lib/Util/Notices/PHPVersionWarnings.php, tests/integration/Util/Notices/PHPVersionWarningsTest.php
[MAILPOET-3641]
[MAILPOET-3641]: https://mailpoet.atlassian.net/browse/MAILPOET-3641
=> Remove upgrade offer [MAILPOET-3641]

composer.json, composer.lock
[MAILPOET-3549]
[MAILPOET-3549]: https://mailpoet.atlassian.net/browse/MAILPOET-3549
=> Upgrade Robo [MAILPOET-3549]

assets/js/src/newsletter_editor/components/heading.js
[MAILPOET-3564]
[MAILPOET-3564]: https://mailpoet.atlassian.net/browse/MAILPOET-3564
=> Change the event for updating email header [MAILPOET-3564]

lib/API/JSON/v1/Settings.php, lib/Config/Populator.php, lib/DI/ContainerConfigurator.php, lib/Form/FormMessageController.php, lib/Settings/SettingsController.php, tests/DataFactories/Form.php, tests/_support/AcceptanceTester.php, tests/integration/API/JSON/v1/SettingsTest.php, tests/integration/Form/FormMessageControllerTest.php, tests/integration/Models/FormTest.php, tests/integration/Settings/SettingsControllerTest.php
[MAILPOET-3643]
[MAILPOET-3643]: https://mailpoet.atlassian.net/browse/MAILPOET-3643
=> Remove dependencies from SettingsController [MAILPOET-3643]

lib/Segments/SegmentSubscribersRepository.php
[MAILPOET-3647]
[MAILPOET-3647]: https://mailpoet.atlassian.net/browse/MAILPOET-3647
=> Fix SQL query for subscribers without list [MAILPOET-3647]

lib/DI/ContainerConfigurator.php, lib/Entities/LogEntity.php, lib/Logging/LogHandler.php, lib/Logging/LogRepository.php, lib/Logging/LoggerFactory.php, lib/Models/Log.php, tests/integration/Logging/LogHandlerTest.php, tests/integration/_bootstrap.php, tests/unit/Logging/LoggerFactoryTest.php
[MAILPOET-3624]
[MAILPOET-3624]: https://mailpoet.atlassian.net/browse/MAILPOET-3624
=> Refactor logs to Doctrine [MAILPOET-3624]

lib/Config/Migrator.php
[MAILPOET-3651]
[MAILPOET-3651]: https://mailpoet.atlassian.net/browse/MAILPOET-3651
=> Add migration for missing updated_at on scheduled_task_subscribers [MAILPOET-3651]

lib/Config/Activator.php, lib/Config/Initializer.php
[MAILPOET-3656]
[MAILPOET-3656]: https://mailpoet.atlassian.net/browse/MAILPOET-3656
=> Add error handling for activation hook [MAILPOET-3656]

lib/WooCommerce/TransactionalEmailHooks.php, tests/integration/WooCommerce/TransactionalEmailHooksTest.php
[MAILPOET-3017]
[MAILPOET-3017]: https://mailpoet.atlassian.net/browse/MAILPOET-3017
=> Gracefully handle missing WC transactional template [MAILPOET-3017]

lib/Segments/DynamicSegments/Filters/EmailOpensAbsoluteCountAction.php
[MAILPOET-3668]
[MAILPOET-3668]: https://mailpoet.atlassian.net/browse/MAILPOET-3668
=> Move the aggregate function count to the having clause [MAILPOET-3668]

lib/Segments/WP.php, tests/integration/Segments/WPTest.php
This commit should revert functionality from the ticket MAILPOET-2134
[MAILPOET-3515]
[MAILPOET-3515]: https://mailpoet.atlassian.net/browse/MAILPOET-3515
=> Remove changing WP users status as unconfirmed [MAILPOET-3515]

README.md, RoboFile.php
[MAILPOET-3500]
[MAILPOET-3500]: https://mailpoet.atlassian.net/browse/MAILPOET-3500
=> Remove `./do watch` task [MAILPOET-3500]

assets/css/src/components-admin/_menu.scss
[MAILPOET-3648]
[MAILPOET-3648]: https://mailpoet.atlassian.net/browse/MAILPOET-3648
=> Set max-width for WP admin menu image icons [MAILPOET-3648]

assets/js/src/segments/dynamic/editor.tsx, assets/js/src/segments/dynamic/form.tsx, assets/js/src/segments/dynamic/subscribers_calculator.ts, lib/API/JSON/v1/DynamicSegments.php, tests/integration/API/JSON/v1/DynamicSegmentsTest.php
[MAILPOET-3649]
[MAILPOET-3559]
[MAILPOET-3650]
[MAILPOET-3649]: https://mailpoet.atlassian.net/browse/MAILPOET-3649
[MAILPOET-3559]: https://mailpoet.atlassian.net/browse/MAILPOET-3559
[MAILPOET-3650]: https://mailpoet.atlassian.net/browse/MAILPOET-3650
=> Dynamic segment empty name [MAILPOET-3649][MAILPOET-3559][MAILPOET-3650]

lib/Subscribers/SubscriberActions.php, lib/Subscription/Pages.php, tests/integration/Subscription/PagesTest.php
[MAILPOET-3659]
[MAILPOET-3659]: https://mailpoet.atlassian.net/browse/MAILPOET-3659
=> Fix duplicate new subscriber notifications [MAILPOET-3659]

assets/js/src/form_editor/components/preview/preview.tsx
[MAILPOET-3636]
[MAILPOET-3636]: https://mailpoet.atlassian.net/browse/MAILPOET-3636
=> Hide beacon in the form preview window [MAILPOET-3636]

lib/Subscription/Pages.php
[MAILPOET-3670]
[MAILPOET-3670]: https://mailpoet.atlassian.net/browse/MAILPOET-3670
=> Prevent Doctrine error for malformed unsubscribe url [MAILPOET-3670]

lib/Util/Notices/DeprecatedShortcodeNotice.php, lib/Util/Notices/PermanentNotices.php
[MAILPOET-3672]
[MAILPOET-3672]: https://mailpoet.atlassian.net/browse/MAILPOET-3672
=> Fix dismissing outdated shortcodes notice [MAILPOET-3672]

.circleci/config.yml, RoboFile.php, tests/javascript_newsletter_editor/mochaTestHelper.js, tests/javascript_newsletter_editor/newsletter_editor/blocks/container.spec.js, tests/javascript_newsletter_editor/newsletter_editor/blocks/image.spec.js, tests/javascript_newsletter_editor/newsletter_editor/blocks/products.spec.js, tests/javascript_newsletter_editor/newsletter_editor/components/heading.spec.js, tests/javascript_newsletter_editor/newsletter_editor/components/save.spec.js, webpack.config.js
[MAILPOET-3673]
[MAILPOET-3673]: https://mailpoet.atlassian.net/browse/MAILPOET-3673
=> Fix newsletter editor tests [MAILPOET-3673]

tests/acceptance/Misc/MailpoetMenuCest.php
[MAILPOET-3677](https://mailpoet.atlassian.net/browse/MAILPOET-3677)
=> Fix flaky acceptance test mailpoet menus [MAILPOET-3677]

tests/acceptance/Segments/ManageSegmentsCest.php
[MAILPOET-3680](https://mailpoet.atlassian.net/browse/MAILPOET-3680)
=> Fix flaky acceptance test ManageSegmentsCest [MAILPOET-3680]

tests/acceptance/Subscribers/ManageSubscribersCest.php
[MAILPOET-3679](https://mailpoet.atlassian.net/browse/MAILPOET-3679)
=> Fix flaky acceptance test ManageSubscribersCest [MAILPOET-3679]

tests/acceptance/Segments/ManageSegmentsCest.php
[MAILPOET-3689](https://mailpoet.atlassian.net/browse/MAILPOET-3689)
=> Update ManageSegmentsCest scenario to have better titles [MAILPOET-3689]

views/newsletters.html, views/welcome_wizard.html
[MAILPOET-3704]
[MAILPOET-3704]: https://mailpoet.atlassian.net/browse/MAILPOET-3704
=> Fix sign up button in wizard step 4 [MAILPOET-3704]

tests/acceptance/Settings/AddSendingKeyCest.php
[MAILPOET-3681]
[MAILPOET-3681]: https://mailpoet.atlassian.net/browse/MAILPOET-3681
=> Update MSS testing address  [MAILPOET-3681]

lib/Subscription/CaptchaRenderer.php
[MAILPOET-3698]
[MAILPOET-3698]: https://mailpoet.atlassian.net/browse/MAILPOET-3698
=> Encode value before printing it [MAILPOET-3698]

readme.txt
[MAILPOET-3711]
[MAILPOET-3711]: https://mailpoet.atlassian.net/browse/MAILPOET-3711
=> Bump "Tested up to" version to 5.8 [MAILPOET-3711]

tests/_support/AcceptanceTester.php, tests/acceptance/Newsletters/StatsPageCest.php
[MAILPOET-3723]
[MAILPOET-3723]: https://mailpoet.atlassian.net/browse/MAILPOET-3723
=> Skip StatPage acceptance test when Premium is active [MAILPOET-3723]

lib/API/JSON/v1/Settings.php, lib/Cache/TransientCache.php, lib/Cron/Workers/SubscribersCountCacheRecalculation.php, lib/Subscribers/SubscribersCountsController.php
[MAILPOET-3714]
[MAILPOET-3714]: https://mailpoet.atlassian.net/browse/MAILPOET-3714
=> Add cleanup subscribers counts cache [MAILPOET-3714]

lib/Segments/WP.php, tests/integration/Segments/WPTest.php
This PR addresses only the issue with subscribers being moved to trash after registration on the checkout page.
Problems with the incorrect global state and confirmation email will be addressed in [a different ticket](https://mailpoet.atlassian.net/browse/MAILPOET-3657).
[MAILPOET-3695]
[MAILPOET-3695]: https://mailpoet.atlassian.net/browse/MAILPOET-3695
=> Prevent trashing customer users when WP segment is inactive [MAILPOET-3695]

lib/Form/DisplayFormInWPContent.php
[MAILPOET-3639]
[MAILPOET-3639]: https://mailpoet.atlassian.net/browse/MAILPOET-3639
=> Allow form on the job_listing post type [MAILPOET-3639]

lib/Newsletter/Shortcodes/Categories/Link.php
[MAILPOET-3464]
[MAILPOET-3464]: https://mailpoet.atlassian.net/browse/MAILPOET-3464
=> Use entities instead of old models in link shortcode filter [MAILPOET-3464]

lib/Config/PersonalDataExporters.php
[MAILPOET-3702]
[MAILPOET-3702]: https://mailpoet.atlassian.net/browse/MAILPOET-3702
=> Fix getting NewsletterExporter instance in PersonalDataExporters [MAILPOET-3702]

assets/js/src/form_editor/components/form_settings/basic_settings_panel.jsx, assets/js/src/newsletters/send/notification.jsx, assets/js/src/newsletters/send/standard.jsx, assets/js/src/newsletters/types/welcome/scheduling.jsx, assets/js/src/settings/components/segments_select.tsx, assets/js/src/subscribers/heading.jsx, lib/AdminPages/Pages/Subscribers.php, lib/Models/Subscriber.php, lib/Subscribers/SubscriberListingRepository.php, tests/integration/API/JSON/v1/SubscribersTest.php, tests/integration/Subscribers/SubscriberListingRepositoryTest.php, views/subscribers/subscribers.html
[MAILPOET-3708]
[MAILPOET-3708]: https://mailpoet.atlassian.net/browse/MAILPOET-3708
=> Remove "~" character from counts [MAILPOET-3708]

lib/Config/Menu.php, lib/Newsletter/Renderer/Blocks/Button.php, lib/Newsletter/Renderer/Renderer.php, tests/integration/Newsletter/RendererTest.php, tests/integration/_fixtures.php, tests/unit/Newsletter/Renderer/Blocks/ButtonTest.php
[MAILPOET-3468]
[MAILPOET-3468]: https://mailpoet.atlassian.net/browse/MAILPOET-3468
QA: This PR contains a few rendering bug fixes, please take a look at rendering emails in different browsers. I have tried to compare master and this branch on Litmus. Unfortunately, I don't have access to Outlook 2016 with the possibility of redirecting.
=> Outlook 2016 Rendering Bug in forwarded mail [MAILPOET-3468]

assets/js/src/newsletter_editor/blocks/products.js
[MAILPOET-3727]
[MAILPOET-3727]: https://mailpoet.atlassian.net/browse/MAILPOET-3727
=> Fix deleting Products block in the newsletter editor [MAILPOET-3727]

assets/js/src/common/datepicker/_stories/datepicker.tsx, assets/js/src/common/datepicker/datepicker.tsx, assets/js/src/mailpoet.js, assets/js/src/newsletters/send/date_text.jsx, package-lock.json, package.json, views/layout.html, views/newsletters.html
Update also @types/react-datepicker to latest to include calendarStartDay.
[MAILPOET-3703]
[MAILPOET-3703]: https://mailpoet.atlassian.net/browse/MAILPOET-3703
=> Set calendarStartDay in DateText to WP "week starts on" [MAILPOET-3703]

lib/Config/Migrator.php, lib/DI/ContainerConfigurator.php, lib/Entities/StatisticsClickEntity.php, lib/Entities/StatisticsOpenEntity.php, lib/Entities/UserAgentEntity.php, lib/Models/StatisticsClicks.php, lib/Router/Endpoints/Track.php, lib/Statistics/StatisticsClicksRepository.php, lib/Statistics/Track/Clicks.php, lib/Statistics/Track/Opens.php, lib/Statistics/UserAgentsRepository.php, tests/integration/Statistics/Track/ClicksTest.php, tests/integration/Statistics/Track/OpensTest.php
[MAILPOET-3735]
[MAILPOET-3735]: https://mailpoet.atlassian.net/browse/MAILPOET-3735
=> Save user agent on tracking [MAILPOET-3735]

lib/Entities/SubscriberEntity.php, tests/integration/Subscribers/SubscriberSaveControllerTest.php
[MAILPOET-3652]
[MAILPOET-3652]: https://mailpoet.atlassian.net/browse/MAILPOET-3652
=> Remove invalid subscriber segments when editing a subscriber [MAILPOET-3652]

lib/Router/Router.php, tests/integration/Router/RouterTest.php
[MAILPOET-3699]
[MAILPOET-3699]: https://mailpoet.atlassian.net/browse/MAILPOET-3699
=> Check that data are not array before base64 decoding [MAILPOET-3699]

tests/DataGenerator/Generators/WooCommercePastRevenues.php
To test:
* Run `./do generate:data` on the docker env.
* Check the error is gone and there are no other errors
* Go to _MailPoet > Emails_
* Verify that the emails have been generated with the associated data
Note: I haven't converted everything, just enough to make it work.
[MAILPOET-3682]
[MAILPOET-3682]: https://mailpoet.atlassian.net/browse/MAILPOET-3682
=> Fix generate data command [MAILPOET-3682]

lib/Subscribers/ConfirmationEmailMailer.php
[MAILPOET-3756]
[MAILPOET-3756]: https://mailpoet.atlassian.net/browse/MAILPOET-3756
=> Ignore Html2Text::convert errors in confirmation email [MAILPOET-3756]

lib/API/JSON/v1/ImportExport.php, lib/Newsletter/Sending/ScheduledTasksRepository.php, tests/integration/API/JSON/v1/ImportExportTest.php
[MAILPOET-3625]
[MAILPOET-3625]: https://mailpoet.atlassian.net/browse/MAILPOET-3625
=> Refactor ImportExport API to Doctrine [MAILPOET-3625]

tests/acceptance/Newsletters/StatsPageCest.php
[MAILPOET-3723]
[MAILPOET-3723]: https://mailpoet.atlassian.net/browse/MAILPOET-3723
=> Run the test only if premium plugin is not present [MAILPOET-3723]

assets/js/src/segments/dynamic/dynamic_segments_filters/email_statistics.tsx, lib/API/JSON/v1/NewsletterLinks.php
This endpoint is used in the segments form to load all links for a newsletter. https://d.pr/i/TmWRba
[MAILPOET-3626]
[MAILPOET-3626]: https://mailpoet.atlassian.net/browse/MAILPOET-3626
=> Refactor \MailPoet\API\JSON\v1\NewsletterLinks::get to Doctrine [MAILPOET-3626]

lib/Mailer/WordPress/PHPMailerLoader.php
[MAILPOET-3769]
[MAILPOET-3769]: https://mailpoet.atlassian.net/browse/MAILPOET-3769
=> Fix a conflict when PhpMailer is already defined [MAILPOET-3769]

assets/js/src/subscribers/heading.jsx, assets/js/src/subscribers/list.jsx
[MAILPOET-3754]
[MAILPOET-3754]: https://mailpoet.atlassian.net/browse/MAILPOET-3754
=> Move subscribers cache note down [MAILPOET-3754]

assets/css/src/components-plugin/_listing-newsletters.scss, assets/js/src/common/listings/newsletter_stats.tsx, tests/acceptance/Newsletters/NewslettersListingCest.php, views/newsletters.html
[MAILPOET-3739]
Note: Point 2c was already done in https://mailpoet.atlassian.net/browse/MAILPOET-3736
[MAILPOET-3739]: https://mailpoet.atlassian.net/browse/MAILPOET-3739
=> Newsletter listing stats UI changes [MAILPOET-3739]

assets/js/src/newsletters/campaign_stats/newsletter_general_stats.tsx, assets/js/src/newsletters/campaign_stats/newsletter_type.ts, lib/API/JSON/ResponseBuilders/NewslettersResponseBuilder.php, lib/Newsletter/Statistics/NewsletterStatistics.php, lib/Newsletter/Statistics/NewsletterStatisticsRepository.php, tests/integration/API/JSON/ResponseBuilders/NewslettersResponseBuilderTest.php, views/newsletters.html
[MAILPOET-3740]
[MAILPOET-3740]: https://mailpoet.atlassian.net/browse/MAILPOET-3740
=> Email stats page UI changes [MAILPOET-3740]

lib/WooCommerce/Subscription.php
[MAILPOET-3772]
[MAILPOET-3772]: https://mailpoet.atlassian.net/browse/MAILPOET-3772
=> Fix subscriber status in subscription via checkout for older WooCommerce [MAILPOET-3772]

lib/WooCommerce/TransactionalEmailHooks.php, lib/WooCommerce/TransactionalEmails/Renderer.php, tests/integration/WooCommerce/TransactionalEmailHooksTest.php, tests/integration/WooCommerce/TransactionalEmails/RendererTest.php
[MAILPOET-3758]
[MAILPOET-3758]: https://mailpoet.atlassian.net/browse/MAILPOET-3758
=> Fix heading rendering in woo email [MAILPOET-3758]

assets/css/src/components-plugin/_subscribers.scss, assets/js/src/help-tooltip.jsx, assets/js/src/subscribers/stats.tsx, assets/js/src/subscribers/stats/summary.tsx, lib/API/JSON/v1/SubscriberStats.php, lib/Subscribers/Statistics/SubscriberStatistics.php, lib/Subscribers/Statistics/SubscriberStatisticsRepository.php, views/subscribers/subscribers.html
This task required also some changes in the premium plugin https://github.com/mailpoet/mailpoet-premium/pull/484
[MAILPOET-3741]
[MAILPOET-3741]: https://mailpoet.atlassian.net/browse/MAILPOET-3741
=> Add machine opens to subscriber stats [MAILPOET-3741]

lib/Subscription/Pages.php
[MAILPOET-3730]
[MAILPOET-3730]: https://mailpoet.atlassian.net/browse/MAILPOET-3730
=> Fix unsubscribe URL for preview when the user isn't logged in [MAILPOET-3730]

assets/js/src/newsletters/send/welcome.jsx, tests/acceptance/Newsletters/CreateWelcomeEmailCest.php, views/newsletters.html
[MAILPOET-3781]
[MAILPOET-3781]: https://mailpoet.atlassian.net/browse/MAILPOET-3781
=> Change header string used when setting up Welcome Emails [MAILPOET-3781]

assets/js/src/segments/dynamic/dynamic_segments_filters/email.tsx, assets/js/src/segments/dynamic/types.ts, lib/Segments/DynamicSegments/FilterDataMapper.php, lib/Segments/DynamicSegments/Filters/EmailAction.php, lib/Segments/DynamicSegments/Filters/EmailOpensAbsoluteCountAction.php, tests/integration/Segments/DynamicSegments/Filters/EmailActionTest.php, tests/integration/Segments/DynamicSegments/Filters/EmailOpensAbsoluteCountActionTest.php, views/segments.html
[MAILPOET-3737]
[MAILPOET-3737]: https://mailpoet.atlassian.net/browse/MAILPOET-3737
=> Machine opens segment [MAILPOET-3737]

lib/API/JSON/v1/ImportExport.php, lib/API/JSON/v1/Segments.php, lib/Cron/CronWorkerScheduler.php, lib/Cron/Workers/WooCommerceSync.php, lib/Newsletter/Sending/ScheduledTasksRepository.php, tests/integration/Cron/CronWorkerSchedulerTest.php
[MAILPOET-3726]
[MAILPOET-3726]: https://mailpoet.atlassian.net/browse/MAILPOET-3726
=> Disable automatic rescheduling of Woo Customers sync [MAILPOET-3726]

RoboFile.php, lib/Config/Migrator.php, lib/Cron/Workers/Bounce.php, lib/DI/ContainerConfigurator.php, lib/Entities/StatisticsBounceEntity.php, lib/Newsletter/Sending/ScheduledTasksRepository.php, lib/Newsletter/Sending/SendingQueuesRepository.php, lib/Statistics/StatisticsBouncesRepository.php, lib/Subscribers/SubscribersRepository.php, tests/integration/Cron/Workers/BounceTest.php
[MAILPOET-3765]
[MAILPOET-3765]: https://mailpoet.atlassian.net/browse/MAILPOET-3765
=> Save bounce statistics [MAILPOET-3765]

assets/js/src/subscribers/stats.tsx, lib/API/JSON/v1/SubscriberStats.php, views/subscribers/subscribers.html
[MAILPOET-3770]
[MAILPOET-3770]: https://mailpoet.atlassian.net/browse/MAILPOET-3770
=> Display the last engagement on the subscribers stats page [MAILPOET-3770]

lib/Form/Util/CustomFonts.php
We have a conflict with WooCommerce Payments plugin. When the file with custom fonts is bigger than 10kB, the payment form isn't loaded.
[MAILPOET-3791]
The fix is available on[ my testing site](https://lysyjan.wpcomstaging.com/).
[MAILPOET-3791]: https://mailpoet.atlassian.net/browse/MAILPOET-3791
=> Load custom fonts in chunks [MAILPOET-3791]

assets/js/src/segments/dynamic/form.tsx, assets/js/src/segments/dynamic/privacy_protection_notice.tsx, views/segments.html
[MAILPOET-3742]
[MAILPOET-3742]: https://mailpoet.atlassian.net/browse/MAILPOET-3742
=> Add component with privacy protection notice [MAILPOET-3742]

lib/Cron/Workers/SubscribersLastEngagement.php
[MAILPOET-3795]
[MAILPOET-3795]: https://mailpoet.atlassian.net/browse/MAILPOET-3795
=> Fix Truncated incorrect DOUBLE error in SQL for last engagement date [MAILPOET-3795]

assets/js/src/listing/notices.jsx, lib/Mailer/MailerError.php, lib/Mailer/Methods/ErrorMappers/MailPoetMapper.php, tests/unit/Mailer/Methods/ErrorMappers/MailPoetMapperTest.php, views/newsletters.html
[MAILPOET-3667]
[MAILPOET-3667]: https://mailpoet.atlassian.net/browse/MAILPOET-3667
=> Display a specific error message for banned users [MAILPOET-3667]

lib/Newsletter/Statistics/NewsletterStatisticsRepository.php
[MAILPOET-3797]
[MAILPOET-3797]: https://mailpoet.atlassian.net/browse/MAILPOET-3797
=> Fix machine opens counter [MAILPOET-3797]

assets/css/src/components-form-editor/_sidebar.scss
[MAILPOET-3666]
[MAILPOET-3666]: https://mailpoet.atlassian.net/browse/MAILPOET-3666
=> Fix displaying horizontal scrollbar in Firefox [MAILPOET-3666]

assets/js/src/newsletters/campaign_stats/newsletter_general_stats.tsx, assets/js/src/newsletters/campaign_stats/newsletter_type.ts, lib/Newsletter/Statistics/NewsletterStatistics.php, lib/Newsletter/Statistics/NewsletterStatisticsRepository.php, tests/integration/API/JSON/ResponseBuilders/NewslettersResponseBuilderTest.php, views/newsletters.html
[MAILPOET-3766]
[MAILPOET-3766]: https://mailpoet.atlassian.net/browse/MAILPOET-3766
=> Show bounce percentage in Email Stats page [MAILPOET-3766]

composer.json, composer.lock
[MAILPOET-3799]
[MAILPOET-3799]: https://mailpoet.atlassian.net/browse/MAILPOET-3799
=> Update lucatume/wp-browser [MAILPOET-3799]

assets/js/src/public.jsx, lib/Form/Block/BlockRendererHelper.php, tests/acceptance/Forms/GutenbergFormBlockCest.php, tests/integration/Subscription/ManageSubscriptionFormRendererTest.php
[MAILPOET-3786]
[MAILPOET-3786]: https://mailpoet.atlassian.net/browse/MAILPOET-3786
=> Add custom validation for names in forms [MAILPOET-3786]

lib/Config/Env.php
[MAILPOET-3798]
[MAILPOET-3798]: https://mailpoet.atlassian.net/browse/MAILPOET-3798
=> Add a WP filter to let users change the MP prefix for DB tables [MAILPOET-3798]

assets/js/src/newsletters/campaign_stats/page.tsx, tests/DataFactories/StatisticsBounces.php, views/newsletters.html
[PREMIUM-154]
[PREMIUM-154]: https://mailpoet.atlassian.net/browse/PREMIUM-154
=> Add bounce tab on stats page [PREMIUM-154]

tests/DataFactories/StatisticsBounces.php
[PREMIUM-154]
[PREMIUM-154]: https://mailpoet.atlassian.net/browse/PREMIUM-154
=> Fix coding style in StatisticsBounces data factory [PREMIUM-154]

.circleci/config.yml
[MAILPOET-3595]
[MAILPOET-3595]: https://mailpoet.atlassian.net/browse/MAILPOET-3595
=> Remove test deployment [MAILPOET-3595]

assets/js/src/segments/dynamic/form.tsx
[MAILPOET-3794]
[MAILPOET-3794]: https://mailpoet.atlassian.net/browse/MAILPOET-3794
=> Use property value instead of defaultValue [MAILPOET-3794]

assets/js/src/form_editor/store/selectors.jsx, assets/js/src/form_editor/store/store.jsx, lib/AdminPages/Pages/FormEditor.php, views/form/editor.html
[MAILPOET-3675]
[MAILPOET-3675]: https://mailpoet.atlassian.net/browse/MAILPOET-3675
=> Remove mailpoet pages from the 'After submit' option [MAILPOET-3675]

RoboFile.php
[MAILPOET-3828]
[MAILPOET-3828]: https://mailpoet.atlassian.net/browse/MAILPOET-3828
=> Remove version detection from svn:publish command [MAILPOET-3828]

lib/Form/Widget.php
[MAILPOET-3837]
[MAILPOET-3837]: https://mailpoet.atlassian.net/browse/MAILPOET-3837
=> Check if the form id is missing in the widget [MAILPOET-3837]

lib/Subscribers/InactiveSubscribersController.php, tests/integration/Cron/Workers/InactiveSubscribersTest.php, tests/integration/Subscribers/InactiveSubscribersControllerTest.php
[MAILPOET-3774]
[MAILPOET-3774]: https://mailpoet.atlassian.net/browse/MAILPOET-3774
=> Inactive subscribers improvements [MAILPOET-3774]

assets/js/src/newsletters/types/welcome/scheduling.jsx
[MAILPOET-3832]
[MAILPOET-3832]: https://mailpoet.atlassian.net/browse/MAILPOET-3832
=> Forbid non-numeric values for scheduling welcome emails [MAILPOET-3832]

.storybook/main.js, package-lock.json, package.json
We needed to add a few additional packages that enable configuring support for Webpack 5.
[MAILPOET-3826]
[MAILPOET-3826]: https://mailpoet.atlassian.net/browse/MAILPOET-3826
=> Switch storybook builds to Webpack 5 [MAILPOET-3826]

lib/Newsletter/Editor/PostContentManager.php, lib/Newsletter/Renderer/Blocks/Text.php, tests/integration/Newsletter/Editor/PostContentManagerTest.php, tests/unit/Newsletter/Renderer/Blocks/TextTest.php
[MAILPOET-3474]
[MAILPOET-3474]: https://mailpoet.atlassian.net/browse/MAILPOET-3474
=> Fix spacing between heading and paragraph in the ALC block [MAILPOET-3474]

lib/API/MP/v1/API.php, lib/API/MP/v1/CustomFields.php, lib/DI/ContainerConfigurator.php, tests/integration/API/MP/APITest.php, tests/integration/API/MP/CustomFieldsTest.php
[MAILPOET-3628]
[MAILPOET-3628]: https://mailpoet.atlassian.net/browse/MAILPOET-3628
=> Refactor API subscriber fields methods to Doctrine [MAILPOET-3628]

lib/Newsletter/Editor/PostContentManager.php, lib/WP/Functions.php
[MAILPOET-3671]
[MAILPOET-3671]: https://mailpoet.atlassian.net/browse/MAILPOET-3671
=> Use WP functions to get content and excerpt [MAILPOET-3671]

lib/Config/Populator.php
[MAILPOET-3892]
[MAILPOET-3892]: https://mailpoet.atlassian.net/browse/MAILPOET-3892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Schedule last engagement detection again [MAILPOET-3892]

assets/js/src/settings/components/pages_select.tsx, assets/js/src/settings/pages/basics/basics.tsx, assets/js/src/settings/pages/basics/re_engagement_page.tsx, assets/js/src/settings/store/normalize_settings.ts, assets/js/src/settings/store/types.ts, lib/Router/Endpoints/Subscription.php, lib/Settings/Pages.php, lib/Subscription/Pages.php, views/settings.html
[MAILPOET-3856]
[MAILPOET-3856]: https://mailpoet.atlassian.net/browse/MAILPOET-3856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add re-engagement page [MAILPOET-3856]

lib/Form/Block/BlockRendererHelper.php, lib/Form/Block/Checkbox.php
[MAILPOET-3858](https://mailpoet.atlassian.net/browse/MAILPOET-3858)
=> Fixed uncheck status not saved in Manage subscriptions page MAILPOET-3858

lib/Config/ServicesChecker.php, lib/Cron/Daemon.php, lib/Cron/Triggers/WordPress.php, lib/Cron/Workers/KeyCheck/SendingServiceKeyCheck.php, lib/Cron/Workers/SubscribersStatsReport.php, lib/Cron/Workers/WorkersFactory.php, lib/DI/ContainerConfigurator.php, lib/Logging/LoggerFactory.php, lib/Services/Bridge.php, lib/Services/Bridge/API.php, tests/integration/Config/ServicesCheckerTest.php, tests/integration/Cron/DaemonHttpRunnerTest.php, tests/integration/Cron/DaemonTest.php, tests/integration/Cron/Workers/KeyCheck/SendingServiceKeyCheckTest.php, tests/integration/Cron/Workers/SubscribersStatsReportTest.php, tests/integration/Services/BridgeTest.php, tests/integration/Services/BridgeTestMockAPI.php
[MAILPOET-3868]
[MAILPOET-3868]: https://mailpoet.atlassian.net/browse/MAILPOET-3868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Subscribers counts reporting [MAILPOET-3868]

lib/DI/ContainerConfigurator.php, lib/DI/ContainerWrapper.php, lib/Doctrine/EntityManagerFactory.php, lib/Logging/LogHandler.php, lib/Logging/LoggerFactory.php, tests/integration/Logging/LogHandlerTest.php, tests/unit/DI/ContainerWrapperTest.php, tests/unit/Logging/LoggerFactoryTest.php
[MAILPOET-3833]
[MAILPOET-3833]: https://mailpoet.atlassian.net/browse/MAILPOET-3833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Recreate entityManager in LogHandler when is closed [MAILPOET-3833]

assets/css/src/components/_parsley.scss, assets/js/src/newsletters/automatic_emails/events/event_scheduling.jsx, assets/js/src/newsletters/send/date_text.jsx, assets/js/src/newsletters/send/date_time.jsx, assets/js/src/newsletters/send/standard.jsx, assets/js/src/newsletters/types/welcome/scheduling.jsx, assets/js/src/parsley-validators.jsx, assets/js/src/webpack_mailpoet_index.jsx, lib/Newsletter/Scheduler/Scheduler.php, tests/unit/Newsletter/Scheduler/SchedulerTest.php, views/newsletters.html
[MAILPOET-3818]
[MAILPOET-3818]: https://mailpoet.atlassian.net/browse/MAILPOET-3818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add limitation for scheduled_at [MAILPOET-3818]

lib/Subscribers/ImportExport/Export/Export.php, tests/integration/Subscribers/ImportExport/Export/ExportTest.php
[MAILPOET-3852](https://mailpoet.atlassian.net/browse/MAILPOET-3852)
=> Include list column for excel subscribers export [MAILPOET-3852]

lib/Util/ConflictResolver.php
[MAILPOET-3854]
[MAILPOET-3854]: https://mailpoet.atlassian.net/browse/MAILPOET-3854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow loading CSS for Woo Payments and AutomateWoo [MAILPOET-3854]

RoboFile.php, tasks/release/TranslationsController.php
[MAILPOET-3806]
[MAILPOET-3806]: https://mailpoet.atlassian.net/browse/MAILPOET-3806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prepare translations before the release [MAILPOET-3806]

assets/css/src/generic/_forms-select.scss, assets/js/src/common/form/react_select/react_select.tsx, package-lock.json, package.json
[MAILPOET-3834]
**For QA:** 
React Select is used in settings (list selections) and dynamic segments (filters). Please make sure both single- and multi-value selects work and look good.
[MAILPOET-3834]: https://mailpoet.atlassian.net/browse/MAILPOET-3834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Upgrade react-select [MAILPOET-3834]

lib/Config/Migrator.php, lib/Entities/DynamicSegmentFilterData.php
[MAILPOET-3910]
[MAILPOET-3910]: https://mailpoet.atlassian.net/browse/MAILPOET-3910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Increase a version for migration execution [MAILPOET-3910]

lib/API/JSON/v1/Subscribers.php
[MAILPOET-3865]
[MAILPOET-3865]: https://mailpoet.atlassian.net/browse/MAILPOET-3865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Improve error message [MAILPOET-3865]

assets/css/src/components-plugin/_newsletter-templates.scss, assets/js/src/newsletters/templates/import_template.jsx
[MAILPOET-3492 ](https://mailpoet.atlassian.net/browse/MAILPOET-3492)
=> Center the content on import newsletter template page - MAILPOET-3492

assets/css/src/components-form-editor/_block-editor.scss
[MAILPOET-3882](https://mailpoet.atlassian.net/browse/MAILPOET-3882)
=> Fix Block toolbar hides under the main top bar in the form editor MAILPOET-3882

lib/Segments/SegmentsRepository.php, tests/integration/Segments/SegmentsRepositoryTest.php
[MAILPOET-3922]
[MAILPOET-3922]: https://mailpoet.atlassian.net/browse/MAILPOET-3922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix fetching count of segments with multiple filters [MAILPOET-3922]

assets/css/src/components-public/_public.scss, assets/js/src/public.jsx, lib/Form/Renderer.php
[MAILPOET-3279]
[MAILPOET-3279]: https://mailpoet.atlassian.net/browse/MAILPOET-3279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Move styles to scss file [MAILPOET-3279]

RoboFile.php, tasks/release/TranslationsController.php
[MAILPOET-3807]
[MAILPOET-3807]: https://mailpoet.atlassian.net/browse/MAILPOET-3807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add a translations check to the release command [MAILPOET-3807]

assets/js/src/form_editor/components/form_settings/form_placement_options/settings_panels/other_settings.tsx, assets/js/src/form_editor/store/reducers/save_form_done.jsx, assets/js/src/form_editor/store/selectors.jsx, lib/AdminPages/Pages/FormEditor.php, lib/Form/Util/Export.php, views/form/editor.html
[MAILPOET-3872]
[MAILPOET-3872]: https://mailpoet.atlassian.net/browse/MAILPOET-3872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix form placement for an unsaved form [MAILPOET-3872]

lib/API/JSON/v1/SendingQueue.php, lib/Entities/NewsletterEntity.php, lib/Newsletter/Sending/SendingQueuesRepository.php, tests/integration/API/JSON/v1/SendingQueueTest.php
[MAILPOET-3876]
[MAILPOET-3876]: https://mailpoet.atlassian.net/browse/MAILPOET-3876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
For QA @veljkho: This is changing the part of the plugin that starts the sending. So try to pause a newsletter that is being sent or resume it. Try to schedule a newsletter or send an email from the plugin.
=> Refactor sending queue API to doctrine [MAILPOET-3876]

lib/Util/Notices/BlackFridayNotice.php
[MAILPOET-3933]
[MAILPOET-3933]: https://mailpoet.atlassian.net/browse/MAILPOET-3933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Black Friday banner [MAILPOET-3933]

lib/Config/Populator.php
This PR just updates the version check in migration code. I guess it can be merged right after the review.
[MAILPOET-2686]
[MAILPOET-2686]: https://mailpoet.atlassian.net/browse/MAILPOET-2686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update versions in templates data migration [MAILPOET-2686]

assets/js/src/form_editor/blocks/custom_checkbox/custom_field_settings.jsx, assets/js/src/form_editor/blocks/custom_checkbox/edit.jsx, assets/js/src/form_editor/blocks/custom_date/custom_field_settings.jsx, assets/js/src/form_editor/blocks/custom_date/edit.jsx, assets/js/src/form_editor/blocks/custom_radio/custom_field_settings.jsx, assets/js/src/form_editor/blocks/custom_radio/edit.jsx, assets/js/src/form_editor/blocks/custom_select/edit.jsx, assets/js/src/form_editor/blocks/custom_text/custom_field_settings.jsx, assets/js/src/form_editor/blocks/custom_text/edit.jsx, assets/js/src/form_editor/blocks/custom_textarea/edit.jsx, assets/js/src/form_editor/blocks/map_custom_field_form_data.jsx, tests/acceptance/Forms/EditorCreateCustomFieldCest.php
[MAILPOET-3926]
[MAILPOET-3926]: https://mailpoet.atlassian.net/browse/MAILPOET-3926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix custom fields label saving [MAILPOET-3926]

assets/js/src/common/set_from_address_modal.tsx, assets/js/src/newsletters/send.jsx, assets/js/src/sending-paused-notices-resume-button.ts, assets/js/src/settings/store/actions/settings.ts, assets/js/src/settings/store/controls.ts, lib/API/JSON/v1/Settings.php, lib/Analytics/Reporter.php, lib/Services/AuthorizedEmailsController.php, tests/integration/API/JSON/v1/SettingsTest.php
[MAILPOET-3881]
[MAILPOET-3881]: https://mailpoet.atlassian.net/browse/MAILPOET-3881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Track unauthorized emails [MAILPOET-3881]

tests/integration/Newsletter/RendererTest.php
[MAILPOET-3945]
[MAILPOET-3945]: https://mailpoet.atlassian.net/browse/MAILPOET-3945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove mixed type from test [MAILPOET-3945]

lib/Newsletter/Sending/ScheduledTasksRepository.php
[MAILPOET-3938]
[MAILPOET-3938]: https://mailpoet.atlassian.net/browse/MAILPOET-3938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix issues with Scheduling subscribers_count_cache_recalculation task [MAILPOET-3938]

lib/Cron/Triggers/WordPress.php, tests/integration/Cron/Triggers/WordPressTest.php
[MAILPOET-3948]
[MAILPOET-3948]: https://mailpoet.atlassian.net/browse/MAILPOET-3948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix stats reports checks in cron worker trigger [MAILPOET-3948]

assets/js/src/settings/pages/key_activation/key_activation.tsx, tests/_support/AcceptanceTester.php, tests/acceptance/Settings/AddSendingKeyCest.php
[MAILPOET-1950]
[MAILPOET-1950]: https://mailpoet.atlassian.net/browse/MAILPOET-1950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update key display - [MAILPOET-1950]

assets/js/src/post_editor_block/subscription_form/edit.jsx, lib/Form/Widget.php, lib/PostEditorBlocks/SubscriptionFormBlock.php
[MAILPOET-3896]
[MAILPOET-3896]: https://mailpoet.atlassian.net/browse/MAILPOET-3896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add info when form is inactive to subscription form block [MAILPOET-3896]

tests/acceptance/Newsletters/ReceivePostNotificationCest.php
[MAILPOET-3823]
[MAILPOET-3823]: https://mailpoet.atlassian.net/browse/MAILPOET-3823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove old models usage from ReceivePostNotification test [MAILPOET-3823]

tests/DataFactories/ScheduledTask.php
[MAILPOET-3817]
[MAILPOET-3817]: https://mailpoet.atlassian.net/browse/MAILPOET-3817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Refactor \MailPoet\Test\DataFactories\ScheduledTask to Doctrine - [MAILPOET-3817]

lib/Subscribers/ImportExport/ImportExportRepository.php, tests/integration/Subscribers/ImportExport/ImportExportRepositoryTest.php
This PR fixes a bug in the code that exports subscribers to a CSV file. This bug caused duplicated entries when exporting subscribers of dynamic segments. Instead of a given subscriber appearing only once in the CSV file, they would be included multiple times, and the number of times would depend on the number of static segments that they had subscribed to.
This bug was caused by a problem in the code that generates the SQL query used to fetch the subscribers that will be exported. The same method is used for subscribers not linked to a segment, static segments, and dynamic segments. The table wp_mailpoet_segments was included in the query in the three cases, but it should not be included for dynamic segments as this type of segment does not have a corresponding entry in this table. …
=> Fix: duplicated entries when exporting subscribers of dynamic segments [MAILPOET-3900]

lib/Cron/Triggers/WordPress.php, tests/integration/Cron/Triggers/WordPressTest.php
[MAILPOET-3970]
[MAILPOET-3970]: https://mailpoet.atlassian.net/browse/MAILPOET-3970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix cron trigger for subscriber stats report for invalid key [MAILPOET-3970]

lib/Cron/Workers/Scheduler.php, lib/Entities/NewsletterEntity.php, lib/Newsletter/Sending/SendingQueuesRepository.php, tests/integration/Cron/Workers/SchedulerTest.php, tests/integration/Newsletter/Sending/SendingQueuesRepositoryTest.php
[MAILPOET-3962]
[MAILPOET-3962]: https://mailpoet.atlassian.net/browse/MAILPOET-3962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix resume sending for post notifications [MAILPOET-3962]

assets/js/src/newsletters/newsletters.jsx, assets/js/src/newsletters/templates.jsx, assets/js/src/newsletters/types.tsx, assets/js/src/settings/pages/advanced/tracking.tsx, lib/Cron/Daemon.php, lib/Features/FeaturesController.php, tests/acceptance/Settings/AdvancedSettingsCest.php, tests/integration/Cron/DaemonHttpRunnerTest.php, tests/integration/Cron/DaemonTest.php
@costasovo, before reviewing this PR, please check the comment that I left on the Jira ticket.
@veljkho, when this PR gets to you for QA, please note that it should not be merged before #3822 (it is fine to include both PRs in the same release, but we should not include this one without including #3822).
[MAILPOET-3859]
[MAILPOET-3859]: https://mailpoet.atlassian.net/browse/MAILPOET-3859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove re-engagement-email feature flag [MAILPOET-3859]

assets/js/src/public.jsx
[MAILPOET-3964]
[MAILPOET-3964]: https://mailpoet.atlassian.net/browse/MAILPOET-3964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Close popup and set cookie before redirect [MAILPOET-3964]

assets/js/src/segments/dynamic/dynamic_segments_filters/subscriber.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/subscriber_subscribed_to_list.tsx, assets/js/src/segments/dynamic/form.tsx, assets/js/src/segments/dynamic/store/selectors.ts, assets/js/src/segments/dynamic/store/store.ts, assets/js/src/segments/dynamic/types.ts, lib/AdminPages/Pages/Segments.php, lib/DI/ContainerConfigurator.php, lib/Doctrine/Repository.php, lib/Entities/DynamicSegmentFilterData.php, lib/Segments/DynamicSegments/FilterDataMapper.php, lib/Segments/DynamicSegments/FilterFactory.php, lib/Segments/DynamicSegments/FilterHandler.php, lib/Segments/DynamicSegments/Filters/SubscriberSegment.php, tests/acceptance/Segments/ManageSegmentsCest.php, tests/integration/Segments/DynamicSegments/Filters/SubscriberSegmentTest.php, views/segments.html
[MAILPOET-3502]
[MAILPOET-3502]: https://mailpoet.atlassian.net/browse/MAILPOET-3502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> New segment: subscribed to list [MAILPOET-3502]

assets/js/src/common/subscribers_cache_message.tsx, views/segments.html, views/subscribers/subscribers.html
[MAILPOET-3972](https://mailpoet.atlassian.net/browse/MAILPOET-3972)
=> Update subscribers count translation strings - MAILPOET-3972

assets/js/src/segments/dynamic/dynamic_segments_filters/woocommerce.tsx, assets/js/src/segments/dynamic/types.ts, lib/API/JSON/v1/DynamicSegments.php, lib/Config/Migrator.php, lib/Entities/DynamicSegmentFilterData.php, lib/Segments/DynamicSegments/Exceptions/InvalidFilterException.php, lib/Segments/DynamicSegments/FilterDataMapper.php, lib/Segments/DynamicSegments/Filters/WooCommerceProduct.php, tests/DataFactories/DynamicSegment.php, tests/acceptance/Segments/ManageSegmentsCest.php, tests/unit/Segments/DynamicSegments/FilterDataMapperTest.php, views/segments.html
[MAILPOET-3954]
[MAILPOET-3954]: https://mailpoet.atlassian.net/browse/MAILPOET-3954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Allow multiple values in "purchased this product" segment [MAILPOET-3954]

lib/Form/Widget.php, lib/PostEditorBlocks/SubscriptionFormBlock.php, tasks/code_sniffer/MailPoet/ruleset.xml
[PREMIUM-166]
[PREMIUM-166]: https://mailpoet.atlassian.net/browse/PREMIUM-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Share code sniffer config [PREMIUM-166]

assets/js/src/segments/list.jsx, lib/Config/Migrator.php, lib/Cron/Workers/WooCommerceSync.php, lib/Entities/SubscriberEntity.php, lib/Segments/WooCommerce.php, lib/Subscribers/SubscriberSaveController.php, tests/integration/Cron/Workers/WooCommerceSyncTest.php, tests/integration/Segments/WooCommerceTest.php, views/segments.html
As a part of this pull request, I refactored the code into Doctrine.
Also, I was thinking a lot about preventing this cron job before performance issues. If you see a better solution or have any ideas, I would be glad about that.
=> Sync WooCommerce subscribers in cron batches [MAILPOET-3753]

assets/js/src/settings/pages/key_activation/key_activation.tsx
[MAILPOET-4003](https://mailpoet.atlassian.net/browse/MAILPOET-4003)
=> Fixed sending hashed MSS API key - MAILPOET-4003

RoboFile.php, tasks/makepot/makepot.js
[PREMIUM-167]
[PREMIUM-167]: https://mailpoet.atlassian.net/browse/PREMIUM-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Share makepot config [PREMIUM-167]

readme.txt
[MAILPOET-4012]
[MAILPOET-4012]: https://mailpoet.atlassian.net/browse/MAILPOET-4012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove link to demo [MAILPOET-4012]

lib/Config/ServicesChecker.php, lib/Newsletter/Renderer/Renderer.php, lib/Util/License/Features/Subscribers.php, tests/integration/Config/ServicesCheckerTest.php, tests/integration/Newsletter/RendererTest.php, tests/integration/WooCommerce/TransactionalEmails/RendererTest.php
[MAILPOET-3981](https://mailpoet.atlassian.net/browse/MAILPOET-3981)
=> Recommend MailPoet in free users emails - [MAILPOET-3981]

lib/Newsletter/Editor/StructureTransformer.php, lib/Util/DOM.php
[MAILPOET-4025]
[MAILPOET-4025]: https://mailpoet.atlassian.net/browse/MAILPOET-4025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix pQuery use statement [MAILPOET-4025]

.circleci/config.yml, RoboFile.php, composer.json, composer.lock, lib/Form/Util/Styles.php, lib/Util/Notices/PHPVersionWarnings.php, mailpoet-cron.php, mailpoet.php, prefixer/composer.json, prefixer/composer.lock, readme.txt, tests/integration/Util/Notices/PHPVersionWarningsTest.php
[MAILPOET-3966]
[MAILPOET-3966]: https://mailpoet.atlassian.net/browse/MAILPOET-3966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Drop PHP 7.1 [MAILPOET-3966]

assets/js/src/segments/dynamic/dynamic_segments_filters/custom_fields/text.tsx, lib/Segments/DynamicSegments/Filters/MailPoetCustomFields.php, tests/integration/Segments/DynamicSegments/Filters/MailPoetCustomFieldsTest.php
[MAILPOET-4008]
[MAILPOET-4008]: https://mailpoet.atlassian.net/browse/MAILPOET-4008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> More comparison options for custom field segment [MAILPOET-4008]

tests/docker/docker-compose.yml
[MAILPOET-3967]
[MAILPOET-3967]: https://mailpoet.atlassian.net/browse/MAILPOET-3967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Use docker image with WP 5.8 and PHP 8.0 [MAILPOET-3967]

assets/js/src/marketing_optin_block/block.json, assets/js/src/marketing_optin_block/index.tsx, lib/PostEditorBlocks/WooCommerceBlocksIntegration.php
[MAILPOET-4030]
[MAILPOET-4030]: https://mailpoet.atlassian.net/browse/MAILPOET-4030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Please refer to the above Jira ticket for testing instructions.
=> Fix marketing optin warnings [MAILPOET-4030]

assets/css/src/generic/_forms-select.scss
[MAILPOET-3997]
[MAILPOET-3997]: https://mailpoet.atlassian.net/browse/MAILPOET-3997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Make react_select component smaller, so they are the same as native_select [MAILPOET-3997]

lib/API/JSON/v1/AutomaticEmails.php, lib/AutomaticEmails/AutomaticEmailFactory.php, lib/AutomaticEmails/AutomaticEmails.php, lib/AutomaticEmails/WooCommerce/Events/AbandonedCart.php, lib/AutomaticEmails/WooCommerce/Events/AbandonedCartPageVisitTracker.php, lib/AutomaticEmails/WooCommerce/WooCommerce.php, lib/AutomaticEmails/WooCommerce/WooCommerceEventFactory.php, lib/Config/Hooks.php, lib/Config/Initializer.php, lib/DI/ContainerConfigurator.php, lib/Statistics/Track/Clicks.php, lib/Statistics/Track/SubscriberCookie.php, lib/Statistics/Track/SubscriberHandler.php, lib/Statistics/Track/WooCommercePurchases.php, lib/Subscription/Pages.php, lib/Subscription/Registration.php, tests/acceptance/Subscribers/SubscriberCookieCest.php, tests/integration/API/JSON/v1/AutomaticEmailsTest.php, tests/integration/AutomaticEmails/AutomaticEmailsTest.php, tests/integration/AutomaticEmails/WooCommerce/Events/AbandonedCartPageVisitTrackerTest.php, tests/integration/AutomaticEmails/WooCommerce/Events/AbandonedCartTest.php, tests/integration/AutomaticEmails/WooCommerce/WooCommerceTest.php, tests/integration/Statistics/Track/ClicksTest.php, tests/integration/Statistics/Track/WooCommercePurchasesTest.php, tests/integration/Subscription/PagesTest.php
[MAILPOET-3924]
[MAILPOET-3924]: https://mailpoet.atlassian.net/browse/MAILPOET-3924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Subscriber cookie [MAILPOET-3924]

lib/Util/pQuery/Html5Parser.php
[MAILPOET-4044]
[MAILPOET-4044]: https://mailpoet.atlassian.net/browse/MAILPOET-4044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix rendering text with unclosed paragraph tags [MAILPOET-4044]

readme.txt
[MAILPOET-4043]
[MAILPOET-4043]: https://mailpoet.atlassian.net/browse/MAILPOET-4043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update WP.org repository description [MAILPOET-4043]

lib/Segments/DynamicSegments/Filters/WooCommerceCategory.php, lib/Segments/DynamicSegments/Filters/WooCommerceNumberOfOrders.php, lib/Segments/DynamicSegments/Filters/WooCommerceProduct.php, lib/Segments/DynamicSegments/Filters/WooCommerceTotalSpent.php, tests/_data/createWCLookupTables.sql, tests/acceptance/Segments/WooCommerceDynamicSegmentsCest.php, tests/integration/Segments/DynamicSegments/Filters/WooCommerceNumberOfOrdersTest.php, tests/integration/Segments/DynamicSegments/Filters/WooCommerceTotalSpentTest.php
[MAILPOET-3576]
[MAILPOET-3576]: https://mailpoet.atlassian.net/browse/MAILPOET-3576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Test steps:
Info: With this pull request, we want to allow also non-registered users to be counted in the result when calculating segment. You need to make sure how many registered users are in `All Users` page, then to see how many Completed orders you have in WooCommerce > Orders.. and then to purchase few more with some random email. This way you'll know that you have enough orders that aren't purchased by registered users.
1. Go to All Users and see how many registered users are there
2. Go and purchase some items under Clothing category but as a guest user (log out and remember to click the checkbox in the …
=> Improve performance and allow guest users in WooCommerce dynamic segments [MAILPOET-3576]

lib/Segments/WooCommerce.php, tests/integration/Segments/WooCommerceTest.php
[MAILPOET-4052]
[MAILPOET-4052]: https://mailpoet.atlassian.net/browse/MAILPOET-4052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Prevent infinite loop in WC sync worker [MAILPOET-4052]

lib/API/JSON/ResponseBuilders/DynamicSegmentsResponseBuilder.php, lib/Segments/DynamicSegments/FilterDataMapper.php
[MAILPOET-4054]
[MAILPOET-4054]: https://mailpoet.atlassian.net/browse/MAILPOET-4054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix clicked segments [MAILPOET-4054]

tests/acceptance/Subscribers/SubscriberCookieCest.php
[MAILPOET-3924]
[MAILPOET-3924]: https://mailpoet.atlassian.net/browse/MAILPOET-3924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Multisite hotfix [MAILPOET-3924]

lib/Config/Migrator.php
[MAILPOET-4058]
[MAILPOET-4058]: https://mailpoet.atlassian.net/browse/MAILPOET-4058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update migration check versions [MAILPOET-4058]

assets/css/src/components-plugin/_segments.scss, assets/css/src/generic/_forms-input.scss, assets/css/src/generic/_forms-select.scss, assets/css/src/generic/_forms-select2.scss, assets/css/src/generic/_forms-textarea.scss, assets/css/src/settings/_form.scss, assets/js/src/segments/dynamic/dynamic_segments_filters/custom_fields/date.tsx, assets/js/src/segments/dynamic/dynamic_segments_filters/subscriber_subscribed_date.tsx, assets/js/src/segments/dynamic/form.tsx
[MAILPOET-4039]
[MAILPOET-4039]: https://mailpoet.atlassian.net/browse/MAILPOET-4039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Testing instructions are inside the Jira.
=> Improve segment form grid layout [MAILPOET-4039]

build.sh, mailpoet.php
[MAILPOET-4028]
[MAILPOET-4028]: https://mailpoet.atlassian.net/browse/MAILPOET-4028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add translations info and pot file [MAILPOET-4028]

lib/Tasks/Subscribers/BatchIterator.php, tasks/phpstan/composer.json, tasks/phpstan/composer.lock, tasks/phpstan/fix-WPStubs-for-PHP-8_1.php, tasks/phpstan/phpstan-7-baseline.neon, tasks/phpstan/phpstan-8-baseline.neon, tasks/phpstan/phpstan-8.1-baseline.neon, tasks/phpstan/phpstan-baseline-fix-lib.php, tasks/phpstan/phpstan.neon, tasks/phpstan/prefix-phpstan-doctrine.php
[MAILPOET-3932](https://mailpoet.atlassian.net/browse/MAILPOET-3932)
Based on #3876 
Please check #3876 for more information.
=> (New) Upgrade PHPStan to version 1.0 - [MAILPOET-3932]

assets/js/src/public.jsx, lib/Subscription/Manage.php
[MAILPOET-3928]
[MAILPOET-3928]: https://mailpoet.atlassian.net/browse/MAILPOET-3928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Parsley validation to the manage form [MAILPOET-3928]

mailpoet/composer.json, mailpoet/composer.lock, mailpoet/lib/Config/Activator.php, mailpoet/lib/Config/Initializer.php, mailpoet/lib/Config/Migrator.php, mailpoet/lib/Config/Populator.php, mailpoet/lib/Config/Updater.php, mailpoet/lib/Cron/Workers/Bounce.php, mailpoet/lib/Cron/Workers/SendingQueue/SendingQueue.php, mailpoet/lib/Tasks/Subscribers/BatchIterator.php, mailpoet/lib/Util/License/Features/Subscribers.php, mailpoet/tasks/fix-codeception-stub.php, mailpoet/tasks/phpstan/phpstan-7-baseline.neon, mailpoet/tests/integration/Subscription/CaptchaTest.php, mailpoet/tests/integration/Subscription/SubscriptionUrlFactoryTest.php, mailpoet/tests/integration/Subscription/ThrottlingTest.php, mailpoet/tests/integration/_bootstrap.php, mailpoet/tests/unit/Util/CSSTest.php
[MAILPOET-4053]
[MAILPOET-4053]: https://mailpoet.atlassian.net/browse/MAILPOET-4053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update PHPUnit to version 8 [MAILPOET-4053]

mailpoet/lib/PostEditorBlocks/WooCommerceBlocksIntegration.php
[MAILPOET-4074]
[MAILPOET-4074]: https://mailpoet.atlassian.net/browse/MAILPOET-4074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add typecast for the checkout option parameter [MAILPOET-4074]

mailpoet/lib/Newsletter/Statistics/NewsletterStatistics.php
[MAILPOET-4100]
[MAILPOET-4100]: https://mailpoet.atlassian.net/browse/MAILPOET-4100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix getBounceCount() to return the correct property [MAILPOET-4100]

CONTRIBUTING.md
[MAILPOET-3916]
[MAILPOET-3916]: https://mailpoet.atlassian.net/browse/MAILPOET-3916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add note about the migration from IdiORM to Doctrine [MAILPOET-3916]

mailpoet/tests/DataFactories/User.php, mailpoet/tests/integration/Statistics/Track/SubscriberActivityTrackerTest.php
I tested the fix [in the multisite environment on Circle CI](https://app.circleci.com/pipelines/github/mailpoet/mailpoet/8753/workflows/2722aaba-9f5a-4c95-bd91-8e9d2b465fac).
[MAILPOET-4123]
[MAILPOET-4123]: https://mailpoet.atlassian.net/browse/MAILPOET-4123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix  SubscriberActivityTracker Test [MAILPOET-4123]

.circleci/config.yml, mailpoet/RoboFile.php, mailpoet/lib/PostEditorBlocks/WooCommerceBlocksIntegration.php, mailpoet/lib/Segments/WooCommerce.php, mailpoet/tests/_support/AcceptanceTester.php, mailpoet/tests/_support/PluginsExtension.php, mailpoet/tests/acceptance/Subscriptions/WooCheckoutBlocksCest.php, mailpoet/tests/docker/codeception/docker-entrypoint.sh
[MAILPOET-3937]
[MAILPOET-3937]: https://mailpoet.atlassian.net/browse/MAILPOET-3937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add acceptance tests for WC block checkout [MAILPOET-3937]

.circleci/config.yml
[MAILPOET-3937]
[MAILPOET-3937]: https://mailpoet.atlassian.net/browse/MAILPOET-3937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix WC blocks version for oldest acceptance tests [MAILPOET-3937]

mailpoet/readme.txt
[MAILPOET-4167]
[MAILPOET-4167]: https://mailpoet.atlassian.net/browse/MAILPOET-4167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update WP.org description [MAILPOET-4167]

mailpoet/assets/js/src/global.d.ts, mailpoet/assets/js/src/listing/notices.jsx, mailpoet/assets/js/src/mailpoet.ts, mailpoet/assets/js/src/newsletters/newsletters.jsx, mailpoet/assets/js/src/notices/email_volume_limit_notice.tsx, mailpoet/assets/js/src/notices/subscribers_limit_notice.jsx, mailpoet/assets/js/src/segments/heading.jsx, mailpoet/assets/js/src/subscribers/list.jsx, mailpoet/lib/API/JSON/v1/Services.php, mailpoet/lib/AdminPages/Pages/Newsletters.php, mailpoet/lib/AdminPages/Pages/Segments.php, mailpoet/lib/AdminPages/Pages/Subscribers.php, mailpoet/lib/Cron/Workers/KeyCheck/KeyCheckWorker.php, mailpoet/lib/Cron/Workers/KeyCheck/PremiumKeyCheck.php, mailpoet/lib/Cron/Workers/KeyCheck/SendingServiceKeyCheck.php, mailpoet/lib/DI/ContainerConfigurator.php, mailpoet/lib/Mailer/Mailer.php, mailpoet/lib/Mailer/MailerError.php, mailpoet/lib/Mailer/Methods/ErrorMappers/MailPoetMapper.php, mailpoet/lib/Util/License/Features/Subscribers.php, mailpoet/tests/integration/Mailer/Methods/MailPoetAPITest.php, mailpoet/tests/unit/Mailer/Methods/ErrorMappers/MailPoetMapperTest.php, mailpoet/views/layout.html, mailpoet/views/shared_config.html
[MAILPOET-4047]
[MAILPOET-4047]: https://mailpoet.atlassian.net/browse/MAILPOET-4047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add notice email limit reached [MAILPOET-4047]

mailpoet/lib/Cron/Workers/SendingQueue/SendingQueue.php, mailpoet/tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php
[MAILPOET-4166]
[MAILPOET-4166]: https://mailpoet.atlassian.net/browse/MAILPOET-4166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Testing instructions are inside Jira ticket.
=> Fix filtering recipients by status during sending [MAILPOET-4166]

mailpoet/lib/Subscribers/ImportExport/Import/Import.php, mailpoet/tasks/phpstan/composer.json, mailpoet/tasks/phpstan/composer.lock, mailpoet/tasks/phpstan/phpstan-7-baseline.neon, mailpoet/tasks/phpstan/phpstan-8-baseline.neon, mailpoet/tasks/phpstan/phpstan-8.1-baseline.neon, mailpoet/tests/DataFactories/Form.php, mailpoet/tests/integration/Cron/Workers/SchedulerTest.php, mailpoet/tests/integration/Newsletter/RendererTest.php, mailpoet/tests/integration/WP/FunctionsTest.php
This PR upgrades PHPStan, removes a few errors, and updates the baselines.
[MAILPOET-4131]
[MAILPOET-4131]: https://mailpoet.atlassian.net/browse/MAILPOET-4131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Upgrade PHPStan

mailpoet/lib/Cron/CronWorkerRunner.php
[MAILPOET-4172]
[MAILPOET-4172]: https://mailpoet.atlassian.net/browse/MAILPOET-4172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Save correct processed_at when finishing scheduled task [MAILPOET-4172]

mailpoet/RoboFile.php, mailpoet/lib/Form/Block/BlockRendererHelper.php, mailpoet/package.json, mailpoet/tasks/phpstan/composer.json, mailpoet/tasks/phpstan/composer.lock, mailpoet/tests/unit/Newsletter/Renderer/Blocks/TextTest.php, mailpoet/tests/unit/Util/DOMTest.php
[MAILPOET-4055]
[MAILPOET-4055]: https://mailpoet.atlassian.net/browse/MAILPOET-4055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Phpstan cache [MAILPOET-4055]

.circleci/config.yml, .circleci/setup.bash, mailpoet/composer.json, mailpoet/composer.lock, mailpoet/lib-3rd-party/Idiorm/idiorm.php, mailpoet/lib/Cron/Workers/SendingQueue/SendingQueue.php, mailpoet/lib/Cron/Workers/SendingQueue/Tasks/Newsletter.php, mailpoet/lib/Models/Subscriber.php, mailpoet/lib/Newsletter/Shortcodes/Shortcodes.php, mailpoet/prefixer/composer.json, mailpoet/prefixer/fix-captcha.php, mailpoet/prefixer/scoper.inc.php, mailpoet/tasks/code_sniffer/composer.json, mailpoet/tasks/fix-requests.php, mailpoet/tests/integration/Models/ModelTest.php, mailpoet/tools/install.php
[MAILPOET-4015]
[MAILPOET-4015]: https://mailpoet.atlassian.net/browse/MAILPOET-4015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Switch Circle CI jobs to PHP8.1 [MAILPOET-4015]

mailpoet/views/upgrade.html
[MAILPOET-4182]
[MAILPOET-4182]: https://mailpoet.atlassian.net/browse/MAILPOET-4182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove empty line in translatable string [MAILPOET-4182]

docker-compose.yml
[MAILPOET-4194]
[MAILPOET-4194]: https://mailpoet.atlassian.net/browse/MAILPOET-4194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix TS type checking not workfing in Docker [MAILPOET-4194]

mailpoet/lib/Newsletter/Renderer/Blocks/Button.php
[MAILPOET-4193](https://mailpoet.atlassian.net/browse/MAILPOET-4193)
Testing:
* Create a new Newsletter or edit an already existing one
* Add the Button component 
* Set button **Height** to 0
* Save
* Click on Preview
Note: you can test before checking out to the branch to see the error
=> Fix Division by zero Error in Newsletter button - MAILPOET-4193

README.md, docker-compose.yml
[MAILPOET-4016]
[MAILPOET-4016]: https://mailpoet.atlassian.net/browse/MAILPOET-4016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Change default PHP to version 8.1 [MAILPOET-4016]

do, mailpoet/lib/DI/ContainerConfigurator.php, mailpoet/lib/Validator/Builder.php, mailpoet/lib/Validator/Schema.php, mailpoet/lib/Validator/Schema/AnyOfSchema.php, mailpoet/lib/Validator/Schema/ArraySchema.php, mailpoet/lib/Validator/Schema/BooleanSchema.php, mailpoet/lib/Validator/Schema/IntegerSchema.php, mailpoet/lib/Validator/Schema/NullSchema.php, mailpoet/lib/Validator/Schema/NumberSchema.php, mailpoet/lib/Validator/Schema/ObjectSchema.php, mailpoet/lib/Validator/Schema/OneOfSchema.php, mailpoet/lib/Validator/Schema/StringSchema.php, mailpoet/lib/Validator/ValidationException.php, mailpoet/lib/Validator/Validator.php, mailpoet/lib/WP/Functions.php, mailpoet/lib/exceptions.php, mailpoet/tests/integration/Validator/ValidatorTest.php, mailpoet/tests/unit/Validator/BuilderTest.php, mailpoet/tests/unit/Validator/Schema/AnyOfSchemaTest.php, mailpoet/tests/unit/Validator/Schema/ArraySchemaTest.php, mailpoet/tests/unit/Validator/Schema/BooleanSchemaTest.php, mailpoet/tests/unit/Validator/Schema/IntegerSchemaTest.php, mailpoet/tests/unit/Validator/Schema/NullSchemaTest.php, mailpoet/tests/unit/Validator/Schema/NumberSchemaTest.php, mailpoet/tests/unit/Validator/Schema/ObjectSchemaTest.php, mailpoet/tests/unit/Validator/Schema/OneOfSchemaTest.php, mailpoet/tests/unit/Validator/Schema/StringSchemaTest.php, mailpoet/tests/unit/Validator/SchemaTest.php
[MAILPOET-4195]
[MAILPOET-4195]: https://mailpoet.atlassian.net/browse/MAILPOET-4195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
For details see https://wp.me/pcNwfB-os.
Usage:
```php
$schema = Builder::object()
->title('User')
->description('User schema definition')
->field('name', 'user')
->field('version', 1)
->properties([
'id' => Builder::string()->required()->formatUuid(),
'created_at' => Builder::string()->required()->formatDateTime(),
'username' => Builder::string()->required()->minLength(2)->maxLength(30)->pattern('^[a-z0-9]+$'),
'password' => Builder::string()->required()->minLength(8)->maxLength(1024),
'email' => Builder::string()->required()->formatEmail(),
'ip' => Builder::string()->required()->formatIp(),
'refresh_interval' => …
```
=> Validator [MAILPOET-4195]

mailpoet/tests/acceptance/Newsletters/ScheduleNewsletterCest.php
It is not an elegant fix but works.
[MAILPOET-4221]
[MAILPOET-4221]: https://mailpoet.atlassian.net/browse/MAILPOET-4221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix ScheduleNewsletter acceptance test [MAILPOET-4221]

mailpoet/lib/WooCommerce/Subscription.php
Fixes [MAILPOET-4233]
[MAILPOET-4233]: https://mailpoet.atlassian.net/browse/MAILPOET-4233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix str_replace to avoid broken HTML [MAILPOET-4233]

mailpoet/lib/Mailer/Methods/PHPMail.php, mailpoet/tests/integration/Mailer/Methods/PHPMailTest.php
[MAILPOET-4235]
[MAILPOET-4235]: https://mailpoet.atlassian.net/browse/MAILPOET-4235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix format for List-Unsubscribe header [MAILPOET-4235]

mailpoet/assets/js/src/newsletters/campaign_stats/premium_banner.jsx, mailpoet/lib/Cron/Workers/StatsNotifications/Worker.php, mailpoet/tests/integration/Cron/Workers/StatsNotifications/WorkerTest.php
[MAILPOET-4183]
[MAILPOET-4183]: https://mailpoet.atlassian.net/browse/MAILPOET-4183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove deprecated upgrade link [MAILPOET-4183]

mailpoet/lib/API/JSON/v1/AutomatedLatestContent.php, mailpoet/lib/DI/ContainerConfigurator.php, mailpoet/lib/Newsletter/AutomatedLatestContent.php, mailpoet/lib/Newsletter/BlockPostQuery.php, mailpoet/lib/Newsletter/Renderer/Blocks/AutomatedLatestContentBlock.php, mailpoet/lib/Util/APIPermissionHelper.php, mailpoet/tasks/phpstan/phpstan-7-baseline.neon, mailpoet/tasks/phpstan/phpstan-8-baseline.neon, mailpoet/tasks/phpstan/phpstan-8.1-baseline.neon, mailpoet/tests/integration/Newsletter/AutomatedLatestContentAPITest.php, mailpoet/tests/integration/Newsletter/AutomatedLatestContentTest.php, mailpoet/tests/integration/Newsletter/Blocks/AbandonedCartContentTest.php, mailpoet/tests/integration/Subscription/SubscriptionUrlFactoryTest.php, mailpoet/tests/integration/_bootstrap.php
Fixes [MAILPOET-4082]
[MAILPOET-4082]: https://mailpoet.atlassian.net/browse/MAILPOET-4082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Process arguments better when querying posts for automated latest content [MAILPOET-4082]

.git-blame-ignore-revs
[MAILPOET-4075]
[MAILPOET-4075]: https://mailpoet.atlassian.net/browse/MAILPOET-4075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add prettier autoformatting commit to .git-blame-ignore-revs

mailpoet/lib/Twig/I18n.php, mailpoet/views/newsletter/editor.html
[MAILPOET-4243]
[MAILPOET-4243]: https://mailpoet.atlassian.net/browse/MAILPOET-4243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix a deprecation warning on PHP8.1 in i18n [MAILPOET-4243]

mailpoet/lib/Segments/DynamicSegments/Filters/MailPoetCustomFields.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/MailPoetCustomFieldsTest.php
[MAILPOET-4157]
[MAILPOET-4157]: https://mailpoet.atlassian.net/browse/MAILPOET-4157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Test steps inside Jira
=> Improve not_equals condition for custom fields [MAILPOET-4157]

mailpoet/lib/Automation/Engine/API/API.php, mailpoet/lib/Automation/Engine/API/Endpoint.php, mailpoet/lib/Automation/Engine/API/EndpointContainer.php, mailpoet/lib/Automation/Engine/API/Request.php, mailpoet/lib/Automation/Engine/Endpoints/System/DatabaseDeleteEndpoint.php, mailpoet/lib/Automation/Engine/Endpoints/System/DatabasePostEndpoint.php, mailpoet/lib/Automation/Engine/Endpoints/Workflows/WorkflowsGetEndpoint.php, mailpoet/lib/Automation/Engine/Endpoints/Workflows/WorkflowsPostEndpoint.php, mailpoet/lib/Automation/Engine/Engine.php, mailpoet/lib/Automation/Engine/Hooks.php, mailpoet/lib/DI/ContainerConfigurator.php, mailpoet/lib/Features/FeaturesController.php, mailpoet/tests/integration/REST/Automation/API/Endpoint.php, mailpoet/tests/integration/REST/Automation/API/EndpointTest.php, mailpoet/tests/integration/REST/Automation/AutomationTest.php, mailpoet/tests/integration/REST/Automation/Workflows/WorkflowsGetTest.php, mailpoet/tests/integration/REST/Automation/Workflows/WorkflowsPostTest.php, mailpoet/tests/integration/REST/Test.php, mailpoet/tests/integration/_bootstrap.php
See a related P2 post titled "REST API".
This PR makes REST endpoint classes per method, adds input validation, and sets up API integration tests.
[MAILPOET-4207]
[MAILPOET-4207]: https://mailpoet.atlassian.net/browse/MAILPOET-4207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
1. Please test the WooCommerce email sending, for example:
a) purchasing a product and receiving automatic email for specific product
b) purchasing a product and receiving automatic email for specific category
c) purchasing a product and receiving automatic email for the first purchase
=> Automation REST API [MAILPOET-4207]

mailpoet/readme.txt
[MAILPOET-4265]
[MAILPOET-4265]: https://mailpoet.atlassian.net/browse/MAILPOET-4265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update info about supported languages in readme.txt [MAILPOET-4265]

mailpoet/lib/Cron/Workers/SendingQueue/SendingQueue.php, mailpoet/lib/Tasks/Subscribers.php, mailpoet/tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php
[MAILPOET-4200]
[MAILPOET-4200]: https://mailpoet.atlassian.net/browse/MAILPOET-4200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Testing:
1. Please perform smoke test around the plugin, no more than 30 mins.
=> Disable marking subscribers from rejected batch as processed [MAILPOET-4200]

mailpoet/lib/Entities/SubscriberEntity.php, mailpoet/lib/Subscription/ManageSubscriptionFormRenderer.php, mailpoet/tests/DataFactories/CustomField.php, mailpoet/tests/integration/Subscription/ManageSubscriptionFormRendererTest.php
[MAILPOET-4137]
[MAILPOET-4137]: https://mailpoet.atlassian.net/browse/MAILPOET-4137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Test steps:
Note: This change was about Manage Subscriptions.
1. Please perform adhoc test around Manage Subscriptions page
2. Try to send newsletter and click on the link Manage Subscription when received newsletter
3. Try saving data inside Manage Subscription page
4. Try to make a custom page for Manage Subscription and to use it (can be set in the Settings - Basic tab)
=> Refactor ManageSubscriptionFormRenderer to Doctrine [MAILPOET-4137]

mailpoet/lib/Config/DatabaseInitializer.php, mailpoet/lib/Doctrine/Validator/Translator.php, mailpoet/lib/Doctrine/Validator/ValidatorFactory.php, mailpoet/prefixer/composer.json, mailpoet/prefixer/composer.lock, mailpoet/prefixer/fix-symfony-di.php, mailpoet/prefixer/fix-twig.php, mailpoet/tasks/phpstan/phpstan-7-baseline.neon, mailpoet/tasks/phpstan/phpstan-8-baseline.neon, mailpoet/tasks/phpstan/phpstan-8.1-baseline.neon, mailpoet/tests/integration/Twig/FunctionsTest.php
[MAILPOET-4227]
[MAILPOET-4227]: https://mailpoet.atlassian.net/browse/MAILPOET-4227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update PHP dependencies that require minimum PHP 7.2.5 [MAILPOET-4227]

mailpoet/assets/js/src/newsletter_editor/blocks/abandonedCartContent.js
Fixes [MAILPOET-4277]
[MAILPOET-4277]: https://mailpoet.atlassian.net/browse/MAILPOET-4277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix issue with wrong import causing Radio props not working

mailpoet/tools/install.php
[MAILPOET-4268]
[MAILPOET-4268]: https://mailpoet.atlassian.net/browse/MAILPOET-4268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update composer to 2.3+ [MAILPOET-4268]

mailpoet/lib/Cron/Triggers/WordPress.php, mailpoet/tests/integration/Cron/Triggers/WordPressTest.php
[MAILPOET-4140]
[MAILPOET-4140]: https://mailpoet.atlassian.net/browse/MAILPOET-4140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Replace Paris code with Doctrine code in MailPoet\Cron\Triggers\Wordpress and the test class [MAILPOET-4140]

mailpoet/lib/Cron/Triggers/WordPress.php
This change optimizes the SQL query that we run in every request when we check whether we should trigger the cron background process.
After some time the majority of scheduled task records in the DB are completed tasks.
In our cron trigger check, we check we need the info about completed tasks only for the Migration task.
Excluding other workers' completed tasks significantly speeds up the query execution on sites with a long history. E.g. on mailpoet.com the query sped up from 0.6s to 0.003s.
[MAILPOET-4314]
[MAILPOET-4314]: https://mailpoet.atlassian.net/browse/MAILPOET-4314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Optimize WordPress cron trigger SQL [MAILPOET-4314]

.circleci/config.yml, mailpoet/tests/docker/docker-compose.yml
[MAILPOET-4103](https://mailpoet.atlassian.net/browse/MAILPOET-4103)
=> Update outdated mysql docker image on Circle CI - MAILPOET-4103

mailpoet/RoboFile.php
Remove memory limit when building translations
=> memory limit when building translations

mailpoet/lib/API/JSON/v1/Subscribers.php, mailpoet/lib/Config/Migrator.php, mailpoet/lib/Cron/Workers/StatsNotifications/Worker.php, mailpoet/lib/CustomFields/ApiDataSanitizer.php, mailpoet/lib/Newsletter/Scheduler/PostNotificationScheduler.php, mailpoet/lib/Newsletter/Scheduler/WelcomeScheduler.php, mailpoet/tests/integration/Cron/Workers/SubscribersLifetimeEmailCountTest.php, mailpoet/tests/integration/Newsletter/Listing/NewsletterListingRepositoryTest.php, mailpoet/tests/integration/Newsletter/NewsletterRepositoryTest.php, mailpoet/tests/integration/Subscribers/SubscribersRepositoryTest.php, mailpoet/tests/integration/Util/Notices/InactiveSubscribersNoticeTest.php, mailpoet/tests/integration/WooCommerce/TransactionalEmailsTest.php, mailpoet/tests/unit/Form/Block/SelectTest.php
[MAILPOET-4338]
[MAILPOET-4338]: https://mailpoet.atlassian.net/browse/MAILPOET-4338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove usage constant from the old model [MAILPOET-4338]

mailpoet/lib/Cron/Workers/StatsNotifications/AutomatedEmails.php
[MAILPOET-4308]
[MAILPOET-4308]: https://mailpoet.atlassian.net/browse/MAILPOET-4308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix annotation in AutomatedEmails [MAILPOET-4308]

mailpoet/lib/AdminPages/Pages/NewsletterEditor.php, mailpoet/lib/Config/Menu.php, mailpoet/lib/Form/Util/CustomFonts.php, mailpoet/tests/integration/Config/MenuTest.php, mailpoet/views/newsletter/editor.html, mailpoet/views/newsletter/templates/components/sidebar/styles.hbs
Fixes [MAILPOET-4247]
[MAILPOET-4247]: https://mailpoet.atlassian.net/browse/MAILPOET-4247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Respect mailpoet_display_custom_fonts filter in Iframe MAILPOET-4247

mailpoet/assets/js/src/form_editor/store/controls.jsx
Fixes [MAILPOET-4341]
[MAILPOET-4341]: https://mailpoet.atlassian.net/browse/MAILPOET-4341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Testing instructions inside Jira, along with GIF image.
=> Mailpoet 4341 creating custom field from form breaks form editor

mailpoet/lib/Segments/DynamicSegments/Filters/WooCommerceNumberOfOrders.php, mailpoet/tests/DataFactories/Subscriber.php, mailpoet/tests/integration/Segments/DynamicSegments/Filters/WooCommerceNumberOfOrdersTest.php
Fixes [MAILPOET-4390]
[MAILPOET-4390]: https://mailpoet.atlassian.net/browse/MAILPOET-4390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Testing instructions inside Jira.
=> Fix issue of getting none-customer subs for # order filter [MAILPOET-4390]
